### PR TITLE
stick with specs2 3.x, not 4.0 yet

### LINKED ISSUE #594: regression: http4s, 2.12: "tests" subproject fails to compile (missing scalaz)
seen e.g. at https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/1886/consoleFull

```
[http4s] Running "compile" in: tests
[http4s] [info] Compiling 60 Scala sources to /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.9/project-builds/http4s-42d278ebf11b609ec05dcfadd02a879f8735448f/tests/target/scala-2.12/test-classes...
[http4s] [error] /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.9/project-builds/http4s-42d278ebf11b609ec05dcfadd02a879f8735448f/tests/src/test/scala/org/http4s/parser/AcceptEncodingSpec.scala:6: not found: object scalaz
[http4s] [error] import scalaz.Validation
[http4s] [error]        ^
[http4s] [error] /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.9/project-builds/http4s-42d278ebf11b609ec05dcfadd02a879f8735448f/tests/src/test/scala/org/http4s/parser/AcceptLanguageSpec.scala:6: not found: object scalaz
[http4s] [error] import scalaz.Validation
[http4s] [error]        ^
[http4s] [error] /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.9/project-builds/http4s-42d278ebf11b609ec05dcfadd02a879f8735448f/tests/src/test/scala/org/http4s/parser/HeaderParserHelper.scala:4: not found: object scalaz
[http4s] [error] import scalaz.Validation
[http4s] [error]        ^
[http4s] [error] three errors found
[http4s] [error] (tests/test:compileIncremental) Compilation failed
```

### PR DESCRIPTION
**Pull request by SethTisue**
fixes #594

fyi @etorreborre

### CODE REVIEW

**Comment by SethTisue** [comment]
test run: https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/1888/consoleFull

**Comment by SethTisue** [comment]
I'm going to go ahead and merge since a local test has http4s passing

**Comment by etorreborre** [comment]
`specs2-4.x` does not depend on scalaz anymore, maybe `scalaz` was expected as a transitive dependency but not accessible anymore?

**Comment by SethTisue** [comment]
@etorreborre yes, I assume so. fyi @rossabaker (since http4s is the project that broke)

**Pull request merged**
