### PR TITLE
sbt 1.3.0-RC5

### PR DESCRIPTION
**Pull request by eed3si9n**

### CODE REVIEW

**Comment by eed3si9n** [comment]
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/4993/console

**Comment by SethTisue** [comment]
not sure why that run didn't complete. sequel queued: https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/4995/

**Comment by SethTisue** [comment]
the repos we still have pinned to 1.2.8 or some earlier 1.3 RC, should we try advancing any of them to RC5?

**Comment by eed3si9n** [comment]
I'm happy to keep it as is until 1.3.0 ships.

**Pull request merged**
