### PR TITLE
2.13: new Scala SHA

### PR DESCRIPTION
**Pull request by SethTisue**
~https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/2577/~
~https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/2578/~
~https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/2579/~
~https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/2583/~
~https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/2584/~
https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/2599/

### CODE REVIEW

**Comment by SethTisue** [comment]
`FAILURES (UNEXPECTED): scalameta,blaze,scalafx`

two now-illegal overrides, one reporter thing

**Comment by SethTisue** [comment]
the [scalameta failure](https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/2579/artifact/logs/scalameta-build.log) is a source incompatibility caused by https://github.com/scala/scala/pull/9449, which adds a parameter to `reportSuspendedMessages` that wasn't there before

**Comment by SethTisue** [comment]
@lrytz I'd like not to spend time on this, so I can focus on other tasks. can I ask you to either make the needed changes to scalameta upstream, or explain to the scalameta maintainers what they need to do?

there is a `semanticdb/scalac/library/src/main/scala-2.13.5` which has a `VersionCompilerOps.scala` that handles calling `reportSuspendedMessages`. looks like there will need to be a `2.13.6` directory as well with different code, but if the `reportSuspendedMessages` needs a `Run`, it wasn't immediately clear to me at the call sites where I would get that `Run`. (but I didn't look very hard.)

**Comment by SethTisue** [comment]
superseded by #1392

**Comment by lrytz** [comment]
@SethTisue the fix should be trivial: `forceWarnings` should again be a no-op for 2.13.6, as it is for 2.13.1 (https://github.com/scalameta/scalameta/blob/master/semanticdb/scalac/library/src/main/scala-2.13.1/scala/meta/internal/semanticdb/scalac/VersionCompilerOps.scala).

I'm not sure how exactly what you need to do in order to make it work in the community build, until 2.13.6 is out.

**Pull request closed without merging**
