### PR TITLE
freeze fs2

### PR DESCRIPTION
**Pull request by SethTisue**
trying to get fs2-reactive-streams green (and, dare I hope, sttp and http4s, too)

### CODE REVIEW

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/3448/consoleFull

**Comment by SethTisue** [comment]
well this gets fs2-reactive-streams green, so that's good

sttp is still failing with

```
[sttp] [error] /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.14/project-builds/sttp-ca849aa235e621097f989cbde1ae1b11025d4b7e/implementations/monix/shared/src/main/scala/com/softwaremill/sttp/impl/monix/TaskMonadAsyncError.scala:18:19: missing parameter type
[sttp] [error]     Task.async { (_, cb) =>
[sttp] [error]                   ^
[sttp] [error] /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.14/project-builds/sttp-ca849aa235e621097f989cbde1ae1b11025d4b7e/implementations/monix/shared/src/main/scala/com/softwaremill/sttp/impl/monix/TaskMonadAsyncError.scala:18:22: missing parameter type
[sttp] [error]     Task.async { (_, cb) =>
[sttp] [error]                      ^
```

http4s fails with

```
[http4s] [error] **** Missing dependency: the library co.fs2#fs2-scodec is not provided (in space "scala.main.jawn_0_11") by any project in this configuration file.
```

which looks like we just need to enable another fs2 subproject? I'll have a look

and I noticed while working on this that in the sttp build we currently have:

```
    // I got some compile error here (June 2018), involving implicit
    // ExecutionContexts, that seemed unlikely to be significant.
    // we don't need to have every last subproject
    extra.exclude: ["asyncHttpClientBackendFs2"]
```

this looks like something to try enabling again, if we can.

**Comment by SethTisue** [comment]
> which looks like we just need to enable another fs2 subproject? I'll have a look

hmm no, this is an fs2 change:

> docs/migration-guide-1.0.md:The `fs2-scodec` interop project has been folded directly in to `fs2-core`. The `fs2.interop.scodec.ByteVectorChunk` type is now `fs2.Chunk.ByteVectorChunk`

but I see we have http4s frozen so the problem will probably go away if we move to a newer http4s commit

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/3450/

**Comment by SethTisue** [comment]
gah

```
[http4s:error] com.fasterxml.jackson.databind.JsonMappingException: Required property 'version' is missing.
[http4s:error] {}
[http4s:error]  ^
[http4s:error] 	at com.typesafe.dbuild.model.Utils$$anonfun$readValueT$1.apply(Utils.scala:47)
[http4s:error] 	at com.typesafe.dbuild.model.ClassLoaderMadness$.withContextLoader(ClassLoaderMadness.scala:8)
[http4s:error] 	at com.typesafe.dbuild.model.Utils$.readValueT(Utils.scala:24)
[http4s:error] 	at com.typesafe.dbuild.model.Utils$.readValue(Utils.scala:50)
[http4s:error] 	at com.typesafe.dbuild.support.sbt.SbtRunner$.scan$1(SbtRunner.scala:312)
[http4s:error] 	at com.typesafe.dbuild.support.sbt.SbtRunner$.collectOutputFiles(SbtRunner.scala:322)
[http4s:error] 	at com.typesafe.dbuild.support.sbt.SbtExtractor$.extractMetaData(DependencyExtractor.scala:109)
[http4s:error] 	at com.typesafe.dbuild.support.sbt.SbtBuildSystem.extractDependencies(SbtBuildSystem.scala:85)
```

## `com.typesafe.dbuild.model.ClassLoaderMadness` 😱😜

**Comment by SethTisue** [comment]
oh I know what this is, it's because dbuild gets all uptight if a project overrides `onLoad`, and I see http4s has

```
// check for library updates whenever the project is [re]load
onLoad in Global := { s =>
  "dependencyUpdates" :: s
}
```

take a chill pill, dbuild

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/3457/ (404 for now)

**Comment by SethTisue** [comment]
the sttp compile error is in the monix subproject. we should probably just disable that subproject, for now anyway, at some point these things aren't worth fiddling with anymore

**Comment by adamw** [comment]
Hm I could just add the type annotation in `TaskMonadAsyncError:18`, but what's quite weird is that it compile locally. Are you using another Scala/Monix version?

**Comment by SethTisue** [comment]
I'm going to go ahead and merge this, since we need to freeze fs2 anyway since they've already started using cats 1.3 features, and we're still only 1.2 (we only just got there!)

what we have so far here gets fs2 green again, and gets fs2-reactive-streams again. sttp and http4s remain red, but I'll deal with that in a separate PR or PRs.

**Comment by SethTisue** [comment]
@adamw yeah in the community build we ignore whatever Scala-based dependency version numbers your own build declares, and use our own versions instead that we build ourselves from source.

and yeah, we're also on a Scala 2.12.7 nightly here rather than vanilla 2.12.6, and that's also a possible cause.

before too much longer I'll do a new PR involving sttp, and ping you then.

**Comment by SethTisue** [comment]
@adamw see #786 and #787

**Pull request merged**
