### PR TITLE
add scaladex and its dependencies

### PR DESCRIPTION
**Pull request by SethTisue**
namely: nscala-time, akka-http-cors, elastic4s, sksamuel-exts

### CODE REVIEW

**Comment by SethTisue** [comment]
normally the community build builds libraries, not whole apps like Scaladex. but, it's good to have a few apps in there too, for diversity, and Scaladex is an especially important app in the world of Scala

fyi @MasseGuillaume @sksamuel @lomigmegard @kmizu @xuwei-k

**Comment by SethTisue** [comment]
we need akka-http-session too, fyi @adamw

**Comment by SethTisue** [comment]
hmm

```
[scaladex] [error]  found   : SortOrder (in org.elasticsearch.search.sort) 
[scaladex] [error]  required: SortOrder (in com.sksamuel.elastic4s.searches.sort) 
[scaladex] [error]       case Some("created")  => fieldSort("created") order SortOrder.DESC
```

looks like I may need to either make Scaladex use a newer elastic4s version, or make the community build use an older version

**Comment by SethTisue** [comment]
okay I switched elastic4s to the series/5.4.x branch, that worked.

but then, hmm

```
[scaladex] [error] Modules were resolved with conflicting cross-version suffixes in {file:/home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.9/project-builds/scaladex-dce52d70e734f302fb14e3a8d71fc7b22b89f83f/}data:
[scaladex] [error]    org.typelevel:macro-compat _2.12, <none>
[scaladex] java.lang.RuntimeException: Conflicting cross-version suffixes in: org.typelevel:macro-compat
[scaladex] 	at scala.sys.package$.error(package.scala:27)
```

(from https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/2364/consoleFull)

**Comment by MasseGuillaume** [comment]
> looks like I may need to either make Scaladex use a newer elastic4s version, or make the community
> build use an older version

I can bump elastic4s version.

**Comment by SethTisue** [comment]
> I can bump elastic4s version.

@MasseGuillaume thanks, but it's looking like that won't be necessary; I'll let you know if it would be helpful. (feel free to do it anyway regardless, though!)

**Comment by SethTisue** [comment]
@MasseGuillaume I ended up disabling the `server` project since it requires `sass`, so... partial victory.

**Pull request merged**
