### PR TITLE
fix scala-js

### PR DESCRIPTION
**Pull request by sjrd**
as per Sebastien's advice at scala-js/scala-js#3255

(cherry picked from commit 027f877f4c1c13abc340388ede0391a7b33de93f)

### CODE REVIEW

**Comment by sjrd** [comment]
Somehow https://github.com/scala/community-builds/commit/027f877f4c1c13abc340388ede0391a7b33de93f didn't make its way to the 2.13.x branch. I'm not sure why. Anyway, here's a cherry-pick to 2.13.x, necessary to fix the test failure in Scala.js.

This time I'm pretty sure Scala.js is going to successfully build. Fingers crossed.

**Comment by SethTisue** [comment]
thanks, not sure what happened here, I was probably merging a bunch of changes and made a wrong guess about whether a change was 2.12-specific? idk

optimistically merging.

**Comment by SethTisue** [comment]
(I just reviewed all the diffs between the current HEADs of 2.12.x and 2.13.x to make sure there wasn't some great merge calamity, but I didn't spot any anomalies.)

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/1724/

**Comment by sjrd** [comment]
Waw, that was fast, thanks!

**Comment by SethTisue** [comment]
green! (I aborted the overall run for other reasons, but the scala-js part had already succeeded)

**Pull request merged**
