### PR TITLE
unfreeze scalameta (to get scalafix working again)

### PR DESCRIPTION
**Pull request by SethTisue**
because scalafix master now needs scalameta's new symtab module

### CODE REVIEW

**Comment by SethTisue** [comment]
test run: 
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/3173/

**Comment by SethTisue** [comment]
if this doesn't work out, we should just freeze scalafix at the last green commit, that would be perfectly fine too /cc @olafurpg

**Comment by olafurpg** [comment]
FWIW I cleaned up the scalafix build yesterday, upgraded to sbt 1, removed Scala.js, and generally simplified the build a lot. Scalafix should work with the latest scalameta master.

**Comment by SethTisue** [comment]
okay, the question then is whether something else will break :-)

**Comment by SethTisue** [comment]
queued: 
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/3175/ (404 for now)

**Comment by SethTisue** [comment]
@olafurpg I had to add `unit` to `extra.excludes`, because it was trying to compile stuff from `testsOutputDotty`. but as a result we don't seem to be running any scalafix tests at all.

offhand, it looks like it might be because:

```
    compileInputs.in(Compile, compile) := {
      compileInputs
        .in(Compile, compile)
        .dependsOn(
          compile.in(testsInput, Compile),
          compile.in(testsOutputDotty, Compile),
```

and as for why it would fail in the community build only, I imagine it's because your build is setting `scalaVersion` to (e.g.) 0.9.0-RC1 and then dbuild overrides that to whatever Scala version the community build is using

can the Dotty stuff be kept more separate?

**Comment by olafurpg** [comment]
@SethTisue My goal is to move the dotty rules into a separate repository soon similar to scala-collection-compat. First I need to improve the support for externally published rules, which is in my queue before scalafix v0.6.

**Comment by olafurpg** [comment]
The dotty rules have now been moved out of the scalafix build so that sbt-dotty should no longer cause problems.

**Comment by SethTisue** [comment]
@olafurpg awesome! but I think unfreezing would still run afoul of #765, let's continue there

**Pull request merged**
