### PR TITLE
readd a temporarily disabled piece of sttp

### PR DESCRIPTION
**Pull request by SethTisue**
as per https://github.com/scala/community-builds/pull/805#discussion_r228572426

### CODE REVIEW

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/3970/

**Comment by SethTisue** [comment]
fyi @kubukoz @adamw

**Comment by SethTisue** [comment]
hmm so

```
[sttp] Processing subproject: asyncHttpClientBackendFs2
[sttp] [error] **** Missing dependency: the library co.fs2#fs2-reactive-streams is not provided (in space "scala.main.jawn_0_11") by any project in this configuration file.
[sttp] [error] In order to control which version is used, please add the corresponding project to the build file
[sttp] [error] (or use "check-missing:false" to ignore (not recommended)).
[sttp] [error] java.lang.RuntimeException: Required dependency not found
[sttp] [error] 	at scala.sys.package$.error(package.scala:26)
[sttp] [error] 	at com.typesafe.dbuild.plugin.DBuildRunner$.$anonfun$fixModule$8(DBuildRunner.scala:205)
```

pushed what I think is a fix. let's try it again:

https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/3977/

**Comment by adamw** [comment]
Great, thanks @SethTisue !

**Pull request merged**
