### PR TITLE
add finagle-core

### PR DESCRIPTION
**Pull request by SethTisue**
I have no idea if this will be easy or not... why not just try it and see?
suggested by @martijnhoekstra

### CODE REVIEW

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/4574/ ~~(will be 404 for a while, Jenkins is busy)~~

**Comment by SethTisue** [comment]
this looks pretty clean/doable:

```
sbt:finagle> show finagle-core/libraryDependencies
[info] * org.scala-lang:scala-library:2.12.8
[info] * org.scalacheck:scalacheck:1.13.4:test
[info] * org.scalatest:scalatest:3.0.0:test
[info] * com.novocode:junit-interface:0.11:test
[info] * org.mockito:mockito-all:1.9.5:test
[info] * com.twitter:util-app:19.5.1
[info] * com.twitter:util-cache:19.5.1
[info] * com.twitter:util-codec:19.5.1
[info] * com.twitter:util-core:19.5.1
[info] * com.twitter:util-hashing:19.5.1
[info] * com.twitter:util-jvm:19.5.1
[info] * com.twitter:util-lint:19.5.1
[info] * com.twitter:util-logging:19.5.1
[info] * com.twitter:util-registry:19.5.1
[info] * com.twitter:util-security:19.5.1
[info] * com.twitter:util-stats:19.5.1
[info] * com.twitter:util-tunable:19.5.1
[info] * com.github.ben-manes.caffeine:caffeine:2.3.4
[info] * org.hdrhistogram:HdrHistogram:2.1.11
[info] * com.google.code.findbugs:jsr305:2.0.1
[info] * io.netty:netty-handler:4.1.31.Final:test
[info] * io.netty:netty-transport:4.1.31.Final:test
[info] * io.netty:netty-transport-native-epoll:4.1.31.Final:test
[info] * io.netty:netty-transport-native-unix-common:4.1.31.Final:test
[info] * io.netty:netty-handler-proxy:4.1.31.Final:test
```

**Comment by SethTisue** [comment]
ScalaCheck 1.13 might be a problem, but not necessarily. sometimes people happen to have stayed in the 1.13/1.14 source-compatible subset

**Comment by SethTisue** [comment]
Martijn notes that other subprojects may require adding https://github.com/twitter/bijection

**Comment by SethTisue** [comment]
well, that was easy. @martijnhoekstra do you have any idea what other subprojects might be worth trying...? and/or who else we might @-mention who might have suggestions?

**Comment by martijnhoekstra** [comment]
`scrooge` (already in), `chill` and `bijection` are the most important transitive deps from the twittersphere I think. I think the man to @ who knows whats what, and what is important/is most likely to break/is most likely to break the compiler is @mosesn

**Comment by SethTisue** [comment]
oh, sorry, I meant "subprojects of the build within the twitter/finagle repo". these things:

```
[info] 	   finagle-base-http
[info] 	   finagle-benchmark
[info] 	   finagle-benchmark-thrift
[info] 	   finagle-core
[info] 	   finagle-doc
[info] 	   finagle-example
[info] 	   finagle-exception
[info] 	   finagle-exp
[info] 	   finagle-grpc-context
[info] 	   finagle-http
[info] 	   finagle-http2
[info] 	   finagle-init
[info] 	   finagle-integration
[info] 	   finagle-memcached
[info] 	   finagle-mux
[info] 	   finagle-mysql
[info] 	   finagle-netty4
[info] 	   finagle-netty4-http
[info] 	   finagle-opencensus-tracing
[info] 	   finagle-redis
[info] 	   finagle-serversets
[info] 	   finagle-stats
[info] 	   finagle-stats-core
[info] 	   finagle-thrift
[info] 	   finagle-thriftmux
[info] 	   finagle-toggle
[info] 	   finagle-tunable
[info] 	   finagle-zipkin-core
[info] 	   finagle-zipkin-scribe
```

from the above list, this PR adds only `finagle-core`

(though I'm interested in the question you answered as well)

hi @mosesn

**Comment by martijnhoekstra** [comment]
Not much of an idea then -- my guess would be the https (base-http, http, http2 and netty4-http)

**Pull request merged**
