### PR TITLE
explore making Left and Right have only one type parameter

### PR DESCRIPTION
**Pull request by SethTisue**
context is https://github.com/scala/scala/pull/9303, cc @joroKr21

source changes needed so far:

* https://github.com/scala/scala-parser-combinators/pull/329/commits/df92b0868d45ea33cbac13414d9e78db83c3ff63
* https://github.com/SethTisue/scodec-bits/commit/6ab718977e142b46799dc5e8479afda8e95a3442
* https://github.com/scala/scala-collection-compat/pull/398/commits/bc2c5f8eadefec624921a7cab238e4c72b8b6917

so far all of these were small, easy, compatible-either-way changes that can even be considered code improvement

~https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/2251/~ `SUCCEEDED: 90`
~https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/2263/~ 
https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/2264/ `SUCCEEDED: 110`

### CODE REVIEW

**Comment by SethTisue** [comment]
@joroKr21 I fixed three repos so far, all easy! (runs 2263/2264 queued — we'll have results by Sunday)

but the next blocker repo, Shapeless, is trickier. I spent about 30 minutes on it  and came up with https://github.com/SethTisue/shapeless/commit/449d3b05cb254c3e435ac14a816e52a31a0fbda6 , but it needs more work — does pursuing that further interest you?

**Comment by joroKr21** [comment]
Shapeless will be more tricky yes. But shouldn't we somehow figure out if the change will break `ScalaSignature` first? I remember that cats did a similar change (removed a type parameter from `Parallel`) and I didn't hear of any problems.

**Comment by SethTisue** [comment]
> shouldn't we somehow figure out if the change will break ScalaSignature first

okay. probably Dale will weigh on in that soon, over on the main ticket. (it would be good to mention the cats thing there, with a link if possible.)

**Comment by SethTisue** [comment]
oh let's @-mention @milessabin to let him know we're looking at this

**Comment by SethTisue** [comment]
run 2264: `SUCCEEDED: 110` and `BLOCKING DOWNSTREAM: specs2 (90), cats (82), shapeless (71), claimant (27), jackson-module-scala (26), pprint (13), sksamuel-exts (2), jsoniter-scala (2), kamon (1)`

**Comment by SethTisue** [comment]
closing, as per discussion in scala/scala#9303

I think the results here were fairly encouraging, actually — the change might not be too disruptive for Scala 3.T, if Typelevel is willing to update their libraries when the time comes

**Pull request closed without merging**
