### PR TITLE
Add cbuild.sh, a configurable Community Build wrapper for dbuild

### PR DESCRIPTION
**Pull request by ghost**
tested against https://github.com/typelevel/catalysts-docker/tree/master/artifactory-oss by running:

```
./cbuild.sh -v 2.12 -r resolvers/resolvers-catalysts-docker.conf 
```

### CODE REVIEW

**Comment by ghost** [comment]
Note that the original structure (with the three config files in the root directory) can be maintained by simply running:

```
./cbuild.sh -c .
```

**Comment by SethTisue** [comment]
hey, sorry I haven't had time to try this quite yet, but I expect to get to it soon. don't worry about the merge conflict, I can sort out that later.

**Comment by ghost** [comment]
@SethTisue np, and thanks for update :smile: 

btw, I know the PR as -is is somewhat intrusive, I had some thoughts at some stage to make it less so, but then it was less clear as to the final goal -  tldr, happy to discuss on gitter/here first.

**Comment by SethTisue** [comment]
still planning to return to this before too much longer :-\

**Comment by SethTisue** [comment]
I merged this with `origin/2.12.x` and pushed the result to https://github.com/SethTisue/community-builds/tree/BennyHill-fix/474

it seems to be working for me locally. if we find it works on Jenkins too, I'm inclined to just merge it and try it for a while.

I've queued up a Jenkins run here: https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/1335/consoleFull but it's 404 til the queue clears, probably tomorrow.

**Comment by SethTisue** [comment]
sigh, Jenkins ran out of disk. I've queued up a new run here: https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/1339/consoleFull but it's 404 til the queue clears

**Comment by SethTisue** [comment]
the one failure in the test run is unrelated, so I'm going to go ahead and merge this. thank you Alistair — for the nice PR, and for all your patience.

**Comment by SethTisue** [comment]
> I know the PR as -is is somewhat intrusive, I had some thoughts at some stage to make it less so, but then it was less clear as to the final goal - tldr, happy to discuss on gitter/here first

I backed out a couple aspects of the naming and structure that I found a bit "intrusive" — see f073143fe4794534310d1a60c228ce22a1943951 and d50b71b92ccd556b7a39eb7d9e6c7dadc7f64fa3. but this is provisional and open to further discussion and further changes

**Pull request merged**
