### PR TITLE
Downgrade to Play 2.3.x versions of sbt-web-*

### PR DESCRIPTION
**Pull request by retronym**

### CODE REVIEW

**Comment by retronym** [comment]
Manual community build attempted: https://jenkins-dbuild.typesafe.com:8499/job/Community-2.11.x-manual/168

**Comment by SethTisue** [comment]
@retronym confused, this PR says it's about sbt-web, but the diffs seem instead to have to do with bintray (https://github.com/typesafehub/dbuild/issues/158)?

**Comment by adriaanm** [comment]
I think this one can be closed in favor of an approach that drops building Scala 2.10 sources and resolves them using `system: "ivy"` instead.

**Comment by SethTisue** [comment]
namely https://github.com/scala/community-builds/pull/106

**Pull request closed without merging**
