### PR TITLE
2.12: advance Scala SHA

### PR DESCRIPTION
**Pull request by SethTisue**
~~https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/5708/~~
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/5713/

### CODE REVIEW

**Comment by SethTisue** [comment]
https://github.com/scala/scala/pull/8917 caused splain to fail — I asked about it on the PR, waiting to hear

**Comment by SethTisue** [comment]
@tek note https://github.com/scalacommunitybuild/splain/commit/c922a86b8a2cbd63d59ee9c3f4e7106f4fd59cd5

**Comment by tek** [comment]
ugh right, I need to move that test into a version compat directory

**Comment by SethTisue** [comment]
or just gamble it won't change again :-)

**Comment by tek** [comment]
well for 2.13 it's without the `=>`, so I only removed it because I wasn't thinking about you running the tests for 2.12 ;)

**Comment by tek** [comment]
tests should be sane now!

**Comment by SethTisue** [comment]
011d58d4279b5ec1428d6804effa47cafbd43bb3 green in local test :+1:

**Pull request merged**
