### PR TITLE
[WIP] add lagom samples

### PR DESCRIPTION
**Pull request by SethTisue**
sequel to #869

### CODE REVIEW

**Comment by SethTisue** [comment]
queued: https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/4783/

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/4787/

**Comment by SethTisue** [comment]
```
[lagom-samples] [info] Set current project to shopping-cart-java (in build file:/home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.16/project-builds/lagom-samples-0c24334b89cbeb8151574fc1c793f86152183f03/shopping-cart/shopping-cart-java/)
[lagom-samples] [error] References to undefined settings: 
[lagom-samples] [error] 
[lagom-samples] [error]   lagom-internal-meta-project-service-locator / scalaModuleInfo from lagom-internal-meta-project-service-locator / scalaModuleInfo
[lagom-samples] [error]      Did you mean lagom-internal-meta-project-service-locator / updateSbtClassifiers / scalaModuleInfo ?
[lagom-samples] [error] 
[lagom-samples] [error]   lagom-internal-meta-project-cassandra / scalaModuleInfo from lagom-internal-meta-project-cassandra / scalaModuleInfo
[lagom-samples] [error]      Did you mean lagom-internal-meta-project-cassandra / updateSbtClassifiers / scalaModuleInfo ?
[lagom-samples] [error] 
[lagom-samples] [error]   lagom-internal-meta-project-kafka / scalaModuleInfo from lagom-internal-meta-project-kafka / scalaModuleInfo
[lagom-samples] [error]      Did you mean lagom-internal-meta-project-kafka / updateSbtClassifiers / scalaModuleInfo ?
```

I think I hit this last time around and doing `extra.exclude: ["lagom-internal-meta-project-*"]` fixed it? I'll try it

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/4790/

**Comment by SethTisue** [comment]
the `exclude:` thing didn't work

@dwijnand I have no idea what to make of these errors, do you?

**Comment by dwijnand** [comment]
It's like a typecheck error but in the settings language.  There is a setting of `lagom-internal-meta-project-kafka / scalaModuleInfo` based on the value of `lagom-internal-meta-project-kafka / scalaModuleInfo` itself, but that initial that definition doesn't exist.

I think that setting might be https://github.com/lightbend/dbuild/blame/be3ba78b88110d19fc802e824a2410bb1447cdae/plugin/src/main/scala/com/typesafe/dbuild/plugin/DBuildRunner.scala#L427 (`scalaModuleInfo` used to be called `ivyScala` so dbuild has `keyIvyScala` as a 0.13.x/1.x shared alias).

I don't like the way that Lagom sets up those those meta projects: https://github.com/lagom/lagom/blob/84166a3ad106f2eb537650105e112bc4d118555f/dev/sbt-plugin/src/main/scala/com/lightbend/lagom/sbt/LagomPlugin.scala#L422-L424.  Why is it only setting projectSettings?  Why not `enablePlugins`?

As the default settings sbt has:
https://github.com/sbt/sbt/blob/d6b8e0388c015e4f61934de94f54dcf07efca3aa/main/src/main/scala/sbt/Defaults.scala#L2220 and https://github.com/sbt/sbt/blob/d6b8e0388c015e4f61934de94f54dcf07efca3aa/main/src/main/scala/sbt/Defaults.scala#L2587.

The first one is also self-referential, but using `or` is there to avoid "undefined settings" so it shouldn't be causing the problem.  The second one is the one that the communnity build _does_ see.  But how is it getting that second one, but not the first one?

I don't have any guesses without minimising it more.  Which sbt version is being used here?

**Comment by dwijnand** [comment]
This came up in a support case, so I've got a fix cooking that you'll be able to use: https://github.com/lagom/lagom/pull/2161.

**Comment by SethTisue** [comment]
hmm okay let's try unfreezing lagom, what could possibly go wrong (said Pandora, reaching for the lid)

**Comment by SethTisue** [comment]
queued: https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/4838/

**Comment by SethTisue** [comment]
queued: https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/4842/

**Comment by SethTisue** [comment]
queued: https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/4845/

**Comment by SethTisue** [comment]
rabbit hole branching and deepening

queued: https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/4858/

**Comment by SethTisue** [comment]
we have emerged from the akka-management portion of this underground rabbit world, at least

is it a waistcoat-and-pocket-watch type rabbit, you think, with important errands to run? or just the kind that eats lettuce and twitches its nose and that's about it? let's continuing trying to find out

https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/4875/

`[lagom] [error] /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.16/project-builds/lagom-f7520545b8e8305e2051dc8378342cfdfd51f56c/cluster/core/src/main/scala/com/lightbend/lagom/internal/cluster/ClusterDistribution.scala:147:39: value scheduleWithFixedDelay is not a member of akka.actor.Scheduler`

**Comment by SethTisue** [comment]
gah, so `scheduleWithFixedDelay` is Akka 2.6 API. I should have checked what Akka version Lagom's master branch used

okay, so let's try the 1.5.x branch instead

**Comment by SethTisue** [comment]
@dwijnand might your change be back-portable to the 1.5.x branch? otherwise I think we're stuck

**Comment by dwijnand** [comment]
Yep, it's in 1.5.x: https://github.com/lagom/lagom/pull/2174

**Comment by SethTisue** [comment]
the Lagom-itself part of this is nearly done, so I've split it off as #962, once merged this one should be rebased

**Comment by SethTisue** [comment]
queued: https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/4895/

**Comment by SethTisue** [comment]
```
[lagom-samples] [error] References to undefined settings: 
[lagom-samples] [error] 
[lagom-samples] [error]   lagom-internal-meta-project-cassandra / scalaModuleInfo from lagom-internal-meta-project-cassandra / scalaModuleInfo
[lagom-samples] [error]      Did you mean lagom-internal-meta-project-cassandra / updateSbtClassifiers / scalaModuleInfo ?
[lagom-samples] [error] 
[lagom-samples] [error]   lagom-internal-meta-project-kafka / scalaModuleInfo from lagom-internal-meta-project-kafka / scalaModuleInfo
[lagom-samples] [error]      Did you mean lagom-internal-meta-project-kafka / updateSbtClassifiers / scalaModuleInfo ?
[lagom-samples] [error] 
[lagom-samples] [error]   lagom-internal-meta-project-service-locator / scalaModuleInfo from lagom-internal-meta-project-service-locator / scalaModuleInfo
[lagom-samples] [error]      Did you mean lagom-internal-meta-project-service-locator / updateSbtClassifiers / scalaModuleInfo ?
```

**Comment by dwijnand** [comment]
Do the Lagom samples use the freshly built Lagom plugin?  Or is it using:

https://github.com/lagom/lagom-samples/blob/ba987f5a92874c852a310bffe08da7def3ca9356/shopping-cart/shopping-cart-java/project/plugins.sbt#L2

**Comment by SethTisue** [comment]
> Do the Lagom samples use the freshly built Lagom plugin? 

No.

We could probably convince dbuild to use this one sbt plugin built from source (it can do that, we used to build all of the sbt plugins from source in the community build, Adriaan changed it circa 2015). But I don't think I want to mess with it, I'm content to wait for the next plugin release.

**Comment by dwijnand** [comment]
Makes sense to do that.  I suspect most developments in Play and Lagom won't be in their build plugins.

**Comment by SethTisue** [comment]
@dwijnand I saw there was a new Lagom release, does it include this change?

**Comment by dwijnand** [comment]
Yes, it does, but it was a Lagom 1.4 release.  While it's also backported to the 1.5 branch we haven't cut a release for it, nor do we have immediate plans to.

**Comment by SethTisue** [comment]
closing for now, we can come back to this when it becomes eligible to progress again

**Comment by dwijnand** [comment]
Actually a Lagom 1.5 release is now planned for this week or next (this sprint).

Opening to track.

**Comment by SethTisue** [comment]
@dwijnand is this ready to advance again?

**Comment by dwijnand** [comment]
Yep, with Lagom 1.5.3 out the Lagom samples should be using the fixed code.

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/5147/

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/5153/

**Comment by SethTisue** [comment]
I thought `set every publishMavenStyle := false` might fix this, but no:

```
[lagom-samples] [warn] 	Note: Unresolved dependencies path:
[lagom-samples] [error] sbt.librarymanagement.ResolveException: Error downloading com.lightbend.lagom:lagom-javadsl-api:1.5.5-dbuildxefdc35bb4e188217cfa6c668b599ce2f4ed13aef
[lagom-samples] [error]   Not found
[lagom-samples] [error]   Not found
[lagom-samples] [error]   not found: /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.16/project-builds/lagom-samples-161765fa86e8c082f8c8a83a73aa0c93e84e4c2c/shopping-cart/shopping-cart-java/.dbuild/local-repo/0/com.lightbend.lagom/lagom-javadsl-api/1.5.5-dbuildxefdc35bb4e188217cfa6c668b599ce2f4ed13aef/ivys/ivy.xml
[lagom-samples] [error]   not found: /home/jenkins/workspace/scala-2.12.x-integrate-community-build/./target-0.9.16/project-builds/lagom-samples-161765fa86e8c082f8c8a83a73aa0c93e84e4c2c/shopping-cart/shopping-cart-java/.dbuild/local-repo/0/com/lightbend/lagom/lagom-javadsl-api/1.5.5-dbuildxefdc35bb4e188217cfa6c668b599ce2f4ed13aef/lagom-javadsl-api-1.5.5-dbuildxefdc35bb4e188217cfa6c668b599ce2f4ed13aef.pom
[lagom-samples] [error]   not found: /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.16/project-builds/lagom-samples-161765fa86e8c082f8c8a83a73aa0c93e84e4c2c/shopping-cart/shopping-cart-java/shopping-cart-api/.dbuild/ivy2/local/com.lightbend.lagom/lagom-javadsl-api/1.5.5-dbuildxefdc35bb4e188217cfa6c668b599ce2f4ed13aef/ivys/ivy.xml
[lagom-samples] [error]   not found: https://scala-ci.typesafe.com/artifactory/dbuild/com/lightbend/lagom/lagom-javadsl-api/1.5.5-dbuildxefdc35bb4e188217cfa6c668b599ce2f4ed13aef/lagom-javadsl-api-1.5.5-dbuildxefdc35bb4e188217cfa6c668b599ce2f4ed13aef.pom
[lagom-samples] [error]   not found: https://scala-ci.typesafe.com/artifactory/dbuild-ivy/com.lightbend.lagom/lagom-javadsl-api/1.5.5-dbuildxefdc35bb4e188217cfa6c668b599ce2f4ed13aef/ivys/ivy.xml
[lagom-samples] [error]   not found: https://scala-ci.typesafe.com/artifactory/dbuild-unchecked/com/lightbend/lagom/lagom-javadsl-api/1.5.5-dbuildxefdc35bb4e188217cfa6c668b599ce2f4ed13aef/lagom-javadsl-api-1.5.5-dbuildxefdc35bb4e188217cfa6c668b599ce2f4ed13aef.pom
[lagom-samples] [error]   not found: https://scala-ci.typesafe.com/artifactory/scala-pr-validation-snapshots/com/lightbend/lagom/lagom-javadsl-api/1.5.5-dbuildxefdc35bb4e188217cfa6c668b599ce2f4ed13aef/lagom-javadsl-api-1.5.5-dbuildxefdc35bb4e188217cfa6c668b599ce2f4ed13aef.pom
[lagom-samples] [error]   not found: https://scala-ci.typesafe.com/artifactory/scala-integration/com/lightbend/lagom/lagom-javadsl-api/1.5.5-dbuildxefdc35bb4e188217cfa6c668b599ce2f4ed13aef/lagom-javadsl-api-1.5.5-dbuildxefdc35bb4e188217cfa6c668b599ce2f4ed13aef.pom
```

**Comment by SethTisue** [comment]
@dwijnand sorry but I give up, this has become too much of a time sink

**Comment by dwijnand** [comment]
Not too worry, they're unlikely to be in any way sophisticated in their compiler/language usage.

**Comment by SethTisue** [comment]
> Not too worry, they're unlikely to be in any way sophisticated in their compiler/language usage.

yup. but, note that I had a specific reason for being interested here, besides general desire to include Lightbend stuff when possible. and the reason is, the Lagom samples involve Java code consuming Scala code, and that's relatively rare in the community build, and worthwhile for QA'ing Scala

@ignasi35 I try to add Lightbend stuff whenever possible, but there's a threshold past which it's out-of-bounds for me as a Scala team member, I can't personally provide cross-repo CI for all of Lightbend OSS. but I would like to emphasize that I am very much available as a consultant and collaborator to anyone at Lightbend who wants to take charge of keeping one or more Lightbend repos in the community build

**Comment by TimMoore** [comment]
@SethTisue are you running any Akka samples in the community build? Some of these also fit into the category of Java code calling Scala APIs, and might be an easier starting point with fewer dependencies. https://github.com/akka/akka-samples

**Comment by SethTisue** [comment]
@TimMoore that's a good suggestion. I'll take a stab at it the next time I do a round of community build work.

**Pull request closed without merging**
