### PR TITLE
Kafka: run tests, use sbt 1.3.0-RC3

### PR DESCRIPTION
**Pull request by SethTisue**
1) can we run the tests again?
2) maybe sbt 1.3.0-RC3 already fixed whatever problem we had using
   RC1 or RC2?

let's find out /cc @ennru

### CODE REVIEW

**Comment by SethTisue** [comment]
queued: https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/4804/

**Comment by SethTisue** [comment]
queued: https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/4808/

**Comment by SethTisue** [comment]
@eed3si9n cross one off the failed-on-sbt-1.3.x list

@ennru note the test exclusion, not sure if it would be worth it for you to look into

**Comment by eed3si9n** [comment]
whoohoo!

**Pull request merged**
