### PR TITLE
unfreeze Play & Lagom (and unfreeze or move forward related projs)

### PR DESCRIPTION
**Pull request by SethTisue**
/cc @marcospereira @dwijnand

### CODE REVIEW

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/3676/ (404 til queue clears)

**Comment by SethTisue** [comment]
if this goes green, we might also consider revisiting https://github.com/scala/community-builds/issues/560 (I still have no opinion on whether it's important)

**Comment by SethTisue** [comment]
```
[ssl-config] [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[ssl-config] [warn] 	::          UNRESOLVED DEPENDENCIES         ::
[ssl-config] [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[ssl-config] [warn] 	:: cf.janga#sbts3;0.10.3: not found
```

**Comment by marcospereira** [comment]
I also see this:

```
[ssl-config] [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[ssl-config] [warn] 	::          UNRESOLVED DEPENDENCIES         ::
[ssl-config] [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[ssl-config] [warn] 	:: com.typesafe.sbt#sbt-osgi;0.9.4: not found
[ssl-config] [warn] 	:: cf.janga#sbts3;0.10.3: not found
[ssl-config] [warn] 	:: com.jsuereth#sbt-pgp;1.1.2: not found
[ssl-config] [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
```

And I see that at least [sbt-pgp 1.1.2](https://github.com/lightbend/ssl-config/commit/152e2f165e39f4b5a717b11e8d6cee4a470ee6a1) is not available at the requested repositories:

https://scala-ci.typesafe.com/artifactory/dbuild-ivy/com.jsuereth/sbt-pgp/scala_2.10/sbt_0.13/

Is that something we can do to help here?

**Comment by SethTisue** [comment]
I think the other errors were just because the community build overrides the sbt version and I neglected, initially, to make the override use sbt 1.x instead of 0.13.x.

as for the `cf.janga#sbts3;0.10.3` one, I think I almost certainly just need to add a resolver to the Artifactory on scala-ci:

```
Resolver.url("sbts3 ivy resolver", url("https://dl.bintray.com/emersonloureiro/sbt-plugins"))(Resolver.ivyStylePatterns)
```

I'll keep you posted.

**Comment by SethTisue** [comment]
I at least attempted to add the new resolver

~~https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/3697/~~
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/3699/

**Comment by SethTisue** [comment]
@dwijnand if I use your branch I get

```
[akka-stream] [error] /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.16/project-builds/akka-stream-fe1d9d022b8160be9527102bfb64d1e77c200315/akka-stream/src/main/scala/com/typesafe/sslconfig/akka/AkkaSSLConfig.scala:113:61: not found: type DisabledComplainingHostnameVerifier
[akka-stream] [error]       if (config.loose.disableHostnameVerification) classOf[DisabledComplainingHostnameVerifier].asInstanceOf[Class[HostnameVerifier]]
[akka-stream] [error]                                                             ^
[akka-stream] [error] /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.16/project-builds/akka-stream-fe1d9d022b8160be9527102bfb64d1e77c200315/akka-stream/src/main/scala/com/typesafe/sslconfig/akka/AkkaSSLConfig.scala:114:19: value hostnameVerifierClass is not a member of com.typesafe.sslconfig.ssl.SSLConfigSettings
[akka-stream] [error]       else config.hostnameVerifierClass.asInstanceOf[Class[HostnameVerifier]]
[akka-stream] [error]                   ^
```

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/3703/

**Comment by SethTisue** [comment]
we're close!

```
[info] Project akka-persistence-cassandra--: FAILED (RuntimeException: Tests unsuccessful)
[info] Project lagom-----------------------: DID NOT RUN (stuck on broken dependencies: akka-persistence-cassandra)
```

```
[akka-persistence-cassandra] [info] Cassandra query currentEventsByTag
[akka-persistence-cassandra] [info] - must set ttl on table (29 milliseconds)
[akka-persistence-cassandra] [info] - must implement standard CurrentEventsByTagQuery (2 milliseconds)
[akka-persistence-cassandra] [info] - must find existing events *** FAILED *** (49 milliseconds)
[akka-persistence-cassandra] [info]   java.lang.AssertionError: assertion failed: received unexpected message RealMessage(OnComplete,Actor[akka://AbstractEventsByTagSpec/deadLetters]) after 0 millis
[akka-persistence-cassandra] [info]   at akka.testkit.TestKitBase.expectNoMsg_internal(TestKit.scala:696)
[akka-persistence-cassandra] [info]   at akka.testkit.TestKitBase.expectNoMessage(TestKit.scala:661)
[akka-persistence-cassandra] [info]   at akka.testkit.TestKitBase.expectNoMessage$(TestKit.scala:660)
[akka-persistence-cassandra] [info]   at akka.testkit.TestKit.expectNoMessage(TestKit.scala:896)
[akka-persistence-cassandra] [info]   at akka.stream.testkit.TestSubscriber$ManualProbe.expectNoMessage(StreamTestKit.scala:599)
[akka-persistence-cassandra] [info]   at akka.persistence.cassandra.query.EventsByTagSpec.$anonfun$new$4(EventsByTagSpec.scala:196)
[akka-persistence-cassandra] [info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
```

maybe it's intermittent? let's find out: https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/3705/

**Comment by SethTisue** [comment]
🎉

**Pull request merged**
