### PR TITLE
fix regression: MiMa failing to extract

### PR DESCRIPTION
**Pull request by SethTisue**
test run: https://scala-ci.typesafe.com/job/scala-2.11.x-jdk8-integrate-community-build/245/consoleFull (404 til Jenkins gets in gear)

### CODE REVIEW

**Comment by SethTisue** [comment]
@dwijnand you might want to look into the details here, this is just me trying for the quick fix without really investigating

**Comment by dwijnand** [comment]
extraProjects is a 0.13.13 feature, so that's the reason.

Did it fail during extracting or running? Because your test run above extracted fine.

**Comment by SethTisue** [comment]
It failed during extraction before. aborting the run and merging.

**Comment by dwijnand** [comment]
In retrospect we shouldn't've upgraded mima to the prerelease

**Pull request merged**
