### PR TITLE
(Don't merge) Bump up to sbt 0.13.10-M1 in 2.12.x

### PR DESCRIPTION
**Pull request by dwijnand**
This is to test the quality of sbt 0.13.10 release candidates.

2.12 clone of #210

### CODE REVIEW

**Comment by SethTisue** [comment]
test run: https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/304/consoleFull (will be 404 for a while as queue clears)

**Comment by dwijnand** [comment]
The only failure was in trying to build sbt, because it hit the classes.bak issue (sbt/sbt#1673). Can we try again please?

**Comment by SethTisue** [comment]
new run is https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/305/consoleFull (will 404 temporarily)

**Comment by dwijnand** [comment]
Re-failed due to a IO/gzip issue.. Thanks for the your help Seth.

**Pull request closed without merging**
