### PR TITLE
build Akka on sbt 1.3.6

### PR DESCRIPTION
**Pull request by SethTisue**

### CODE REVIEW

**Comment by SethTisue** [comment]
queued: https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/2937/

perhaps this will fail, in which case at least I can put in a better comment

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/2937/artifact/logs/akka-stream-build.log

oh right:

```
[akka-stream] [error] Modules were resolved with conflicting cross-version suffixes in ProjectRef(uri("file:/home/jenkins/workspace/scala-2.13.x-integrate-community-build/target-0.9.16/project-builds/akka-stream-846ad85d1f88be2f35d8140306bfcfe2a465d919/"), "akka-stream"):
[akka-stream] [error]    com.typesafe.akka:akka-protobuf-v3 <none>, _2.13
[akka-stream] [error] java.lang.RuntimeException: Conflicting cross-version suffixes in: com.typesafe.akka:akka-protobuf-v3
```

@dwijnand is there an sbt/sbt ticket on this, something I can link to in a comment? I looked through https://github.com/scala/community-build/pull/1008 briefly and thought I would find a place where we'd discussed this, but I don't see it

**Comment by dwijnand** [comment]
No, not yet.  We hit that in Lagom's upgrade to 1.3.4 too, and then in the 1.3.5 upgrade we hit https://github.com/sbt/sbt/issues/5314, but I suspect the cross-version issue is still present in 1.3.5.  I've not spent time diagnosing, minimising it or reporting it, sorry (but I will, eventually, if you don't first).

**Comment by SethTisue** [comment]
let's see if anything changed here in 1.3.6

queued: https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/2947/

**Comment by SethTisue** [comment]
same in 1.3.6: https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/2947/artifact/logs/akka-stream-build.log

**Comment by SethTisue** [comment]
queued a run that uses 1.3.6 but also `useCoursier := false`, to see what happens

hmm, idk what to make of  https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/2955/ , akka-stream compiles, but then akka-remote gives `unresolved dependency: com.typesafe.akka#akka-protobuf;2.6.1-dbuildxffc81352f3bf39a202b20e021c1e26f8c9eb1379: not found`

perhaps it's useful to know that `useCoursier` does make *something* different happen :-/

**Comment by SethTisue** [comment]
maybe we can just `conflictWarning in ThisBuild := ConflictWarning.disable` our way out of this instead

queued: https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/2956/

**Comment by SethTisue** [comment]
queued: https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/2958/

**Comment by SethTisue** [comment]
well we still have no insight into what changed between 1.3.3 and 1.3.5, but I won't be digging any further into it myself

pureconfig failed in the test run for some weird ScalaTest related reason; I'll dig into that separately, I don't understand how it can be related, but perhaps it somehow is

**Pull request merged**
