### PR TITLE
add discipline-scalatest and cats-mtl (and also, not green yet: meow-mtl, pfps-shopping-cart)

### PR DESCRIPTION
**Pull request by SethTisue**
we like to include sample end-user apps like this; we're always long on libraries and short on apps

hello @gvolpe

### CODE REVIEW

**Comment by SethTisue** [comment]
queued: https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/2886/

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/2887/artifact/logs/pfps-shopping-cart-extract.log shows that something in the repo's build is causing `update` to run when the build definition is loaded. that doesn't work with dbuild, since the dbuild-built dependencies aren't available yet so resolution fails

I suspect that upgrading sbt-scalafmt would help; I have seen this before in other repos, and 1.16 is quite old. @gvolpe can I interest you in attempting to upgrade? latest version at https://github.com/scalameta/sbt-scalafmt/releases is 2.3.0

**Comment by gvolpe** [comment]
That's great @SethTisue , thanks! I just tried to update but I'm hitting a strange binary incompatibility error (`NoClassDefFoundError`). Let me see what I can do :)

**Comment by gvolpe** [comment]
Done! :smiley:

**Comment by SethTisue** [comment]
thanks Gabriel!

but I think I already see the next (one of the next?) places this is going to get stuck: squants only just merged their 2.13 support, but they're also on ScalaTest 3.1, which we don't support yet. but 3.1 is in final release now. the 3.0->3.1 move is an issue I've known for a long time I'd be facing eventually, and now's a good time actually (see #1020)

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/2898/

`[info] Project pfps-shopping-cart----------: DID NOT RUN (stuck on broken dependencies: squants)`

**Comment by gvolpe** [comment]
I had to manually update ScalaTest because it was binary incompatible with the latest `sbt-scalafmt` and it wasn't that easy because of `scalacheck` (found this: https://github.com/scalatest/scalatestplus-scalacheck/issues/21).

I guess getting support for ScalaTest 3.1.0 would be the solution (even if slowly) :smiley:

**Comment by SethTisue** [comment]
#1023 should fix squants, after merge we can rebase this one on top of it

**Comment by gvolpe** [comment]
Awesome, thanks @SethTisue!

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/2905/

```
[pfps-shopping-cart] Processing subproject: core
[pfps-shopping-cart] [error] **** Missing dependency: the library com.olegpy#meow-mtl-core is not provided (in space "scala.main") by any project in this configuration file.
```

should be straightforward to add (knock on wood). fyi @oleg-py

https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/2906/

**Comment by SethTisue** [comment]
we need cats-mtl too, which needs metaconfig... this rabbit hole is getting deeper :-)

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/2911/

```
[metaconfig] [error] java.lang.NoSuchMethodError: lmcoursier.definitions.ToCoursier$.project(Llmcoursier/definitions/Project;)Lcoursier/core/Project;
[metaconfig] [error] 	at coursier.sbtcoursier.ResolutionTasks$.$anonfun$resolutionsTask$3(ResolutionTasks.scala:43)
```

I have previously hit this and failed to find a workaround. I can try again, not today though

**Comment by SethTisue** [comment]
metaconfig is green

cats-mtl is green (though we won't be able to run the test suite until we have ScalaTest31)

as for meow-mtl, at https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/2925/artifact/logs/meow-mtl-build.log we see

```scala
[meow-mtl] [error] /home/jenkins/workspace/scala-2.13.x-integrate-community-build/target-0.9.16/project-builds/meow-mtl-84fb782d5d2e9134bbb58cbe04c41fb7fcdd2cd5/core/src/test/scala/com/olegpy/meow/derivations/DerivedLawsSuite.scala:16:29: object DeprecatedEqInstances is not a member of package cats.laws.discipline
[meow-mtl] [error] import cats.laws.discipline.DeprecatedEqInstances._
[meow-mtl] [error]                             ^
```

afaict it's because our cats version is a little too old. but we won't able to move to newer cats until we have ScalaTest 3.1

so we're stuck for now, but lots of good progress was made

will return to this after ScalaTest 3.1 upgrade

**Comment by gvolpe** [comment]
Sounds like you had fun @SethTisue , thanks! :)

**Comment by SethTisue** [comment]
queued: https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/2931/ (if green, we can still merge this PR, just by marking meow-mil as expected-to-fail)

**Comment by gvolpe** [comment]
:tada:

**Pull request merged**
