### PR TITLE
play2-core: re-enable Play-Integration-Test

### PR DESCRIPTION
**Pull request by SethTisue**
cc @schmitch

### CODE REVIEW

**Comment by SethTisue** [comment]
test run: https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/1045/consoleFull (404 til Jenkins gets back from the laundromat)

**Comment by SethTisue** [comment]
```
[play2-core] [error] Failed: Total 529, Failed 2, Errors 0, Passed 523, Skipped 4, Pending 4
[play2-core] [error] Failed tests:
[play2-core] [error] 	play.it.http.NettyIdleTimeoutSpec
[play2-core] [error] 	play.it.http.AkkaIdleTimeoutSpec
[play2-core] [error] (Play-Integration-Test/test:test) sbt.TestsFailedException: Tests unsuccessful
[play2-core:error] Incomplete(node=Some(ScopedKey(Scope(Select(ProjectRef(file:/home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.7-RC1/project-builds/play2-core-69098b021155bb490c563b9e9543905351be1b1b/framework/,Play-Integration-Test)),Select(ConfigKey(test)),Global,Global),test)), tpe=Error, msg=None, causes=List(), directCause=Some(sbt.TestsFailedException: Tests unsuccessful))
```

maybe just needs longer timeouts...?

**Comment by schmitch** [comment]
Hm I will look into it.
Looks like a SSL problem:
```
[play2-core] [info] NettyIdleTimeoutSpec
[play2-core] [info] 
[play2-core] [info] Play's idle timeout support should
[play2-core] [info]   + support sub-second timeouts
[play2-core] [error]   x support a separate timeout for https
[play2-core] [error]    Expected: java.net.SocketException. Got: javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection? instead 
[play2-core] [error]    
[play2-core] [error]     The  SSLException stacktrace is
[play2-core] [error]    
[play2-core] [error]    sun.security.ssl.InputRecord.handleUnknownRecord(InputRecord.java:710)
[play2-core] [error]    sun.security.ssl.InputRecord.read(InputRecord.java:527)
[play2-core] [error]    sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
[play2-core] [error]    sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
[play2-core] [error]    sun.security.ssl.SSLSocketImpl.writeRecord(SSLSocketImpl.java:747)
[play2-core] [error]    sun.security.ssl.AppOutputStream.write(AppOutputStream.java:123)
[play2-core] [error]    sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)
[play2-core] [error]    sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:282)
```

**Comment by schmitch** [comment]
can you tell me the exact java version of the build server?

**Comment by SethTisue** [comment]
```
openjdk version "1.8.0_111"
OpenJDK Runtime Environment (build 1.8.0_111-8u111-b14-2ubuntu0.16.04.2-b14)
OpenJDK 64-Bit Server VM (build 25.111-b14, mixed mode)
```

Oracle vs. OpenJDK can affect certificate-type issues, I (vaguely) think?

**Comment by schmitch** [comment]
well I looked into it but actually I couldn't find something that might make problems.
Currently what I've fought at first is that tests run more parallel than in our case, however since the https tests are using a totally different port it can't be the case.

Well so the error is either one of the following:
- the port `9443` is used elsewhere?
- the server generates incorrect ssl messages, maybe caused by a java agent that somehow gets loaded or tcnative that somehow gets loaded (the client actually accepts any certificate and is extremly simple)
- the certificate that gets generated somehow is incorrect, but still used

Well the first one could be changed pretty fast I guess, I can just change the port to something higher and we could see what happens.

**Comment by SethTisue** [comment]
@wsargent possibly of interest?

I'm going to provisionally close this, we can reopen if someone decides to tackle it

**Pull request closed without merging**
