### PR TITLE
add alpakka-kafka (and more of Lagom too)

### LINKED ISSUE #932: Add Alpakka Kafka
Alpakka Kafka https://github.com/akka/alpakka-kafka/ (aka akka-stream-kafka) could be included it builds for both 2.12.8 and 2.13.0 (by excluding a few tests that need an embedded Kafka broker).

Lagom depends on Alpakka Kafka (relevant for #846)

### PR DESCRIPTION
**Pull request by SethTisue**
fixes #932

/cc @dwijnand since this involves Lagom too

### CODE REVIEW

**Comment by SethTisue** [comment]
@ennru you'll see in the diffs this is a modest initial stab, we can up the ambition level later if this much goes well

queued: https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/4933/

**Comment by ennru** [comment]
```
[alpakka-kafka] [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[alpakka-kafka] [warn] 	::          UNRESOLVED DEPENDENCIES         ::
[alpakka-kafka] [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[alpakka-kafka] [warn] 	:: net.virtual-void#sbt-dependency-graph;0.9.2+10-148ba0ff: not found
[alpakka-kafka] [warn] 	:: com.github.ehsanyou#sbt-docker-compose;67284e73-envvars-2m: not found
[alpakka-kafka] [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
```

The first plugin is used when generating documentation with Paradox.
The second is used for integration tests.

Both are special builds available from 
```
resolvers += Resolver.bintrayIvyRepo("2m", "sbt-plugins")
```
which is part of Alpakka Kafka's plugins.sbt

**Comment by SethTisue** [comment]
We resolve everything through Artifactory regardless of what resolvers the project declares, so I'll need to add that resolver to our Artifactory.

**Comment by SethTisue** [comment]
my local Artifactory config (which is also checked in to this repo) apparently is missing the JCenter resolver, so I get `net.aichler#jupiter-interface;0.8.2: not found`

here's a log showing the precise URLs all this stuff should come from

```
[info] downloading https://jcenter.bintray.com/net/aichler/jupiter-interface/0.8.2/jupiter-interface-0.8.2.jar ...
[info] downloading https://dl.bintray.com/2m/sbt-plugins/com.github.ehsanyou/sbt-docker-compose/scala_2.12/sbt_1.0/67284e73-envvars-2m/jars/sbt-docker-compose.jar ...
[info] downloading https://dl.bintray.com/2m/sbt-plugins/net.virtual-void/sbt-dependency-graph/scala_2.12/sbt_1.0/0.9.2+10-148ba0ff/jars/sbt-dependency-graph.jar ...
```

**Comment by SethTisue** [comment]
pushed commit adding needed resolvers to local Artifactory config

made parallel modification on http://scala-ci.typesafe.com/artifactory/ config via web UI

https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/4973/

dependencies extract now!

```
[alpakka-kafka] [info] These subprojects will be built: alpakka-kafka, tests, testkit, core
[alpakka-kafka] --== End Extracting dependencies for alpakka-kafka ==--
```

we'll see how the actual build does

oh oops lagom mistake, fixed

https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/4975/

at this stage of work the alpakka dependencies are `akka, akka-more, akka-stream, cloc-plugin, genjavadoc, kind-projector, scala, scala-collection-compat, scala-java8-compat, scala-js-stubs, scala-parser-combinators, scalacheck, scalatest, silencer, specs2, spray-json, ssl-config`

and lagom has `akka, akka-http, akka-management, akka-more, akka-persistence-cassandra, akka-persistence-jdbc, akka-stream, alpakka-kafka, better-files, cachecontrol, cloc-plugin, genjavadoc, kind-projector, macro-compat, macro-paradise, play-file-watch, play-json, play-ws, playframework, sbt-testng, scala, scala-collection-compat, scala-java8-compat, scala-js-stubs, scala-parser-combinators, scalacheck, scalatest, shapeless, silencer, slick, specs2, spray-json, ssl-config, twirl`

**Comment by SethTisue** [comment]
hmm, in local testing

```
[alpakka-kafka] Processing subproject: testkit
[alpakka-kafka] [error] **** Missing dependency: the library org.apache.kafka#kafka is not provided (in space "scala.main") by any project in this configuration file.
[alpakka-kafka] [error] In order to control which version is used, please add the corresponding project to the build file
[alpakka-kafka] [error] (or use "check-missing:false" to ignore (not recommended)).
[alpakka-kafka] [error] java.lang.RuntimeException: Required dependency not found
```

@ennru do we need to modify the entry for the kafka repo to build this? or should I just exclude the `testkit` subproject?

and then also:

```
[alpakka-kafka] [error] **** Missing dependency: the library io.github.embeddedkafka#embedded-kafka is not provided (in space "scala.main") by any project in this configuration file.
```

for now I'll exclude `testkit` I guess

**Comment by SethTisue** [comment]
in `tests`,

```
[alpakka-kafka] Processing subproject: tests
[alpakka-kafka] [error] **** Missing dependency: the library io.github.embeddedkafka#embedded-kafka-schema-registry is not provided (in space "scala.main") by any project in this configuration file.
```

**Comment by SethTisue** [comment]
excluding `tests` also, so we're only building `core`, makes alpakka green. let's work on the downstream Lagom stuff next, then worry later about whether to go back and add alpakka tests

**Comment by ennru** [comment]
Some tests use "Embedded Kafka" to check against, others run Kafka in Docker. Only very few don't actually talk to Kafka. So I'd say just don't test it.

There are some significant tweaks in Alpakka Kafka `tests` to only run tests that use Docker on 2.13, but I assume the community-builds would need it the other way round once "Embedded Kafka" becomes available for 2.13.

See
https://github.com/akka/alpakka-kafka/blob/master/build.sbt#L276-L287
https://github.com/akka/alpakka-kafka/blob/master/build.sbt#L304-L321

**Comment by SethTisue** [comment]
okay!

queued: https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/4981/

**Comment by ennru** [comment]
All green, Yay!

**Review by ennru — APPROVED** [review]
LGTM.

**Pull request merged**
