### PR TITLE
bump Scala 2.12 SHA

### PR DESCRIPTION
**Pull request by SethTisue**
in preparation for 2.12.11 release later in February

### CODE REVIEW

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/5448/

**Comment by SethTisue** [comment]
and also, on JDK 14, with the optimizer re-enabled on those repos that use it, to test https://github.com/scala/scala/pull/8676:

https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-jdk14-integrate-community-build/710/

**Comment by SethTisue** [comment]
new runs:

* https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/5452/
* https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-jdk14-integrate-community-build/713/

**Comment by dwijnand** [comment]
```
[scala-xml] [info] Updating {file:/home/jenkins/workspace/scala-2.12.x-jdk14-integrate-community-build/target-0.9.16/project-builds/scala-37de85195694dc9896e867a637cc8fa1ca054acd/projects/343f5b0d8e5d2010fa11c724c13ea5e68a6b9fb5/project-builds/scala-xml-f3b436f6514120ec4ebb0635542b06b18ba79c6a/project/}scala-xml-f3b436f6514120ec4ebb0635542b06b18ba79c6a-build...
FATAL: command execution failed
java.io.IOException
	at hudson.remoting.Channel.close(Channel.java:1422)
	at hudson.remoting.Channel.close(Channel.java:1399)
	at hudson.slaves.SlaveComputer.closeChannel(SlaveComputer.java:849)
	at hudson.slaves.SlaveComputer.kill(SlaveComputer.java:816)
	at hudson.model.AbstractCIBase.killComputer(AbstractCIBase.java:89)
	at jenkins.model.Jenkins.access$2100(Jenkins.java:316)
	at jenkins.model.Jenkins$19.run(Jenkins.java:3515)
	at hudson.model.Queue._withLock(Queue.java:1398)
	at hudson.model.Queue.withLock(Queue.java:1275)
	at jenkins.model.Jenkins._cleanUpDisconnectComputers(Jenkins.java:3509)
	at jenkins.model.Jenkins.cleanUp(Jenkins.java:3387)
	at hudson.WebAppMain.contextDestroyed(WebAppMain.java:379)
...
Caused: hudson.remoting.ChannelClosedException: Channel "hudson.remoting.Channel@2876ac8f:jenkins-worker-behemoth-1": Remote call on jenkins-worker-behemoth-1 failed. The channel is closing down or has closed down
```

**Comment by lrytz** [comment]
re-started https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/5455/

**Comment by SethTisue** [comment]
I think Jenkins restarted itself, maybe for an automatic upgrade. new JDK 14 run, too: https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-jdk14-integrate-community-build/715/

I have already seen in a local run that the optimizer is working on JDK 14.

**Comment by SethTisue** [comment]
green on JDK 8. (if there turns out to be any problem on JDK 11 or 14, I'll handle that separately.)

**Pull request merged**
