### PR TITLE
add pcplod to the community build

### PR DESCRIPTION
**Pull request by fommil**

### CODE REVIEW

**Comment by fommil** [comment]
We won't be pushing anything to the `master` branch without it passing our CI first for 2.12. If we break anything we can create a commit/tag for this.

**Comment by SethTisue** [comment]
hey, really great to have this, the presentation compiler is in need of testing.

test run: https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/886/consoleFull

**Comment by SethTisue** [comment]
it's not critical, but there are a number of deprecation warnings in the build (you'll see them if you build with sbt 0.13.13)

**Comment by SethTisue** [comment]
hmm, it failed with:

```
[pcplod] Processing subproject: example
[pcplod] All Dependencies for subproject example:
[pcplod]    org.scala-lang:scala-compiler:2.12.0-4a487ca-nightly:scala-tool->default,optional(default)
[pcplod]    org.scala-lang:scala-library:2.12.0-4a487ca-nightly:scala-tool->default,optional(default)
[pcplod]    org.ensime:pcplod:1.1.1-dbuildxef61eae2eecd72e50365b2af437db0aa8e830b4d:test
[pcplod]    org.scala-lang:scala-library:2.12.0-4a487ca-nightly
[pcplod]    org.codehaus.janino:janino:2.7.8:test
[pcplod]    org.scalatest:scalatest:3.0.0-dbuildxa08b91b736bf772987e948aa5693e4039eacff20:test
[pcplod]    ch.qos.logback:logback-classic:1.1.7:test
[pcplod]    org.slf4j:slf4j-api:1.7.21:test
[pcplod]    org.slf4j:jul-to-slf4j:1.7.21:test
[pcplod]    org.slf4j:jcl-over-slf4j:1.7.21:test
[pcplod]    org.scala-lang:scala-compiler:2.12.0-4a487ca-nightly
[pcplod]    org.scala-lang:scala-reflect:2.12.0-4a487ca-nightly
[pcplod] Running build: example
[pcplod] [info] Formatting 2 Scala sources {file:/home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.5/project-builds/pcplod-ef61eae2eecd72e50365b2af437db0aa8e830b4d/}example(compile) ...
[pcplod] [info] Packaging /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.5/project-builds/pcplod-ef61eae2eecd72e50365b2af437db0aa8e830b4d/example/target/scala-2.12.0-4a487ca-nightly/example-1.1.1-dbuildxef61eae2eecd72e50365b2af437db0aa8e830b4d-sources.jar ...
[pcplod] [info] Done packaging.
[pcplod] [info] Updating org.ensime:example:1.1.1-dbuildxef61eae2eecd72e50365b2af437db0aa8e830b4d
[pcplod] [info] Wrote /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.5/project-builds/pcplod-ef61eae2eecd72e50365b2af437db0aa8e830b4d/example/target/scala-2.12.0-4a487ca-nightly/example-1.1.1-dbuildxef61eae2eecd72e50365b2af437db0aa8e830b4d.pom
[pcplod] [info] Resolved org.ensime:example:1.1.1-dbuildxef61eae2eecd72e50365b2af437db0aa8e830b4d dependencies
[pcplod] [info] Fetching artifacts of org.ensime:example:1.1.1-dbuildxef61eae2eecd72e50365b2af437db0aa8e830b4d
[pcplod] [info] Fetched artifacts of org.ensime:example:1.1.1-dbuildxef61eae2eecd72e50365b2af437db0aa8e830b4d
[pcplod] [info] Main Scala API documentation to /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.5/project-builds/pcplod-ef61eae2eecd72e50365b2af437db0aa8e830b4d/example/target/scala-2.12.0-4a487ca-nightly/api...
[pcplod] [info] Compiling 2 Scala sources to /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.5/project-builds/pcplod-ef61eae2eecd72e50365b2af437db0aa8e830b4d/example/target/scala-2.12.0-4a487ca-nightly/classes...
[pcplod] [error] /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.5/project-builds/pcplod-ef61eae2eecd72e50365b2af437db0aa8e830b4d/example/src/main/scala/org/ensime/noddy/NoddyPlugin.scala:29: not found: type BackCompat
[pcplod] [error] trait WithPos { this: BackCompat =>
[pcplod] [error]                       ^
[pcplod] [error] /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.5/project-builds/pcplod-ef61eae2eecd72e50365b2af437db0aa8e830b4d/example/src/main/scala/org/ensime/noddy/NoddyPlugin.scala:29: not found: type BackCompat
[pcplod] [error] trait WithPos { this: BackCompat =>
[pcplod] [error]                       ^
[pcplod] [error] 5 errors found
```

@fommil any clue what this might be about? should we exclude the `example` subproject?

**Comment by fommil** [comment]
Yes this means is not picking up scala sources for 2.12. but I pushed those on Saturday, hmm. Are you sure the community build can see these folders

**Comment by fommil** [comment]
Accidental close.

Btw, i don't plan on upgrading sbt usage until, ironically, the macros work in the pc. Otherwise it significantly reduces my ability to write sbt code.

**Comment by fommil** [comment]
If the scala version is defined as scala-2.12.x-integrate-community-build I bet sbt is getting confused by hyphens and doesn't know the use the scala-2.12 cross build folder.

**Comment by SethTisue** [comment]
`CrossVersion.partialVersion` is the tool you need here, as documented at https://github.com/scala/community-builds/wiki/Eligibility

**Comment by SethTisue** [comment]
re: "I pushed those on Saturday", I don't see anything more recent than September 13 on your repository's `master` branch

**Comment by fommil** [comment]
@SethTisue the built-in `sbt` cross build directory is picking up the wrong directory. Does this mean I have to define custom cross build directories? That seems a massive faff, and might be worth sbt updating their defaults.

**Comment by SethTisue** [comment]
@fommil use `CrossVersion.partialVersion`

**Comment by SethTisue** [comment]
I don't know. @dwijnand?

**Comment by SethTisue** [comment]
you didn't respond to "I don't see anything more recent than September 13 on your repository's master branch". there is no scala-2.12 directory in your repository's master branch

**Comment by fommil** [comment]
hmm, no there is a commit 3 days ago, e.g. https://github.com/ensime/pcplod/tree/master/example/src/main symbolic link `scala-2.12`

**Comment by SethTisue** [comment]
my mistake, I somehow had a clone of `fommil/pcplod` instead of `ensime/pcplod`

**Comment by fommil** [comment]
oh damn, did I add the wrong repo?

**Comment by SethTisue** [comment]
no, it was totally my mistake that I made locally on my laptop. it's correct in the PR.

**Comment by SethTisue** [comment]
as for the versioned source directories, after some investigation, I think the problem is in the `scala/scala` repo. the 2.12.x branch there doesn't have a `scalaBinaryVersion` of 2.12. I'll fix that and try running this PR again

**Comment by SethTisue** [comment]
`CrossVersion.partialVersion` was a necessary tool here during the 2.12 RC series (since e.g. the `scalaBinaryVersion` of 2.12.0-RC2 was 2.12.0-RC2, not 2.12), so that's why I was suggesting it and why the doc suggests it. but now that 2.12.0 is tagged, it shouldn't be necessary anymore.

@dwijnand I wonder, though, if it's really the right thing for sbt to use `scalaBinaryVersion` here instead of truncating it to just `s"$major.$minor"`. 2.13 will have an RC cycle too, and so even if people take that `CrossVersion` stuff out of their builds now, it won't be too long before they'll have to add it right back in again

**Comment by SethTisue** [comment]
I'll need to rebase https://github.com/scala/scala/pull/5389, wait it for to pass CI, merge it, and then wait for a nightly build to succeed. so let's come back to this in a day or two

**Comment by dwijnand** [comment]
@SethTisue I agree with you using `CrossVersion.binary` sounds like a better default. But it might be something that's a little too transparent to change in a minor release and must go into 1.0.

Opened https://github.com/sbt/sbt/issues/2819

**Comment by fommil** [comment]
@dwijnand is there maybe a hack for the 0.13.13 line?

**Comment by dwijnand** [comment]
Sorry?

**Comment by SethTisue** [comment]
> is there maybe a hack for the 0.13.13 line?

do something like

```
def scalaPartV = Def setting (CrossVersion partialVersion scalaVersion.value)

lazy val crossVersionSharedSources: Seq[Setting[_]] =
  Seq(Compile, Test).map { sc =>
    (unmanagedSourceDirectories in sc) ++= {
      (unmanagedSourceDirectories in sc).value.map { dir =>
        scalaPartV.value match {
          case Some((2, y)) if y == 10 => new File(dir.getPath + "_2.10")
          case Some((2, y)) if y >= 11 => new File(dir.getPath + "_2.11+")
        }
      }
    }
  }
```

tweaked as appropriate for your project. this example is from milessabin/macro-compat

multiple projects in the community build have something like this in their builds

**Comment by fommil** [comment]
nice, I didn't know about the `+` notation, well I guess you're making it up.

**Comment by dwijnand** [comment]
It's not a notation, it's just to convey the meaning.

**Comment by fommil** [comment]
ok, I've pushed a similar workaround to master so this should work now

**Comment by SethTisue** [comment]
new test run: https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/895/consoleFull (404 til Jenkins finishes braiding his hair)

**Comment by SethTisue** [comment]
thanks Sam!

**Pull request merged**
