### PR TITLE
Revert "freeze spray-json-shapeless and pcplod"

### PR DESCRIPTION
**Pull request by SethTisue**
This reverts commit d8ee267ed96f14f13bca8bf309350ee8fb328873.

This can be merged once sbt-sensible 1.0.6 hits Maven Central
(@fommil says it's on its way there already)

### CODE REVIEW

**Comment by fommil** [comment]
it's landed already

**Comment by SethTisue** [comment]
test run: https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/968/consoleFull (404 til Jenkins splits his car into motorcycles)

**Comment by SethTisue** [comment]
@fommil what do you make of the pcplod failure at https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/968/consoleFull ?

```
145e8052e24f38cdd9625c78b1c3c703eb64a835/example/src/main/scala/org/ensime/noddy/NoddyPlugin.scala:29: not found: type BackCompat
[pcplod] [error] trait WithPos { this: BackCompat =>
[pcplod] [error]                       ^
```

**Comment by fommil** [comment]
Huh? Must be a cross version thing again. I'll have a look tonight.

**Comment by fommil** [comment]
I see the problem. I forgot to migrate the ncala cross version hack to sbt-sensible. I'll do that tonight and bump the version.

**Comment by fommil** [comment]
fix is disting to maven central, will push an update to pcplod in 30 mins or an hour to give it a good time period. My tests don't catch this because I don't have any unusually versioned scalas in my cross builds. By being in sbt-sensible, it should mean that all my projects are immune to the problem.

**Comment by fommil** [comment]
ok, it is disted for me and upgrade for pcplod is pushed.

**Comment by SethTisue** [comment]
new test run: https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/974/consoleFull

**Comment by SethTisue** [comment]
thanks Sam!

**Pull request merged**
