### PR TITLE
(Don't merge) Bump up to sbt 0.13.10-M1

### PR DESCRIPTION
**Pull request by eed3si9n**
This is to test the quality of sbt 0.13.10 release candidates.

/cc @SethTisue

### CODE REVIEW

**Comment by SethTisue** [comment]
test run: https://scala-ci.typesafe.com/job/scala-2.11.x-integrate-community-build/211/consoleFull (link will 404 until worker comes online)

**Comment by eed3si9n** [comment]
```
[akka] :: problems summary ::
[akka] :::: WARNINGS
[akka]      [NOT FOUND  ] org.scala-lang.modules#scala-pickling_2.10;0.10.1!scala-pickling_2.10.jar (0ms)
[akka] 
[akka]  ==== maven-cache: tried
[akka] 
[akka]    https://scala-ci.typesafe.com/artifactory/central/org/scala-lang/modules/scala-pickling_2.10/0.10.1/scala-pickling_2.10-0.10.1.jar
[akka] 
[akka]      ::::::::::::::::::::::::::::::::::::::::::::::
[akka] 
[akka]      ::              FAILED DOWNLOADS            ::
[akka] 
[akka]      :: ^ see resolution messages for details  ^ ::
[akka] 
[akka]      ::::::::::::::::::::::::::::::::::::::::::::::
[akka] 
[akka]      :: org.scala-lang.modules#scala-pickling_2.10;0.10.1!scala-pickling_2.10.jar
[akka] 
[akka]      ::::::::::::::::::::::::::::::::::::::::::::::
[akka] 
[akka] 
[akka] 
[akka] :: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
[akka] download failed: org.scala-lang.modules#scala-pickling_2.10;0.10.1!scala-pickling_2.10.jar
[akka] Error during sbt execution: Error retrieving required libraries
[akka]   (see /home/jenkins/workspace/scala-2.11.x-integrate-community-build/./target-0.9.5/sbt-base-dir/extractor/boot/update.log for complete log)
[akka] Error: Could not retrieve sbt 0.13.10-M1
```

could you "retest this please" please?

**Comment by retronym** [comment]
https://scala-ci.typesafe.com/job/scala-2.11.x-integrate-community-build/212/

**Comment by SethTisue** [comment]
peculiar. but, apparently just a transient error

**Comment by dwijnand** [comment]
After waiting all day it has aborted :(

https://scala-ci.typesafe.com/job/scala-2.11.x-integrate-community-build/212/consoleFull

**Comment by SethTisue** [comment]
successfully built projects are cached, so progress made in an aborted run isn't lost. very likely this one will finish: https://scala-ci.typesafe.com/job/scala-2.11.x-integrate-community-build/213/consoleFull

**Comment by dwijnand** [comment]
Oh excellent. Come on little 213 I believe.

**Comment by dwijnand** [comment]
@eed3si9n Could you push the tag for 0.13.10-M1 please? I'm not sure what fixes are included in it.

**Comment by dwijnand** [comment]
No SHA in the ivy metadata :(
http://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/main/0.13.10-M1/ivys/

**Comment by SethTisue** [comment]
why M1 and not RC1?

**Comment by SethTisue** [comment]
one more: https://scala-ci.typesafe.com/job/scala-2.11.x-integrate-community-build/214/consoleFull (404 til the worker spins up)

**Comment by dwijnand** [comment]
RC1 was our first release candidate, but https://github.com/sbt/sbt/issues/2411 was found.

So M1 is our current, less certain, milestone release.

I think it's probably sbt/sbt@e64b011 which is essentially https://github.com/sbt/sbt/pull/2418 to fix https://github.com/sbt/sbt/issues/2411.

**Comment by dwijnand** [comment]
Oh and thanks for the rebuild.

It's failed to download https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/interface/0.13.5/jars/interface.jar for some reason. Could you poke it again please?

**Comment by lrytz** [comment]
https://scala-ci.typesafe.com/job/scala-2.11.x-integrate-community-build/215/ coming up

**Comment by lrytz** [comment]
hmm, same failure - the exact error:

```
[Play2-core] [info] Compiling 2 Scala sources to /home/jenkins/workspace/scala-2.11.x-integrate-community-build/target-0.9.5/project-builds/Play2-core-14d06b3dbb5fb2cd6fa61d7d6614d54ccba80f08/framework/src/play-datacommons/target/scala-2.11/classes...
[Play2-core] [info] Attempting to fetch org.scala-sbt % compiler-interface % 0.13.5. This operation may fail.
[Play2-core] [info] Resolving org.scala-sbt#compiler-interface;0.13.5 ...
[Play2-core] [info] Resolving org.scala-sbt#compiler-interface;0.13.5 ...
[Play2-core] [info] Resolving org.scala-lang#scala-library;2.10.4 ...
[Play2-core] [info] Resolving org.scala-lang#scala-library;2.10.4 ...
[Play2-core] [info] Resolving org.scala-sbt#interface;0.13.5 ...
[Play2-core] [info] Resolving org.scala-sbt#interface;0.13.5 ...
[Play2-core] [warn]     [NOT FOUND  ] org.scala-sbt#compiler-interface;0.13.5!compiler-interface.jar(src) (371ms)
[Play2-core] [warn] ==== typesafe-ivy-releases: tried
[Play2-core] [warn]   https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/compiler-interface/0.13.5/srcs/compiler-interface-sources.jar
[Play2-core] [info] downloading https://scala-ci.typesafe.com/artifactory/central/org/scala-lang/scala-library/2.10.4/scala-library-2.10.4.jar ...
[Play2-core] [info]     [SUCCESSFUL ] org.scala-lang#scala-library;2.10.4!scala-library.jar (154ms)
[Play2-core] [info] downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/interface/0.13.5/jars/interface.jar ...
[Play2-core] [info]     [SUCCESSFUL ] org.scala-sbt#interface;0.13.5!interface.jar (1604ms)
[Play2-core] [warn]     ::::::::::::::::::::::::::::::::::::::::::::::
[Play2-core] [warn]     ::              FAILED DOWNLOADS            ::
[Play2-core] [warn]     :: ^ see resolution messages for details  ^ ::
[Play2-core] [warn]     ::::::::::::::::::::::::::::::::::::::::::::::
[Play2-core] [warn]     :: org.scala-sbt#compiler-interface;0.13.5!compiler-interface.jar(src)
[Play2-core] [warn]     ::::::::::::::::::::::::::::::::::::::::::::::
[Play2-core] sbt.InvalidComponent: Couldn't retrieve source module: org.scala-sbt:compiler-interface:0.13.5:component
[Play2-core]    at sbt.compiler.IvyComponentCompiler$$anonfun$sbt$compiler$IvyComponentCompiler$$compileAndInstall$1$$anonfun$apply$2$$anonfun$apply$mcV$sp$1.apply(ComponentCompiler.scala:124)
```

**Comment by dwijnand** [comment]
Thanks @lrytz, sorry I miss-read, the real blocking error seems to be

```
sbt.InvalidComponent: Couldn't retrieve source module: org.scala-sbt:compiler-interface:0.13.5:component
```

I'm not 100% sure what that is. @eed3si9n @Duhemm any ideas?

**Comment by Duhemm** [comment]
sbt fails to find the compiler interface. The question is why does it try to get it in version 0.13.5? We changed the way the compiler interface and bridge are published with `publishMavenStyle := true` last summer if I remember correctly.

**Comment by SethTisue** [comment]
several subprojects (`Play-Exceptions` and `Build-Link`) build successfully, then the failure occurs during `[Play2-core] Processing subproject: Play-DataCommons`. not sure yet why that one might be special.

here is a log of successful build of play2-core from a recent community build run using sbt 0.13.9: https://gist.github.com/SethTisue/2d9761ffcb68f3a6f05a. Note that the string `0.13.5` doesn't appear in the log. So whatever changed here, it has to do with why 0.13.5 would be retrieved at all — it's not a question of why the retrieval failed. We don't want the retrieval to happen at all.

`framework/project/Build.scala` has `val buildSbtVersion = propOr("play.sbt.version", "0.13.5")`, so perhaps it's as simple as telling dbuild to set the play.sbt.version system property.

**Comment by dwijnand** [comment]
Who can be cc'd in from play that might be able to help here?

**Comment by SethTisue** [comment]
trying it myself here: https://scala-ci.typesafe.com/job/scala-2.11.x-integrate-community-build/216/consoleFull (going slowly so far because of cascading rebuilds of unrelated, updated dependencies)

**Comment by SethTisue** [comment]
hey, the play2-core build succeeded. so @eed3si9n, I think all you need to do is incorporate https://github.com/SethTisue/community-builds/commit/218687a6352d5c09c74ffd3e51724288c132b0fb into this PR

**Comment by SethTisue** [comment]
I mean, I guess some possibility remains that the fact that this is now needed means there has been some weird regression in sbt. promising avenue of investigation, or rabbit hole with no rabbit at the bottom? I don't know.

**Comment by dwijnand** [comment]
So play2-core was the only one out of 51 community build projects that failed to cleanly upgrade to 0.13.10-M1. Am I reading that right? (I expected a lot more projects to be honest) Thanks Seth.

**Comment by SethTisue** [comment]
> So play2-core was the only one out of 51 community build projects that failed to cleanly upgrade to 0.13.10-M1. Am I reading that right?

yup. I mean, there are entire huge categories of regressions this won't catch (those having to do with resolving binary dependencies, for example, or with publishing). but still, it's encouraging.

**Comment by SethTisue** [comment]
I guess we can just close this, for now anyway.

**Comment by jroper** [comment]
My recommendation would be to move to the Play 2.4.x branch - Play doesn't read its sbt version from a system property anymore, it uses whatever version of sbt is configured in build.properties.

**Comment by SethTisue** [comment]
> My recommendation would be to move to the Play 2.4.x branch

I believe that requires Java 8, so the 2.11.x(-jdk6) community build must stay on Play 2.3.

The 2.11.x-jdk8 and 2.12.x community builds are already on Play 2.4.

**Comment by dwijnand** [comment]
Shall I open "don't merge" pull requests against those to further test sbt 0.13.10-M1?

**Comment by SethTisue** [comment]
sure!

**Comment by jroper** [comment]
Ok, well it's not likely that we're going to fix this, as Play 2.3 is nearing end of life, and back porting the fixes we did in Play 2.4 to our build is a high effort high risk task that we don't have the time to do.

**Comment by SethTisue** [comment]
> not likely that we're going to fix this

no worries, it's easily worked around

**Pull request closed without merging**
