### PR TITLE
add scala-clippy

### PR DESCRIPTION
**Pull request by SethTisue**
trying to get sttp green again

### CODE REVIEW

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/4203/

**Comment by SethTisue** [comment]
compile errors, first one is

```
[scala-clippy] [error] /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.16/project-builds/scala-clippy-8f5e9ba4bcce2b19544717ec09d1690d67e6898b/plugin/src/main/scala/com/softwaremill/clippy/Highlighter.scala:132: type mismatch;
[scala-clippy] [error]  found   : scalaparse.Scala.Semis.type (with underlying type fastparse.all.Parser[Unit])
[scala-clippy] [error]  required: ?{def ?: ?}
[scala-clippy] [error] Note that implicit conversions are not applicable because they are ambiguous:
[scala-clippy] [error]  both method parserApi in object all of type [T, V](p: T)(implicit c: T => fastparse.core.Parser[V,Char,String])fastparse.core.ParserApi[V,Char,String]
[scala-clippy] [error]  and method parserApi2 in class Wrapper2 of type [T, V](p0: T)(implicit c: T => fastparse.noApi.P[V])scalaparse.Scala.WhitespaceApi2[V]
[scala-clippy] [error]  are possible conversion functions from scalaparse.Scala.Semis.type to ?{def ?: ?}
[scala-clippy] [error]     P(Semis.? ~ (!blockSep ~ Statement ~~ WS ~~ (Semis | End)).!.repX)
[scala-clippy] [error]       ^
```

probably a fastparse version mismatch?

**Comment by SethTisue** [comment]
@adamw I'm abandoning this effort. in order to have scala-clippy in the community build, y'all would need to update it to use a modern version of fastparse

the next thing I'll try to get sttp green again is to see if we can disable or ignore scala-clippy there

**Comment by adamw** [comment]
Ah, it's the build plugin. I'll drop the clippy dep from there. Give me a couple of hours :)

**Comment by adamw** [comment]
Ah sonatype was fast this time :) Build updated, the clippy dependency should be gone

**Pull request closed without merging**
