### PR TITLE
2.13: new Scala SHA

### PR DESCRIPTION
**Pull request by SethTisue**
~https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/2615/~
~https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/2624/~
~https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/2625/~
~https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/2627/~
https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/2628/

### CODE REVIEW

**Comment by SethTisue** [comment]
this has the same [Scalameta failure](https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/2615/artifact/logs/scalameta-build.log) I described at https://github.com/scala/community-build/pull/1384#issuecomment-798792714 — it has to do with the `reportSuspendedMessages` change in scala/scala#9449

@lrytz you didn't respond to that — are you planning on looking into this, or do you want me to deal with it myself?

**Comment by lrytz** [comment]
I missed it last time, sorry. Will take a look next week.

**Comment by SethTisue** [comment]
Lukas [writes](https://github.com/scala/community-build/pull/1384#issuecomment-809452621):

> the fix should be trivial: `forceWarnings` should again be a no-op for 2.13.6, as it is for 2.13.1 (https://github.com/scalameta/scalameta/blob/master/semanticdb/scalac/library/src/main/scala-2.13.1/scala/meta/internal/semanticdb/scalac/VersionCompilerOps.scala).
>
>I'm not sure how exactly what you need to do in order to make it work in the community build, until 2.13.6 is out.

**Comment by SethTisue** [comment]
@lrytz that did it. thanks!

**Comment by SethTisue** [comment]
one more failure: [blaze](https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/2625/artifact/logs/blaze-build.log)

```
[blaze] [error] /home/jenkins/workspace/scala-2.13.x-jdk11-integrate-community-build/target-0.9.17/project-builds/blaze-5f5ec77ce1f780dd59b6304759401718f47295bc/http/src/main/scala/org/http4s/blaze/http/http1/server/Http1ServerParser.scala:37:26: weaker access privileges in overriding
[blaze] [error] def submitRequestLine(methodString: String, path: String, scheme: String, majorVersion: Int, minorVersion: Int): Boolean (defined in class Http1ServerParser)
[blaze] [error]   override should be public
[blaze] [error]   override protected def submitRequestLine(
[blaze] [error]                          ^
```

which I recall already hitting when we did a trial CB run before merging https://github.com/scala/scala/pull/9525 . it should work to just fork it and make the needed source adjustment

**Comment by SethTisue** [comment]
now http4s is running afoul of scala/scala#9336:

```
[http4s] [error] /home/jenkins/workspace/scala-2.13.x-jdk11-integrate-community-build/target-0.9.17/project-builds/http4s-d35ab4a78b2b5b39eee74c29418609e7bdf5238f/core/src/main/scala/org/http4s/multipart/Part.scala:33:9: annotation argument needs to be a constant; found: scala.Predef.augmentString("Empty parts are not allowed by the multipart spec, see: https://tools.ietf.org/html/rfc7578#section-4.2\n       Moreover, it allows the creation of potentially incorrect multipart bodies\n    ").stripMargin
[http4s] [error]     """.stripMargin,
[http4s] [error]         ^
[http4s] [error] one error found
[http4s] [error] /home/jenkins/workspace/scala-2.13.x-jdk11-integrate-community-build/target-0.9.17/project-builds/http4s-d35ab4a78b2b5b39eee74c29418609e7bdf5238f/core/src/main/scala/org/http4s/multipart/Part.scala:33:9: annotation argument needs to be a constant; found: scala.Predef.augmentString("Empty parts are not allowed by the multipart spec, see: https://tools.ietf.org/html/rfc7578#section-4.2\n       Moreover, it allows the creation of potentially incorrect multipart bodies\n    ").stripMargin
[http4s] [error]     """.stripMargin,
[http4s] [error]         ^
```

but it's an easy fix

**Pull request merged**
