### PR TITLE
Add ScalaFX.

### PR DESCRIPTION
**Pull request by jpsacha**
Add ScalaFX to community builds with basic setup.

### CODE REVIEW

**Comment by SethTisue** [comment]
test run: https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/891/consoleFull

**Comment by SethTisue** [comment]
```
[scalafx] [error] /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.5/project-builds/scalafx-95067f4f190cbe688f76dd78b4c753cd97558030/scalafx/src/main/scala/scalafx/animation/Animation.scala:29: not found: object javafx
[scalafx] [error] import javafx.{animation => jfxa, event => jfxe, util => jfxu}
[scalafx] [error]        ^
```

how is the `javafx` package supposed to get on the classpath? I don't see anything in the build that adds it. the community build uses OpenJDK, maybe that's the problem?

**Comment by jpsacha** [comment]
I will need to figure out how to handle OpenJDK, possibly JavaFX jar just need to be explicitly added to path, as it used to be for Java 7. It should be part of OpenJDK already.

**Comment by jpsacha** [comment]
Do you run test on Linux? Ubuntu?
Look that Ubuntu requires installation of [openjfx package](http://packages.ubuntu.com/xenial/openjfx)

**Comment by jpsacha** [comment]
I tested on Ubuntu 16.04 using OpenJDK 1.8.0_111. It is sufficient to install the [openjfx package](http://packages.ubuntu.com/xenial/openjfx). No changes needed in ScalaFX build files.

**Comment by SethTisue** [comment]
this will need a little work over in the scala/scala-jenkins-infra repo, then

**Comment by SethTisue** [comment]
sorry for the delay — I got busy with other work, but I have some more time now again.

are you still interested in pursuing this? if so, please rebase.

...and then I'll experiment with getting javafx installed. if you know of any sample for installing javafx using Chef, that would be helpful; we don't install packages by hand if we can possibly avoid it.

**Comment by jpsacha** [comment]
@SethTisue I rebased the PR. 
I do not know how to install openjfx with Chef.

**Comment by SethTisue** [comment]
closing for inactivity. while I would like to include ScalaFX, the cost/benefit is probably not there since it has special requirements

**Pull request closed without merging**
