### PR TITLE
sbt 1.3.6 (was 1.3.5)

### PR DESCRIPTION
**Pull request by SethTisue**

### CODE REVIEW

**Comment by SethTisue** [comment]
queued: https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/2946/

**Comment by eed3si9n** [comment]
👀

**Comment by SethTisue** [comment]
note that two projects progressed (sttp no longer stuck on 1.2.8, twirl no longer stuck on 1.3.4)

**Comment by eed3si9n** [comment]
Nice

**Pull request merged**
