### PR TITLE
add github4s (and base64)

### PR DESCRIPTION
**Pull request by SethTisue**
test run: https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/2095/consoleFull ~~(404 til Jenkins finishes mixing 4 parts water with 1 part alcohol-based cleaning solution)~~

### CODE REVIEW

**Comment by SethTisue** [comment]
```
[github4s] Processing subproject: github4sJVM
[github4s] [error] **** Missing dependency: the library io.circe#circe-core is not provided (in space "default") by any project in this configuration file.
```

so this needs to wait on #622

**Comment by SethTisue** [comment]
new test run now that we have circe-core: https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/2107/consoleFull

**Comment by SethTisue** [comment]
```
[github4s] [error] **** Missing dependency: the library io.circe#circe-generic is not provided (in space "default") by any project in this configuration file.
```

so, this will need to wait on #623, too

**Comment by SethTisue** [comment]
let's try again now that we have circe: https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/2142/consoleFull ~~(404 til Jenkins finishes respackling the rumpus room)~~

**Comment by SethTisue** [comment]
fyi @BenFradet

**Comment by BenFradet** [comment]
Here to help :+1:

**Comment by SethTisue** [comment]
fyi @marklister

**Comment by SethTisue** [comment]
@BenFradet at https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/2153/consoleFull I'm seeing

```
[github4s] [info] *** 24 TESTS FAILED ***
[github4s] [error] Failed tests:
[github4s] [error] 	github4s.unit.ApiSpec
[github4s] [error] 	github4s.integration.IntegrationSpec
```

details behind the link. for now I'll just make it so we compile your tests but don't run them, but if you see a way to address the failures, let me know

**Comment by SethTisue** [comment]
green run (without running github4s tests): https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/2155/consoleFull

**Comment by BenFradet** [comment]
@SethTisue There are integrations tests that rely on an GitHub API key set as [the `GITHUB4S_ACCESS_TOKEN` env variable](https://github.com/47deg/github4s/blob/master/build.sbt#L17)

**Comment by SethTisue** [comment]
@BenFradet hmm, I don't have a convenient way to get an API key in without revealing it publicly, and besides, running tests like that, that involve contacting live services, is somewhat outside the usual scope of the community build

if you can segregate those tests to their own subproject, or make them skippable via an env variable or whatever, that'd be cool, otherwise I'll (sorry) just leave the test suite disabled

**Comment by BenFradet** [comment]
I'll work towards making those tests skippable, I'll update this thread once I'm done.

**Pull request merged**
