### PR TITLE
add sttp and fs2-reactive-streams

### PR DESCRIPTION
**Pull request by SethTisue**
fyi @adamw

### CODE REVIEW

**Comment by SethTisue** [comment]
test run: https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/2077/consoleFull ~~(404 til Jenkins finishes brushing the dust and cobwebs off a newly discovered cache of vintage Typesafe swag)~~

**Comment by SethTisue** [comment]
let's try again, with `sbt.version` set appropriately this time: https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/2078/consoleFull

**Comment by SethTisue** [comment]
and again, after some scalafmt-related tweaking: https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/2079/consoleFull

**Comment by SethTisue** [comment]
these should be easy enough to address, either by disabling the subprojects in question, or adding the libraries:
* `[sttp] [warn] **** Missing dependency: the library com.github.zainab-ali#fs2-reactive-streams is not provided (in space "default") by any project in this configuration file.`
* `[sttp] [warn] **** Missing dependency: the library io.circe#circe-parser is not provided (in space "default") by any project in this configuration file.` are easy enough to understand

but I don't know wtf this is:

```
[sttp] [error] Modules were resolved with conflicting cross-version suffixes in {file:/home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.9/project-builds/sttp-e1fdb9bddff73c71fe68ffdfb5cfe4444cb2dc77/}tests:
[sttp] [error]    org.typelevel:cats-macros <none>, _2.12
[sttp] [error]    org.typelevel:cats-effect <none>, _2.12
[sttp] [error]    org.typelevel:cats-kernel <none>, _2.12
[sttp] [error]    org.typelevel:machinist <none>, _2.12
[sttp] [error]    org.typelevel:cats-core <none>, _2.12
```

**Comment by SethTisue** [comment]
new test run: https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/2096/consoleFull ~~(404 til Jenkins finishes swimming with the manatees)~~

**Comment by SethTisue** [comment]
let's try that again with merged changes from 2.12.x head: https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/2099/consoleFull ~~(404 til Jenkins finishing picking a big of hunk of he doesn't even want to know what it is out of from between his teeth)~~

**Comment by SethTisue** [comment]
```
[sttp] [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[sttp] [warn] 	::          UNRESOLVED DEPENDENCIES         ::
[sttp] [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[sttp] [warn] 	:: com.softwaremill.sttp#async-http-client-backend-fs2;0.0.20-dbuildx98c95f489f1d4f1bfc0c4451cee79baee72091be: not found
[sttp] [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
```

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/2101/consoleFull

**Comment by SethTisue** [comment]
really not sure what that error is about. further commits haven't helped

**Comment by SethTisue** [comment]
well, I wanted to finish this up, but there's just too much else on my plate right now. I threw it on the list at https://github.com/scala/community-builds/issues/161 and linked to this PR in case I decide to take it back up (or somebody else wants to work on it)

**Comment by SethTisue** [comment]
says @adamw:
> I just noticed this & a (so far failed) attempt to add sttp. No idea how this works, but if you would need some help on the sttp's build, let me know :)

**Comment by adamw** [comment]
@SethTisue yes, well, since then sbt has been updated, and as I understand the build should work fine when excluding some modules but it doesn't - is it something in sttp's build which prevents this from working?

**Comment by SethTisue** [comment]
@adamw I was confused before, I think.... there is no mysterious problem here, it's just that fs2-reactive-streams needs be in there first before we can add sttp. I'll try it sometime soon-ish and see how it goes

**Comment by SethTisue** [comment]
new test run: https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/2395/consoleFull (404 til Jenkins finishes his holiday secret-Santa party shopping)

**Comment by SethTisue** [comment]
tons of compile errors in fs2-reactive-streams, e.g.:

```
[fs2-reactive-streams] [error] /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.9/project-builds/fs2-reactive-streams-5fb9cbb5bebf7cef2afd2cf8e7e4e97f82d7964c/core/src/main/scala/fs2/interop/reactivestreams/StreamSubscriber.scala:8:8: object Promise is not a member of package fs2.async
[fs2-reactive-streams] [error] import fs2.async.{Promise, Ref}
[fs2-reactive-streams] [error]        ^
```

**Comment by SethTisue** [comment]
I suggest we revisit this after cats 1.0.0 final is out and after the whole Typelevel ecosystem has pushed that through (including a final fs2 0.10 release that uses it). Wading into this stuff is currently too fragile

**Comment by SethTisue** [comment]
ticket on the cats 1.0 upgrade: #653

**Comment by SethTisue** [comment]
the cats 1.0 upgrade is finished. over in our sttp fork I merged master onto my community-build-2.12 branch, and here in this repo I merged 2.12.x into this PR

**Comment by SethTisue** [comment]
new test run queued: https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/2579/consoleFull (404 for now, Jenkins is busy)

**Comment by SethTisue** [comment]
fs2-reactive-streams fails to compile. the first error is

```
[fs2-reactive-streams] [error] /Users/tisue/community.212/target-0.9.9/project-builds/fs2-reactive-streams-60051abc8aef0da66fb828297f5c53dfbbaa2c0d/core/src/main/scala/fs2/interop/reactivestreams/StreamSubscription.scala:106:12: not found: type AsyncPull
[fs2-reactive-streams] [error]       aap: AsyncPull[F, Option[(Segment[A, Unit], Stream[F, A])]],
[fs2-reactive-streams] [error]            ^
```

over in the fs2 repo I see that `AsyncPull` was removed by https://github.com/functional-streams-for-scala/fs2/pull/1066

I imagine once fs2 0.10 comes out, at some point fs2-reactive-streams will upgrade to it and we could try again. closing for now

**Comment by SethTisue** [comment]
zainab-ali/fs2-reactive-streams@c534a8f3bf3348a8cf85c78bfe594b968031e48a has the upgrade, so this is now worth a try-again

**Comment by SethTisue** [comment]
https://github.com/zainab-ali/fs2-reactive-streams/pull/43 should enable a try-again on this

**Comment by SethTisue** [comment]
@adamw I think you'll need to upgrade sttp to fs2 0.10 to make this error go away. currently you're on 0.10.0-M10. I think the way to fix it is to move to `"com.github.zainab-ali" %% "fs2-reactive-streams" % "0.5.0"`

```
[sttp] [error] /Users/tisue/community.212/target-0.9.9/project-builds/sttp-b0a17e3b67acebf6e11f3c2d33519f5590682631/tests/src/test/scala/com/softwaremill/sttp/streaming/AsyncHttpClientFs2StreamingTests.scala:27:8: value runFoldMonoid is not a member of fs2.Stream[cats.effect.IO,String]
[sttp] [error] possible cause: maybe a semicolon is missing before `value runFoldMonoid'?
[sttp] [error]       .runFoldMonoid
[sttp] [error]        ^
```

**Comment by SethTisue** [comment]
for now I'll simply exclude your `tests` subproject from the community build, so we can get this merged

**Comment by SethTisue** [comment]
fyi @zainab-ali

**Comment by adamw** [comment]
@SethTisue updated to latest `fs2-reactive-streams`

**Comment by SethTisue** [comment]
@adamw where? did you push the change?

**Comment by adamw** [comment]
@SethTisue there was a connection error during push, now it's pushed :)

**Comment by SethTisue** [comment]
thanks! 7f64fdc01ecd421732ce7cae6e946e4987b5baec re-adds the subproject in question

**Pull request merged**
