### PR TITLE
build sbt 1.2.0

### PR DESCRIPTION
**Pull request by SethTisue**
not building anything *with* sbt 1.2.0 yet (awaiting dbuild support),
just building sbt and its modules

### CODE REVIEW

**Comment by SethTisue** [comment]
fyi @eed3si9n @dwijnand 

test run: https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/3225/

**Review by dwijnand — APPROVED** [review]

**Comment by SethTisue** [comment]
the all-the-same version numbers are very soothing to my OCD, thanks for that

**Comment by SethTisue** [comment]
```
[error]    Project "sbt" uses org.scala-sbt:zinc-classpath:jar (build level 0, space "scala.main.jawn_0_10"), which is provided by: "zinc".
[error]    Project "sbt" uses org.scala-sbt:compiler-interface:jar (build level 0, space "scala.main.jawn_0_10"), which is provided by: "zinc".
[error]    Project "sbt" uses org.scala-sbt:compiler-bridge:jar (build level 0, space "scala.main.jawn_0_10"), which is provided by: "zinc".
[error]    Project "sbt" uses org.scala-sbt:zinc:jar (build level 0, space "scala.main.jawn_0_10"), which is provided by: "zinc".
[error]    Project "sbt" uses org.scala-sbt:zinc-apiinfo:jar (build level 0, space "scala.main.jawn_0_10"), which is provided by: "zinc".
[error]    Project "sbt" uses org.scala-sbt:zinc-compile:jar (build level 0, space "scala.main.jawn_0_10"), which is provided by: "zinc".
[error]    Project "sbt" uses org.scala-sbt:zinc-ivy-integration:jar (build level 0, space "scala.main.jawn_0_10"), which is provided by: "zinc".
[error]    Project "zinc" uses org.scala-sbt:completion:jar (build level 0, space "scala.main.jawn_0_10"), which is provided by: "sbt".
[error] The graph is not acyclic.
```

to resolve the circularity, it looks I like I need to split sbt-completion off from sbt

Eugene, Dale, do you mean for the sbt and zinc repos to have this cyclic dependency between them...?

**Comment by SethTisue** [comment]
new test run: 
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/3227/ (404 for now)

**Comment by dwijnand** [comment]
No I was against the change, which was merged.

**Comment by SethTisue** [comment]
hmm

```
[sbt-util] [info] LogExchangeSpec:
[sbt-util] [info] LogExchange.stringTypeTagThrowable
[sbt-util] [info] - should match real StringTypeTag[Throwable] *** FAILED ***
[sbt-util] [info]   scala.Throwable did not equal Throwable (LogExchangeSpec.scala:15)
```

any idea what's up there...?

**Comment by eed3si9n** [comment]
To avoid circular dependency between sbt and Zinc, bloopScripted subproject should be excluded from the community build.

**Comment by eed3si9n** [comment]
> [sbt-util] [info] - should match real StringTypeTag[Throwable] *** FAILED ***

It's a test for https://github.com/sbt/util/pull/153 that was added in https://github.com/sbt/util/pull/158. StringTypeTag (https://github.com/sbt/util/blob/7e9e4879aad0d7f004e032da47c7e835c88d2369/internal/util-logging/src/main/scala/sbt/internal/util/StringTypeTag.scala) is our typetag that uses String to capture the type name using `tpe.toString`.
Did `tpe.toString` change from `scala.Throwable` to `Throwable`?

**Comment by SethTisue** [comment]
> Did tpe.toString change from scala.Throwable to Throwable

historically it has been inconsistent whether `scala.` is included, or not, here.

I feel like a PR landed recently-ish, like in the last 6 months or so, that made the behavior consistent. I think it was a PR by @retronym. I looked for it now but couldn't find it.

would it be hard to make the test accept either result?

**Comment by SethTisue** [comment]
regardless, in the context of the community build I can just `set excludeFilter in (Test, unmanagedSources) in utilLogging := HiddenFileFilter || "StringTypeTag.scala"`

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/3237/

**Comment by dwijnand** [comment]
https://github.com/sbt/util/pull/172

**Comment by dwijnand** [comment]
whip it harder, cos it's merged 🙂

**Comment by SethTisue** [comment]
okay this is now green, but before merging, I also want to try Eugene's suggestion to avoid the sbt/sbt-completion split:

> To avoid circular dependency between sbt and Zinc, bloopScripted subproject should be excluded from the community build.

**Comment by SethTisue** [comment]
in local test:

```
[sbt:error] AsyncLogger error handling event seq=174437, value='':
[sbt:error] java.lang.BootstrapMethodError: call site initialization exception
[sbt:error] 	at java.lang.invoke.CallSite.makeSite(CallSite.java:341)
```

**Comment by SethTisue** [comment]
let's try it on Jenkins: https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/3243/

**Comment by SethTisue** [comment]
gah, on Jenkins, at the end of the log it says `sbt.ParseKey` failed but the string `ParseKey` doesn't occur anywhere else in the log

maybe transient? let's find out https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/3245/

**Comment by SethTisue** [comment]
gah `[sbt:error] java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: GC overhead limit exceeded`

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/3247/

**Comment by SethTisue** [comment]
run 3247 has the same thing again where it says `sbt.ParseKey` failed but there doesn't seem to be anything in the log that indicates how/why

@eed3si9n is this worth investigating, or should I just exclude the test?

**Comment by eed3si9n** [comment]
Let's exclude the test for now. There is a corner case in slash syntax that's ambiguous, but in reality it hasn't been a real issue.

**Comment by SethTisue** [comment]
~~https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/3252/~~ https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/3254/

**Comment by dwijnand** [comment]
FYI that's https://github.com/sbt/sbt/issues/3893

**Pull request merged**
