### PR TITLE
unfork paradise, use 2.12.2 branch

### PR DESCRIPTION
**Pull request by SethTisue**
fyi @xeno-by

### CODE REVIEW

**Comment by SethTisue** [comment]
test run: https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/1438/consoleFull (404 while Jenkins finishes replacing the battery in the laser cat toy)

**Comment by SethTisue** [comment]
@xeno-by 

```
[macro-paradise] [info] - ad-hoc macros expand *** FAILED ***
...
[macro-paradise] [info] *** 1 TEST FAILED ***
[macro-paradise] [error] Failed tests:
[macro-paradise] [error] 	Repl
```

**Comment by xeno-by** [comment]
This is strange. Everything works on my machine. What environment / what SHA are you using to run tests?

**Comment by SethTisue** [comment]
scala/scala@d61301de77fffabfc6d0a1331589e9287db5f256 (the same commit the staged 2.12.2 was built from), scalamacros/paradise@c95ba4ad3ad440fa26a258f7d242e64a7712957e . not sure what you mean by "what environment"

**Comment by SethTisue** [comment]
it works on my local machine, too, with `++2.12.2` and `tests/testOnly Repl`

**Comment by xeno-by** [comment]
Can this be an OS difference? I'm on OSX 10.11.6.

**Comment by SethTisue** [comment]
conceivable. jenkins-worker-behemoth-2 is Ubuntu 16.04.1, OpenJDK 1.8.0_111-8u111-b14-2ubuntu0.16.04.2-b14

**Comment by xeno-by** [comment]
Allright. I'll look into this later this weekend.

**Comment by SethTisue** [comment]
to determine whether the issue somehow depends on whether you're in the community build or not, I've started a local run with `version=2.12.2 ./run.sh -l macro-paradise`, I'll comment again once I have a result

**Comment by SethTisue** [comment]
fails in local run too, so not a Mac vs Linux thing

the difference the test complains about (visible in the consoleFull link above) is just whether the code is indented or not. any idea what could affect that?

it's possible it has to do with the version of dependencies you're using — dbuild overrides your dependencies to use whatever it built itself instead.

though, paradise has so few dependencies:

```
[info] Project macro-paradise
[info]   depends on: scala, scala-parser-combinators, scalacheck, scalatest
```

**Comment by xeno-by** [comment]
How about we try out https://github.com/scalamacros/paradise/commit/c44d24af2e4860180fb55ead7cfe4258596d127f?

**Comment by SethTisue** [comment]
yup that does it, green already at https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/1440/consoleFull (though dependent projects are still rebuilding). merging. thanks!

**Pull request merged**
