### PR TITLE
add refined

### PR DESCRIPTION
**Pull request by SethTisue**
/cc @fthomas @soronpo @fommil

Oron reminded me this was still missing.  I had tried to add it a year
ago but failed, I don't remember why. let's see how it goes this time.

### CODE REVIEW

**Comment by fthomas** [comment]
Many thanks, @SethTisue!

Are sbt subprojects that aggregate all JVM subprojects common? If you think this is beneficial for the community build, we can add such project to the refined build.

**Comment by SethTisue** [comment]
@fthomas it's pretty common. typical naming would be `refinedJVM`. it's a fairly minor issue, but, it would ensure that if you add a new subproject, it will get picked up here.

it can also be useful for contributors who want to get all the JVM stuff working and then worry about Scala.js and/or Scala Native in a separate step. (it is fairly common for prospective open source contributors not to have familiarity or experience with Scala.js or Scala Native.)

**Comment by fthomas** [comment]
Ok, that makes sense. I've opened https://github.com/fthomas/refined/issues/460 to track that in refined. Thanks again @SethTisue.

**Comment by fommil** [comment]
you can also use https://github.com/sjrd/sbt-dynscalajs which makes the JVM the first class citizen.

Or, like me, you can just let the scalajs community publish independent artefacts of your projects or have source dependencies. Cross building for js and native has become such a huge burden for library authors.

**Pull request merged**
