### PR TITLE
2.13: advance project SHAs

### PR DESCRIPTION
**Pull request by SethTisue**
~https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/2775/~
~https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/2776/~
~https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/2777/~
~https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/2778/~
~https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/2779/~
~https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/2781/~
https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/2782/

### CODE REVIEW

**Comment by SethTisue** [comment]
hmm

```
[fs2] [error] /home/jenkins/workspace/scala-2.13.x-jdk11-integrate-community-build/target-0.9.17/project-builds/fs2-ade28ac0461a0679f037b2fe91a420626c41e241/core/shared/src/test/scala/fs2/PullLawsSuite.scala:42:67: ambiguous implicit values:
[fs2] [error]  both method arbitrarySilentThrowable in object arbitrary of type org.scalacheck.Arbitrary[Throwable]
[fs2] [error]  and value throwableArbitrary in trait MiscellaneousGenerators of type org.scalacheck.Arbitrary[Throwable]
[fs2] [error]  match expected type org.scalacheck.Arbitrary[Throwable]
[fs2] [error]   checkAll("Sync[Pull[F, O, *]]", SyncTests[Pull[IO, Int, *]].sync[Int, Int, Int])
[fs2] [error]                                                                   ^
```

plus also my effort to fix the `genTheyTests` problem in scalatest-tests didn't work

**Comment by SethTisue** [comment]
ah, fs2 problem stems from https://github.com/typelevel/cats-effect/commit/7237d4cf9bb38eaa616d9d31d197e58d456d5b32 ; I'll freeze cats-effect at the version fs2 currently expects

@vasilmkd not sure if this is an expected outcome or not

**Comment by vasilmkd** [comment]
This is really unfortunate. Can you disable this test for the time being? I think I can push out a fix in the next 20 minutes.

**Comment by vasilmkd** [comment]
Let me know if the fix was successful. 😄

**Comment by SethTisue** [comment]
thanks Vasil! we'll see how run 2782 does.

**Comment by vasilmkd** [comment]
I tested `fs2` manually by publishling `cats-effect` locally and the tests passed without issue.

**Comment by SethTisue** [comment]
@vasilmkd all good now, thanks!

**Pull request merged**
