### PR TITLE
advance sconfig, add sjavatime

### PR DESCRIPTION
**Pull request by SethTisue**
fyi @ekrich, who alerted me the sjavatime dependency had been added ([commit history](https://github.com/ekrich/sjavatime/commits/master))

https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/2437/ queued

### CODE REVIEW

**Comment by SethTisue** [comment]
@ekrich what do you make of these test failures? I saw them locally as well.

```
[sjavatime] [error] Test org.scalajs.testsuite.javalib.time.InstantTest.truncatedTo failed: expected:<-0687-08-07T23:38:33.088937Z> but was:<-0687-08-07T23:38:33.088936Z>, took 0.002 sec
[sjavatime] [error] Test org.scalajs.testsuite.javalib.time.DurationTest.test_toMillis failed: expected:<-2> but was:<-1>, took 0.001 sec
[sjavatime] [error] Test org.scalajs.testsuite.javalib.time.DurationTest.test_toNanos failed: unexpected exception type thrown;ArithmeticException AssertionError, took 0.001 sec
[sjavatime] [error] Failed: Total 354, Failed 3, Errors 0, Passed 351
[sjavatime] [error] Failed tests:
[sjavatime] [error] 	org.scalajs.testsuite.javalib.time.InstantTest
[sjavatime] [error] 	org.scalajs.testsuite.javalib.time.DurationTest
```

**Comment by SethTisue** [comment]
also it appears that sjavatime is a JS/Native only dependency of sconfig, and hence not actually needed to be included here. (though I don't mind including it anyway)

**Comment by ekrich** [comment]
I forgot about that. I wanted to ask about that first. I think you mentioned "all roads lead to community build" on either the Scala Native or Scala.js gitter.

I guess it doesn't need adding sorry.

**Comment by SethTisue** [comment]
okay, but I'm happy to add it regardless. if the test failures can be addressed, then it will be done.

**Comment by ekrich** [comment]
What JVM version are you using?
Looks like they added a leap second 😄

**Comment by SethTisue** [comment]
11. And I see now in a local test that it succeeds on 8, fails on 11 and 15.

**Comment by SethTisue** [comment]
closing for now, happy to resume anytime

**Comment by ekrich** [comment]
Agreed.

**Comment by ekrich** [comment]
Just for posterity - https://github.com/ekrich/sjavatime/issues/58

**Pull request closed without merging**
