### PR TITLE
Newer 2.12 SHA, unbreaking scala-rewrites

### PR DESCRIPTION
**Pull request by dwijnand**
Let's see:
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-jdk8-integrate-community-build/6190/
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-jdk8-integrate-community-build/6191/

### CODE REVIEW

**Comment by SethTisue** [comment]
small community build tip: when you're doing a full rebuild (like when the Scala SHA changes), it's best to queue two runs, since the first one might not complete due to an intermittent failure, or due to Jenkins restarting to upgrade itself. unfortunately you have to wait for the first one to start (which might take 2 minutes or so, if the behemoth needs to be roused) before Jenkins will let you queue another one

I queued a second run (6191)

**Comment by dwijnand** [comment]
```
Lines of Scala code recompiled during this run only:
    23165 scalameta
     6364 zinc
      245 scala-rewrites
      155 shapeless-java-records
    29929 TOTAL
SUCCEEDED: 204
BLOCKING DOWNSTREAM: scalameta (5), zinc (1)
FAILED: 4
BLOCKED, DID NOT RUN: 6
TOTAL: 214
</pre>
Archiving artifacts
Notifying endpoint with url 'http://scala-ci.typesafe.com:8888/jenkins'
Notifying endpoint with url 'https://scala-ci.typesafe.com/benchq/webhooks/jenkins'
Finished: SUCCESS
```

**Comment by SethTisue** [comment]
@dwijnand this seems to have broken the build — https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-jdk8-integrate-community-build/6194/console

```
[silencer] [error] /home/jenkins/workspace/scala-2.12.x-jdk8-integrate-community-build/target-0.9.17/project-builds/silencer-66a58c8d89e1d6ec8dc0b261e6a70830304d562d/silencer-plugin/src/main/scala/com/github/ghik/silencer/SilencerPlugin.scala:31:62: type mismatch;
[silencer] [error]  found   : scala.tools.nsc.reporters.Reporter
[silencer] [error]  required: scala.tools.nsc.reporters.FilteringReporter
[silencer] [error]   private lazy val reporter = new SuppressingReporter(global.reporter,
```

**Comment by SethTisue** [comment]
@dwijnand scala-refactoring failing at https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-jdk8-integrate-community-build/6197/console

**Comment by dwijnand** [comment]
```
[scala-refactoring] [0m[[0m[31merror[0m] [0m[0mTest scala.tools.refactoring.tests.implementations.extraction.ExtractionsTest.findExtractionTargets failed: assertion failed: Race condition detected: You are running a presentation compiler method outside the PC thread.[phase: <no phase>] Please file a ticket with the current stack trace at https://www.assembla.com/spaces/scala-ide/support/tickets[0m
```

**Comment by SethTisue** [comment]
oh, false alarm, intermittent failure, I was fooled because it happened twice in a row. (I reverted your commit marking it as expected-to-fail.)

**Pull request merged**
