### PR TITLE
Support sbt 1.4.x by pinning some projects to 1.3.13

### PR DESCRIPTION
**Pull request by eatkins**

### CODE REVIEW

**Comment by eatkins** [comment]
I've been tracking the sbt issues here: https://github.com/sbt/sbt/issues/5808

**Comment by SethTisue** [comment]
did you mean to also change `sbt-version: "1.3.13"` to `sbt-version: "1.4.0-M2"`?

**Comment by eatkins** [comment]
No. I was holding off for 1.4.0-RC1.

**Comment by eatkins** [comment]
I think 1.4.0-RC1 is coming soon so I can update the PR once it's released.

**Comment by eed3si9n** [comment]
1.4.0-RC1 is out.

**Comment by eatkins** [comment]
I updated the pr to set the sbt version to 1.4.0-RC1.

**Comment by SethTisue** [comment]
~~https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/1821/~~
~~https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/1822/~~
~~https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/1824/~~
https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/1826/
https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/1827/ queued

**Comment by SethTisue** [comment]
```
[munit] [info] loading settings for project munit-376310c7773f9c38d3768e4ddfdaa19130cb5ea9 from build.sbt,ÿÿÿÿÿÿÿÿÿÿ~~~~dbuild~defs.sbt ...
[munit] [info] resolving key references (13710 settings) ...
[munit] [error] java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.CompletableFuture$AsyncSupply@20c19fca rejected from java.util.concurrent.ThreadPoolExecutor@44ed8c88[Running, pool size = 5, active threads = 5, queued tasks = 0, completed tasks = 0]
[munit] [error] Use 'last' for the full log.
[munit] [warn] Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? (default: r)
```

not sure what to make of this — it didn't happen in a local run

**Comment by SethTisue** [comment]
not sure what to make of this one, either

https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/1822/artifact/logs/scalatest-tests-build.log

```
[scalatest-tests] [error] /home/jenkins/workspace/scala-2.13.x-jdk11-integrate-community-build/target-0.9.16/project-builds/scalatest-tests-af83eea7af37ac0556aab38c23df6d25b6c956ab/scalatest-doc/target/scala-2.13.4-bin-7b85389/src_managed/main/org/scalatest/Fact.scala:116:5: object Resources in package scalactic cannot be accessed as a member of package org.scalactic from class Fact in package scalatest
[scalatest-tests] [error]     Resources.formatString(raw, args.map(prettifier.apply).toArray)
[scalatest-tests] [error]     ^
```

**Comment by SethTisue** [comment]
munit's own CI likes 1.4.0-RC1 fine: https://github.com/scalameta/munit/pull/193

**Comment by eatkins** [comment]
munit failed for me once when I ran it locally in that exact way and then it worked in all subsequent runs. I couldn't figure out what the heck was going on with the rejected execution exception but I didn't spend a lot of time on it either.

**Pull request merged**
