### PR TITLE
bump sbt tags to sbt 1.1.6 versions

### PR DESCRIPTION
**Pull request by SethTisue**

### CODE REVIEW

**Comment by SethTisue** [comment]
test run: https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/2982/consoleFull (404 for now)

**Review by dwijnand — APPROVED** [review]
Nice one.

**Comment by SethTisue** [comment]
green in local testing

**Comment by dwijnand** [comment]
Misclick?

**Comment by SethTisue** [comment]
haha oops, thanks

**Pull request merged**
