### PR TITLE
Test sbt 0.13.10-RC3

### PR DESCRIPTION
**Pull request by dwijnand**

### CODE REVIEW

**Comment by SethTisue** [comment]
test run: https://scala-ci.typesafe.com/job/scala-2.11.x-jdk8-integrate-community-build/155/consoleFull (temporarily 404)

**Comment by dwijnand** [comment]
Please could you rebuild.

> Build timed out (after 720 minutes). Marking the build as aborted.
> Build was aborted

**Comment by lrytz** [comment]
https://scala-ci.typesafe.com/job/scala-2.11.x-jdk8-integrate-community-build/156/console

**Comment by dwijnand** [comment]
Failed with

``` scala
[spray-json-shapeless] [error] /home/jenkins/workspace/scala-2.11.x-jdk8-integrate-community-build/target-0.9.5/project-builds/spray-json-shapeless-bb2e4feafb60bed23fd42c8684aa6172bcdc7014/src/test/scala/fommil/sjs/FamilyFormatsSpec.scala:99: inst$macro$7  is already defined as value inst$macro$7
[spray-json-shapeless] [error]   implicit val SimpleTraitFormat: RootJsonFormat[SimpleTrait] = cachedImplicit
[spray-json-shapeless] [error]                                                                 ^
[spray-json-shapeless] [error] one error found
[spray-json-shapeless] [error] (test:compileIncremental) Compilation failed
```

**Comment by dwijnand** [comment]
sbt 0.13.10 has been cut. Thank you for the help.

**Pull request closed without merging**
