### PR TITLE
Added Rapture

### PR DESCRIPTION
**Pull request by propensive**
Currently using version 2.0.0-M2

### CODE REVIEW

**Comment by SethTisue** [comment]
test run: https://scala-ci.typesafe.com/job/scala-2.11.x-integrate-community-build/200/consoleFull

**Comment by SethTisue** [comment]
```
[rapture:error] fatal: ambiguous argument '2.0.0-M2': unknown revision or path not in the working tree.
[rapture:error] Use '--' to separate paths from revisions, like this:
[rapture:error] 'git <command> [<revision>...] -- [<file>...]'
[rapture:error] java.lang.RuntimeException: The reference 2.0.0-M2 is not a valid branch, or tag, or commit of this git repository
```

**Comment by SethTisue** [comment]
oh, missing `v`

**Comment by propensive** [comment]
Groan...whoops. Thanks @SethTisue.

**Comment by SethTisue** [comment]
new test run: https://scala-ci.typesafe.com/job/scala-2.11.x-integrate-community-build/204/

**Comment by SethTisue** [comment]
```
[error] Fatal: multiple projects have the same artifacts visible in the same space.
[error] 
[error]   com.propensive#data  from rapture and rapture, both visible in space "default"
[error]   com.propensive#json  from rapture and rapture, both visible in space "default"
[error]   com.propensive#latex  from rapture and rapture, both visible in space "default"
[error]   com.propensive#json-jackson  from rapture and rapture, both visible in space "default"
[error]   com.propensive#xml-test  from rapture and rapture, both visible in space "default"
[error]   com.propensive#json-json4s  from rapture and rapture, both visible in space "default"
[error]   com.propensive#html  from rapture and rapture, both visible in space "default"
[error]   com.propensive#fs  from rapture and rapture, both visible in space "default"
[error] *** Deploy cannot run: build did not complete.
[error] *** Comparison cannot run: build did not complete.
```

this is typical for projects that support Scala.js. you need to add a `extra.projects` setting listing only the JVM-based subprojects. (you don't need an exhaustive list, just list the top level JVM projects and their dependent subprojects will be pulled in)

**Comment by SethTisue** [comment]
@propensive interested in getting this over the finish line?

**Comment by SethTisue** [comment]
closing for apparent lack of interest

**Pull request closed without merging**
