### PR TITLE
2.13: support both ScalaTest 3.0 and 3.1

### LINKED ISSUE #1020: 2.13: upgrade to ScalaTest 3.1
there is previous history on this at #913, #898, #875 

as discussed there, I think it's fine for the 2.11 and 2.12 builds to stay on ScalaTest 3.0 forever, and we can just freeze things downstream as needed

but the 2.13 build, we should start moving now that 3.1 is in final release. we have already accumulated a substantial number of frozen projects (some green but frozen, some known-to-fail) that are waiting on this. (I've commented them with "ScalaTest 3.1" so I can find them)

and also as discussed at #913 already, I think the best strategy is:
* build 3.1 from source
* for projects still on 3.0, use 3.0 binaries from Maven Central. it's fine

### PR DESCRIPTION
**Pull request by SethTisue**
this will probably take weeks of intermittent work to work through...

fixes #1020 

note to self: update dependencies.txt before merging

### CODE REVIEW

**Comment by SethTisue** [comment]
queued: https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/2960/

**Comment by SethTisue** [comment]
in progress: https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/2965/

dependency extraction now completes

**Comment by SethTisue** [comment]
queued: https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/2967/

but in a local run I'm already seeing:

```
[scalatestplus-scalacheck:error] scala.MatchError: d73729e1+20191231-1112-SNAPSHOT (of class java.lang.String)
[scalatestplus-scalacheck:error] 	at com.typesafe.dbuild.project.build.LocalBuildRunner$.prepareDepsArtifacts(LocalBuildRunner.scala:106)
```

which I'll have to come back to

**Comment by SethTisue** [comment]
good progress: the basic approach seems to be sound, namely supporting ScalaTest 3.0 by 1) using a fork with a different org name, and 2) using `deps.inject` + `removeDependency` + `set libraryDependencies...` in repos that need 3.0

lots of stuff is green already, but now it's matter of doing multiple cycles of
* identifying repos that need 3.0
* unfreezing repos that can now move to 3.1
* dealing with the downstream consequences of unfreezing

queued: https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/2979/

**Comment by SethTisue** [comment]
2979 has 119 green, `BLOCKING DOWNSTREAM: cats (48), catalysts (21), scalapb (10), akka-http (9), twitter-util (4), slick (3), unfiltered (2), better-files (1)`

cats needs newer simulacrum, the org name changed

the 21 number of catalysts seems high, I suspect that will drop to nothing, or next to nothing, once we advance the cats-effect SHA

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/2983/

`SUCCEEDED: 131`, `BLOCKING DOWNSTREAM: circe (12), scalapb (10), fs2 (10), refined (6), unique (5), twitter-util (4), algebra (4), slick (3), monix (3), unfiltered (2), akka-http-cors (2), scala-logging (1), monocle (1), scala-newtype (1), better-files (1)`

**Comment by SethTisue** [comment]
latest wip commit unfreezes a ton of projects we'd frozen because we didn't support 3.1

probably at least one will fail to extract in the next run

https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/2988/

**Comment by som-snytt** [comment]
:tada:

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/view/scala-2.13.x/job/scala-2.13.x-integrate-community-build/2993/

**Comment by som-snytt** [comment]
This is a pretty active channel.

**Comment by SethTisue** [comment]
I try to keep a steady beat of about 120 wpm (wips-per-minute) for repo watchers to dance to.

**Comment by som-snytt** [comment]
I'm having trouble keeping up.

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/2999/ has `SUCCEEDED: 144` and `BLOCKING DOWNSTREAM: scalameta (15), fs2 (13), enumeratum (9), monix (3), spire (2), circe-config (1), scrooge (1), scala-newtype (1), circe-jackson (1), akka-http-cors (1), scalameter (1), better-files (1)`

* scalameta: scalapb version mismatch perhaps?
* fs2: compile error I don't understand, perhaps a version mismatch with cats or cats-effect or something
* enumeratum: `Missing dependency: the library com.lihaoyi#pprint`
* monix: compile error I don't understand, presumably some kind of dependency version mismatch
* better-files: `java.lang.NoSuchMethodError: org.scalactic.BooleanMacro.<init>(Lscala/reflect/macros/whitebox/Context;Ljava/lang/String;)V`, some of other repos have the same error. better-files uses ScalaTest 3.1, but it depends on Akka which uses ScalaTest 3.0, so I suspect that they're both ending up the classpath, something like that

**Comment by som-snytt** [comment]
I have to take a breather.

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/3008/

```
SUCCEEDED: 161
FAILURES (UNEXPECTED): fs2,enumeratum,akka-http,akka-more,monix,cats-mtl,scalatest-tests,scalafmt,github4s,gigahorse,eff,circe-derivation,breeze
BLOCKING DOWNSTREAM: fs2 (13), enumeratum (9), akka-http (8), akka-more (6), monix (3), cats-mtl (2)
FAILED: 19
BLOCKED, DID NOT RUN: 24
```

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/3012/

```
SUCCEEDED: 174
FAILURES (UNEXPECTED): fs2,monix,akka-http-cors,scalatest-tests,scalafmt,github4s,eff,circe-derivation,breeze
BLOCKING DOWNSTREAM: fs2 (13), monix (3), akka-http-cors (1)
FAILED: 15
BLOCKED, DID NOT RUN: 15
TOTAL: 204
```

**Comment by SethTisue** [comment]
fs2 is a difficult case

first, I got compile errors that, after a process of guess-and-test, turned out to be a cats-effect version mismatch. so I froze cats-effect at v2.0.0, which is annoying because there are older dependencies there, but it seems to have worked out

and then second, it appears that fs2 isn't on ScalaTest 3.1 final because of https://github.com/scalatest/scalatest/issues/1735 — they're on some 3.1 prerelease that isn't source compatible with either 3.0 or 3.1 final 😱

I think I can convince dbuild to simply skip over everything testing-related in fs2 for now and we can maybe revisit it someday

**Comment by SethTisue** [comment]
I pulled most projects that still haven't upgraded to 2.13, we can always re-add them if they ever upgrade. in the meantime there's no point in building them over and over again. this cuts down the known-failures list to: eff, coursier, scalafix

https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/3016/

```
SUCCEEDED: 181
FAILURES (UNEXPECTED): http4s,akka-http-cors,scalatest-tests,github4s,breeze
BLOCKING DOWNSTREAM: http4s (11), akka-http-cors (1)
FAILED: 8
BLOCKED, DID NOT RUN: 11
TOTAL: 200
```

I already fixed akka-http-cors; working on http4s and sttp

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/3019

```
SUCCEEDED: 188
FAILURES (UNEXPECTED): tsec,doobie,sttp,scalatest-tests,pfps-shopping-cart,github4s,droste,breeze,avro4s
BLOCKING DOWNSTREAM: doobie (1), tsec (1)
FAILED: 12
BLOCKED, DID NOT RUN: 1
TOTAL: 201
```

the light at the end of the tunnel is in sight

**Comment by SethTisue** [comment]
geez, pfps-shopping-cart has more dependencies than a \<thing known for having many other things\> has \<things that that many-thinged thing has\>

**Comment by SethTisue** [comment]
my-god-its-full-of-stars-quote-1

**Comment by SethTisue** [comment]
(testing locally, Jenkins is behind)

gah, wth is this

```
[pfps-shopping-cart] [error] /Users/tisue/community.213/target-0.9.16/project-builds/pfps-shopping-cart-ef667029c01fde679d6996e8ea4def1dec809a19/modules/core/src/main/scala/shop/config/loader.scala:67:18: exception during macro expansion: 
[pfps-shopping-cart] [error] java.lang.AssertionError: assertion failed: import failure: cannot determine unique overloaded method alternative from
[pfps-shopping-cart] [error]  final package eu
[pfps-shopping-cart] [error] final package eu
[pfps-shopping-cart] [error]  that matches package eu:eu.type
[pfps-shopping-cart] [error] 	at scala.reflect.internal.SymbolTable.throwAssertionError(SymbolTable.scala:170)
[pfps-shopping-cart] [error] 	at scala.reflect.internal.Importers$StandardImporter.disambiguate$1(Importers.scala:195)
[pfps-shopping-cart] [error] 	at scala.reflect.internal.Importers$StandardImporter.recreateOrRelink$1(Importers.scala:200)
[pfps-shopping-cart] [error] 	at scala.reflect.internal.Importers$StandardImporter.importSymbol(Importers.scala:222)
[pfps-shopping-cart] [error] 	at scala.reflect.internal.Importers$StandardImporter.recreateOrRelink$1(Importers.scala:181)
[pfps-shopping-cart] [error] 	at scala.reflect.internal.Importers$StandardImporter.importSymbol(Importers.scala:222)
[pfps-shopping-cart] [error] 	at scala.reflect.internal.Importers$StandardImporter.recreateOrRelink$1(Importers.scala:178)
[pfps-shopping-cart] [error] 	at scala.reflect.internal.Importers$StandardImporter.importSymbol(Importers.scala:222)
[pfps-shopping-cart] [error] 	at scala.reflect.internal.Importers$StandardImporter.recreateOrRelink$1(Importers.scala:178)
[pfps-shopping-cart] [error] 	at scala.reflect.internal.Importers$StandardImporter.importSymbol(Importers.scala:222)
[pfps-shopping-cart] [error] 	at scala.reflect.internal.Importers$StandardImporter.recreateOrRelink$1(Importers.scala:178)
[pfps-shopping-cart] [error] 	at scala.reflect.internal.Importers$StandardImporter.importSymbol(Importers.scala:222)
[pfps-shopping-cart] [error] 	at scala.reflect.internal.Importers$StandardImporter.recreatedTreeCompleter(Importers.scala:310)
[pfps-shopping-cart] [error] 	at scala.reflect.internal.Importers$StandardImporter.$anonfun$importTree$1(Importers.scala:429)
[pfps-shopping-cart] [error] 	at scala.reflect.internal.Importers$StandardImporter.tryFixup(Importers.scala:61)
[pfps-shopping-cart] [error] 	at scala.reflect.internal.Importers$StandardImporter.importTree(Importers.scala:430)
[pfps-shopping-cart] [error] 	at scala.reflect.internal.Importers$StandardImporter.recreateTree(Importers.scala:395)
[pfps-shopping-cart] [error] 	at scala.reflect.internal.Importers$StandardImporter.importTree(Importers.scala:427)
[pfps-shopping-cart] [error] 	at scala.reflect.internal.Importers$StandardImporter.recreateTree(Importers.scala:395)
[pfps-shopping-cart] [error] 	at scala.reflect.internal.Importers$StandardImporter.importTree(Importers.scala:427)
[pfps-shopping-cart] [error] 	at scala.reflect.internal.Importers$StandardImporter.recreateTree(Importers.scala:379)
[pfps-shopping-cart] [error] 	at scala.reflect.internal.Importers$StandardImporter.importTree(Importers.scala:427)
[pfps-shopping-cart] [error] 	at scala.reflect.internal.Importers$StandardImporter.recreateTree(Importers.scala:382)
[pfps-shopping-cart] [error] 	at scala.reflect.internal.Importers$StandardImporter.importTree(Importers.scala:427)
[pfps-shopping-cart] [error] 	at scala.reflect.internal.Importers$StandardImporter.importTree(Importers.scala:41)
[pfps-shopping-cart] [error] 	at scala.reflect.macros.contexts.Evals.eval(Evals.scala:31)
[pfps-shopping-cart] [error] 	at scala.reflect.macros.contexts.Evals.eval$(Evals.scala:26)
[pfps-shopping-cart] [error] 	at scala.reflect.macros.contexts.Context.eval(Context.scala:18)
[pfps-shopping-cart] [error] 	at eu.timepit.refined.macros.MacroUtils.$anonfun$eval$1(MacroUtils.scala:22)
[pfps-shopping-cart] [error] 	at scala.Option.getOrElse(Option.scala:201)
[pfps-shopping-cart] [error] 	at eu.timepit.refined.macros.MacroUtils.tryN(MacroUtils.scala:26)
[pfps-shopping-cart] [error] 	at eu.timepit.refined.macros.MacroUtils.tryN$(MacroUtils.scala:25)
[pfps-shopping-cart] [error] 	at eu.timepit.refined.macros.RefineMacro.tryN(RefineMacro.scala:10)
[pfps-shopping-cart] [error] 	at eu.timepit.refined.macros.MacroUtils.eval(MacroUtils.scala:22)
[pfps-shopping-cart] [error] 	at eu.timepit.refined.macros.MacroUtils.eval$(MacroUtils.scala:15)
[pfps-shopping-cart] [error] 	at eu.timepit.refined.macros.RefineMacro.eval(RefineMacro.scala:10)
[pfps-shopping-cart] [error] 	at eu.timepit.refined.macros.RefineMacro.$anonfun$validateInstance$2(RefineMacro.scala:55)
[pfps-shopping-cart] [error] 	at scala.Option.getOrElse(Option.scala:201)
[pfps-shopping-cart] [error] 	at eu.timepit.refined.macros.RefineMacro.validateInstance(RefineMacro.scala:55)
[pfps-shopping-cart] [error] 	at eu.timepit.refined.macros.RefineMacro.impl(RefineMacro.scala:25)
[pfps-shopping-cart] [error]           port = 5432,
[pfps-shopping-cart] [error]                  ^
```

**Comment by SethTisue** [comment]
rather than let pfps-shopping-cart hold up this whole PR any longer, I've marked it as expected-to-fail and opened a separate ticket on it: #1039

**Comment by SethTisue** [comment]
new PR: #1040

**Pull request closed without merging**
