### PR TITLE
sbt 1.3.12 (was 1.3.10)

### PR DESCRIPTION
**Pull request by SethTisue**
~~https://scala-ci.typesafe.com/view/scala-2.11.x/job/scala-2.11.x-integrate-community-build/1812/~~
~~https://scala-ci.typesafe.com/view/scala-2.11.x/job/scala-2.11.x-integrate-community-build/1817/~~
~~https://scala-ci.typesafe.com/view/scala-2.11.x/job/scala-2.11.x-integrate-community-build/1818/~~
~~https://scala-ci.typesafe.com/view/scala-2.11.x/job/scala-2.11.x-integrate-community-build/1821/~~
~~https://scala-ci.typesafe.com/view/scala-2.11.x/job/scala-2.11.x-integrate-community-build/1822/~~
https://scala-ci.typesafe.com/view/scala-2.11.x/job/scala-2.11.x-integrate-community-build/1824/
https://scala-ci.typesafe.com/view/scala-2.11.x/job/scala-2.11.x-integrate-community-build/1825/

### CODE REVIEW

**Comment by SethTisue** [comment]
`EXTRACTION FAILED (failed: cats, circe, coursier, droste, metaconfig, scalacheck-shapeless, scalafix, scalafmt, sourcecode)`

oh boy... getting a bunch of `Error downloading com.typesafe.dbuild:plugin;sbtVersion=1.0;scalaVersion=2.12:0.9.16 ` errors during dependency extraction, like:

```
[circe] [info] Resolved root-64adb8a1ee5aa8b326100b8658f2f1d0586869c7-build dependenciessha1
[circe] [error] coursier.error.ResolutionError$CantDownloadModule: Error downloading com.typesafe.dbuild:plugin;sbtVersion=1.0;scalaVersion=2.12:0.9.16
[circe] [error]   Not found
[circe] [error]   not found: https://repo1.maven.org/maven2/com/typesafe/dbuild/plugin_2.12_1.0/0.9.16/plugin-0.9.16.pom
[circe] [error]   not found: /Users/tisue/.ivy2/local/com.typesafe.dbuild/plugin/scala_2.12/sbt_1.0/0.9.16/ivys/ivy.xml
[circe] [error]   not found: https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.dbuild/plugin/scala_2.12/sbt_1.0/0.9.16/ivys/ivy.xml
[circe] [error] 	at coursier.Resolve$.$anonfun$validate$1(Resolve.scala:275)
```

it's not obvious to me what the failing projects have in common

I wonder if this will turn out to be something trivial... or maybe I'm in for a wild ride

many of these projects have big/complicated builds, but sourcecode is very small, so that's probably a good place to start

**Comment by SethTisue** [comment]
oh I see what they have in common, they have `project/project/plugins.sbt` (note the extra level of nesting) with `addSbtPlugin("io.get-coursier" % "sbt-coursier" % ...)`

well, I didn't check every one, but I checked four of them

okay, so it's going to be fine to freeze the sbt version of these projects. whew

as I merge this forward onto the 2.12.x and 2.13.x branches, I'll likely find that the count of affected projects drops, since people will have moved to sbt 1.3.x and removed sbt-coursier from their builds

**Comment by SethTisue** [comment]
okay well everything extracts now :+1:

but even cloc-plugin won't build :scream:

```
[cloc-plugin] [error] sbt.librarymanagement.ResolveException: Error downloading org.scala-lang:scala-compiler:2.11.12-bin-2e2f65a
[cloc-plugin] [error]   Not found
[cloc-plugin] [error]   Not found
[cloc-plugin] [error]   not found: /home/jenkins/workspace/scala-2.11.x-integrate-community-build/target-0.9.16/project-builds/cloc-plugin-1606571dada0289f783ca9cf9a7b168fd5cf863c/.dbuild/ivy2/local/org.scala-lang/scala-compiler/2.11.12-bin-2e2f65a/ivys/ivy.xml
[cloc-plugin] [error]   not found: https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.11.12-bin-2e2f65a/scala-compiler-2.11.12-bin-2e2f65a.pom
```

offhand, it looks like our `resolvers.conf` is being ignored:

```
  // and this is where we get Scala nightlies
  20: "scala-integration: https://scala-ci.typesafe.com/artifactory/scala-integration/"
```

**Comment by SethTisue** [comment]
in the dbuild debugging environment (`dbuild checkout ...`), I see:

```
sbt:cloc-plugin> show appResolvers
[info] None
```

whereas with 1.3.10 I see:

```
sbt:cloc-plugin> show appResolvers
[info] Some(Vector(FileRepository(local, Patterns(ivyPatterns=Vector(${ivy.home}/local/[organisation]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)([branch]/)[revision]/[type]s/[artifact](-[classifier]).[ext]), artifactPatterns=Vector(${ivy.home}/local/[organisation]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)([branch]/)[revision]/[type]s/[artifact](-[classifier]).[ext]), isMavenCompatible=false, descriptorOptional=false, skipConsistencyCheck=false), FileConfiguration(true, None)), FileRepository(ivy-build-local, Patterns(ivyPatterns=Vector(/Users/tisue/community.212/newdir2/.dbuild/local-repo/0/[organization]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]), artifactPatterns=Vector(/Users/tisue/community.212/newdir2/.dbuild/local-repo/0/[organization]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]), isMavenCompatible=false, descriptorOptional=false, skipConsistencyCheck=false), FileConfiguration(true, None)), mvn-build-local: file:/Users/tisue/community.212/newdir2/.dbuild/local-repo/0/, dbuild: https://scala-ci.typesafe.com/artifactory/dbuild/, URLRepository(dbuild-ivy, Patterns(ivyPatterns=Vector(https://scala-ci.typesafe.com/artifactory/dbuild-ivy/[organisation]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]), artifactPatterns=Vector(https://scala-ci.typesafe.com/artifactory/dbuild-ivy/[organisation]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]), isMavenCompatible=false, descriptorOptional=false, skipConsistencyCheck=false), false), dbuild-unchecked: https://scala-ci.typesafe.com/artifactory/dbuild-unchecked/, scala-pr-validation-snapshots: https://scala-ci.typesafe.com/artifactory/scala-pr-validation-snapshots, scala-integration: https://scala-ci.typesafe.com/artifactory/scala-integration/))
```

which includes `https://scala-ci.typesafe.com/artifactory/scala-integration/` as expected

**Comment by SethTisue** [comment]
It looks like `appResolvers` comes from the launcher

@eed3si9n I can keep digging into this, including trying to reproduce it outside of dbuild, but I'm curious if what I have so far is ringing any bells with you

**Comment by eed3si9n** [comment]
I did update the launcher so it's possible I messed something up.

**Comment by SethTisue** [comment]
@eed3si9n I was able to get dbuild out of the equation, here; see  https://github.com/sbt/sbt/issues/5582

closing this PR, since 1.3.11 is unusable in this repo

**Comment by SethTisue** [comment]
reopened since it should be possible for me to ensure that the 1.3.11 launcher jar is used, apparently dbuild is using an older one

**Comment by SethTisue** [comment]
> apparently dbuild is using an older one

it's using the sbt 1.0.0 launcher 😱 

that launcher is downloaded when dbuild is build and then is included as a resource in `com.typesafe.dbuild/build/0.9.16/build_2.10-0.9.16.jar`:

```
~/.dbuild/boot/scala-2.10.7/com.typesafe.dbuild/build/0.9.16 % jar tf build_2.10-0.9.16.jar | grep sbt-launch.jar
sbt-launch.jar
```

and then `SbtRunner.scala` uses that

and I don't see a way to override to a different version without republishing dbuild

**Comment by SethTisue** [comment]
I made an effort to test this by changing the launcher version in dbuild and publishing dbuild locally. here's what I did

in the dbuild repo,

```diff
diff --git build.sbt build.sbt
index a50b2ec5..bcd04e78 100644
--- build.sbt
+++ build.sbt
@@ -4 +4 @@ import RemoteDepHelper._
-def MyVersion: String = "0.9.16"
+def MyVersion: String = "0.9.17-seth-20200530-1"
diff --git project/SbtSupport.scala project/SbtSupport.scala
index 878a8949..288bc0a5 100644
--- project/SbtSupport.scala
+++ project/SbtSupport.scala
@@ -22 +22 @@ object SbtSupport {
-    sbtLaunchJarUrl := "https://repo1.maven.org/maven2/org/scala-sbt/sbt-launch/1.0.0/sbt-launch.jar",
+    sbtLaunchJarUrl := "https://repo1.maven.org/maven2/org/scala-sbt/sbt-launch/1.3.11/sbt-launch.jar",
```

then run sbt and run `^publishLocal` and `dist`

then here in this repo,

```diff
diff --git run.sh run.sh
index 282ae821..ea670d03 100755
--- run.sh
+++ run.sh
@@ -135 +135 @@ fi
-DBUILDVERSION=0.9.16
+DBUILDVERSION=0.9.17-seth-20200530-1
@@ -150 +150 @@ then
-  curl -LO "http://repo.lightbend.com/typesafe/ivy-releases/com.typesafe.dbuild/dbuild/${DBUILDVERSION}/tgzs/dbuild-${DBUILDVERSION}.tgz"
+  cp ~/dbuild/dist/target/universal/dbuild-${DBUILDVERSION}.tgz .
```

so far so good but then it turns out that dbuild doesn't look in your `~/.ivy2/local`, so you get

```
[scala-xml] [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[scala-xml] [warn] 	::          UNRESOLVED DEPENDENCIES         ::
[scala-xml] [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[scala-xml] [warn] 	:: com.typesafe.dbuild#plugin;0.9.17-seth-20200530-1: not found
[scala-xml] [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
```

and that happens regardless of whether I `./run.sh`, or whether I `./run.sh -l` to use my `~/.sbt/repositories` which is for my local Artifactory but does include a `local` entry

so I tried adding this to `~/.sbt/repositories`:

```
  no-really-local: file:///Users/tisue/.ivy2/local/, [organisation]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]
```

and that did the trick:

```
[info] Project cloc-plugin-----------------: SUCCESS (project rebuilt ok)
```

**Comment by eed3si9n** [comment]
I am pushing sbt 1.3.12 to Maven Central now with the https://github.com/sbt/sbt/pull/5583 patch.

**Comment by eed3si9n** [comment]
So sbt 1.3.12 is ok?

**Comment by SethTisue** [comment]
> So sbt 1.3.12 is ok?

I believe so. https://scala-ci.typesafe.com/view/scala-2.11.x/job/scala-2.11.x-integrate-community-build/1821/ (and run 1822 as well) stopped early for unrelated reasons, but 1821 did get far enough to see that a number of projects were green on 1.3.12.

If you want to be maximally cautious we could wait for run 1824 to complete and see if turns up any _other_ problems.

**Comment by SethTisue** [comment]
run 1825 🟢

**Pull request merged**
