### PR TITLE
add lsp4s

### PR DESCRIPTION
**Pull request by SethTisue**
sequel to #740, which added all of lsp4s's dependencies

this is now blocked waiting for @olafurpg to upgrade lsp4s itself to upgrade to monix 3 (
https://github.com/scalameta/lsp4s/issues/13)

### CODE REVIEW

**Comment by olafurpg** [comment]
I'll look into it this week!

**Comment by SethTisue** [comment]
@olafurpg you should wait for monix 3.0.0-RC2 (or, if it comes to that, 3.0 final); see https://github.com/scala/community-builds/pull/787#issuecomment-421393741

/cc @alexandru

**Comment by alexandru** [comment]
I'm working on it, sorry for the delay.

**Comment by olafurpg** [comment]
FYI @SethTisue I plan to use lsp4j instead of lsp4s in metals and it seems intellij-scala will do the same. The only remaining user of lsp4s that I'm aware of is bloop, I leave it to you to decide if you want to keep the module in the community build.

**Comment by olafurpg** [comment]
FYI @SethTisue I plan to use lsp4j instead of lsp4s in metals and it seems intellij-scala will do the same. The only remaining user of lsp4s that I'm aware of is bloop, I leave it to you to decide if you want to keep the module in the community build.

**Comment by SethTisue** [comment]
@jvican opinion?

**Comment by jvican** [comment]
I don’t plan on doing maintenance of lsp4s that doesn’t affect bloop, and bloop is still stuck on monix 2.x and will be for a long time... I think the best solution is to remove lsp4s from the community build.

**Comment by SethTisue** [comment]
never finished adding it in the first place, so I’ll just close this! thanks guys

**Pull request closed without merging**
