### PR TITLE
add finch

### PR DESCRIPTION
**Pull request by SethTisue**
motivation: finagle/finch#1417

### CODE REVIEW

**Comment by SethTisue** [comment]
I did a run locally and I'm seeing similar compile errors as reported on the finch ticket:

```
[finch] [error] /Users/tisue/cb3/target-0.9.17/project-builds/finch-d51e08307f3d52080ece80921b9ca8e62d6eb526/core/src/test/scala/io/finch/BootstrapSpec.scala:43:16: overloaded method apply with alternatives:
[finch] [error]   (mapper: io.finch.internal.Mapper[cats.effect.IO,shapeless.HNil])io.finch.Endpoint[cats.effect.IO,mapper.Out] <and>
[finch] [error]   (input: io.finch.Input)io.finch.Endpoint.Result[cats.effect.IO,shapeless.HNil]
[finch] [error]  cannot be applied to (io.finch.Output[String])
[finch] [error]     val a = get("foo")(Ok("get foo"))
[finch] [error]                ^
```

I'll stand by as the finch folks dig into it.

**Comment by SethTisue** [comment]
closing for now, for inactivity, but I'd be happy to return to it

**Comment by joroKr21** [comment]
@SethTisue does it make sense to try again now that the fix was merged?

**Comment by SethTisue** [comment]
Yes. Need to land #1519 first, then rebase this on that.

**Comment by SethTisue** [comment]
local run on 2.13.8-bin-b59fa66

```
[info] Project finch-----------------------: SUCCESS (project rebuilt ok)
```

👍 

I'll merge this PR after #1519 lands.

**Comment by SethTisue** [comment]
actually I've just folded this into #1519

**Pull request closed without merging**
