### PR TITLE
2.13: new Scala SHA

### PR DESCRIPTION
**Pull request by SethTisue**
https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/3816/
https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/3818/

### CODE REVIEW

**Comment by SethTisue** [comment]
`FAILURES (UNEXPECTED): scala-collection-contrib`

https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/3818/artifact/logs/scala-collection-contrib-build.log

a series of "incompatible type in overriding" compilation errors, the first of which is

```
[scala-collection-contrib] [error] /home/jenkins/workspace/scala-2.13.x-jdk11-integrate-community-build/target-0.9.17/project-builds/scala-collection-contrib-10f20e94f4f64087cad7a7582bf16efe24375298/src/main/scala/scala/collection/MultiDict.scala:11:7: incompatible type in overriding
[scala-collection-contrib] [error] def addString(b: StringBuilder, start: String, sep: String, end: String): b.type (defined in trait IterableOnceOps)
[scala-collection-contrib] [error]   with override def addString(sb: StringBuilder, start: String, sep: String, end: String): StringBuilder (defined in trait MultiDictOps);
[scala-collection-contrib] [error]  found   : (sb: StringBuilder, start: String, sep: String, end: String): StringBuilder
[scala-collection-contrib] [error]  required: (b: StringBuilder, start: String, sep: String, end: String): b.type
[scala-collection-contrib] [error] trait MultiDict[K, V]
[scala-collection-contrib] [error]       ^
```

regression? progression? or just a change downstream needs to adapt to?

do I need to bisect?

**Comment by SethTisue** [comment]
oh, it's obviously this StringBuilder PR: https://github.com/scala/scala/pull/10047

@som-snytt offhand, I guess the PR is fine and we just need to change the code in scala-collection-contrib? wdyt?

**Comment by SethTisue** [comment]
I'm going to merge this PR regardless — it's only one red repo, so let's book the overall progress

**Comment by som-snytt** [comment]
> There is probably more to the story.

It was a cliffhanger!

**Comment by SethTisue** [comment]
The one-line change to scala-collection-contrib is https://github.com/scala/scala-collection-contrib/pull/185

To make the repo green again here, I pushed 046e880c41cae732715964e0d6a40d1cc8dec456

**Pull request merged**
