### PR TITLE
unfreeze scalafix (and scalameta and scalapb and jackson-module-scala)

### PR DESCRIPTION
**Pull request by SethTisue**
now that we are on latest scalafmt, we should try to do the same for scalafix

this will be more fun than having a family of ferrets in your pants, for sure

### CODE REVIEW

**Comment by SethTisue** [comment]
test runs:
* https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/2989/consoleFull
* https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/2991/consoleFull

**Comment by SethTisue** [comment]
hmm, there is a scalapb compilation error where it seems to not be picking up the right Scala-version-specific source directory. surely some trivial thing. I'll come back to it

**Comment by SethTisue** [comment]
let's check the current status. test run: https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/3044/

**Comment by SethTisue** [comment]
Tell us, run 3044! Where did you go? What did you see?

```
[info] >>> The dbuild result is----------------: FAILED (failed: scalatest-tests, lagom, scalapb)
```

the scalatest-tests and lagom failures are presumably intermittent and unrelated.

but scalapb failing took out the downstream projects we were interested in.

and scalapb failed because I made a silly mistake in `extra.commands`

try again: https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/3047/ (404 for now)

**Comment by SethTisue** [comment]
scalapb is green now.

I had to add more scalameta subprojects that scalafix and/or scalafmt now need.

one of the newly added scalameta subprojects uses geny, but it needs an older version, geny master has a source-incompatible change.

currently trying freezing geny at the older version. if that works, great. (but if it breaks something else, I should probably submit a scalameta PR upgrading the new version.)

**Comment by SethTisue** [comment]
@olafurpg seems likely I'll succeed here. however, I still have separate metaconfig_old and metaconfig_new spaces in dbuild since scalafix and scalafmt are on different metaconfig versions. would it be difficult to get them both onto v0.8.x?

**Comment by olafurpg** [comment]
Hmm, I should be able to have them use the same metaconfig version. I will look into it in the coming days.

**Comment by SethTisue** [comment]
the ferret family has been evicted

**Comment by SethTisue** [comment]
fyi @thesamet on scalapb (P.S. very nice talk at Scala Days NYC!)

**Comment by SethTisue** [comment]
this needs one little bit of extra work, semanticdb-sbt is failing, we probably just need to refresh our fork

**Comment by olafurpg** [comment]
semanticdb-sbt is no longer a dependency of scalafix, the project had been archived and is no longer under development.

**Pull request merged**
