### PR TITLE
2.11: fix utest by using scala-js's 0.6.x branch instead of master

### PR DESCRIPTION
**Pull request by SethTisue**

### CODE REVIEW

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/view/scala-2.11.x/job/scala-2.11.x-jdk8-integrate-community-build/703/

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/view/scala-2.11.x/job/scala-2.11.x-jdk8-integrate-community-build/704/

**Comment by sjrd** [comment]
uTest was updated to support the latest master of Scala.js. So maybe this can be reverted now?

**Comment by SethTisue** [comment]
fixed by #790

**Pull request merged**
