### PR TITLE
add sourcecode

### PR DESCRIPTION
**Pull request by lrytz**

### CODE REVIEW

**Comment by lrytz** [comment]
Merges `2.11.x-jdk8-with-sourcecode-added` into `2.12.x` - i'm submitting this one first because i have a community build for 2.12.x ready that has everything cached except fastparse, so I can test it quickly. started a build: ~~https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/300/~~

**Comment by lrytz** [comment]
hmm.. getting

```
[info] Project sourcecode--------------: EXTRACTION FAILED (RuntimeException: These subprojects were not found: "jvm"...)
```

here's the build definition: https://github.com/lihaoyi/sourcecode/blob/master/build.sbt#L50

@SethTisue any idea? it looks very similar to what we do for `fastparse` (https://github.com/lihaoyi/fastparse/blob/master/build.sbt#L102)

**Comment by lrytz** [comment]
oh, there's more information in the log file:

```
[sourcecode:error] java.lang.RuntimeException: These subprojects were not found: "jvm".  Found: "default-sbt-project", "sourcecodeJVM", "sourcecodeJS". 
```

**Comment by lrytz** [comment]
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/301/

**Comment by lrytz** [comment]
build passed

**Comment by SethTisue** [comment]
thanks Lukas! a bit unclear on the 2.11 vs. 2.12 situation — do you plan to submit a 2.11 backport?

**Comment by SethTisue** [comment]
ah, and I see the backport in #212. thanks Lukas!

**Pull request merged**
