### PR TITLE
Bump SBT from v0.13.6-M1-31-g0b2f2ae5a to 0.13

### PR DESCRIPTION
**Pull request by retronym**
Hopefully will work after the fixes in sbt/sbt#1523.

Fixes scala/community-builds#480

### CODE REVIEW

**Review by dwijnand — APPROVED** [review]
.. pending a blue Jenkins.

**Comment by adriaanm** [comment]
Let's merge first and ask questions later :-)

**Comment by adriaanm** [comment]
https://scala-ci.typesafe.com/job/scala-2.11.x-integrate-community-build/524

**Comment by adriaanm** [comment]
still working on this -- committed directly to 2.11.x

**Comment by adriaanm** [comment]
The bintray plugin fails with None.get...

https://scala-ci.typesafe.com/job/scala-2.11.x-integrate-community-build/526/console

**Comment by adriaanm** [comment]
https://github.com/typesafehub/dbuild/issues/158

**Comment by adriaanm** [comment]
Reverting this version bump until we can fix the bintray issue.

**Comment by SethTisue** [comment]
previous discussion on building sbt as part of the community build: https://github.com/scala/community-builds/pull/290

**Pull request merged**
