### PR TITLE
2.13: re-enable scala-js linker subproject

### PR DESCRIPTION
**Pull request by SethTisue**
as per https://github.com/scala-js/scala-js/pull/3703

### CODE REVIEW

**Comment by SethTisue** [comment]
queued: https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/2323/

**Comment by SethTisue** [comment]
green in local test

**Comment by SethTisue** [comment]
fyi @sjrd

**Comment by sjrd** [comment]
Thanks @SethTisue!

**Pull request merged**
