### PR TITLE
Green 2.12.x community build!

### PR DESCRIPTION
**Pull request by adriaanm**
Review by @SethTisue! Over to you for next round :-)

### CODE REVIEW

**Comment by adriaanm** [comment]
All :+1: over at https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/60/console

**Comment by retronym** [comment]
@adriaanm Just checking: I'm not sure if you intended the last commit to be included in this PR just yet.

**Comment by adriaanm** [comment]
Nope, that wasn't meant to be here -- the joys of reusing branches :)

**Comment by SethTisue** [comment]
merged all but last commit in 3953d2c102215c712a0b8307f87a0c7a29ed0ccf

**Pull request closed without merging**
