### PR TITLE
Move the sbt-verse to sbt 1.1.4 tags

### PR DESCRIPTION
**Pull request by dwijnand**

### CODE REVIEW

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/2785/ ~~(404 til Jenkins finishes researching why pastis gets cloudy when you add water to it)~~

**Comment by SethTisue** [comment]
running this locally I'm seeing

```
[sbt-io] [info] DefaultWatchServiceSpec:
[sbt-io] [info] - should detect modified files *** FAILED ***
[sbt-io] [info]   false was not equal to true (SourceModificationWatchSpec.scala:312)
```

**Comment by dwijnand** [comment]
Hmm. There's been action on that in the 1.1.x branch, but it hasn't been made part of a release yet: https://github.com/sbt/io/commits/1.1.x/io/src/test/scala/sbt/internal/io/DefaultWatchServiceSpec.scala.. :-/

**Comment by SethTisue** [comment]
it's green on Jenkins, but in b44cf005c80c3dd13bc73b742a6b5dd56524b33d I disabled the sbt-io tests since I often run the build locally on MacOS

**Comment by SethTisue** [comment]
thanks Dale!

**Pull request merged**
