### PR TITLE
2.12: advance project SHAs

### PR DESCRIPTION
**Pull request by SethTisue**
~~https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/5678/~~
~~https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/5679/~~
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/5681/

### CODE REVIEW

**Comment by SethTisue** [comment]
@dwijnand what do you make of the failure at https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/5679/artifact/logs/scala-rewrites-build.log ?

**Comment by SethTisue** [comment]
(I froze scala-rewrites for now)

**Comment by dwijnand** [comment]
Hmm.  No idea, but I'll create an issue for it.

**Comment by SethTisue** [comment]
to help not lose track of it: fb945aeb833808189e76063a853f59daae220367

**Pull request merged**
