### PR TITLE
add TwoTails

### PR DESCRIPTION
**Pull request by SethTisue**
saw @wheaties give a talk on it, and my ears pricked up when he
said it had no (almost no?) dependencies

### CODE REVIEW

**Comment by SethTisue** [comment]
tested locally, but Jenkins test run just to be sure: ~~https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/1367/consoleFull~~ https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/1368/consoleFull

**Comment by wheaties** [comment]
It's not ready for general population yet. 0.4.0-SNAPSHOT has a "bug" for async side effecting code. 0.3.1 has the method size issue. Give me a few weeks.

**Comment by SethTisue** [comment]
no worries, adding it to the community build isn't general population. we only have a handful of compiler plugins in the build and so I have a goal to have a few more.

**Comment by SethTisue** [comment]
I added a comment clarifying the status.

**Pull request merged**
