### PR TITLE
2.13: new Scala SHA

### PR DESCRIPTION
**Pull request by SethTisue**
~https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/3737/~
~https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/3743/~
~https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/3745/~
~https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/3750/~
~https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/3753/~
~https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/3754/~
~https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/3758/~
https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/3760/ queued

### CODE REVIEW

**Comment by SethTisue** [comment]
```
[airframe:error] java.lang.IllegalStateException: Recursive update
[airframe:error] 	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1760)
[airframe:error] 	at scala.collection.convert.JavaCollectionWrappers$JConcurrentMapWrapper.getOrElseUpdate(JavaCollectionWrappers.scala:442)
[airframe:error] 	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$SurfaceFinder.surfaceOf(ReflectSurfaceFactory.scala:337)
[airframe:error] 	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$.$anonfun$apply$1(ReflectSurfaceFactory.scala:136)
[airframe:error] 	at scala.collection.convert.JavaCollectionWrappers$JConcurrentMapWrapper.$anonfun$getOrElseUpdate$2(JavaCollectionWrappers.scala:442)
[airframe:error] 	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
[airframe:error] 	at scala.collection.convert.JavaCollectionWrappers$JConcurrentMapWrapper.getOrElseUpdate(JavaCollectionWrappers.scala:442)
[airframe:error] 	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$.apply(ReflectSurfaceFactory.scala:136)
```

@xerial @som-snytt this looks like a conflict with scala/scala#10027 — do either of you have an opinion whether the PR needs amending, or whether airframe should be changed?

**Comment by som-snytt** [comment]
```
  def apply(tpe: ru.Type): Surface = {
    surfaceCache.getOrElseUpdate(fullTypeNameOf(tpe), new SurfaceFinder().surfaceOf(tpe))
  }
```
where `surfaceOf`
```
          // Cache if not yet cached
          surfaceCache.getOrElseUpdate(fullName, surface)
```
`ConcurrentHashMap#computeIfAbsent` says

> The mapping function must not modify this map during computation.

So, yes, it must be amended somehow.

I suppose that if you're doing this atomic update, you'd need a flag to say the operation must not attempt caching.

**Comment by som-snytt** [comment]
I'll attempt a PR. Wish me luck.

**Comment by som-snytt** [comment]
That was harder than expected for sbt reasons. Partial result at https://github.com/wvlet/airframe/pull/2260

**Comment by som-snytt** [comment]
@SethTisue I see that the problem with my fix is that `getOrElseUpdate` calls `putIfAbsent` (which NPEs on null) in 2.13.8, vs `computeIfAbsent` (ignore if null) in the fixed version.

In other words, the release notes should highlight that change. I'll edit the PR comment.

Although airframe has to make more than the local change I proposed, I see that it would be convenient if clients of the wrapper could access the `underlying` java collection, even if that required a cast to some well-known interface.

**Comment by xerial** [comment]
I've made a potential fix to airframe's master branch. Let me know if the build still fails.

**Comment by SethTisue** [comment]
@xerial new failure log at https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/3753/artifact/logs/airframe-build.log

**Comment by SethTisue** [comment]
(note that progress was made — it no longer hangs the build)

**Comment by xerial** [comment]
Thanks for the update. I'll check these failures at https://github.com/wvlet/airframe/issues/2265

**Comment by SethTisue** [comment]
@xerial almost there!

```
[airframe] [error] Error: Total 40, Failed 0, Errors 2, Passed 37, Skipped 1, Pending 1
[airframe] [error] Error during tests:
[airframe] [error] 	wvlet.airframe.http.openapi.SimpleOpenAPITest
[airframe] [error] (httpCodeGen / Test / test) sbt.TestsFailedException: Tests unsuccessful
```

https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/3758/artifact/logs/airframe-build.log

**Comment by xerial** [comment]
Applied a fix.

**Comment by SethTisue** [comment]
```
[info] Project airframe--------------------: SUCCESS (project rebuilt ok)
```

**Pull request merged**
