### PR TITLE
move to sbt 0.13.15 (from 0.13.13)

### PR DESCRIPTION
**Pull request by SethTisue**
test run: https://scala-ci.typesafe.com/view/scala-2.11.x/job/scala-2.11.x-integrate-community-build/593/consoleFull

### CODE REVIEW

**Comment by SethTisue** [comment]
after merge, we should promptly merge forward onto 2.11.x-jdk8->2.12.x->2.13.x

UPDATE: done

**Comment by SethTisue** [comment]
utest failure is unrelated. merging

**Comment by SethTisue** [comment]
fyi @eed3si9n @dwijnand this was smooth, no resulting problems in any of the four branches

confession: I sometimes only @-mention Dale because I have to think in order to type "eed3si9n" :-)

**Comment by dwijnand** [comment]
This might help: the tail bit is "design", with the necessary letter alternatives. So it's "Eugene eDesign"?

**Pull request merged**
