### PR TITLE
newer genjavadoc, pick up sbt 1.3 upgrade

### PR DESCRIPTION
**Pull request by SethTisue**
references lightbend/genjavadoc#208

fyi @raboof

### CODE REVIEW

**Comment by SethTisue** [comment]
gah

```
[genjavadoc] [info] Test com.typesafe.genjavadoc.StrictVisibilitySpec.compileSourcesAndGenerateExpectedOutput started
[genjavadoc] [error] Test com.typesafe.genjavadoc.StrictVisibilitySpec.compileSourcesAndGenerateExpectedOutput failed: java.lang.NoClassDefFoundError: com/typesafe/genjavadoc/GenJavadocPlugin, took 1.139 sec
[genjavadoc] [error]     at com.typesafe.genjavadoc.util.GenJavadocCompiler$$anon$1.loadRoughPluginsList(GenJavaDocCompiler.scala:21)
```

**Comment by raboof** [comment]
Hmm, that is weird: I've seen that error (or a very similar one) as well, but it seemed to have gone away when I simplified the sbt build to just have `genjavadoc-plugin` as the root of the project

**Comment by SethTisue** [comment]
curiouser and curiouser:

```
~/genjavadoc % git clean -ffxd
Removing plugin/
Removing project/project/
Removing project/target/
Removing target/
~/genjavadoc % sbt
[info] Loading settings for project genjavadoc-build from plugins.sbt ...
[info] Loading project definition from /Users/tisue/genjavadoc/project
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
[info] Loading settings for project root from build.sbt ...
[info] Set current project to genjavadoc-plugin (in build file:/Users/tisue/genjavadoc/)
[info] sbt server started at local:///Users/tisue/.sbt/1.0/server/7b50a27c862a91e66451/sock
sbt:genjavadoc-plugin> ++2.12.10
[info] Setting Scala version to 2.12.10 on 1 projects.
[info] Reapplying settings...
[info] Set current project to genjavadoc-plugin (in build file:/Users/tisue/genjavadoc/)
sbt:genjavadoc-plugin> test
[info] Compiling 9 Scala sources to /Users/tisue/genjavadoc/target/scala-2.12/classes ...
[info] Compiling 8 Scala sources to /Users/tisue/genjavadoc/target/scala-2.12/test-classes ...
[error] /Users/tisue/genjavadoc/src/test/scala/com/typesafe/genjavadoc/util/GenJavaDocCompiler.scala:21:11: not found: type GenJavadocPlugin
[error]       new GenJavadocPlugin(this) :: super.loadRoughPluginsList()
[error]           ^
[error] one error found
[error] (Test / compileIncremental) Compilation failed
[error] Total time: 5 s, completed Nov 4, 2019 8:15:41 AM
```

**Comment by SethTisue** [comment]
fooling with this outside of dbuild, I have seen all three outcomes (success, compile-time error, runtime `NoClassDefFoundError`). I'm not sure yet if it's deterministic. but at least we know it isn't dbuild's fault

**Comment by SethTisue** [comment]
@raboof this is deeper down this rabbit hole than I have time to go today

**Comment by raboof** [comment]
https://github.com/lightbend/genjavadoc/pull/210 might be it

**Comment by SethTisue** [comment]
merged. genjavadoc itself went green in a local test. let's make sure everything downstream remains green as well: https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/5228/

**Pull request merged**
