### PR TITLE
upgrade sbt 1 from 1.0.4 to 1.1.0-RC1

### PR DESCRIPTION
**Pull request by SethTisue**

### CODE REVIEW

**Comment by SethTisue** [comment]
test run https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/2321/consoleFull ~~(404 til Jenkins gets back from his three-hour tour, three-hour tour)~~

**Comment by SethTisue** [comment]
circe failed to extract, with `[circe] [error] Caused by: java.lang.IllegalArgumentException: requirement failed: A named attribute key must start with a lowercase letter: Optional. Includes Gitter sidecar Chat functionality. Enabled by default.`

I saw somebody on https://gitter.im/sbt/sbt say this error had something to do with sbt-microsites?  maybe check back there to see if they resolved it

**Comment by SethTisue** [comment]
the sbt-microsites fix is https://github.com/47deg/sbt-microsites/pull/247

**Comment by SethTisue** [comment]
having the sbt-microsites fix merged doesn't help until there's a release, and until downstream projects adopt the new version (either themselves, or we do it in forks). I requested a release (47deg/sbt-microsites#248)

**Comment by SethTisue** [comment]
sbt-microsites 0.7.3 is out with the fix

**Comment by SethTisue** [comment]
sbt-microsites upgraded in our fork of circe; also brought this branch up to date with origin/2.12.x

new test run queued: https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/2406/consoleFull ~~(404 til Jenkins finishes digging the tunnel for SF's Central Subway)~~

**Comment by dwijnand** [comment]
Green! Nice.

**Pull request merged**
