### PR TITLE
upgrades: dbuild 0.9.13, sbt 1.2.0

### PR DESCRIPTION
**Pull request by SethTisue**
and unfreeze some projects we'd frozen waiting for sbt 1.2.0
support to land in dbuild

hello @cunei

### CODE REVIEW

**Comment by SethTisue** [comment]
test run: 
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/3258/ (404 for now)

**Comment by SethTisue** [comment]
`failed: scalapb, scalikejdbc`

```
[scalapb] [error] /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.13/project-builds/scalapb-f47005dc19deb1eabaa951faaa78653907462ffd/scalapb-runtime/shared/src/main/scala-2.12/scalapb/textformat/ParserCompat.scala:3:7: ParserCompat is already defined as trait ParserCompat
[scalapb] [error] trait ParserCompat
```

```
[scalikejdbc] [error] **** Missing dependency: the library org.scala-sbt#scripted-plugin is not provided (in space "scala.main") by any project in this configuration file.
```

for scalapb, let's see if using sbt 1.1.x again helps

for scalikejdbc, they are already on 1.2.0, so it isn't that. it probably just needs the same scripted-plugin workaround we have for tut? @xuwei-k's commit that does the 1.2.0 upgrade (scalikejdbc/scalikejdbc@5fa4bb7ce18a720f9e5e0aec31081a506397a6b5) removes usages of`.disablePlugins(ScriptedPlugin)`, so this isn't out of the blue. it also removes `libraryDependencies += "org.scala-sbt" %% "scripted-plugin" % sbtVersion.value`. did something change in 1.2.0 w/r/t scriptedPlugin?

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/3262/

**Comment by xuwei-k** [comment]
https://github.com/sbt/sbt/pull/3875

> Scripted plugin is no longer triggered.

/cc @eed3si9n

**Comment by SethTisue** [comment]
squashy mergy

**Pull request merged**
