### PR TITLE
Add basic build for Scala.js.

### PR DESCRIPTION
**Pull request by sjrd**
I did this in "blind" mode. I cannot test it locally due to #64.

### CODE REVIEW

**Comment by sjrd** [comment]
Updated.
I have rebased on top of master, and I have removed the `scalaJSStage` setup. This will run the JS with Rhino rather than Node.js or PhantomJS. But that won't run the optimizer at all.

@gkossakowski Could you relaunch a build, please?

**Comment by gkossakowski** [comment]
Fails with:

```
[scala-js:error] test in (ScalaJSBuild.compiler, Test) := {}
[scala-js:error]          ^
[scala-js] [error] Type error in expression
[scala-js:error] java.lang.RuntimeException: 
[scala-js:error] 	at scala.sys.package$.error(package.scala:27)
[scala-js:error] 	at distributed.support.sbt.SbtRunner.distributed$support$sbt$SbtRunner$$processCommand(SbtRunner.scala:93)
[scala-js:error] 	at distributed.support.sbt.SbtRunner$$anonfun$run$1$$anonfun$apply$2$$anonfun$apply$3.apply(SbtRunner.scala:74)
[scala-js:error] 	at distributed.support.sbt.SbtRunner$$anonfun$run$1$$anonfun$apply$2$$anonfun$apply$3.apply(SbtRunner.scala:74)
[scala-js:error] 	at distributed.support.sbt.SbtRunner$$anonfun$run$1.apply(SbtRunner.scala:74)
[scala-js:error] 	at distributed.support.sbt.SbtRunner$$anonfun$run$1.apply(SbtRunner.scala:64)
[scala-js:error] 	at sbt.IO$.withTemporaryFile(IO.scala:311)
[scala-js:error] 	at distributed.support.sbt.SbtRunner.run(SbtRunner.scala:64)
[scala-js:error] 	at distributed.support.sbt.SbtBuilder$.buildSbtProject(SbtBuildRunner.scala:84)
[scala-js:error] 	at distributed.support.sbt.SbtBuildSystem.runBuild(SbtBuildSystem.scala:68)
[scala-js:error] 	at distributed.support.sbt.SbtBuildSystem.runBuild(SbtBuildSystem.scala:18)
[scala-js] --== End Building scala-js ==--
```

It's probably caused by scala-js/scala-js@8888bf9bf51aed1abc52cb66a1f6791d981abce1. I'll try to fix this problem and give it another whirl.

**Comment by sjrd** [comment]
Right ... Didn't think about that (and a local build didn't finish overnight ^^, so I can't really test it locally anymore). I've updated.

**Comment by gkossakowski** [comment]
Could you have a look at: https://jenkins-dbuild.typesafe.com:8499/job/Community-2.11.x-manual/142/consoleFull

This has been ran from my own fork but the commit is basically the same one as you just pushed.

**Comment by gkossakowski** [comment]
The build passed but there were a number of weird things like:

```
[scala-js] Testing: library
[scala-js] [warn] No main class detected
[scala-js] [warn] No main class detected
[scala-js] [info] Compiling 0 Scala sources to /mnt/dbuild/jenkinsdbuild3/localhome-a8/workspace/Community-2.11.x-manual/target-0.9.1/project-builds/scala-js-d730909b67045631132a6e50f1db7d04c0c4c79b/library/target/scala-2.11/test-classes...
[scala-js] [error] Usage: scalac <options> <source files>
[scala-js] [error] where possible standard options include:
[scala-js] [error]   -Dproperty=value                Pass -Dproperty=value directly to the runtime system.
[...]
```

**Comment by sjrd** [comment]
These weird things are "normal". Well, it's dbuild's fault: it insists on compiling the `Test` config of every project in the dependency chainBut `library` doesn't have any source in its Test config (the tests actually being in the `testSuite` project). These things appear as `[error]` mostly because scalac just prints the usage on stderr if it is given 0 sources to compile. But if it doesn't fail the build, it means scalac takes it as a warning and still reports success, which is what we want.

AFAICT, the output is normal other than this weirdness. IMO it's good.

**Comment by gkossakowski** [comment]
Ok. The issue is tracked in typesafe/dbuild#161.

**Comment by gkossakowski** [comment]
Welcome to the family!

**Comment by sjrd** [comment]
Yeah :-)

**Comment by sjrd** [comment]
Thanks a lot for bearing with this difficult build, @gkossakowski :-)

**Pull request merged**
