### PR TITLE
add monix

### LINKED ISSUE #414: add monix as a good source of macro regression backstops
it caught e.g. SI-10009

https://github.com/monix/monix/blob/cff18e4f19559a56a0f984016c3da640368c7139/monix-execution/shared/src/main/scala_2.11/monix/execution/schedulers/ExecuteMacros.scala

(inferred from the reproduction in https://gist.github.com/alexandru/26400bfc6209d4884d9cc916ad48d196)

### PR DESCRIPTION
**Pull request by SethTisue**
fixes #414

### CODE REVIEW

**Comment by SethTisue** [comment]
test run: https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/1003/consoleFull (404 til Jenkins recounts all the paper ballots)

**Comment by SethTisue** [comment]
curse you autocorrect! no, I didn't want to run "monks"

https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/1004/consoleFull

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/1005/consoleFull

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/1007/consoleFull

**Comment by adriaanm** [comment]
Awesome!

**Pull request merged**
