### PR TITLE
move sbt tags forward to sbt 1.0.4 version

### PR DESCRIPTION
**Pull request by SethTisue**
and try running sbt tests

### CODE REVIEW

**Comment by SethTisue** [comment]
failed test run, can't even extract dependencies: https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/2297/consoleFull

this doesn't play well with the new cloc-plugin stuff. there is stuff in sbt-houserules now that calls `update` (on the project, not on the build) from the build definition, which fails because cloc-plugin isn't built yet. I ran into this before and worked around it by removing or downgrading sbt-houserules, but I don't want to do that to every sbt module, so I think we'll need to look into how to remove those `update` calls for real

**Comment by SethTisue** [comment]
I submitted this PR on sbt-houserules: https://github.com/sbt/sbt-houserules/pull/20

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/2320/consoleFull ~~(404 til Jenkins finishes drying his quick-drying underthings on the music stand)~~

**Comment by SethTisue** [comment]
I kinda forgot where I left this, so I updated the branch and triggered a new test run: https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/2387/consoleFull

I think the next step is to try to follow Eugene's suggestion at https://github.com/sbt/sbt-houserules/pull/20#issuecomment-347649027

**Comment by SethTisue** [comment]
yuck, I'm already doing `set every scalafmtOnCompile := false` and it doesn't fix it.

**Comment by SethTisue** [comment]
but why doesn't zinc fail to extract? zinc is using the same version (0.3.3) of sbt-houserules as the other sbt modules are

**Comment by SethTisue** [comment]
perhaps it's because there seem to be a variety of sbt-scalafmt versions involved:

```
sbt-io/project/plugins.sbt:addSbtPlugin("com.lucidchart" % "sbt-scalafmt" % "1.10")
sbt-librarymanagement/project/plugins.sbt:addSbtPlugin("com.lucidchart" % "sbt-scalafmt" % "1.10")
sbt-util/project/plugins.sbt:addSbtPlugin("com.lucidchart" % "sbt-scalafmt" % "1.14")
sbt/project/plugins.sbt:addSbtPlugin("com.lucidchart" % "sbt-scalafmt" % "1.10")
zinc/project/plugins.sbt:addSbtPlugin("com.lucidchart" % "sbt-scalafmt" % "1.12")
```

the projects that won't extract are all on 1.10, the projects that do extract (zinc, sbt-util) are the two on newer versions

**Comment by SethTisue** [comment]
sigh, upgrading sbt-scalafmt to 1.14 in my fork of the sbt repo didn't make the problem go away

I now think the problem is that we need to set `scalafmtOnCompile` to false, but we need to do it sooner, doing it in `extra.commands` isn't soon enough

**Comment by SethTisue** [comment]
okay, now we're getting somewhere: https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/2391/consoleFull

**Comment by SethTisue** [comment]
using `extra.settings` instead of `extra.commands` to disable scalafmt worked. this is close now. new test run: https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/2393/consoleFull

**Comment by SethTisue** [comment]
there is one test failure:

```
[sbt] [info] SettingQueryTest
[sbt] [info] setting query should
[sbt] [info]   + t/scalaVersion
[sbt] [info]   + t/sourcesInBase
[sbt] [info]   + t/startYear
[sbt] [info]   + t/scalaArtifacts
[sbt] [error]   x t/libraryDependencies
[sbt] [error]    '{"type":"SettingQuerySuccess","value":[{"organization":"org.scala-lang","name":"scala-library","revision":"2.12.1","isChanging":false,"isTransitive":true,"isForce":false,"explicitArtifacts":[],"inclusions":[],"exclusions":[],"extraAttributes":{},"crossVersion":{"type":"Disabled"}}],"contentType":"scala.collection.Seq[sbt.librarymanagement.ModuleID]"}' != '{"type":"SettingQuerySuccess","value":[{"organization":"org.scala-lang","name":"scala-library","revision":"2.12.1","isChanging":false,"isTransitive":true,"isForce":false,"crossVersion":{"type":"Disabled"}}],"contentType":"scala.collection.Seq[sbt.librarymanagement.ModuleID]"}' (file:1)
[sbt] [error] Actual:   ...lue":{"...,"[explicitA]r[t]i[facts]":[],[inclus]
[sbt] [error] io...":[],"xc...":[],"...le[sbt.librarymanagement.ModuleID]"}
[sbt] [error] Expected: ...lue":{"...,"[crossVe]r[s]i[on":{]"[type]"[:"Disabl]
[sbt] [error] []e[]d"}}[sbt.librarymanagement.ModuleID]"}
```

but I'm eager to merge this and move on, so I'll just disable running the tests

**Comment by SethTisue** [comment]
@dwijnand (maybe the test failure interests you)

**Comment by dwijnand** [comment]
Yes it does. Looks like maybe a hashing difference, due to running on different jvm versions/types?

**Pull request merged**
