### PR TITLE
unfreeze scala-rewrites

### PR DESCRIPTION
**Pull request by SethTisue**
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/5752/

### CODE REVIEW

**Comment by SethTisue** [comment]
@dwijnand what do you make of these test failures? https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/5752/artifact/logs/scala-rewrites-build.log

**Comment by SethTisue** [comment]
I did a local run with `./narrow scala-rewrites` and `version=2.12.11` and got the same failures. so, doesn't have to do with post-2.12.11 changes, apparently

**Comment by dwijnand** [comment]
> what do you make of these test failures?

My first guess is the "Power" thingy isn't kicking in? https://github.com/scala/scala-rewrites/pull/14/files#diff-b09e11820eea2f4cca90f9346899e64a

> I did a local run with `./narrow scala-rewrites` and `version=2.12.11` and got the same failures.

I'm stating the obvious, but 2.12.11 runs cleanly on Travis CI: https://travis-ci.com/github/scala/scala-rewrites/builds/162320176 so it seems to do with either the modded config in the CB, or something deeper in the CB?

Thanks for that check though.  I was going to suggest that I try to setup Travis CI cron jobs to run against 2.12.next (next CB't candidate release version).  Now it seems not relevant here, so I'll postpone that until it proves worthwhile.

About this one, I'll have to circle back to go deeper to understand what's going on.  Thanks for the initial push.

**Comment by dwijnand** [comment]
I've found a way to test Scala nightlies in sbt proper, in scala-rewrites:

* https://github.com/scala/scala-rewrites/pull/35

and I've set up nightly builds of it:

https://travis-ci.com/github/scala/scala-rewrites/settings

So we can drop this effort, IMO.

**Pull request closed without merging**
