### PR TITLE
get akka-http green on JDK 17

### PR DESCRIPTION
**Pull request by SethTisue**
https://scala-ci.typesafe.com/job/scala-2.13.x-jdk17-integrate-community-build/482/ queued

https://scala-ci.typesafe.com/job/scala-2.13.x-jdk8-integrate-community-build/4858/ queued

### CODE REVIEW

**Comment by SethTisue** [comment]
fyi @raboof @jrudolph

**Comment by SethTisue** [comment]
(note that Akka itself still fails because of the incompatibility between JDK 17 and sbt-osgi 0.9.4)

**Comment by raboof** [comment]
> (note that Akka itself still fails because of the incompatibility between JDK 17 and sbt-osgi 0.9.4)

For reference: https://github.com/akka/akka/issues/31132 . Akka artifacts should work with jdk17, but indeed may need some packages to be opened up - https://github.com/akka/akka/issues/31087

**Comment by jrudolph** [comment]
Thanks, I'm also working on enabling JDK 17 nightlies for Akka HTTP at https://github.com/akka/akka-http/actions/workflows/nightly.yml. This fix is only needed against Akka 2.5. When running the build against Akka 2.6 this problem isn't there (running the akka-http build with `sbt -Dakka.http.build.akka.version=2.6.18`).

**Comment by SethTisue** [comment]
@jrudolph excellent! I added that flag and removed the workaround: 14485a75231c7b7b90a9bf26c861cf2e50179d1d — but note that I had to exclude `Http2ServerSpec.scala`, it started failing, and also `WebSocketIntegrationSpec.scala`, saw several failures on that one (not every time)

**Comment by jrudolph** [comment]
Yes, since the move from Jenkins we did not run any builds against Akka 2.6 any more, so a few timing issues need fixing. I'm probably going to spent a bit more time on improving the situation.

**Comment by jrudolph** [comment]
> `WebSocketIntegrationSpec.scala`,

Fixed in https://github.com/akka/akka-http/pull/4076

> `Http2ServerSpec.scala`,

Fixed in https://github.com/akka/akka-http/pull/4062

Our own nightlies against JDK 17 have now been green for a few days:

https://github.com/akka/akka-http/actions/workflows/nightly.yml

**Comment by SethTisue** [comment]
@jrudolph trying it out here: https://github.com/scala/community-build/pull/1547

**Pull request merged**
