### PR TITLE
add pimpathon

### PR DESCRIPTION
**Pull request by SethTisue**
it's in the 2.11.x-jdk8 build, but got the boot from 2.12 at some point.
it has a lot more dependencies these days, but we actually have all of
them now (I think?)

### CODE REVIEW

**Comment by SethTisue** [comment]
fyi @stacycurl. not sure yet if this is going to work or run into trouble, but opening the PR anyway to at least have a record of the attempt. test run in progress at https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/1393/consoleFull

**Comment by SethTisue** [comment]
jsonpath is in there now, but dbuild doesn't rewrite the pimpathon->jsonpath dependency for some reason. setting this aside for now

**Comment by SethTisue** [comment]
let's leave a record of the last attempt, anyway: https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/1398/consoleFull ~~(404 while Jenkins ponders the premature spoilage of that bag of minneolas he bought)~~

**Comment by stacycurl** [comment]
Sorry, I'm terrible with email, is there anything i can do ? Use a
different version of jsonpath, fur example.

**Comment by SethTisue** [comment]
@stacycurl I have no idea because I don't even understand what the cause of the error is. I might have time to return to it next month.

@cunei is it apparent to you what's going on with dbuild here...?

**Comment by SethTisue** [comment]
new test run (just to see if anything has changed): https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/1760/consoleFull (404 til Jenkins finishes tearing up a big pile of cardboard boxes)

**Comment by SethTisue** [comment]
closing for inactivity. I would like to include pimpathon, but it's not a priority

**Pull request closed without merging**
