### PR TITLE
fix scalafix on JDK 9

### PR DESCRIPTION
**Pull request by SethTisue**
references https://github.com/sbt/zinc/issues/520 /cc @olafurpg

### CODE REVIEW

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-jdk9-integrate-community-build/439/consoleFull

**Comment by SethTisue** [comment]
```
[scalafix] [error] Failed tests:
[scalafix] [error] 	scalafix.tests.cli.CliSyntacticSuite
[scalafix] [error] 	scalafix.tests.cli.CliSemanticSuite
[scalafix] [error] 	scalafix.tests.util.PrettyExpectSuite
[scalafix] [error] 	scalafix.tests.cli.CliGitDiffSuite
[scalafix] [error] 	scalafix.tests.cli.CliSuppressSuite
[scalafix] [error] Error during tests:
[scalafix] [error] 	scalafix.tests.core.SemanticdbIndexSuite
[scalafix] [error] 	scalafix.tests.rule.RuleSuite
[scalafix] [error] 	scalafix.tests.core.PrettyTypeFuzzSuite
[scalafix] [error] 	scalafix.tests.core.PrettyTypeSuite
[scalafix] [error] 	scalafix.tests.v0.LegacyDenotationSuite
[scalafix] [error] 	scalafix.tests.v1.SymbolInfoSuite
[scalafix] [error] 	scalafix.tests.core.DenotationOpsSuite
[scalafix] [error] 	scalafix.tests.core.BasePrettyTypeSuite
[scalafix] [error] 	scalafix.tests.core.SymbolMatcherSuite
[scalafix] [error] 	scalafix.tests.v0.LegacySyntheticsSuite
```

**Comment by SethTisue** [comment]
this is reproducible outside dbuild with by running on Java 9 and doing `sbt -J--add-modules=java.xml.bind` followed by `set every javaHome := None` (I find this is needed on my Mac as well as Jenkins) followed by `unit/Test/test`

I tried JDK 10 as well, same result.

@olafurpg shall I open a ticket in the scalafix repo? I see your https://github.com/scalacenter/scalafix/blob/master/.travis.yml only has `oraclejdk8`

an example failure looks like

```
[info] - --help *** FAILED *** (349 milliseconds)
[info]   CommandLineError=4 did not equal Ok=0 error: Unable to load symbol table (BaseCliSuite.scala:73)
```

**Comment by SethTisue** [comment]
@olafurpg for context, it's not strictly necessary that every project in the Scala community build be buildable on Java 9, 10, or 11. we're just trying to get as many of them green as we can to increase overall coverage, and since often the project fixes required to make it happen are tiny.

**Comment by olafurpg** [comment]
I guess this line here is the culprit https://github.com/scalacenter/scalafix/blob/6584af204fd2a5ef0c261fdc97ad599962a8ffa0/scalafix-reflect/src/main/scala/scalafix/internal/reflect/ClasspathOps.scala#L20

```scala
def bootClasspath: Option[Classpath] = sys.props.collectFirst {
    case (k, v) if k.endsWith(".boot.class.path") => Classpath(v)
}
```

What is the JDK 9 equivalent? We do the same in the Scalameta build to access the local file path to rt.jar and friends.

**Comment by SethTisue** [comment]
@retronym can you advise Olaf on this...?

**Comment by SethTisue** [comment]
we can bother Jason about it after he's not on the 2.12.7 hot seat anymore :-)

**Comment by SethTisue** [comment]
note that `--add-modules=java.xml.bind` doesn't work anymore as of JDK 11, instead you do e.g. `libraryDependencies += "javax.xml.bind" % "jaxb-api" % "2.3.0"`

and, I've stopped doing any testing on JDK 9, and I'll stop doing any further testing on 10 soon. only 11.

**Comment by SethTisue** [comment]
ping @retronym

**Comment by olafurpg** [comment]
I have investigated the new jrt:// file system and that should solve the issue. I will likely get around to this sometime in October since java 11 support is high in demand.

**Comment by SethTisue** [comment]
@olafurpg SGTM

**Comment by olafurpg** [comment]
We BTW already have a java-11-compat branch in scalafix that fixes lower hanging fruit issues like build.sbt settings and String.lines.

**Comment by SethTisue** [comment]
anyway in the 2.12.x-on-JDK11 build currently,

```
[info] Project scalafix--------------------: DID NOT RUN (stuck on broken dependencies: coursier, slick)
```

so this isn't an even an issue currently until those two upstream projects become buildable on JDK 11

**Comment by olafurpg** [comment]
Scalafix works on JDK 11 now and we run CI on openjdk11 for every PR.

**Pull request closed without merging**
