### PR TITLE
 added scala-gopher to set of builds.

### PR DESCRIPTION
**Pull request by rssh**

### CODE REVIEW

**Comment by SethTisue** [comment]
test run: https://scala-ci.typesafe.com/job/scala-2.11.x-integrate-community-build/203/

**Comment by rssh** [comment]
It was a problem with using java8 API,  fixed now. Need touch Jenkins for next try.

**Comment by SethTisue** [comment]
new run: https://scala-ci.typesafe.com/job/scala-2.11.x-integrate-community-build/203/

**Comment by SethTisue** [comment]
```
[scala-gopher] [error] /home/jenkins/workspace/scala-2.11.x-integrate-community-build/target-0.9.5/project-builds/scala-gopher-c4d186df0fdaf28edac44ab61e4447e045abd21d/src/main/scala/gopher/Transputer.scala:333: not found: value addSuppressed
[scala-gopher] [error]    addSuppressed(t.recoveryStatistics.lastFailure.get) 
[scala-gopher] [error] /home/jenkins/workspace/scala-2.11.x-integrate-community-build/target-0.9.5/project-builds/scala-gopher-c4d186df0fdaf28edac44ab61e4447e045abd21d/src/main/scala/gopher/Transputer.scala:333: not found: value addSuppressed
[scala-gopher] [error]    addSuppressed(t.recoveryStatistics.lastFailure.get) 
[scala-gopher] [error]    ^
[scala-gopher] [error]    ^
```

you'll also see an unrelated Shapeless failure in the log. if you rebase onto current upstream 2.11.x, that will go away.

**Comment by rssh** [comment]
New run was  https://scala-ci.typesafe.com/job/scala-2.11.x-integrate-community-build/205/ .
I see, scala-gopher build was successfull there.
(doing rebase)

**Comment by rssh** [comment]
rebase done

**Comment by SethTisue** [comment]
new test run: https://scala-ci.typesafe.com/job/scala-2.11.x-integrate-community-build/207/   (link will 404 until job reaches head of queue)

**Comment by SethTisue** [comment]
test run passed, so this is ready to merge, but first, can you squash it into a single commit? right now there's 4.

**Comment by rssh** [comment]
done  (btw, not sure that I doing this right).

**Comment by SethTisue** [comment]
still showing 4 commits

**Comment by SethTisue** [comment]
still showing 4 commits. you need to squash and rebase onto the current head of 2.11.x

**Comment by SethTisue** [comment]
your changes are now in a single commit, but this needs another rebase onto current 2.11.x

**Comment by rssh** [comment]
done

**Comment by SethTisue** [comment]
thank you, Ruslan, for this contribution! I'll let you know if any issues crop up when this gets merged onto the 2.11.x-jdk8 and 2.12.x community builds.

**Pull request merged**
