### PR TITLE
2.13: re-add akka-more, akka-http

### PR DESCRIPTION
**Pull request by SethTisue**
wip

### CODE REVIEW

**Comment by SethTisue** [comment]
test run queued: https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/988 (404 til Jenkins catches up)

this will probably progress slowly until 2.12.5 is out, but let's get the ball rolling

**Comment by SethTisue** [comment]
```
[akka-more] [error] Error during tests:
[akka-more] [error] 	akka.persistence.LeveldbPersistentActorSpec
[akka-more] [error] 	akka.persistence.InmemPersistentActorSpec
```

@2m ?

**Comment by SethTisue** [comment]
might as well attempt to re-add at the same time: twirl, play-doc, play-json, play-ws (all were published for 2.13.0-M3 recently, so very likely they will work here too)

**Comment by SethTisue** [comment]
new test run queued: https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/990 ~~(404 til Jenkins finishes up his phone call with Rex Tillerson)~~

**Comment by SethTisue** [comment]
this is good:

```
[info] Project play-doc--------------------: SUCCESS (project rebuilt ok)
[info] Project play-json-------------------: SUCCESS (project rebuilt ok)
[info] Project twirl-----------------------: SUCCESS (project rebuilt ok)
```

but:

```
[akka-more] [error] Failed tests:
[akka-more] [error] 	akka.stream.tck.EmptyProcessorTest
```

intermittent? let's try again: new test run queued: https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/992 (404 til Jenkins finishes counting how many times he can rub the cat's fur backwards before it bites him)

**Comment by 2m** [comment]
The `akka.stream.tck.EmptyProcessorTest` is intermittent. Already tracked in https://github.com/akka/akka/issues/24581

**Comment by SethTisue** [comment]
we can try again after https://github.com/scalamacros/paradise/issues/114 is merged

**Comment by SethTisue** [comment]
judging from https://github.com/playframework/playframework/issues/7940 I should be able to add all of Play back in now

**Comment by SethTisue** [comment]
merging new collections took us back to square one, so it'll be a while before this is actionable again, so I'm just going to close it.

**Comment by SethTisue** [comment]
Akka ticket is https://github.com/akka/akka/issues/24535

**Pull request closed without merging**
