### PR TITLE
add scalaz-zio (and remove scalaz 8 for now)

### PR DESCRIPTION
**Pull request by SethTisue**
fyi @jdegoes

### CODE REVIEW

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/3964/

**Comment by jdegoes** [comment]
@SethTisue Woohoo! 🕺 🎉 

Let me know if there's anything I can / should do.

**Comment by SethTisue** [comment]
@jdegoes will do.

new run, after needed tweak to config: 
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/3975/

**Comment by SethTisue** [comment]
hmm

```
[scalaz-zio] [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[scalaz-zio] [warn] 	::          UNRESOLVED DEPENDENCIES         ::
[scalaz-zio] [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[scalaz-zio] [warn] 	:: org.openjdk.jcstress#jcstress-core;0.5.3-dbuildxb59e5c54089b3a59c53f293997356b294ec1118c: not found
[scalaz-zio] [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
```

not sure why dbuild seems to think jcstress is a Scala-based dependency, subject to version number rewriting. it's Java-based, dbuild should be leaving it alone. I'll have to take a closer look at this later

**Comment by SethTisue** [comment]
a similar thing occurs with sbt-jmh. something about sbt plugins that modify `libraryDependencies` I guess

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/3992/

**Comment by SethTisue** [comment]
the good news is that the core, and some of the integration subprojects, are already green in local testing

but this is failing:

```
[scalaz-zio] [error] Modules were resolved with conflicting cross-version suffixes in ProjectRef(uri("file:/Users/tisue/community.212/target-0.9.16/project-builds/scalaz-zio-79af555fda03d99511440081a947716e1a1bb90e/"), "interopCatsJVM"):
[scalaz-zio] [error]    org.typelevel:macro-compat <none>, _2.12
[scalaz-zio] [error]    org.scalacheck:scalacheck <none>, _2.12
```

it's in `interopCatsJVM` which is a subproject we don't absolutely need to have, but it would be nice to make it work if it isn't too much trouble

right now I don't know yet what might be causing this

**Comment by SethTisue** [comment]
let's just drop `interopCatsJVM`, I think the cost/benefit of me troubleshooting that is probably not justified, at least for now

~~https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/4016/~~
~~https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/4022/~~
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/4025/

**Comment by SethTisue** [comment]
status report: in the last test run, scalaz-zio itself was green (with `interopCatsJVM` disabled), but scalaz8 failed because scalaz8 is in its own independent dbuild space, but it and scalaz-zio both use pascal.

I could have worked around it by building pascal twice, once in each space, but I'd like to rethink all this instead, as follows.

at the time I added scalaz 8 to the community build, circa May 2018, it was actually mainly because I wanted to include scalaz-effect, which was starting to get some traction.

but scalaz-effect became scalaz-zio (and doesn't depend on scalaz 8), and scalaz 8 hasn't seen a ton of development action lately, and I haven't seen other projects start to depend on it, so I don't think it's currently worth keeping if it must be in its own dbuild space, since multiple spaces complicates everything (as we see with the pascal issue).

so what I've done in the latest wip commit is moved scalaz 8 into the same space with scalaz 7 and scalaz-zio. if that works out, great. but if this approach proves impossible, or just too hard, I'll just drop scalaz 8 for now. we could always bring it back later.

new run queued: 
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/4034/ (404 til Jenkins queue clears)

**Comment by jdegoes** [comment]
I can delete `pascal` from `scalaz-zio`. In fact, it shouldn't even be there. Would that help matters?

**Comment by jdegoes** [comment]
Btw thanks for your work on this and sorry it's been such a pain!

**Comment by SethTisue** [comment]
> I can delete pascal from scalaz-zio. In fact, it shouldn't even be there. Would that help matters?

yes please!

> Btw thanks for your work on this and sorry it's been such a pain!

no worries, it's pretty much always like this, here in this repo :-)

**Comment by SethTisue** [comment]
I went ahead and removed scalaz 8 for now, see #843, any further discussion on that aspect can go there

**Comment by jdegoes** [comment]
Too late to help, perhaps, but we deleted Pascal too! Looks like a holdover from when ZIO was copied over from Scalaz 8.

**Pull request merged**
