### PR TITLE
upgrade to sbt 0.13.16 + refresh MiMA + reinstate conductr-lib + add scalastyle + refresh lightbend-emoji

### PR DESCRIPTION
**Pull request by SethTisue**
not to be merged until 0.13.16 final is out.  in the meantime,
just helping test the new sbt version.  @eed3si9n @dwijnand

### CODE REVIEW

**Comment by SethTisue** [comment]
test run: https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/1468/consoleFull

**Comment by dwijnand** [comment]
```
EXTRACTION FAILED (failed: scala-parser-combinators)

Cyclic reference involving
*:scalaVersion
root-950fabd31421f835198eabd03f5fa1753af44c91/*:crossScalaVersions
root-950fabd31421f835198eabd03f5fa1753af44c91/*:scalaVersion
```

@SethTisue known?

**Comment by SethTisue** [comment]
perhaps a recent change in that repo. I'll investigate

**Comment by lrytz** [comment]
```
[scala-parser-combinators] Commit: 2324d69d24e5540e220c91e46aa07a0962e3b330
```

This is from Jan 25 https://github.com/scala/scala-parser-combinators/commit/2324d69d24e5540e220c91e46aa07a0962e3b330

**Comment by SethTisue** [comment]
yeah, so this must have to do with the sbt version bump. @dwijnand can you think of a change in 0.13.16-M1 that could affect this somehow?

the scala-parser-combinators build has `scalaVersion in ThisBuild := crossScalaVersions.value.head` and then the `crossScalaVersions` doesn't consult any other keys

**Comment by SethTisue** [comment]
maybe sbt/sbt@ff017eb475fbf18b8066125596bcd1a8cd8fb3ff ?

**Comment by eed3si9n** [comment]
> maybe sbt/sbt@ff017eb ?

That could be the culprit since I did add `scalaVersion` at the project level.

**Comment by eed3si9n** [comment]
I can start up sbt 0.13.16-M1 on 1.0.x branch of scala-parser-combinators, so I'm wondering if the problem was actually to do with AutoPlugin ordering that @dwijnand fixed in https://github.com/scala/sbt-scala-modules/pull/20. Will scala/scala-parser-combinators@6cac8c3c603e3ff3ec1a3c8dde438d38fbebcced be forward ported?

**Comment by eed3si9n** [comment]
Actually the forward porting was already done 5 days ago in https://github.com/scala/scala-parser-combinators/pull/115, so it should build now.

**Comment by SethTisue** [comment]
rebased. new test run: https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/1493/consoleFull

**Comment by SethTisue** [comment]
```
[info] >>> The dbuild result is------------: SUCCESS (project rebuilt ok)
```

**Comment by eed3si9n** [comment]
Awesome.

**Comment by SethTisue** [comment]
test run with 0.13.6-RC1: https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/1689/consoleFull ~~(404 while Jenkins sits and ponders why the little birds flit from branch to branch, couldn't they just sit still?)~~

UPDATE: doh, I should have merged 2.12.x onto this branch before running

**Comment by SethTisue** [comment]
new test run: https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/1690/consoleFull ~~(404 while Jenkins gazes blankly at Warren Harding's deathbed)~~

**Comment by SethTisue** [comment]
I think I'm going to merge this even though 0.13.16 is still in release candidates, since it enables building the master branch of MiMa (now that Scala 2.12 support in that repo was merged), which is a pretty nice benefit.

**Comment by SethTisue** [comment]
aborted the old test run — everything extracts, at least.

new test run to test just the conductr-lib reinstatement: https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/1691/consoleFull

**Comment by SethTisue** [comment]
new test run https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/1692/consoleFull

**Comment by SethTisue** [comment]
new test run https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/1693/consoleFull

**Comment by SethTisue** [comment]
sure is dark down here in this rabbit hole

but the bunnies are friendly.... SO FAR

**Comment by SethTisue** [comment]
the scalafmt part of this is turning out to be especially hard, so I'll make a separate PR out of that

**Comment by SethTisue** [comment]
ok I think this is done, but we need a full test run to make sure nothing regressed: https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/1696/consoleFull

**Pull request merged**
