### PR TITLE
Reintroduce notifications post scala-ci infra move

### PR DESCRIPTION
**Pull request by dwijnand**
Using shapeless' master branch test sources, which currently don't compile with 2.12.0-RC1.

/cc @milessabin

### CODE REVIEW

**Comment by dwijnand** [comment]
@SethTisue how do I trigger a build for this?

**Comment by SethTisue** [comment]
I started it for you at https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/574/ (404 til an earlier build finishes)

contact me privately if you want admin access to Jenkins so you can do it yourself in the future, if you like. (but I'm happy to triggers runs occasionally on request.)

**Comment by dwijnand** [comment]
Outcomes:

1) The Scala build failed, when trying to run `com.typesafe.dbuild.support.scala.ScalaBuildSystem$.antHasTarget` ([as I expected it would](https://github.com/typesafehub/dbuild/issues/185)) - I'm not sure what I'm doing wrong here

2) Failed to email because there's no localhost SMTP server

```
[info] Sending outcome of project shapeless to: miles@milessabin.com
[error] ERROR SENDING to miles@milessabin.com the outcome of project shapeless using template email
[error] javax.mail.MessagingException: Could not connect to SMTP host: localhost, port: 25;
[error]   nested exception is:
[error]     java.net.ConnectException: Connection refused
[error]     at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:1961)
[error]     at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:654)
[error]     at javax.mail.Service.connect(Service.java:295)
[error]     at javax.mail.Service.connect(Service.java:176)
[error]     at javax.mail.Service.connect(Service.java:125)
[error]     at javax.mail.Transport.send0(Transport.java:194)
[error]     at javax.mail.Transport.send(Transport.java:124)
[error]     at com.typesafe.dbuild.build.EmailNotificationContext.send(Notifications.scala:185)
[error]     at com.typesafe.dbuild.build.EmailNotificationContext.send(Notifications.scala:94)
```

@SethTisue Do you know what SMTP server I should use?

**Comment by dwijnand** [comment]
Oh. I guess Jenkins runs the HEAD of the PR, rather than GitHub's merge commit?

Rebased so it picks up Adriaan's Scala Aether fix.

**Comment by dwijnand** [comment]
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/576/console

**Comment by SethTisue** [comment]
after the Aether change, the job parameters are different. see e.g. https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/571/parameters/ (scala-ref isn't a git ref but a version number for a published Scala, and we temporarily hijacked `scala_build_bootstrap_opt` for STARR, so e.g. `2.12.0-RC1`)

(before too much longer I'll rationalize this via changes to scala-jenkins-infra)

**Comment by SethTisue** [comment]
```
[info] Sending outcome of project shapeless to: miles@milessabin.com
[error] ERROR SENDING to miles@milessabin.com the outcome of project shapeless using template email
[error] javax.mail.MessagingException: Could not connect to SMTP host: localhost, port: 25;
[error]   nested exception is:
[error]     java.net.ConnectException: Connection refused
[error]     at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:1961)
```

but then ironically later:

```
Sending e-mails to: adriaan@typesafe.com seth.tisue@typesafe.com
```

why one works and the other doesn't, I don't know. but here's one guess: perhaps the failure to send mail is on the worker, and the successful mail sending is actually happening on jenkins-master?

**Comment by dwijnand** [comment]
```
Build failed after: 00h 12m 59.1s
All done.
Build step 'Execute shell' marked build as failure
erreicht: 265188
Sending e-mails to: adriaan@typesafe.com seth.tisue@typesafe.com
Notifying endpoint 'HTTP:http://scala-ci.typesafe.com:8888/jenkins'
Finished: FAILURE
```

I think that "All done." is dbuild exiting. So I'm inclined to believe that that's dbuild failing to send to Miles and then Jenkins emailing you guys. Especially because those 2 emails don't appear in the community-build repo.

**Comment by SethTisue** [comment]
right. but I'm assuming that a particular host can either send mail or it can't, regardless of which program is trying to do it, so that's why I was interested in the master-or-worker question

**Comment by dwijnand** [comment]
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/577/console

**Comment by dwijnand** [comment]
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/578/consoleFull

**Comment by dwijnand** [comment]
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/579/console

**Comment by dwijnand** [comment]
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/580/console

**Comment by dwijnand** [comment]
Ok this is now successfully reproducing the compilation failures that shapeless' tests have with Scala 2.12.0-RC1.

Kindly paging @adriaanm for SMTP help on the Scala-CI Jenkins.

**Comment by adriaanm** [comment]
Redirect to @sethtisue. I'm away until Sep 23

**Comment by SethTisue** [comment]
I'm reluctant to take on the needed Chef changes myself, to be honest... so much other stuff on my plate. In particular, the 2.12 community build is in poor shape overall and I want to fix that. Once the 2.12 build is in better shape (many fewer forks and freezes, a few more key projects, etc) — and I'm actively working on it — then I'd be in a better position to accept help from library authors, at which point the email notifications thing might start seeming higher priority.

If you want to try the Chef stuff yourself, you'll find it's far better documented than it was 1.5 years ago, at least.

Or, would some kludge work? Either on the community build side, or on the dbuild side?

**Comment by dwijnand** [comment]
This was scratching an itch. I'm equally reluctant at this time to get stuck in with Chef.

Anyone interested in receiving notifications for their build failures will hopefully see this effort and pick up from here.

**Comment by SethTisue** [comment]
> Or, would some kludge work? Either on the community build side, or on the dbuild side?

or, on some other side. here's what I mean.

one idea that's come up a few times would be to have a "community build status" web page somewhere, so library authors could see at a glance what libraries are in the three community builds and what the last result was. you could imagine having additional columns for whether the tests ran or not, etc.

whatever built that web page (by retrieving and digesting the dbuild logs from Jenkins) could also send emails to the authors — making it a separate concern, rather than something requiring dbuild and/or scala-jenkins-infra participation

or, if we had that page, maybe the emails would seem less necessary.

I have no idea what the chances of this happening are, but I think this would a neat thing for the Scala Center to tackle. it doesn't need a Scala team member

**Pull request closed without merging**
