### PR TITLE
move scalaz to 7.3 (from 7.2)

### LINKED ISSUE #515: move scalaz to 7.3.x?
@aloiscochard asked if this would be possible

we can certainly try it and see what happens. cc @xuwei-k

### PR DESCRIPTION
**Pull request by SethTisue**
fixes #515

### CODE REVIEW

**Comment by SethTisue** [comment]
holding off on queueing a test run until after 2.12.2 is built

**Comment by SethTisue** [comment]
rebased, test run queued: https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/1439/consoleFull (404 til Jenkins finishes cleaning up the stain the hand sanitizer left on the credenza)

fyi @xuwei-k

**Comment by SethTisue** [comment]
```
[info] >>> The dbuild result is------------: FAILED (failed: scalaprops, specs2)
```

@xuwei-k want to look at the scalaprops thing? `scalazlaws/src/main/scala/scalaprops/scalazlaws/bindRec.scala:13: missing parameter type`

as for specs2,

```
[specs2] [error] /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.7-RC1/project-builds/specs2-aeb48d71b1cb2ad59a9bcdbfc9d7128312808335/core/src/main/scala/org/specs2/specification/process/Levels.scala:55: not found: value leaf
[specs2] [error]     val init = leaf((DefaultFragmentFactory.text("root"), 0)).loc
[specs2] [error]                ^
[specs2] [error] /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.7-RC1/project-builds/specs2-aeb48d71b1cb2ad59a9bcdbfc9d7128312808335/core/src/main/scala/org/specs2/specification/process/Levels.scala:62: not found: value leaf
[specs2] [error]           case Some(fragment) => parent.insertDownLast(leaf((fragment, level)))
[specs2] [error]                                                        ^
```

in the specs2 build I see `scalazVersion in GlobalScope := "7.2.7"`, so I would imagine this would be reproducible outside of dbuild. @etorreborre any interest in moving specs2 to Scalaz 7.3...? either yourself, or putting out a call for assistance? so many projects depend on specs2, directly or indirectly, that we can't really move the community build to 7.3 unless specs2 moves.

even if there's a reason you want to stay on 7.2 for now, perhaps there could be a 7.3 branch we could track, it doesn't have to be your actual release branch.

another possibility would be to try to find a way to fix the error in a way that's source-compatible with both 7.2 and 7.3. then neither upgrading or branching would be necessary.

**Comment by SethTisue** [comment]
P.S. note that I don't know that much about the scalaz ecosystem; I don't know how common it is for people to still be on 7.2. one thing we don't know yet is, even if we fix or work around this in specs2, how many downstream projects will still fail here?

**Comment by etorreborre** [comment]
@SethTisue I'm currently working on a [new specs2 version](https://github.com/etorreborre/specs2/tree/specs2-fp-lib) without anymore dependency on Scalaz to avoid those problems. There will still be a `specs2-scalaz` module for `Task` matchers though. I don't think this branch is quite ready yet (the build seems to be blocking in Travis), my plan was also to finish a scala.js build and publish a brand new 4.x series with both changes.

However if that helps I can put master with a default `scalaz 7.3` version.

**Comment by etorreborre** [comment]
Oh, I also see that scalaz 7.3 is not yet official. Can we do that move once it is?

**Comment by SethTisue** [comment]
fyi @aloiscochard

**Comment by etorreborre** [comment]
@SethTisue @aloiscochard [here](https://github.com/etorreborre/specs2/tree/scalaz-7.3) is at least a compiling branch.

**Comment by SethTisue** [comment]
@etorreborre awesome thx, new test run kicked off: https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/1445/consoleFull

**Comment by SethTisue** [comment]
the new test run shows only a handful of other failures:

```
[info] Project kxbmap-configs----------: DID NOT RUN (stuck on broken dependencies: scalaprops)
[info] Project monix-------------------: FAILED (RuntimeException: )
[info] Project nyaya-------------------: FAILED (RuntimeException: )
[info] Project scalamock---------------: FAILED (RuntimeException: Tests unsuccessful)
[info] Project scalaprops--------------: FAILED (RuntimeException: )
```

**Comment by xuwei-k** [comment]
> scalazlaws/src/main/scala/scalaprops/scalazlaws/bindRec.scala:13: missing parameter type

This error is expected to me because scalaz 7.3 is not source compatible with 7.2
https://github.com/scalaz/scalaz/commit/bc3d51fd70c2a57ea86f4854a9ef83d45c54650f

I don't think there is a need to move 7.3 at this time.

**Comment by SethTisue** [comment]
ok, thanks for looking at it. I'll close this but leave #515 open since we might come back to this later.

**Pull request closed without merging**
