### PR TITLE
(wip) sbt 1.3.0-M3

### PR DESCRIPTION
**Pull request by eed3si9n**

### CODE REVIEW

**Comment by dwijnand** [comment]
You can bring back play-ws with https://github.com/dwijnand/play-ws/tree/avoid-sbt-1.3-regression or when https://github.com/playframework/play-ws/pull/338 is merged.

**Comment by SethTisue** [comment]
is it too early to move the whole build to 1.3.0-RC1?

(if there are a handful of troublesome projects, we could override those to stick with 1.2.8 for now)

**Comment by eed3si9n** [comment]
We should certainly try moving to 1.3.0-RC1, and fork the breakers if we have to.

**Comment by SethTisue** [comment]
okay let's move to #909

**Pull request closed without merging**
