### PR TITLE
Simplify airframe community build

### PR DESCRIPTION
**Pull request by xerial**

### CODE REVIEW

**Comment by SethTisue** [comment]
looks good, but why is

```
"jsonBenchmark", "msgpackBenchmark"  // out of scope
```

still needed? can we delete the whole `extra.exclude` section?

**Comment by xerial** [comment]
We can delete them as well if this community build points to the latest head of airframe.

**Comment by SethTisue** [comment]
it does:

```
  airframe-uri:                 "https://github.com/wvlet/airframe.git"
```

which defaults to HEAD of `master`

**Comment by SethTisue** [comment]
final fixup in 6d6477c0db97294d77d7ad030f4262a7a6501106

thank you for this!

**Comment by xerial** [comment]
Sorry. The project name should be `communityBuild`, not `communityBuildProjects`

**Comment by xerial** [comment]
I'll create another PR for fixing this

**Pull request merged**
