### PR TITLE
sbt 1.1 -> 1.2

### PR DESCRIPTION
**Pull request by SethTisue**
fyi @eed3si9n @dwijnand

### CODE REVIEW

**Comment by SethTisue** [comment]
test run: https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/3137/ (404 for now)

**Comment by SethTisue** [comment]
looks like dbuild isn't compatible: https://github.com/lightbend/dbuild/issues/212

**Comment by SethTisue** [comment]
1.2.0-RC3 is out

**Comment by SethTisue** [comment]
note to self: when 1.2 comes out, I should also bump our tags for building sbt and its modules, and deal with https://github.com/sbt/sbt/issues/4186 at that time too

**Comment by eed3si9n** [comment]
Waiting on https://github.com/lightbend/dbuild/pull/213

**Comment by SethTisue** [comment]
happened in 2cd392196c313ae01cd7edd31f93f00336d52f8f (and c719c3858d8055cf6aa791df1c6b3ae001846694)

**Pull request closed without merging**
