### PR TITLE
add ScalaMeter + scala-ssh + jackson-module-scala

### PR DESCRIPTION
**Pull request by SethTisue**

### CODE REVIEW

**Comment by SethTisue** [comment]
test run: https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/806/consoleFull

**Comment by SethTisue** [comment]
fyi @axel22, but note that I disabled the test suite because of several failures; perhaps you will get the same failures if you run the tests with 2.12.0-RC2?

fyi @bphelan, and thank you @xuwei-k for the 2.12 compatibility work on scala-ssh

fyi @nbauernfeind

**Comment by axel22** [comment]
@SethTisue Weird, these should normally pass on 2.12.0-RC1 - https://travis-ci.org/scalameter/scalameter/jobs/167936382#L946

**Comment by SethTisue** [comment]
There are changes in RC2 potentially affecting serialization.

**Comment by axel22** [comment]
Interesting. I would not expect serialization changes to affect tests like `GZIPJSONSerializationPersistorTest` - this one, for example, uses custom JSON-based serialization.

I changed the version to 2.12.0-RC2, and ran:

```
> ++ 2.12.0-RC2 test
```

The `GZIPJSONSerializationPersistorTest`, for example, passes:

```
[info] GZIPJSONSerializationPersistorTest:
[info] - Should correctly serialize and deserialize history
[info] - Should produce data which occupies less than 4.0kB
```

and so do the other tests:

```
[info] Run completed in 2 minutes, 33 seconds.
[info] Total number of tests run: 41
[info] Suites: completed 28, aborted 0
[info] Tests: succeeded 41, failed 0, canceled 0, ignored 0, pending 2
[info] All tests passed.
```

Where could I see the build log, and what the failure was about?

**Comment by SethTisue** [comment]
> Where could I see the build log, and what the failure was about?

from https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/813/consoleFull:

```
[scalameter] [error] Failed tests:
[scalameter] [error]    org.scalameter.persistence.JSONSerializationPersistorTest
[scalameter] [error]    org.scalameter.persistence.SerializationPersistorTest
[scalameter] [error]    org.scalameter.persistence.GZIPJSONSerializationPersistorTest
```

**Comment by axel22** [comment]
Ok, I fixed those. When dependencies are on RC2, I can release it.

**Comment by SethTisue** [comment]
new test run with tests enabled: https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/822/consoleFull (404 til Jenkins catches up)

**Comment by SethTisue** [comment]
fixed in #359

**Pull request merged**
