### PR TITLE
Add running MiMa's functional tests

### PR DESCRIPTION
**Pull request by dwijnand**
Assuming this will be merged and be forward-merged or forward-ported to the 2.13.x (and eventually 2.14.x) branch, then this...
Resolves https://github.com/lightbend/mima/issues/193

### CODE REVIEW

**Comment by SethTisue** [comment]
I'm getting `[mima] [error] You asked dbuild to test using the task "test". The task key exists, but it is undefined in project "test-class-method-overload-with-default-parameters-nok".`

I don't think `extra.test-tasks` offer the flexibility needed here. Perhaps we will need to have two MiMa entries in the config file, one similar to the current entry and a second to run the integration tests. I think we could do this using spaces, or perhaps we could find some lighter weight trick.

**Comment by dwijnand** [comment]
I can fix that by changing MiMa's build, no problem.

**Comment by dwijnand** [comment]
With https://github.com/lightbend/mima/pull/320 that error should no longer happen.

**Comment by SethTisue** [comment]
optimistically merging, then!

**Comment by SethTisue** [comment]
oops

**Comment by SethTisue** [comment]
5816cdbb04d3a09b62475c38cb9a39c78faf6437

**Comment by dwijnand** [comment]
What happened?

**Comment by SethTisue** [comment]
in a local test, after the change, `Project mima------------------------: SUCCESS (project rebuilt ok)`. but I suggest that you check the log on Jenkins, or in a local run, and make sure the tests are actually running. it isn't obvious to me from this if they are:

```
[mima] Processing subproject: test-object-becomes-class-nok
[mima] All Dependencies for subproject test-object-becomes-class-nok:
[mima]    org.scala-lang:scala-compiler:2.12.9-bin-c35194d:scala-tool->default,optional(default)
[mima]    org.scala-lang:scala-library:2.12.9-bin-c35194d:scala-tool->default,optional(default)
[mima]    com.lightbend:cloc-plugin:0.0.1-dbuildx6075428377c9af8cdd3f0942c53d654132439a7d:plugin->default(compile)
[mima]    org.scala-lang:scala-library:2.12.9-bin-c35194d
[mima] Running build: test-object-becomes-class-nok
[mima] [info] Wrote /Users/tisue/community.212/target-0.9.16/project-builds/mima-6fee06503f1f253e267d999b3697a0e76b53272e/functional-tests/src/test/object-becomes-class-nok/target/scala-2.12/test-object-becomes-class-nok-0.3.0-dbuildx6fee06503f1f253e267d999b3697a0e76b53272e.pom
[mima] Running "test" in: test-object-becomes-class-nok
[mima] Publishing: test-object-becomes-class-nok
[mima] [info] Wrote /Users/tisue/community.212/target-0.9.16/project-builds/mima-6fee06503f1f253e267d999b3697a0e76b53272e/functional-tests/src/test/object-becomes-class-nok/target/scala-2.12/test-object-becomes-class-nok-0.3.0-dbuildx6fee06503f1f253e267d999b3697a0e76b53272e.pom
[mima] [info] 	published test-object-becomes-class-nok to /Users/tisue/community.212/target-0.9.16/project-builds/mima-6fee06503f1f253e267d999b3697a0e76b53272e/.dbuild/local-publish-repo/com/typesafe/test-object-becomes-class-nok/0.3.0-dbuildx6fee06503f1f253e267d999b3697a0e76b53272e/test-object-becomes-class-nok-0.3.0-dbuildx6fee06503f1f253e267d999b3697a0e76b53272e.pom
[mima] [info] 	published test-object-becomes-class-nok to /Users/tisue/community.212/target-0.9.16/project-builds/mima-6fee06503f1f253e267d999b3697a0e76b53272e/.dbuild/local-publish-repo/com/typesafe/test-object-becomes-class-nok/0.3.0-dbuildx6fee06503f1f253e267d999b3697a0e76b53272e/test-object-becomes-class-nok-0.3.0-dbuildx6fee06503f1f253e267d999b3697a0e76b53272e.jar
[mima] [info] 	published test-object-becomes-class-nok to /Users/tisue/community.212/target-0.9.16/project-builds/mima-6fee06503f1f253e267d999b3697a0e76b53272e/.dbuild/local-publish-repo/com/typesafe/test-object-becomes-class-nok/0.3.0-dbuildx6fee06503f1f253e267d999b3697a0e76b53272e/test-object-becomes-class-nok-0.3.0-dbuildx6fee06503f1f253e267d999b3697a0e76b53272e-sources.jar
[mima] [info] 	published test-object-becomes-class-nok to /Users/tisue/community.212/target-0.9.16/project-builds/mima-6fee06503f1f253e267d999b3697a0e76b53272e/.dbuild/local-publish-repo/com/typesafe/test-object-becomes-class-nok/0.3.0-dbuildx6fee06503f1f253e267d999b3697a0e76b53272e/test-object-becomes-class-nok-0.3.0-dbuildx6fee06503f1f253e267d999b3697a0e76b53272e-javadoc.jar
```

**Pull request merged**
