### PR TITLE
allow passing ant options when building scala/scala

### PR DESCRIPTION
**Pull request by lrytz**

### CODE REVIEW

**Comment by lrytz** [comment]
companion of https://github.com/scala/scala-jenkins-infra/pull/147, build running here: https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/269/parameters/. the Scala build picked up the option.

**Comment by lrytz** [comment]
I just realize I'd also need an option to do a full bootstrap (disalbe `locker.skip` in https://github.com/scala/community-builds/blob/2.11.x/community.dbuild#L35)

**Comment by SethTisue** [comment]
nbd, but may I suggest calling it `scala-build-opts` instead of `scala-ant-opts`, in anticipation of the ant->sbt switchover?

**Comment by lrytz** [comment]
sure, that's fine with me. dbuild will require some other adjustments when we do the switch, and the option introduced here will not continue to work in the same way.

**Comment by lrytz** [comment]
@SethTisue PTAL, I didn't find a better way than the current form.

**Pull request merged**
