### PR TITLE
advance akka / akka-persistence-cassandra / lagom

### PR DESCRIPTION
**Pull request by SethTisue**
references akka/akka-persistence-cassandra#772, cc @chbatey

~~https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/1369/~~
~~https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/1374/~~
~~https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/1381/~~
https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/1382/

### CODE REVIEW

**Comment by SethTisue** [comment]
```
[akka-persistence-cassandra] Processing subproject: core
[akka-persistence-cassandra] [error] **** Missing dependency: the library com.lightbend.akka#akka-stream-alpakka-cassandra is not provided (in space "default") by any project in this configuration file.
[akka-persistence-cassandra] [error] In order to control which version is used, please add the corresponding project to the build file
[akka-persistence-cassandra] [error] (or use "check-missing:false" to ignore (not recommended)).
[akka-persistence-cassandra] [error] java.lang.RuntimeException: Required dependency not found
```

ok, I will try to add that

**Comment by SethTisue** [comment]
hey @ennru, the alpakka repo has its foot in the door here, now

**Comment by ennru** [comment]
Oh, great. I'll get the herd running than...

**Comment by SethTisue** [comment]
so far so good, everything is green but Lagom. but then:

```
[lagom] [error] /home/jenkins/workspace/scala-2.13.x-jdk11-integrate-community-build/target-0.9.16/project-builds/lagom-0d0b251fdfa059f1916c43e69c16a2318930c62e/persistence-cassandra/core/src/main/scala/com/lightbend/lagom/internal/persistence/cassandra/CassandraOffsetStore.scala:9:35: object session is not a member of package akka.persistence.cassandra
[lagom] [error] import akka.persistence.cassandra.session.scaladsl.CassandraSession
[lagom] [error]                                   ^
```

it appears that CassandraSession has moved to `akka.stream.alpakka.cassandra.scaladsl.CassandraSession` and Lagom hasn't adjusted to the change yet (I checked master as well as 1.6.x)

@renatocaval is this on your radar?

there's no particular rush. from my perspective it would be okay to just put this PR on ice for a while until Lagom is ready

**Comment by ennru** [comment]
Lagom is not updated to Akka Persistence Cassandra 1.0 (which is in RC phase), yet. It still depends on the 0.x version.

**Comment by SethTisue** [comment]
closing for now, but let's return to this later

in lagom repo, `git grep AkkaPersistenceCassandra` to check the version

**Comment by SethTisue** [comment]
my occasional checks on this could also include checking on akka-persistence-jdbc; they recently did a 4.0 release. `git grep AkkaPersistenceJdbc`

**Comment by ennru** [comment]
Yes, that is the first release within the Akka organisation. Same here, Lagom won't use it before going 1.7.

**Pull request closed without merging**
