### PR TITLE
unfork sttp, add monix-nio, add finagle-htttp

### PR DESCRIPTION
**Pull request by SethTisue**
fyi @adamw @alexandru @mosesn

~~https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/1749/~~
~~https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/1765/~~
~~https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/1766/~~
https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/1767/

### CODE REVIEW

**Comment by SethTisue** [comment]
this is now green (https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/1765/) if we only compile the tets, but running them fails (https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/1766/) 

the problem seems to be with `testServerJVM2_13`, which starts a test HTTP server which must stay running in order for the other tests to pass

**Comment by SethTisue** [comment]
oh, I think I know the problem, we need a trick that `akka-http.conf` also uses

**Comment by adamw** [comment]
👍 thank you!

**Comment by alexandru** [comment]
cc @Avasil

**Comment by mosesn** [comment]
great, thanks @SethTisue!

**Pull request merged**
