### PR TITLE
add scala-json-ast

### PR DESCRIPTION
**Pull request by SethTisue**
fyi @mdedetrich

### CODE REVIEW

**Comment by SethTisue** [comment]
test run: https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/792/consoleFull (404 til Jenkins catches up)

**Comment by SethTisue** [comment]
well, this (from an attempted local run) puzzles me:

```
[scala-json-ast] Processing subproject: scalaJsonASTJVM
[scala-json-ast] [error] **** Missing dependency: the library com.geirsson#scalafmt-cli is not provided (in space "default") by any project in this configuration file.
[scala-json-ast] [error] In order to control which version is used, please add the corresponding project to the build file
[scala-json-ast] [error] (or use "check-missing:false" to ignore (not recommended)).
[scala-json-ast] java.lang.RuntimeException: Required dependency not found
```

note also:

```
[info] scalaJsonASTJVM/*:libraryDependencies
[info]  List(org.scala-lang:scala-library:2.11.8, org.scala-lang:scala-library:2.11.8:scalafmt, com.geirsson:scalafmt-cli_2.11:0.4.5:scalafmt, com.storm-enroute:scalameter:0.7:test, org.specs2:specs2-core:3.7.2:test, org.specs2:specs2-scalacheck:3.7.2:test, org.scalacheck:scalacheck:1.13.0:test)
```

why is the scalafmt plugin altering `libraryDependencies`? shouldn't scalafmt only be a dependency of the build definition itself?

**Comment by SethTisue** [comment]
about running the tests, we can try:

```
    // run only correctness tests, not performance tests
    extra.test-tasks: ["testOnly specs.*"]
```

but I'm not sure if dbuild will accept an arbitrary command like that, as opposed to a bare task name

**Comment by mdedetrich** [comment]
> why is the scalafmt plugin altering libraryDependencies? shouldn't scalafmt only be a dependency of the build definition itself?

I assume so, I am not getting this problem locally. Then again I am not sure what magic dbuild/scalafmt is doing here.

As a last resort, I can remove scalafmt from plugins.sbt and instead use the intellij plugin to format the code. Bit hacky but it would work

> about running the tests, we can try:

How about test-tasks from http://typesafehub.github.io/dbuild/0.9.6/dbuild.html#sbt-specific-options

**Comment by SethTisue** [comment]
> why is the scalafmt plugin altering libraryDependencies

relevant: https://github.com/olafurpg/scalafmt/issues/485

**Comment by SethTisue** [comment]
new test run: https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/800/consoleFull

**Comment by SethTisue** [comment]
hmm, so this is currently blocked because ScalaMeter doesn't have 2.12 support yet; I opened a ticket on it at https://github.com/scalameter/scalameter/issues/169

@mdedetrich may I suggest that you put the correctness tests and the performance tests in separate subprojects, with only the performance test subproject having the ScalaMeter dependency? then I can exclude that subproject in the community build, and that will kill two birds with one stone. and it's actually good practice anyway, I think.

(I'm hoping the latest changes I pushed will allow us to work around the scalafmt thing, but we can't test it until the ScalaMeter thing is resolved.)

**Comment by mdedetrich** [comment]
@SethTisue Sure thing, will try to get this to tomorrow/Monday

**Comment by mdedetrich** [comment]
@SethTisue ScalaMeter was placed into its own subproject (which also means you don't need a custom command for testing with SBT). Do you also need the correctness tests to be put into their own subproject?

**Comment by SethTisue** [comment]
> Do you also need the correctness tests to be put into their own subproject

nope, should be fine. new test run: https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/811/consoleFull

**Comment by SethTisue** [comment]
yay, green! but, one more test run on the final, ready-to-merge version: https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/812/consoleFull

**Comment by SethTisue** [comment]
thx @mdedetrich for your help

**Comment by mdedetrich** [comment]
@SethTisue No worries, glad its working!

**Pull request merged**
