### PR TITLE
2.13: fork minitest

### PR DESCRIPTION
**Pull request by SethTisue**
previously: https://github.com/monix/minitest/issues/23

### CODE REVIEW

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/1347/ (404 for now)

**Comment by SethTisue** [comment]
at the moment this doesn't result in any additional green projects downstream, but that's probably because scala-xml and shapeless are red at the moment

**Comment by SethTisue** [comment]
thank you @xuwei-k!

**Comment by xuwei-k** [comment]
https://github.com/monix/minitest/pull/24 merged

**Comment by SethTisue** [comment]
@xuwei-k thanks for the heads up. I'll look at this after I fix some more urgent new failures

**Comment by SethTisue** [comment]
#794

**Pull request merged**
