### PR TITLE
add scalafmt

### PR DESCRIPTION
**Pull request by SethTisue**
successor to the ill-fated #578 

fyi @olafurpg

### CODE REVIEW

**Comment by SethTisue** [comment]
test run: https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/2249/consoleFull

**Comment by olafurpg** [comment]
Cool! Thanks for getting this working @SethTisue 

My plan is to make scalafmt v2 be a proper tree printer using scalameta v2, my WIP is here https://github.com/olafurpg/scala-syntax Early results look promising (5x speedup and prettier output!) but still need more time to handle comments before merging it into scalafmt repo.

**Comment by SethTisue** [comment]
sounds good — although I did manage to get this working (perhaps more as a testament to my own cussedness than any kind of sensible cost/benefit analysis...) it would be nice to drop the Scalameta 1 stuff again before toooo much longer

**Comment by olafurpg** [comment]
The situation is quite bad since scalafmt currently hasn't benefited from scalameta parser improvements since april this year. I made a mistake to LGTM too big breaking changes in scalameta v2. Having a proper tree printer will not only enable scalafmt to upgrade the scalameta dep but also enable syntax preserving tree transforms in scalafix, which is very exciting. I'll keep you posted on progress.

**Comment by olafurpg** [comment]
Good news, scalafmt is now on the latest scalameta version 🎉 Additionally, scalafmt no longer depends on the scalameta/paradise compiler plugin.

The upgrade from v1.8 to v2.0 only took ~1hr to finish https://github.com/scalameta/scalafmt/pull/1170, but the removal of scalameta/paradise was harder https://github.com/scalameta/scalafmt/pull/1145

**Comment by SethTisue** [comment]
> Good news, scalafmt is now on the latest scalameta version 🎉 Additionally, scalafmt no longer depends on the scalameta/paradise compiler plugin.

@olafurpg thanks, this resulted in a nice community build simplification: 9e7cb40a9b84445b547af5a7ca6c20281c380817

**Pull request merged**
