### PR TITLE
2.13: new Scala SHA

### PR DESCRIPTION
**Pull request by SethTisue**
~https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/5207/~

### CODE REVIEW

**Comment by SethTisue** [comment]
in local run, `FAILURES (UNEXPECTED): specs2,scala-supertagged,refined,doobie,coulomb`, and I don't think any of them are using `-Xsource:3`? I'm investigating

**Comment by SethTisue** [comment]
I've put some details on the culprit PR which is https://github.com/scala/scala/pull/10621

**Comment by SethTisue** [comment]
The culprit PR is https://github.com/scala/scala/pull/10621

It's difficult to discern what the five failures have in common.

All five are in test code, but that's probably a red herring — the five projects use four different test frameworks.

The error message is different in all five projects.

In all five cases, the problem is reproducible outside dbuild. (Locally publishing kind-projector, or changing the dependency to use the 2.13.12 version, is required for two of them.)

@lrytz Do you have any theories as to what might be going on here? I eyeballed 10621 but I don't see any obvious leads. I could go digging, but I think the most efficient next step would be for you to have a look and hopefully have a flash of insight.

fyi @som-snytt 

### specs2

https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/5207/artifact/logs/specs2-build.log

```
[specs2] [error] /home/jenkins/workspace/scala-2.13.x-jdk11-integrate-community-build/target-0.9.20/project-builds/specs2-c947771b26baf83077f82d611a9a67182d217be1/shapeless/src/test/scala/org/specs2/shapeless/ProjectionSpec.scala:25:40: could not find implicit value for parameter projection: org.specs2.shapeless.ProjectsOn[ProjectionSpec.this.A,ProjectionSpec.this.Empty]
[specs2] [error]     A(1, 2.0, 'c', B(1, 'c')).projectOn[Empty] must be equalTo Empty()
[specs2] [error]                                        ^
```

### scala-supertagged

https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/5207/artifact/logs/scala-supertagged-build.log

```
[scala-supertagged] [error] /home/jenkins/workspace/scala-2.13.x-jdk11-integrate-community-build/target-0.9.20/project-builds/scala-supertagged-03b41e9e8a820a493914e582ffea570b6000a0df/tests/src/test/scala/supertaggedtests/misc/PluanceNuanceShadowing.scala:20:20: type mismatch;
[scala-supertagged] [error]  found   : Object{type Raw = Int; type T = supertagged.Tag[Int,supertaggedtests.newtypes.Step1.Ops]} with supertagged.ImplicitScope[Int,supertaggedtests.newtypes.Step1.type]
[scala-supertagged] [error]  required: ?{def +(x$1: ? >: Object{type Raw = Int; type T = supertagged.Tag[Int,supertaggedtests.newtypes.Step1.Ops]} with supertagged.ImplicitScope[Int,supertaggedtests.newtypes.Step1.type]): ?}
[scala-supertagged] [error] Note that implicit conversions are not applicable because they are ambiguous:
[scala-supertagged] [error]  both method newtypeOps in package supertagged of type [Repr, Ops](t: supertagged.package.Newtype[Repr,Ops])(implicit mkOps: Repr => Ops): Ops
[scala-supertagged] [error]  and method newtypeOps in package supertagged of type [Repr, Ops](t: supertagged.Newtype[Repr,Ops])(implicit mkOps: Repr => Ops): Ops
[scala-supertagged] [error]  are possible conversion functions from step1.type to ?{def +(x$1: ? >: Object{type Raw = Int; type T = supertagged.Tag[Int,supertaggedtests.newtypes.Step1.Ops]} with supertagged.ImplicitScope[Int,supertaggedtests.newtypes.Step1.type]): ?}
[scala-supertagged] [error]     val stepPlus = step1 + step1
[scala-supertagged] [error]                    ^
```

### refined

https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/5207/artifact/logs/refined-build.log

```
[refined] [error] /home/jenkins/workspace/scala-2.13.x-jdk11-integrate-community-build/target-0.9.20/project-builds/refined-b20db0306c88b2166e8da19b88f43b411201fc40/modules/core/shared/src/test/scala-3.0-/eu/timepit/refined/api/RefTypeSpec.scala:116:23: ambiguous implicit values:
[refined] [error]  both method nsub in package shapeless of type [A, B]A <:!< B
[refined] [error]  and method nsub in package shapeless of type [A, B]A <:!< B
[refined] [error]  match expected type eu.timepit.refined.api.Refined[Int,eu.timepit.refined.numeric.Positive] <:!< Int
[refined] [error]     val x = implicitly[(Int Refined Positive) <:!< Int]
[refined] [error]                       ^
```

### doobie

https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/5207/artifact/logs/doobie-build.log

```
[doobie] [error] /home/jenkins/workspace/scala-2.13.x-jdk11-integrate-community-build/target-0.9.20/project-builds/doobie-d4f428840c2a94d91ffcba33e7a1406ddfe75940/modules/core/src/test/scala/doobie/util/ReadSuite.scala:63:9: 
[doobie] [error] Cannot find or construct a Read instance for type:
[doobie] [error] 
[doobie] [error]   Option[(Int, Int)]
[doobie] [error] 
[doobie] [error] This can happen for a few reasons, [...]
```

### coulomb

https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/5207/artifact/logs/coulomb-build.log

```
[coulomb] [error] /home/jenkins/workspace/scala-2.13.x-jdk11-integrate-community-build/target-0.9.20/project-builds/coulomb-b25383cf3f4fa699f0ccdde2abe43eb4d05dbd55/coulomb-tests/jvm/src/test/scala/coulomb/PhyisicalConstantsShowSuite.scala:10:38: could not find implicit value for parameter ustr: coulomb.unitops.UnitString[coulomb.si.Meter %/ coulomb.si.Second]
[coulomb] [error]     assert(speedOfLightInVacuum[Int].show == "299792458 m/s")
[coulomb] [error]                                      ^
```

**Comment by som-snytt** [comment]
Obviously, they're doing something wrong...

Maybe "implicits found in package prefix" includes "packages with the word prefix in them":

`src/main/scala/coulomb/siprefix/package.scala`

I can't tell casually what it is testing. I realize you're the only one who knows how dbuild works. Did I try it once? I wouldn't mind publishing a few dependencies locally to try out e.g. coulomb because "it's, um, cool!" Otherwise I will just try something and it will probably just work because it's not testing the thing.

@SethTisue forgot to summon[Seth]

**Comment by SethTisue** [comment]
in local testing, 10685 fixed all 5 projects (and is now merged)

https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/5213/ queued

**Pull request merged**
