### PR TITLE
add squants

### PR DESCRIPTION
**Pull request by SethTisue**
keeping up with the Dotty community build Joneses

### CODE REVIEW

**Comment by SethTisue** [comment]
test run queued: https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/1798/consoleFull (404 while Jenkins silently steals up through a panel in the drop ceiling and takes up residence there, descending only by night to subsist on free office snacks)

**Comment by SethTisue** [comment]
@cunei I'll need your help here, I think. dbuild seems to be behaving strangely here. there seems to be some crosstalk between a project's dependencies, and the dependencies of its build definition, or something like that.

I'm seeing multiple anomalies in this build log:

## anomaly 1

the list of dependencies dbuild finds for squants is much too long:

`Project squants depends on: acyclic, akka, akka-http, akka-more, fastparse, genjavadoc, gigahorse, jawn, json4s, kind-projector, macro-compat, macro-paradise, pcplod, sbinary, sbt, sbt-io, sbt-librarymanagement, sbt-util, scala, scala-java8-compat, scala-js, scala-parser-combinators, scalacheck, scalapb, scalapb-lenses, scalatest, scalaz, shaded-scalajson, shapeless, sjson-new, sourcecode, specs2, spray-json, ssl-config, tut, unfiltered, utest, zinc`

in particular, we should not be seeing `tut` here, as squants uses the tut sbt plugin, but tut is not a dependency of actual project code

## anomaly 2

in what seems to be another instance of the same problem, in `tut`'s own entry we see:

`Project tut depends on: acyclic, akka, akka-http, akka-more, fastparse, genjavadoc, gigahorse, jawn, json4s, kind-projector, macro-compat, macro-paradise, pcplod, sbinary, sbt, sbt-io, sbt-librarymanagement, sbt-util, scala, scala-java8-compat, scala-js, scala-parser-combinators, scalacheck, scalapb, scalapb-lenses, scalatest, scalaz, shaded-scalajson, shapeless, sjson-new, sourcecode, specs2, spray-json, ssl-config, unfiltered, utest, zinc`

this is also way too long and in particular, should not include `sbt`. we are not building tut's sbt plugin (`extra.exclude: ["plugin"]`).

## anomaly 3 

dbuild seems be getting confused between sbt 0.13 and sbt 1.0. squants is an sbt 0.13 project, but despite that, we get:

```
[squants] [info] Set current project to squants (in build file:/home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.9/project-builds/squants-897a4e31c83e9e8fee5c1653bbca4872b6aabdab/)
[squants:error] <set>:3: error: value extract is not a member of object Project
[squants:error]     val extracted = Project extract s
[squants:error]                             ^
[squants:error] <set>:5: error: value relation is not a member of object Project
[squants:error]     val r = Project.relation(extracted.structure, true)
[squants:error]                     ^
[squants:error] <set>:7: error: not found: value currentRef
[squants:error]     val projectScope = Load.projectScope(currentRef)
[squants:error]                                          ^
[squants:error] <set>:11: error: not found: value structure
[squants:error]     BuiltinCommands.reapply(session, structure, s)
[squants:error]                                      ^
[squants] [error] Type error in expression
```

which indicates that somehow sbt 1.0 is on the classpath, since this code (which comes from `extra.commands` ) compiles fine against sbt 0.13.

**Comment by SethTisue** [comment]
rebasing didn't help

**Comment by SethTisue** [comment]
@cunei any clue what's going on here...? I'm mystified

**Comment by cunei** [comment]
Maybe a run with the debugging information switched on ("-d") may shed some light?

**Comment by SethTisue** [comment]
I do want to investigate and finish this up, but there's just too much on my plate right now. I'm going to close this for now. I threw it on the list over at #161, with a link to this PR in case I (or somebody) takes it back up

**Comment by SethTisue** [comment]
sequel: #974

**Pull request closed without merging**
