### PR TITLE
move sbt tags from 1.0.4 -> 1.1.0

### LINKED ISSUE #650: move sbt tags from 1.0.4 -> 1.1.0
sequel to #642, sister to #645 

it can wait until 1.1.0 is finalized, I think.

### PR DESCRIPTION
**Pull request by dwijnand**
Fixes #650

### CODE REVIEW

**Comment by dwijnand** [comment]
I had a look at the various workarounds as well as the single failing unit test in sbt/lm and I don't think any of that can be remove or re-enabled, so I didn't risk it.

Please let me know how I can help get this to completion, I'm still a dbuild/community-build noob.

**Comment by SethTisue** [comment]
test run queued: https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/2536/consoleFull (404 for now, Jenkins is busy)

**Comment by SethTisue** [comment]
~~blocked by https://github.com/scala/community-builds/issues/666~~ fixed

**Comment by SethTisue** [comment]
new test run: https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/2540/consoleFull (404 for now)

**Comment by dwijnand** [comment]
Failed due to an unfiltered test error:

```
[unfiltered] [info] SslServerSpec
[unfiltered] [info] 
[unfiltered] [info] A Secure Server should
[unfiltered] [info]   + respond to secure requests
[unfiltered] [error]   x refuse connection to unsecure requests
[unfiltered] [error]    Expected: java.net.ConnectException. Got: java.io.IOException: unexpected end of stream on okhttp3.Address@63670263 instead 
[unfiltered] [error]    
[unfiltered] [error]     The  IOException stacktrace is
[unfiltered] [error]    
[unfiltered] [error]    okhttp3.internal.http1.Http1Codec.readResponse(Http1Codec.java:206)
[unfiltered] [error]    okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:132)
[unfiltered] [error]    okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:54)
[unfiltered] [error]    okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
[unfiltered] [error]    okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
[unfiltered] [error]    okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
[unfiltered] [error]    okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
[unfiltered] [error]    okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
[unfiltered] [error]    okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
[unfiltered] [error]    okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
[unfiltered] [error]    okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
[unfiltered] [error]    okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
[unfiltered] [error]    okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
[unfiltered] [error]    okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
[unfiltered] [error]    okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
[unfiltered] [error]    okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:179)
[unfiltered] [error]    okhttp3.RealCall.execute(RealCall.java:63)
[unfiltered] [error]    unfiltered.specs2.Hosted.requestWithNewClient(Hosted.scala:55)
[unfiltered] [error]    unfiltered.specs2.Hosted.requestWithNewClient$(Hosted.scala:51)
[unfiltered] [error]    unfiltered.netty.SslServerSpec$.requestWithNewClient(SslServerSpec.scala:16)
[unfiltered] [error]    unfiltered.specs2.SecureClient.httpsx(SecureClient.scala:42)
[unfiltered] [error]    unfiltered.specs2.SecureClient.httpsx$(SecureClient.scala:41)
[unfiltered] [error]    unfiltered.netty.SslServerSpec$.httpsx(SslServerSpec.scala:16)
[unfiltered] [error]    unfiltered.specs2.SecureClient.https(SecureClient.scala:33)
[unfiltered] [error]    unfiltered.specs2.SecureClient.https$(SecureClient.scala:32)
[unfiltered] [error]    unfiltered.netty.SslServerSpec$.https(SslServerSpec.scala:16)
[unfiltered] [error]    unfiltered.netty.SslServerSpec$.$anonfun$new$6(SslServerSpec.scala:69)
```

**Comment by SethTisue** [comment]
blocked by #668

**Comment by SethTisue** [comment]
new test run: https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/2547/consoleFull

**Comment by SethTisue** [comment]
sigh, a different unfiltered test failed. disabled that test suite. new run: https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/2548/consoleFull

**Comment by SethTisue** [comment]
I'll have to disable the sbt-io tests until something is done about this: https://github.com/sbt/io/issues/122

**Comment by SethTisue** [comment]
new run: https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/2548/consoleFull

**Comment by SethTisue** [comment]
https://github.com/sbt/zinc/issues/485 means I have to disable zincIvyIntegration tests

**Comment by SethTisue** [comment]
next try: https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/2549/consoleFull

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/2550/consoleFull

**Comment by SethTisue** [comment]
```
[info] Project sbt---------------------: SUCCESS (project rebuilt ok)
```

🍾

**Pull request merged**
