### PR TITLE
add Machinist, newer Spire, re-add Breeze, run Scalikejdbc tests

### PR DESCRIPTION
**Pull request by SethTisue**
breeze depends on spire, spire depends on machinist, so I did the three
together

the scalikejdbc thing is an unrelated bonus.

### CODE REVIEW

**Comment by SethTisue** [comment]
green run at https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/647/console

fyi @dlwh

**Comment by SethTisue** [comment]
fyi @non

**Comment by SethTisue** [comment]
fyi @non

**Comment by SethTisue** [comment]
Spire tests remain disabled. reported upstream at https://github.com/non/spire/issues/580

**Comment by seratch** [comment]
scalikejdbc's issue must be fixed by https://github.com/scalikejdbc/scalikejdbc/pull/566
pls check the latest revision.

**Pull request merged**
