### PR TITLE
unfork scala-ssh

### PR DESCRIPTION
**Pull request by SethTisue**
@sirthias has revived the original repo

/cc @veact @xuwei-k

### CODE REVIEW

**Comment by SethTisue** [comment]
oh great and mighty Jenkins, tell us if this humble offering pleases you https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/2677/consoleFull

**Comment by SethTisue** [comment]
again, with scalafmt disabled, if it so pleases your all-powerful exaltedness https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/2679/consoleFull

**Comment by SethTisue** [comment]
the same tests still fail (@sirthias, is it of interest?), so we'll continue to disable running the test suite.

**Comment by sirthias** [comment]
Yes, Seth, unfortunately the tests are expected to currently fail in a plain environment since they aren't fully self-contained. I should probably somehow tag the "special" tests that try logging into some external server, so the regular `test` command doesn't try to run them and things appear green.

Just created https://github.com/sirthias/scala-ssh/issues/38 to track this...

Thank you!

**Comment by SethTisue** [comment]
👍  68722ab325a66b109e7a52c0f39106629bb8736a

**Pull request merged**
