### PR TITLE
add advxml

### PR DESCRIPTION
**Pull request by SethTisue**
fyi @geirolz

### CODE REVIEW

**Comment by SethTisue** [comment]
queued: https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/5348/

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/5348/artifact/logs/advxml-build.log

`depends on: catalysts, cats, cloc-plugin, discipline, export-hook, kind-projector, machinist, macro-compat, macro-paradise, scala, scala-js-stubs, scala-parser-combinators, scalacheck, scalatest, shapeless, simulacrum, specs2`


```
[advxml] [error] /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.16/project-builds/advxml-3a9bf016a500ec0c257a2f82fe45bedf4d2ae4e8/src/main/scala/advxml/core/convert/package.scala:20:8: contravariant type A occurs in invariant position in type [F[_], -A, B]cats.data.Kleisli[F,A,B] of type Converter
[advxml] [error]   type Converter[F[_], -A, B] = Kleisli[F, A, B]
[advxml] [error]        ^
```

not sure if cats version mismatch, change in Scala, or what. advxml's cats dependency is `"org.typelevel" %% "cats-core" % "2.1.0"`, we're behind that here, but we could/should move to 2.1 once we have ScalaTest 3.1 (which is #1020)

**Comment by SethTisue** [comment]
#1040 has landed, so this is now eligible to progress again (but retargeted for 2.13.x only)

**Comment by SethTisue** [comment]
@geirolz thanks for merging your own ScalaTest 3.1 upgrade, that makes this easier.

**Comment by geirolz** [comment]
Thanks @SethTisue for your time

**Pull request merged**
