### PR TITLE
2.12: new Scala SHA

### PR DESCRIPTION
**Pull request by SethTisue**
~~https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/5687/~~
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/5690/
~~https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/5691/~~
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/5696/
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/5697/

### CODE REVIEW

**Comment by SethTisue** [comment]
community build regression-catching powers, activate!

@lrytz @retronym @mkeskells @hrhino 

* scalameta is failing: `not found: value treeTpe`
  * https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/5690/artifact/logs/scalameta-build.log
  * looks to be caused by Harrison's https://github.com/scala/scala/pull/8771
  * for us to do something that then requires changes in scalameta certainly isn't out of the question, but if we can easily provide a deprecated forwarder or something, that might be nice. not sure whether other people might be using the removed method(s). wd y'all think? should I just PR an appropriate adjustment to the scalameta repo and call it a day?

* there are failing tests (not intermittent, I don't think) in Akka and ScalaTest that both look RedBlackTree related to me, so probably Mike's recent PRs in that area
  * who wants to dig into this? (I could do it, if assigned to)
  * https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/5690/artifact/logs/scalatest-tests-build.log
  * https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/5690/artifact/logs/akka-more-build.log

**Comment by retronym** [comment]
We should re-run with https://github.com/scala/scala/pull/8898 merged.

**Comment by retronym** [comment]
... and https://github.com/scala/scala/pull/8901 for the `SortedSet` bug,

**Comment by hrhino** [comment]
ah, scalameta is in the `scala` package...

**Pull request merged**
