### PR TITLE
[dont merge] Upgrade to sbt 0.13.13-RC3

### LINKED ISSUE #352: upgrade to sbt 0.13.13
@dwijnand @eed3si9n before 0.13.13 final is released, should we a run a community build using 0.13.13-RC3, to help ensure that the new version isn't breaking people's builds?

### PR DESCRIPTION
**Pull request by dwijnand**
Fixes #352

### CODE REVIEW

**Comment by dwijnand** [comment]
Huh, should I be testing this in the 2.11.x branch like #290?

**Comment by dwijnand** [comment]
https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/821/ (if I did things right)

**Comment by SethTisue** [comment]
> should I be testing this in the 2.11.x branch

up to you I guess whether to do one or both, and which one. (it doesn't seem _impossible_ that some Scala-version-specific issue could crop up in one or not the other... perhaps not likely...)

**Comment by SethTisue** [comment]
not sure what to make of the akka-more failure

**Comment by dwijnand** [comment]
```
[akka-more] [info] Defining akka/*:commands
[akka-more] [info] The new value will be used by no settings or tasks.
[akka-more] [info] Reapplying settings...
[akka-more] [info] Set current project to akka (in build file:/home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.5/project-builds/akka-more-fbb572189d78874fd6a1dd4ee26a775267a6006f/)
[akka-more] [info] Reapplying settings...
[akka-more] [info] Set current project to akka (in build file:/home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.5/project-builds/akka-more-fbb572189d78874fd6a1dd4ee26a775267a6006f/)
[akka-more:error] <set>:1: error: not found: value httpCore
[akka-more:error] sources in doc in Compile in httpCore := List()
[akka-more:error]                              ^
[akka-more] [error] Type error in expression
[akka-more:error] java.lang.RuntimeException: 
[akka-more:error]   at scala.sys.package$.error(package.scala:27)
[akka-more:error]   at com.typesafe.dbuild.support.sbt.SbtRunner.com$typesafe$dbuild$support$sbt$SbtRunner$$processCommand(SbtRunner.scala:91)
[akka-more:error]   at com.typesafe.dbuild.support.sbt.SbtRunner$$anonfun$run$1$$anonfun$apply$2$$anonfun$apply$3.apply(SbtRunner.scala:72)
[akka-more:error]   at com.typesafe.dbuild.support.sbt.SbtRunner$$anonfun$run$1$$anonfun$apply$2$$anonfun$apply$3.apply(SbtRunner.scala:72)
[akka-more:error]   at com.typesafe.dbuild.support.sbt.SbtRunner$$anonfun$run$1.apply(SbtRunner.scala:72)
[akka-more:error]   at com.typesafe.dbuild.support.sbt.SbtRunner$$anonfun$run$1.apply(SbtRunner.scala:63)
[akka-more:error]   at sbt.IO$.withTemporaryFile(IO.scala:311)
[akka-more:error]   at com.typesafe.dbuild.support.sbt.SbtRunner.run(SbtRunner.scala:63)
[akka-more:error]   at com.typesafe.dbuild.support.sbt.SbtBuilder$.buildSbtProject(SbtBuildRunner.scala:84)
[akka-more:error]   at com.typesafe.dbuild.support.sbt.SbtBuildSystem.runBuild(SbtBuildSystem.scala:89)
[akka-more:error]   at com.typesafe.dbuild.support.sbt.SbtBuildSystem.runBuild(SbtBuildSystem.scala:17)
[akka-more] --== End Building akka-more ==--
```

**Comment by dwijnand** [comment]
Thanks Seth, I'll dig into it tomorrow.

**Comment by SethTisue** [comment]
maybe it's just akka/akka@a6a5556a8f972172482e50f9e6b4fdb2bb29f221

**Comment by SethTisue** [comment]
yeah. I'll make a separate ticket on it

**Comment by dwijnand** [comment]
Great find!

Ok, so you need to solve [this](https://github.com/scala/community-builds/blob/02a6addbe01c2d8037c202c89cf27cabcf147719/community.dbuild#L551) in main-line 2.12.x community build, this isn't an sbt 0.13.13 issue (a wise man once spoke about pinning versions..)

**Pull request closed without merging**
