### PR TITLE
Remove publish from droste.conf excludes

### PR DESCRIPTION
**Pull request by eatkins**
Project extraction failed with 1.4.0-SNAPSHOT.

### CODE REVIEW

**Comment by eatkins** [comment]
I'm not sure if this is a good idea or not but prior to this change, I got the following error trying to extract the project with 1.4.0-SNAPSHOT:
```
[droste] [error] These subprojects were not found: "publish".  Found: "root", "docs", "laws", "tests", "reftreeJS", "metaJS", "coverage", "athemaJS", "coreJS", "macrosJS", "lawsJS", "meta", "testsJS", "scalacheck", "macros", "athema", "readme", "core", "reftree", "scalach
eckJS".
```

**Comment by SethTisue** [comment]
The version of droste we are building definitely has a `publish` subproject that we want to exclude. after `hub clone higherkindness/droste; cd droste; git checkout 1e4b3569fc30f8027f59e2c188bb739b5552271b; sbt projects` I see `publish` on the list. but if I change `project/build.properties` to `1.4.0-M2` and run `sbt projects` again, `publish` has vanished.

So this looks like a regression of some kind in 1.4.0-M2. (Perhaps there's some issue with the project having the same name as the `publish` task? Wild guess.)

**Comment by eatkins** [comment]
Ok, thanks for the clarification. I do think it's a poor idea to have a project mirror a built-in task but I guess it should still work if it did before.

**Comment by eatkins** [comment]
Actually, the problem was that droste was depending on undefined behavior in sbt: https://github.com/higherkindness/droste/pull/180.

**Pull request closed without merging**
