### PR TITLE
use sbt 1.3.0-RC1 by default

### PR DESCRIPTION
**Pull request by SethTisue**

### CODE REVIEW

**Comment by SethTisue** [comment]
Eugene's strategy at #900 was to tweak projects as necessary to get as much pre-release feedback as possible

my strategy here will be to stick with 1.2.8 for any project that has trouble, in order to get as many projects on 1.3 as possible with minimum fuss, then worry later about the laggards

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/4492/

**Comment by eed3si9n** [comment]
For the record here's my scorecard for the last milestone https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/4482/console:

```
[info] ---==  Execution Report ==---
[info] Report from the dbuild run for dbuild: 
[info] Project acyclic---------------------: FAILED (RuntimeException: Tests unsuccessful)
[info] Project airframe--------------------: SUCCESS (project rebuilt ok)
[info] Project akka------------------------: SUCCESS (project rebuilt ok)
[info] Project akka-contrib-extra----------: DID NOT RUN (stuck on broken dependencies: akka-stream)
[info] Project akka-http-------------------: DID NOT RUN (stuck on broken dependencies: akka-stream)
[info] Project akka-http-cors--------------: DID NOT RUN (stuck on broken dependencies: akka-stream)
[info] Project akka-http-json--------------: DID NOT RUN (stuck on broken dependencies: acyclic, akka-stream)
[info] Project akka-http-session-----------: DID NOT RUN (stuck on broken dependencies: akka-stream)
[info] Project akka-more-------------------: DID NOT RUN (stuck on broken dependencies: akka-stream)
[info] Project akka-persistence-cassandra--: DID NOT RUN (stuck on broken dependencies: akka-stream)
[info] Project akka-persistence-jdbc-------: DID NOT RUN (stuck on broken dependencies: akka-stream)
[info] Project akka-stream-----------------: FAILED (RuntimeException: )
[info] Project algebra---------------------: SUCCESS (project rebuilt ok)
[info] Project atto------------------------: SUCCESS (project rebuilt ok)
[info] Project autowire--------------------: DID NOT RUN (stuck on broken dependencies: acyclic)
[info] Project base64----------------------: SUCCESS (project rebuilt ok)
[info] Project better-files----------------: SUCCESS (project rebuilt ok)
[info] Project better-monadic-for----------: SUCCESS (project rebuilt ok)
[info] Project blaze-----------------------: DID NOT RUN (stuck on broken dependencies: log4s)
[info] Project boopickle-------------------: SUCCESS (project rebuilt ok)
[info] Project breeze----------------------: DID NOT RUN (stuck on broken dependencies: spire)
[info] Project cachecontrol----------------: SUCCESS (project rebuilt ok)
[info] Project case-app--------------------: SUCCESS (project rebuilt ok)
[info] Project catalysts-------------------: SUCCESS (project rebuilt ok)
[info] Project cats------------------------: SUCCESS (project rebuilt ok)
[info] Project cats-effect-----------------: SUCCESS (project rebuilt ok)
[info] Project circe-----------------------: FAILED (RuntimeException: Tests unsuccessful)
[info] Project circe-config----------------: DID NOT RUN (stuck on broken dependencies: circe)
[info] Project circe-derivation------------: DID NOT RUN (stuck on broken dependencies: circe)
[info] Project circe-jackson---------------: DID NOT RUN (stuck on broken dependencies: circe)
[info] Project claimant--------------------: SUCCESS (project rebuilt ok)
[info] Project classutil-------------------: SUCCESS (project rebuilt ok)
[info] Project cloc-plugin-----------------: SUCCESS (project rebuilt ok)
[info] Project coursier--------------------: DID NOT RUN (stuck on broken dependencies: acyclic)
[info] Project curryhoward-----------------: SUCCESS (project rebuilt ok)
[info] Project decline---------------------: SUCCESS (project rebuilt ok)
[info] Project discipline------------------: SUCCESS (project rebuilt ok)
[info] Project dispatch--------------------: SUCCESS (project rebuilt ok)
[info] Project doobie----------------------: DID NOT RUN (stuck on broken dependencies: circe)
[info] Project doodle----------------------: SUCCESS (project rebuilt ok)
[info] Project eff-------------------------: SUCCESS (project rebuilt ok)
[info] Project elastic4s-------------------: SUCCESS (project rebuilt ok)
[info] Project enumeratum------------------: DID NOT RUN (stuck on broken dependencies: circe)
[info] Project euler-----------------------: FAILED (RuntimeException: )
[info] Project expecty---------------------: SUCCESS (project rebuilt ok)
[info] Project export-hook-----------------: SUCCESS (project rebuilt ok)
[info] Project fansi-----------------------: SUCCESS (project rebuilt ok)
[info] Project fast-string-interpolator----: SUCCESS (project rebuilt ok)
[info] Project fastparse-------------------: DID NOT RUN (stuck on broken dependencies: acyclic)
[info] Project fs2-------------------------: SUCCESS (project rebuilt ok)
[info] Project genjavadoc------------------: SUCCESS (project rebuilt ok)
[info] Project geny------------------------: SUCCESS (project rebuilt ok)
[info] Project gigahorse-------------------: SUCCESS (project rebuilt ok)
[info] Project giter8----------------------: SUCCESS (project rebuilt ok)
[info] Project github4s--------------------: DID NOT RUN (stuck on broken dependencies: circe)
[info] Project grizzled--------------------: SUCCESS (project rebuilt ok)
[info] Project http4s----------------------: DID NOT RUN (stuck on broken dependencies: acyclic, circe, http4s-parboiled2, log4s, twirl)
[info] Project http4s-parboiled2-----------: FAILED (RuntimeException: )
[info] Project jackson-module-scala--------: SUCCESS (project rebuilt ok)
[info] Project jawn-0-10-------------------: SUCCESS (project rebuilt ok)
[info] Project jawn-0-11-------------------: SUCCESS (project rebuilt ok)
[info] Project jawn-fs2--------------------: SUCCESS (project rebuilt ok)
[info] Project json4s----------------------: SUCCESS (project rebuilt ok)
[info] Project jsoniter-scala--------------: SUCCESS (project rebuilt ok)
[info] Project kafka-----------------------: FAILED (RuntimeException: )
[info] Project kind-projector--------------: SUCCESS (project rebuilt ok)
[info] Project kittens---------------------: SUCCESS (project rebuilt ok)
[info] Project lagom-----------------------: DID NOT RUN (stuck on broken dependencies: akka-stream, twirl)
[info] Project lift-json-------------------: SUCCESS (project rebuilt ok)
[info] Project lightbend-emoji-------------: SUCCESS (project rebuilt ok)
[info] Project linter----------------------: SUCCESS (project rebuilt ok)
[info] Project log4s-----------------------: FAILED (RuntimeException: Tests unsuccessful)
[info] Project machinist-------------------: SUCCESS (project rebuilt ok)
[info] Project macro-compat----------------: SUCCESS (project rebuilt ok)
[info] Project macro-paradise--------------: SUCCESS (project rebuilt ok)
[info] Project magnolia--------------------: SUCCESS (project rebuilt ok)
[info] Project mdoc------------------------: DID NOT RUN (stuck on broken dependencies: acyclic, paiges)
[info] Project mercator--------------------: SUCCESS (project rebuilt ok)
[info] Project metaconfig------------------: DID NOT RUN (stuck on broken dependencies: acyclic, paiges)
[info] Project metrics-scala---------------: FAILED (RuntimeException: Required dependency not found)
[info] Project mima------------------------: SUCCESS (project rebuilt ok)
[info] Project minitest--------------------: SUCCESS (project rebuilt ok)
[info] Project monix-----------------------: SUCCESS (project rebuilt ok)
[info] Project monocle---------------------: SUCCESS (project rebuilt ok)
[info] Project mouse-----------------------: SUCCESS (project rebuilt ok)
[info] Project multibot--------------------: DID NOT RUN (stuck on broken dependencies: spire)
[info] Project newts-----------------------: SUCCESS (project rebuilt ok)
[info] Project nscala-time-----------------: SUCCESS (project rebuilt ok)
[info] Project paiges----------------------: FAILED (RuntimeException: Tests unsuccessful)
[info] Project paradox---------------------: SUCCESS (project rebuilt ok)
[info] Project parboiled-------------------: SUCCESS (project rebuilt ok)
[info] Project parboiled2------------------: FAILED (RuntimeException: )
[info] Project pascal----------------------: SUCCESS (project rebuilt ok)
[info] Project pcplod----------------------: SUCCESS (project rebuilt ok)
[info] Project perfolation-----------------: SUCCESS (project rebuilt ok)
[info] Project play-doc--------------------: DID NOT RUN (stuck on broken dependencies: twirl)
[info] Project play-file-watch-------------: SUCCESS (project rebuilt ok)
[info] Project play-json-------------------: SUCCESS (project rebuilt ok)
[info] Project play-webgoat----------------: DID NOT RUN (stuck on broken dependencies: akka-stream, twirl)
[info] Project playframework---------------: DID NOT RUN (stuck on broken dependencies: akka-stream, twirl)
[info] Project portable-scala-reflect------: SUCCESS (project rebuilt ok)
[info] Project pprint----------------------: SUCCESS (project rebuilt ok)
[info] Project pureconfig------------------: DID NOT RUN (stuck on broken dependencies: circe)
[info] Project refined---------------------: SUCCESS (project rebuilt ok)
[info] Project sbinary---------------------: DID NOT RUN (stuck on broken dependencies: acyclic, paiges)
[info] Project sbt-io----------------------: SUCCESS (project rebuilt ok)
[info] Project sbt-librarymanagement-------: SUCCESS (project rebuilt ok)
[info] Project sbt-testng------------------: SUCCESS (project rebuilt ok)
[info] Project sbt-util--------------------: SUCCESS (project rebuilt ok)
[info] Project scala-----------------------: SUCCESS (unchanged, not rebuilt)
[info] Project scala-async-----------------: SUCCESS (project rebuilt ok)
[info] Project scala-collection-compat-----: SUCCESS (project rebuilt ok)
[info] Project scala-collection-laws-------: SUCCESS (project rebuilt ok)
[info] Project scala-continuations---------: SUCCESS (project rebuilt ok)
[info] Project scala-debugger--------------: DID NOT RUN (stuck on broken dependencies: parboiled2)
[info] Project scala-gopher----------------: SUCCESS (project rebuilt ok)
[info] Project scala-java-time-------------: SUCCESS (project rebuilt ok)
[info] Project scala-java8-compat----------: SUCCESS (project rebuilt ok)
[info] Project scala-js--------------------: SUCCESS (project rebuilt ok)
[info] Project scala-js-stubs--------------: SUCCESS (project rebuilt ok)
[info] Project scala-logging---------------: SUCCESS (project rebuilt ok)
[info] Project scala-newtype---------------: SUCCESS (project rebuilt ok)
[info] Project scala-parser-combinators----: SUCCESS (project rebuilt ok)
[info] Project scala-partest---------------: SUCCESS (project rebuilt ok)
[info] Project scala-pet-store-------------: DID NOT RUN (stuck on broken dependencies: acyclic, circe, http4s-parboiled2, log4s, twirl)
[info] Project scala-records---------------: SUCCESS (project rebuilt ok)
[info] Project scala-refactoring-----------: SUCCESS (project rebuilt ok)
[info] Project scala-sculpt----------------: SUCCESS (project rebuilt ok)
[info] Project scala-ssh-------------------: DID NOT RUN (stuck on broken dependencies: acyclic, paiges)
[info] Project scala-stm-------------------: SUCCESS (project rebuilt ok)
[info] Project scala-swing-----------------: SUCCESS (project rebuilt ok)
[info] Project scala-xml-quote-------------: DID NOT RUN (stuck on broken dependencies: acyclic)
[info] Project scalacheck------------------: SUCCESS (project rebuilt ok)
[info] Project scalacheck-shapeless--------: SUCCESS (project rebuilt ok)
[info] Project scaladex--------------------: DID NOT RUN (stuck on broken dependencies: acyclic, akka-stream, twirl)
[info] Project scalafix--------------------: DID NOT RUN (stuck on broken dependencies: acyclic, paiges)
[info] Project scalafmt--------------------: DID NOT RUN (stuck on broken dependencies: acyclic, paiges)
[info] Project scalaj-http-----------------: SUCCESS (project rebuilt ok)
[info] Project scalajson-------------------: SUCCESS (project rebuilt ok)
[info] Project scalameta-------------------: DID NOT RUN (stuck on broken dependencies: acyclic)
[info] Project scalameter------------------: SUCCESS (project rebuilt ok)
[info] Project scalamock-------------------: SUCCESS (project rebuilt ok)
[info] Project scalapb---------------------: DID NOT RUN (stuck on broken dependencies: acyclic)
[info] Project scalaprops------------------: SUCCESS (project rebuilt ok)
[info] Project scalariform-----------------: SUCCESS (project rebuilt ok)
[info] Project scalasti--------------------: SUCCESS (project rebuilt ok)
[info] Project scalastyle------------------: SUCCESS (project rebuilt ok)
[info] Project scalatags-------------------: DID NOT RUN (stuck on broken dependencies: acyclic)
[info] Project scalatest-------------------: SUCCESS (project rebuilt ok)
[info] Project scalatest-tests-------------: SUCCESS (project rebuilt ok)
[info] Project scalikejdbc-----------------: SUCCESS (project rebuilt ok)
[info] Project scallop---------------------: SUCCESS (project rebuilt ok)
[info] Project scapegoat-------------------: SUCCESS (project rebuilt ok)
[info] Project scodec----------------------: SUCCESS (project rebuilt ok)
[info] Project scodec-bits-----------------: SUCCESS (project rebuilt ok)
[info] Project sconfig---------------------: SUCCESS (project rebuilt ok)
[info] Project scopt-----------------------: SUCCESS (project rebuilt ok)
[info] Project scoverage-------------------: SUCCESS (project rebuilt ok)
[info] Project scribe----------------------: SUCCESS (project rebuilt ok)
[info] Project scrooge---------------------: SUCCESS (project rebuilt ok)
[info] Project scrooge-shapes--------------: DID NOT RUN (stuck on broken dependencies: circe)
[info] Project shaded-scalajson------------: SUCCESS (unchanged, not rebuilt)
[info] Project shapeless-------------------: SUCCESS (project rebuilt ok)
[info] Project silencer--------------------: SUCCESS (project rebuilt ok)
[info] Project simulacrum------------------: SUCCESS (project rebuilt ok)
[info] Project singleton-ops---------------: SUCCESS (project rebuilt ok)
[info] Project sjson-new-------------------: SUCCESS (project rebuilt ok)
[info] Project sksamuel-exts---------------: SUCCESS (project rebuilt ok)
[info] Project slick-----------------------: SUCCESS (project rebuilt ok)
[info] Project sourcecode------------------: SUCCESS (project rebuilt ok)
[info] Project specs2----------------------: SUCCESS (project rebuilt ok)
[info] Project specs2-more-----------------: SUCCESS (project rebuilt ok)
[info] Project spire-----------------------: FAILED (RuntimeException: )
[info] Project spray-json------------------: SUCCESS (project rebuilt ok)
[info] Project ssl-config------------------: SUCCESS (project rebuilt ok)
[info] Project sttp------------------------: DID NOT RUN (stuck on broken dependencies: akka-stream, circe)
[info] Project tsec------------------------: DID NOT RUN (stuck on broken dependencies: acyclic, circe, http4s-parboiled2, log4s, twirl)
[info] Project tut-------------------------: SUCCESS (project rebuilt ok)
[info] Project twirl-----------------------: FAILED (RuntimeException: Tests unsuccessful)
[info] Project twitter-util----------------: SUCCESS (project rebuilt ok)
[info] Project twotails--------------------: SUCCESS (project rebuilt ok)
[info] Project unfiltered------------------: SUCCESS (project rebuilt ok)
[info] Project unique----------------------: SUCCESS (project rebuilt ok)
[info] Project upickle---------------------: DID NOT RUN (stuck on broken dependencies: acyclic)
[info] Project utest-----------------------: SUCCESS (project rebuilt ok)
[info] Project vault-----------------------: SUCCESS (project rebuilt ok)
[info] Project wartremover-----------------: SUCCESS (project rebuilt ok)
[info] >>> The dbuild result is----------------: FAILED (failed: acyclic, kafka, http4s-parboiled2, log4s, akka-stream, twirl, metrics-scala, euler, paiges, spire, circe, parboiled2)
[info] ---==  End Execution Report ==---
```

**Comment by dwijnand** [comment]
The `org.boris:pecoff4j:0.0.2.1` ones are due to an issue with coursier and something in sbt-whitesource dependency tree.  Fixed by upgraded to latest sbt-whitesource (I already fixed it a while back for sbt/sbt).

**Comment by eed3si9n** [comment]
I think I updated whitesource to the latest, but Community Build had frozen the refs.
io, util, and librarymanagement should point to develop branch.
I think I had to comment out sbt and Zinc in #900.

**Comment by eed3si9n** [comment]
Similar story for Blaze:

```
   blaze-uri:                    "https://github.com/http4s/blaze.git#v0.14.0"  # was master
```

I fixed the build in project https://github.com/http4s/blaze/pull/289 so pointing at master should extract.

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/4501/ (404 til Jenkins wakes up)

**Comment by SethTisue** [comment]
this isn't 100% green yet I don't think, but I'm going to merge it anyway to conserve disk space and inodes

**Comment by SethTisue** [comment]
we're back at 100% green as of https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/4518/

the following projects remain on sbt 1.2.8: genjavadoc, mockito-scala, akka-stream, acyclic, (http4s-)parboiled2, twirl, play-doc, playframework, monocle, scala-ssh, log4s, blaze, paiges, play-webgoat, sbt-{io,util,librarymanagement}, metaconfig, circe, http4s, circe-config, circe-derivation, sttp, circe-jackson

**Comment by dwijnand** [comment]
> but I'm going to merge it anyway to conserve disk space and inodes

What's the connection here?  Does the projects using sbt 1.3 use less disk space?

**Comment by SethTisue** [comment]
> What's the connection here? Does the projects using sbt 1.3 use less disk space?

the problem is cached builds. anytime we're testing a branch that requires rebuilding most/all projects, cache usage doubles

**Comment by eed3si9n** [comment]
> we're back at 100% green as of https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/4518/

Nice. Thanks for working on this.

**Pull request merged**
