### PR TITLE
newer coursier, scalafix, scalameta; add coursier-small; pull ammonite

### PR DESCRIPTION
**Pull request by SethTisue**
because scalafix now depends on coursier-small

/cc @olafurpg

### CODE REVIEW

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/3288/ (404 til Jenkins queue clears)

**Comment by olafurpg** [comment]
Thanks, I didn't think of this when I added the dependency 😅

**Comment by SethTisue** [comment]
mercator is green (and so is magnolia)

`coursier-small`:

```
[coursier-small] [error] /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.14/project-builds/coursier-small-ef765717232c2339bf41aced25e10801fd2dea56/small/src/main/scala/com/geirsson/coursiersmall/CoursierSmall.scala:5:8: object Gather is not a member of package coursier.util
[coursier-small] [error] import coursier.util.Gather
[coursier-small] [error]        ^
```

`Gather` wasn't added to coursier until a bit later than the commit we're frozen at.

unfreezing coursier might break ammonite, but that's something we'd probably need to deal with sooner or later regardless

**Comment by SethTisue** [comment]
I moved the mercator/magnolia part to #768

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/3291/ (404 til Jenkins queue clears)

**Comment by SethTisue** [comment]
> unfreezing coursier might break ammonite, but that's something we'd probably need to deal with sooner or later regardless

indeed, it did. (the other failures in run 3291 are unrelated)

I don't have time to deal with it until after 2.13.0-M5 is out, so for now I'll just freeze scalafix at the last green commit, before the coursier-small addition

not sure how hard moving ammonite to the new version might be.

one possibility might be to introduce a space split and have both old-coursier and new-coursier in the build

**Comment by olafurpg** [comment]
I can probably replace the usage of coursier-small in the scalafix repo with https://github.com/sbt/librarymanagement if that helps. It's only used for a single integration test that can run in 2.12 only. I only strictly need coursier-small in sbt-scalafix to support 0.13.

**Comment by olafurpg** [comment]
Or even easier, I can downgrade the coursier dependency version in coursier-small to match the ammonite version. 

I'd prefer not to change things right away, hopefully it can be sorted out. But if this continues to be a problem I'm happy to accommodate.

**Comment by SethTisue** [comment]
let's get a fresh read on the current status: 
https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/3385/

**Comment by SethTisue** [comment]
try again: 
https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/3395/ (404 for now)

**Comment by SethTisue** [comment]
```
[scalafix] [error] **** Missing dependency: the library org.scalameta#metap is not provided (in space "scala.main") by any project in this configuration file.
```

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/3403/

**Comment by SethTisue** [comment]
`failed: scalafix` because of compile errors, apparently we need a different scalameta version

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/3411/

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/3414/

**Comment by SethTisue** [comment]
okay, run 3414 has scalafix green, but we still need to see what else breaks: 
https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/3416/

**Comment by SethTisue** [comment]
as expected, ammonite breaks

but also, classpath-shrinker breaks, I think because the even-newer coursier doesn't have a scalaz dependency anymore

**Comment by SethTisue** [comment]
https://github.com/scalacommunitybuild/classpath-shrinker/commit/ac7cff06f4f9e5b157a9da78ea34974acfe57d44 should take care of the classpath-shrinker issue

**Comment by SethTisue** [comment]
the only project downstream from ammonite proper (as opposed to ammonite-ops) is scala-debugger. if everything else is green, I'm rather tempted to just pull ammonite and scala-debugger from the build

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/3423/

**Comment by SethTisue** [comment]
oh, you know what, we have Ammonite frozen at an old version, on master it's already on coursier 1.1.0-M7, which is where we want to be

so let's unfreeze Ammonite and see what happens

**Comment by SethTisue** [comment]
gah, Ammonite isn't even built with sbt anymore

perhaps eventually we'll need to add mill support to dbuild, but that isn't happening anytime soon, so I guess I'll just pull ammonite and scala-debugger for now

**Comment by SethTisue** [comment]
> guess I'll just pull ammonite and scala-debugger for now

oh, we should only have to pull the one subproject of scala-debugger that depends on ammonite, not pull the whole thing

**Comment by SethTisue** [comment]
fyi @chipsenkbeil @lihaoyi

@olafurpg there's nothing you need to do here, unless you have some insight into this:

```
      // java.lang.IllegalStateException: unable to auto-detect semanticdb-scalac compiler plugin
       //   at scalafix.tests.cli.ScalafixImplSuite.$anonfun$semanticdbPluginPath$1(ScalafixImplSuite.scala:37)
       //   at scala.Option.getOrElse(Option.scala:121)
       //   at scalafix.tests.cli.ScalafixImplSuite.semanticdbPluginPath(ScalafixImplSuite.scala:36)
       "set excludeFilter in (Test, unmanagedSources) in unit := HiddenFileFilter || \"ScalafixImplSuite.scala\""
```

**Comment by chipsenkbeil** [comment]
@SethTisue, ammonite is used for the __scala-debugger-tool__ and subsequent __sbt-scala-debugger-plugin__ modules. Could you just exclude those? In fact, I think you're already excluding the sbt plugin, right? The main module that serve as good build test is the api one.

**Comment by olafurpg** [comment]
@SethTisue Thanks! The test failure is not surprising if the classloader's classpath is different than from when opening sbt normally. I generally try to avoid writing such tests but this was the quickest way to get a full e2e test, it's fine to disable the test.

When I think of it, if you disable `ToolClasspathSuite` as well then you can remove the coursier-small dependency in the scalafix build.

**Comment by SethTisue** [comment]
> @SethTisue, ammonite is used for the scala-debugger-tool and subsequent sbt-scala-debugger-plugin modules. Could you just exclude those?

@chipsenkbeil yes, that's what I ended up doing.

@olafurpg the coursier-small dependency isn't really causing any trouble, but if it does, I'll keep it in mind that it would be easy to remove.

**Comment by olafurpg** [comment]
@SethTisue Excluding `ToolClasspathSuite` on your side should make the dependency unnecessary

**Pull request merged**
