### PR TITLE
reinstate spire, breeze, multibot

### LINKED ISSUE #672: re-add spire (and its dependencies breeze and multibot)
I removed these 3 projects in #671 because spire was failing to compile

```
[spire] [error] /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.9/project-builds/spire-5fbe50f072cd8e261bc19152a834475a38379fd2/core/shared/src/main/scala/spire/syntax/std/Ops.scala:154: value on is not a member of spire.algebra.Order[B]
[spire] [error]     implicit val ord: Order[A] = ev.on(f)
[spire] [error]                                     ^
[spire] [error] /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.9/project-builds/spire-5fbe50f072cd8e261bc19152a834475a38379fd2/core/shared/src/main/scala/spire/syntax/std/Ops.scala:170: value on is not a member of spire.algebra.Order[B]
[spire] [error]     implicit val ord: Order[A] = ev.on(f)
[spire] [error]                                     ^
[spire] [error] /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.9/project-builds/spire-5fbe50f072cd8e261bc19152a834475a38379fd2/core/shared/src/main/scala/spire/syntax/std/Ops.scala:240: value reverse is not a member of spire.algebra.PartialOrder[A]
[spire] [error]     Searching.minimalElements(as)(ev.reverse)
[spire] [error]                                      ^
[spire] [error] /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.9/project-builds/spire-5fbe50f072cd8e261bc19152a834475a38379fd2/core/shared/src/main/scala/spire/syntax/std/Ops.scala:305: value on is not a member of spire.algebra.Order[B]
[spire] [error]     implicit val ord: Order[A] = ev.on(f)
[spire] [error]                                     ^
```

full log at https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/2570/consoleFull

### PR DESCRIPTION
**Pull request by SethTisue**
fixes #672

### CODE REVIEW

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/2842/ (404 for now)

**Comment by SethTisue** [comment]
```
[breeze] [error] /Users/tisue/community.212/target-0.9.12/project-builds/breeze-c8fb167a2c9462bb82f2134a8a8fce5ebdd944f4/math/src/test/scala/breeze/stats/distributions/MultivariateGaussianTest.scala:34:21: value wrap is not a member of object org.scalacheck.Gen
[breeze] [error]  Note: implicit method arbDistr is not applicable here because it comes after the application point and it lacks an explicit result type
[breeze] [error]     Arbitrary { Gen.wrap(DenseVector.rand(N)) }
[breeze] [error]                     ^
[breeze] [error] /Users/tisue/community.212/target-0.9.12/project-builds/breeze-c8fb167a2c9462bb82f2134a8a8fce5ebdd944f4/math/src/test/scala/breeze/stats/distributions/MultivariateGaussianTest.scala:39:11: value wrap is not a member of object org.scalacheck.Gen
[breeze] [error]  Note: implicit method arbDistr is not applicable here because it comes after the application point and it lacks an explicit result type
[breeze] [error]       Gen.wrap {
[breeze] [error]           ^
[breeze] [error] two errors found
[breeze] [error] (math / Test / compileIncremental) Compilation failed
```

could be a ScalaCheck 1.13 vs 1.14 issue?

@dlwh would you like to try upgrading your repo to ScalaCheck 1.14.0?

**Comment by SethTisue** [comment]
as for multibot,

```
[multibot] [info] - testScalaInterpreter *** FAILED ***
[multibot] [info]   "[java.lang.SecurityException: ("java.io.FilePermission" "/var/folders/j1/sv5gcszx0tn0t_q5xr58v1q40000gn/T/repl8930283871211067074.tmp/$line12" "write")
[multibot] [info]   	at org.multibot.ScriptSecurityManager$.doChecks(ScriptSecurityManager.scala:72)
[multibot] [info]   	at org.multibot.ScriptSecurityManager$.checkPermission(ScriptSecurityManager.scala:27)
[multibot] [info]   	at java.lang.SecurityManager.checkWrite(SecurityManager.java:979)
[multibot] [info]   	at sun.nio.fs.UnixPath.checkWrite(UnixPath.java:801)
[multibot] [info]   	at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:376)
```

this is in a local run on MacOS. @OlegYch?

**Comment by SethTisue** [comment]
with multibot tests only compiled not run, and with breeze tests not even compiled: https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/2845/ (404 for now)

**Comment by SethTisue** [comment]
merging because green in local testing, but let me know if y'all want to help with re-enabling the disabled pieces

**Comment by OlegYch** [comment]
@SethTisue fixed multibot test, you can enable them

**Comment by SethTisue** [comment]
@OlegYch thx! 1619f2942ad807e3dc79c3acb4d1877f041f0ef3

**Pull request merged**
