### PR TITLE
Freeze sha script

### PR DESCRIPTION
**Pull request by lrytz**

### CODE REVIEW

**Comment by lrytz** [comment]
Just putting adriaan's commands into a script https://github.com/scala/community-builds/issues/338#issuecomment-253613276

**Comment by SethTisue** [comment]
can you target 2.12.x here...? then we can merge it forward onto 2.13.x

**Comment by lrytz** [comment]
Sure - I wasn't sure if we actually merge forward in this repo or not, I expect there are many merge conflicts all the time?

**Comment by SethTisue** [comment]
Merge conflicts are common, yes, but otoh they're nearly always easy to resolve.

**Comment by lrytz** [comment]
OK, rebased and changed the base to 2.12.x

**Comment by dwijnand** [comment]
BTW @SethTisue, if you're in the business of common but easy to solve conflicts you might want to give git-mediate a shot. It's apparently really good.

**Comment by adriaanm** [comment]
❤️

**Pull request merged**
