### PR TITLE
bump sbt 1.4 version to 1.4.0-RC2

### PR DESCRIPTION
**Pull request by SethTisue**
~~https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/1879/~~
~~https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/1880/~~
~~https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/1881/~~
~~https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/1882/~~
~~https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/1885/~~
~~https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/1886/~~
~~https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/1890/~~
~~https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/1891/~~
~~https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/1892/~~
~~https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/1893/~~
~~https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/1899/~~
~~https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/1900/~~
~~https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/1901/~~
~~https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/1902/~~
https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/1903/

### CODE REVIEW

**Comment by SethTisue** [comment]
@eatkins the following repos are pinned to 1.3 — should we try any of them with RC2 instead here?

```
proj/droste.conf
proj/enumeratum.conf
proj/gigahorse.conf
proj/lagom.conf
proj/munit.conf
proj/playframework.conf
proj/scalatest.conf
proj/zinc.conf
```

**Comment by eatkins** [comment]
* droste should be ok now
* enumeratum haven't responded to the PR I made to fix their build
* gigahorse should be ok
* lagom should be ok
* munit might work? It has both passed and failed on my local build and I don't know if other changes we've made maybe resolved the transient failures
* playframework doesn't work with the documentation subproject: https://github.com/sbt/zinc/issues/927. I think the other projects work ok but I don't know if there is an easy way to just pin a subproject.
* scalatest I'm not sure. I never had problems running that locally.
* zinc doesn't work because of issues with the protobuf plugin with dbuild. I am pretty sure that this is true with 1.3.13 as well because I think zinc is pinned to an older commit before we changed the protobuf plugin.

**Comment by SethTisue** [comment]
thanks, I'll update this PR next week based on that.

at the moment, multiple projects are failing to extract: https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/1880/console shows `EXTRACTION FAILED (failed: advxml, akka-http, akka-persistence-cassandra, alpakka-kafka, avro4s, jwt-scala, spire) `

I can dig into it next week after I return from vacation, but feel free to look it at sooner if you like. the split logs are at https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/1880/artifact/logs/ . I just looked at one so far (akka-http) and it looked a conflict between sbt-dependency-graph as a plugin and as in-source, something like that?

for now I'm going to modify those projects to use 1.3.13 just as a temporary measure so the runs can proceed past the extraction phase

**Comment by SethTisue** [comment]
run 1881 has now made it past extraction

UPDATE: run 1881 was canceled for Jenkins to restart; let's see how 1885 and 1886 do

**Comment by SethTisue** [comment]
1886: green

trying it now with fewer projects pinned to 1.3.13

**Comment by SethTisue** [comment]
lagom fails to extract with:

```
[lagom:error] /home/jenkins/workspace/scala-2.13.x-jdk11-integrate-community-build/target-0.9.16/extraction/37505b03d8434d2cb793324151657750e3ef5383/projects/ed62915b4a67ec03d7569330aff2f5bcda75a108/build.sbt:245: error: value ** is not a member of Seq[xsbti.VirtualFileRef]
[lagom:error]     val products = (a.asInstanceOf[sbt.internal.inc.Analysis]).relations.allProducts.toSeq ** new SimpleFileFilter(
[lagom:error]                                                                                            ^
[lagom] [error] sbt.compiler.EvalException: Type error in expression
```

**Comment by eatkins** [comment]
I think you need to bump the lagom version. My PR that fixed that issue was merged: https://github.com/lagom/lagom/pull/3031.

**Comment by SethTisue** [comment]
okay... moving to newer lagom hits the sbt-dependency-graph issue, but I can fork it temporarily to get around that

**Comment by SethTisue** [comment]
we ended up with the following still on 1.3:

* alpakka-kafka: uses sbt-dependency-graph
* gigahorse: same error, idk why, not investigated
* playframework: we're on 2.8.x, fixes are on master. it's fine, it can wait
* scalatest-tests: ScalaTest core is fine on 1.4.0-RC2, the part that isn't is `scalatest-tests`, which is so big and fragile I doubt it's worth looking into
* zinc: because we're pinned to an old version

overall, this seems very good to me. cc @eed3si9n

**Comment by eed3si9n** [comment]
@SethTisue thanks for this!

**Pull request merged**
