### PR TITLE
2.13: support both fastparse 1 and 2; get scalameta green again; unfork ScalaPB; drop moribund projects

### LINKED ISSUE #897: projects are moving to Fastparse 2
which is hard because it isn't remotely source-compatible with Fastparse 1

this is timely because right now is an important time to be testing on Scala 2.13, but if a project's 2.13 support is landing in a branch that also requires Fastparse 2, we have a problem

perhaps this can be addressed with splitting the build into spaces

or perhaps we could keep everything in the same space, but use dbuild to publish Fastparse 1 and 2 under different org and/or artifacts, and then override the dependency downstream accordingly

### PR DESCRIPTION
**Pull request by SethTisue**
sequel to #910

fixes #897, #915, #936

### CODE REVIEW

**Comment by SethTisue** [comment]
queued: https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/2407/

**Comment by SethTisue** [comment]
with Maven-retrieved (rather than source-built) fastparse 2, in local testing:

```
[info] Project scalameta-------------------: SUCCESS (project rebuilt ok)
```

but the question is what else will break.

**Comment by SethTisue** [comment]
queued: https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/2411/

**Comment by SethTisue** [comment]
I wrote new sbt builds for fastparse 2 and utest (since they only have mill builds these days). Doing so was reasonably easy/pleasant.

And in local testing now, all the low-level projects I would want to still be green, are. So I'm now confident this should go forward; if there ends up being more breakage farther downstream, we'll deal with it.

I'm a bit tempted to try to target 2.12.x on this. But I think there's no real need; in general, it's fine for the 2.12.x to get increasingly frozen. If it eventually turns out that other 2.12.x community build things would end up benefiting from this, we can do the backport then.

**Comment by SethTisue** [comment]
Added a commit which drops nearly all of the projects in the "jawn 0.10" space, including sbt and its modules. jawn 0.10 is unlikely to ever make the jump to 2.13. /cc @eed3si9n

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/2415/

**Comment by eed3si9n** [comment]
I created a new release of sjson-new recently using Jawn 0.14.2 for Scala 2.13 - https://github.com/eed3si9n/sjson-new/blob/60158cbc3a42ef235b8c85390da8ef6ec6f28a4a/project/Dependencies.scala#L25

**Comment by SethTisue** [comment]
@eed3si9n I'll attempt to re-add

overall PR situation: latest test run has `SUCCESS 131 FAILED?! akka-http,upickle,scalatex` which is excellent. I think the akka-http failure is unrelated, and getting upickle and scalatex green again probably won't be hard (and in any case isn't completely essential). so this is nearly ready for merge

**Comment by SethTisue** [comment]
* scalatex: fixed by forking it
* upickle: dropped
* sjson-new: re-added
* akka-http: fixed (scalacommunitybuild/akka-http@215e6744d490354ea64638123c72cc0ef4a41c50)

**Pull request merged**
