### PR TITLE
wip -- not for merge

### PR DESCRIPTION
**Pull request by SethTisue**
if this works, push the updated forks to scalacommunitybuild
instead of merging this

### CODE REVIEW

**Comment by SethTisue** [comment]
test run: https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/1319/consoleFull

**Comment by SethTisue** [comment]
disabled coursier in scalameta, trying again: https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/1320/consoleFull

**Comment by SethTisue** [comment]
disabled scalamock's new Scala.js support. updated comments on forked projects to include date fork was refreshed. try again: https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/1321/consoleFull

**Comment by SethTisue** [comment]
huh — here's a new one, that run got wedged at:

```
[scalameta] running git ls-files --others --exclude-standard in /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.7-RC1/project-builds/scalameta-269d65971ddc6b917639b963fba32d6b02dbb59c/.
```

never seen that before. aborted it, trying again at https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/1322/consoleFull

**Comment by SethTisue** [comment]
hmm, maybe this isn't just a transient thing? I'll have to come back to it

**Comment by SethTisue** [comment]
one more, just testing scalameta only so it finishes faster: https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/1330/consoleFull

**Comment by SethTisue** [comment]
try again after merging ScalaCheck fix onto our branch: https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/1334/consoleFull (404 til Jenkins unstraps his roller skates)

**Comment by SethTisue** [comment]
the scalameta hang is reproducible running locally:

```
[scalameta] running git rev-list HEAD v1.0.0 --count in /Users/tisue/community.213/target-0.9.7-RC1/project-builds/scalameta-ad236c3ba23899052c3c154e2d934d4a61ba2410/.
[scalameta] running git rev-parse HEAD in /Users/tisue/community.213/target-0.9.7-RC1/project-builds/scalameta-ad236c3ba23899052c3c154e2d934d4a61ba2410/.
```

**Comment by SethTisue** [comment]
debugging locally as per https://typesafehub.github.io/dbuild/0.9.5/introduction.html#what-if-the-build-fails:

```
./dbuild-0.9.7-RC1/bin/dbuild checkout \
  a1f7259505ca37fa9554f0c84edceebf0cf9f90f \
  scalameta newdir
newdir/.dbuild/start
```

also reproduces the hang:

```
running git rev-list HEAD v1.0.0 --count in /Users/tisue/community.213/newdir/.
running git rev-parse HEAD in /Users/tisue/community.213/newdir/.
running git ls-files --others --exclude-standard in /Users/tisue/community.213/newdir/.
```

the relevant commit in the scalameta repo is https://github.com/scalameta/scalameta/commit/f4ca319c05c292e2bc7a2de7308c43fed9224eab (EDIT: but note that the code in os.scala has changed quite a bit since then)

during the hang the stack is:

```
"main" #1 prio=5 os_prio=31 tid=0x00007f86b6806800 nid=0x1c03 in Object.wait() [0x0000700004dd9000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        - waiting on <0x00000007a2480840> (a java.lang.UNIXProcess)
        at java.lang.Object.wait(Object.java:502)
        at java.lang.UNIXProcess.waitFor(UNIXProcess.java:395)
        - locked <0x00000007a2480840> (a java.lang.UNIXProcess)
        at org.scalameta.os.shell$.exec(os.scala:22)
        at org.scalameta.os.shell$.check_output(os.scala:38)
        at org.scalameta.os.git$.noUntrackedFiles$1(os.scala:114)
        at org.scalameta.os.git$.isStable(os.scala:125)
        at $b4f3a0acdbfff8a19bf0$.computePreReleaseVersion(build.sbt:421)
```

**Comment by SethTisue** [comment]
ha, so adding `.dbuild/` to `.gitignore` makes the problem go away, by reducing the amount of output from `git ls-files --others --exclude-standard .` from a few thousand lines to just a handful

why having a few thousand lines of output would cause a hang, I don't know. os.scala is calling `Runtime#exec` itself and doing its own I/O, maybe that code is buggy whenever the process outputs something long? /cc @xeno-by

but anyway I pushed the `.gitignore` change to my fork. we're already forked because of bintray, so having a second small change in the fork doesn't hurt

I'll run a test locally

**Comment by SethTisue** [comment]
in my local test scalameta passed, but scalafix failed, some difference between org.scalamacros and org.scalameta ~~(I didn't keep the error)~~, here's the error:

```
[scalafix] [debug] Dependency not rewritten: org.scalameta:paradise:3.0.0-M7:plugin->default(compile)
[scalafix] [error] **** Missing dependency: the library org.scalameta#paradise is not provided (in space "default") by any project in this configuration file.
[scalafix] [error] In order to control which version is used, please add the corresponding project to the build file
[scalafix] [error] (or use "check-missing:false" to ignore (not recommended)).
[scalafix] java.lang.RuntimeException: Required dependency not found
```

I've queued up a similar run here: https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/1340/consoleFull (404 til Jenkins sinks the eleven ball in the corner pocket). if only scalafix fails I think we can declare victory and deal with that one failure separately

**Comment by xeno-by** [comment]
@SethTisue Thanks for figuring that out! I've never encountered anything like that before.

**Comment by SethTisue** [comment]
latest results

```
[info] >>> The dbuild result is------------: FAILED (failed: scalafix, scalamock)
```

scalamock is also a leaf, so I'm going to move forward with this.

**Comment by SethTisue** [comment]
I pushed the updated forks to the scalacommunitybuild org, and here in this repo I pushed c6f39df82eec0b6e93f9120406ec277b3be7e777 which has the necessary changes here

**Pull request closed without merging**
