### PR TITLE
add quicklens

### PR DESCRIPTION
**Pull request by SethTisue**
fyi @adamw

already green in local testing

### CODE REVIEW

**Comment by SethTisue** [comment]
followup https://github.com/scala/community-builds/commit/64943f8e6bd35b1a61b261dced32f35540507705

**Comment by SethTisue** [comment]
@adamw can haz 2.13 crossbuild, by any chance?

**Comment by adamw** [comment]
@SethTisue two dependencies have problems: scalatest and clippy. I guess I'll wait for 2.13 final :)

**Comment by SethTisue** [comment]
both ScalaTest 3.0.x and 3.1.x are [available](https://github.com/scala/make-release-notes/blob/2.13.x/projects-2.13.md) for 2.13.0-RC3. or, you mean some more specific ScalaTest problem?

**Comment by adamw** [comment]
Ok, updating scalatest to RC5 helped :)

But of course there's a problem with collecitons. Not sure if there's going to be a solution which will work both with 2.12 and 2.13:

```
  implicit def traversableQuicklensFunctor[F[_], A](
      implicit cbf: CanBuildFrom[F[A], A, F[A]],
      ev: F[A] => TraversableLike[A, F[A]]
  ): QuicklensFunctor[F, A] =
    new QuicklensFunctor[F, A] {
      override def map(fa: F[A])(f: A => A) = fa.map(f)
    }
```

(`TraversableLike` is the problem)

**Comment by martijnhoekstra** [comment]
@adamw does something like  https://scastie.scala-lang.org/TEGv0IpnTOK4LJ6gz3PNAw suffice?

**Comment by adamw** [comment]
@martijnhoekstra thanks! I suppose I'll have to create separate <2.13 and >=2.13 source modules

**Comment by adamw** [comment]
@SethTisue done! Thanks @martijnhoekstra !

and even the tests pass ;)

**Comment by SethTisue** [comment]
https://github.com/scala/community-builds/commit/eeb0d7541191fd7f25517b31c418cdb8f0ed7ff3 :+1: (confirmed by our Jenkins)

**Pull request merged**
