### PR TITLE
2.12: new Scala SHA

### PR DESCRIPTION
**Pull request by SethTisue**
~~https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/5801/~~
~~https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/5802/~~
~~https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/5825/~~
~~https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/5826/~~
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/5829/
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/5830/

### CODE REVIEW

**Comment by SethTisue** [comment]
* 58ce104566 - Merge pull request scala/scala#9006
* 61cf896c51 - Merge pull request scala/scala#8995
* 798705facb - Merge pull request scala/scala#8997
* 1c3825bc0d - Merge pull request scala/scala#8999

https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/5802/artifact/logs/silencer-build.log

```
[info] - macro expandee *** FAILED ***
[info]   1 did not equal 0 (SilencerPluginTest.scala:47)
silencer-plugin/testdata/messagePatterns.scala:12: warning: a pure expression does nothing in statement position
    123
    ^
...
[silencer] [error] Failed tests:
[silencer] [error] 	com.github.ghik.silencer.SilencerPluginTest
```

https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/5802/artifact/logs/linter-build.log

```
[linter] [error] Error while emitting org/psywerx/hairyfotr/LinterPlugin$PostTyperComponent$PostTyperTraverser
[linter] [error] Method too large: org/psywerx/hairyfotr/LinterPlugin$PostTyperComponent$PostTyperTraverser.traverse (Lscala/reflect/internal/Trees$Tree;)V
```

**Comment by SethTisue** [comment]
The silencer failure is reproducible outside of dbuild with `++2.12.12-bin-58ce104`. And it's reproducible on master, not just on the old commit we're frozen at. Bisecting showed that https://github.com/scala/scala/pull/8995 is the cause. @ghik this looks to like a test you will need to adjust rather than a problem with the PR, but I'm not completely sure, wdyt?

**Comment by SethTisue** [comment]
as for linter, the repo seems abandoned, though the author is still doing other things on GitHub. and we aren't even running their tests. but, I bisected it anyway (since that's pretty easy to do when the problem is reproducible outside dbuild, in this case with `test:compile`) — and the culprit is https://github.com/scala/scala/pull/8997 . I don't know what to make of that at all, and I don't know whether it's worth digging into. @retronym @lrytz wdyt?

**Comment by SethTisue** [comment]
in the interest of getting this PR merged, I disabled the silencer test, and I'm pulling linter from the build along with multibot, its only downstream project — this can always be reversed later

**Comment by SethTisue** [comment]
@lrytz said he'd look at the linter thing tomorrow

**Comment by ghik** [comment]
@SethTisue yes, the silencer failure will simply require a test adjustment

**Comment by lrytz** [comment]
Story of what's going on with linter here: https://github.com/scala/scala/pull/9065

**Comment by SethTisue** [comment]
#1168 reinstates linter and multibot

**Pull request merged**
