### PR TITLE
2.13: new Scala SHA

### PR DESCRIPTION
**Pull request by SethTisue**
~https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/3125/~
~https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/3128/~
https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/3132/

### CODE REVIEW

**Comment by SethTisue** [comment]
gah https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/3130/ wtf is up with twitter-util

**Comment by SethTisue** [comment]
twitter-util failure is real. `git bisect` found the responsible PR; I've notified Princess here: https://github.com/scala/scala/pull/9727#issuecomment-906652954

**Comment by SethTisue** [comment]
I've excluded the test for now so we can run the rest of the build.

**Comment by NthPortal** [comment]
@SethTisue I've opened scala/scala#9737 which fixes it

**Comment by SethTisue** [comment]
the rest of the build ran and there were also failures in sbt-io (which 9737 does fix), so I'll close this PR and open a followup after 9737 lands

**Comment by NthPortal** [comment]
it has landed

**Comment by SethTisue** [comment]
#1477

**Pull request closed without merging**
