### PR TITLE
newer scala-logging, newer scoverage, unfreeze Shapeless, unfork Scala.js

### PR DESCRIPTION
**Pull request by SethTisue**
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/587/consoleFull (404 til Jenkins catches up)

### CODE REVIEW

**Comment by SethTisue** [comment]
oh, I failed to notice there is some prior art on this in the config file, some of it commented out, some of it not. let's try removing it: https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/588/consoleFull

**Comment by SethTisue** [comment]
ok, so this thing from the comments where scoverage wants a `scala-logging-slf4j` artifact rather than a `scala-logging` artifact is still an issue. perhaps this will get mired in a cascade of upgrades, but let's try newer `scoverage` forked to have the right form of scala-logging dependency:
- ~~https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/589/consoleFull~~
- ~~https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/590/consoleFull~~
- ~~https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/591/consoleFull~~
- https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/592/consoleFull

**Comment by SethTisue** [comment]
among other reasons this knot may be worth untangling: the 2.12 community build doesn't currently track Shapeless master (attn @milessabin, [did you know](https://github.com/scala/community-builds/blob/eaf55abf80357196326add921b46f3181f401e74/common.conf#L74-L75) this?) because of an scoverage dependency. I've added a commit to this PR returning to Shapeless master. knock on wood

**Comment by dwijnand** [comment]
The scoverage upgrade has been underway over the last few days. See https://github.com/scoverage/scalac-scoverage-plugin/pull/177 and a few days worth of back and forth in the scoverage gitter room. Hopefully a release will be cut soon. Cats is also awaiting it.

**Comment by SethTisue** [comment]
thanks, I was not aware. I've subscribed to that ticket

**Comment by SethTisue** [comment]
omg it's green 🎉

**Comment by SethTisue** [comment]
squashed

**Comment by SethTisue** [comment]
fyi @analytically

**Pull request merged**
