### PR TITLE
add more of circe

### PR DESCRIPTION
**Pull request by SethTisue**
followup to #622, which added circe-core only

let's see how this goes... ran into trouble last time I tried it

### CODE REVIEW

**Comment by SethTisue** [comment]
test run: https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/2108/consoleFull

**Comment by travisbrown** [comment]
The jawn issue is likely to be incompatibilities between 0.10 and 0.11, I'd guess?

**Comment by SethTisue** [comment]
I'll probably have to set this aside for a while, but:

here's a test run to get the current error message on the record: https://scala-ci.typesafe.com/view/scala-2.13.x/job/scala-2.13.x-integrate-community-build/771/consoleFull

thanks Travis for the tip, I'll see whether I can use that information to work around it

**Comment by SethTisue** [comment]
error is

```
[circe] [error] /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.9/project-builds/circe-69f47d0c848cc166aa21e007b57906fee3756121/modules/jawn/src/main/scala/io/circe/jawn/CirceSupportParser.scala:22:56: ambiguous reference to overloaded definition,
[circe] [error] both method jstring of type (s: CharSequence)io.circe.Json
[circe] [error] and  method jstring in trait Facade of type (s: String)io.circe.Json
[circe] [error] match argument types (String) and expected result type io.circe.Json
[circe] [error]       final def add(s: CharSequence): Unit = { value = jstring(s.toString) }
[circe] [error]                                                        ^
```

**Comment by travisbrown** [comment]
I don't know enough about how the community builds work to be helpful here, but jawn 0.11 has a `jstring(s: CharSequence)` method and earlier versions have `jstring(s: String)`—there are no versions with both.

**Comment by SethTisue** [comment]
previously: #565

**Comment by SethTisue** [comment]
okay, let's try again with unfrozen jawn: https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/2117/consoleFull ~~(404 while Jenkins makes two lists of celebrities, the ones named “Marc” and the ones named “Mark”)~~

**Comment by SethTisue** [comment]
another try https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/2119/consoleFull

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/2120/consoleFull:

```
[info] >>> The dbuild result is------------: FAILED (failed: sjson-new, circe)
```

sjson-new depends on jawn 0.10, so that's why that's failing. we could try to push an upgrade to 0.11 through there (either on the mainline, or in a fork if necessary, e.g. if we run into sbt 1's bincompat guarantees)

splitting into two spaces wouldn't easily work, I think, because http4s has both circe and sjson-new somewhere in dbuild's view of its transitive dependencies:

```
[info] Project http4s------------------: DID NOT RUN (stuck on broken dependencies: circe, sjson-new)
```

normally sjson-new is just used in sbt/zinc stuff, but then sometimes a project depends on an sbt/zinc thing. in http4s's case perhaps sjson-new is getting pulled in for spurious or work-around-able reasons, e.g. because of a dependency on tut in a subproject we don't need, something like that.

**Comment by SethTisue** [comment]
the circe failure was

```[circe] Processing subproject: streaming
[circe] [error] **** Missing dependency: the library io.iteratee#iteratee-core is not provided (in space "default") by any project in this configuration file.
[circe] [error] In order to control which version is used, please add the corresponding project to the build file
[circe] [error] (or use "check-missing:false" to ignore (not recommended)).
```

but I see that the streaming module is actually got the axe entirely in a recent commit (circe/circe@70aec8d23dacaea9b0b3ec3846980a3b1fd6d3aa), so we can just pull it.

try again with that change (not worrying about the sjson-new stuff for now): https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/2122/consoleFull

**Comment by SethTisue** [comment]
```
[info] Project circe-------------------: SUCCESS (project rebuilt ok)
```

so just the sjson-new situation remains to be sorted out.

**Comment by dwijnand** [comment]
We have a pending PR in sjson-new where I'm scratching my head about whether it's a safe upgrade or not.. https://github.com/eed3si9n/sjson-new/pull/85.

**Comment by dwijnand** [comment]
The fact that jawn doesn't enforce its own binary API is concerning: https://github.com/non/jawn/pull/96.

**Comment by travisbrown** [comment]
@dwijnand What's the concerning part? The breakage in 0.11 was known and fully intentional, and was discussed in detail in various places. (It's also my fault—I talked @non into it probably against his better judgment.)

Personally, for most of my own pre-1.0 projects I have MiMa set up for my own reference, but don't have it reporting in CI, and am totally happy to break binary compatibility in pre-1.0 minor versions whenever I want.

**Comment by SethTisue** [comment]
@dwijnand thanks for letting me know about that sjson-new PR. let's a try a test run from that branch: https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/2126/consoleFull

**Comment by SethTisue** [comment]
sbt-librarymanagement needs coordinated changes:

```
[sbt-librarymanagement] [error] <https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/ws/target-0.9.9/project-builds/sbt-librarymanagement-0300fdf2585958be49e37b4a701a2e626d5ef53d/ivy/src/main/scala/sbt/internal/librarymanagement/IvyCache.scala>:133:9: object creation impossible, since:
[sbt-librarymanagement] [error] it has 2 unimplemented members.
[sbt-librarymanagement] [error] /** As seen from <$anon: jawn.MutableFacade[sjsonnew.shaded.scalajson.ast.unsafe.JValue]>, the missing signatures are as follows.
[sbt-librarymanagement] [error]  *  For convenience, these are usable as stub implementations.
[sbt-librarymanagement] [error]  */
[sbt-librarymanagement] [error]   def jnum(s: CharSequence,decIndex: Int,expIndex: Int): sjsonnew.shaded.scalajson.ast.unsafe.JValue = ???
[sbt-librarymanagement] [error]   def jstring(s: CharSequence): sjsonnew.shaded.scalajson.ast.unsafe.JValue = ???
[sbt-librarymanagement] [error]     new MutableFacade[JValue] {
[sbt-librarymanagement] [error]         ^
```

**Comment by dwijnand** [comment]
> @dwijnand What's the concerning part? The breakage in 0.11 was known and fully intentional, and was discussed in detail in various places. (It's also my fault—I talked @non into it probably against his better judgment.)
>
> Personally, for most of my own pre-1.0 projects I have MiMa set up for my own reference, but don't have it reporting in CI, and am totally happy to break binary compatibility in pre-1.0 minor versions whenever I want.

Sorry, all I meant is that without CI-enforced mima checking I fear there's a risk that (future, possible) 0.11.1 could be inadvertently binary incompatible with 0.11.

**Comment by SethTisue** [comment]
I have attempted to split the community build into three spaces: default, jawn_0_10, and jawn_0_11. 

I'm out of practice with this spaces stuff in dbuild (we got rid of the spec2 spaces split quite some time ago), so I probably won't get it right the first time, but let's see how it goes: https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/2132/consoleFull ~~(404 til Jenkins finishes pondering that Indy 500 racetrack core sample)~~

**Comment by SethTisue** [comment]
try again (I got the spaces stuff wrong for scala itself and its modules): https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/2134/consoleFull ~~(404 while Jenkins stares into his pannier’s mounting bracket as if it were a creature's eye)~~

**Comment by SethTisue** [comment]
`[info] >>> The dbuild result is------------: FAILED (failed: monix, sjson-new, http4s)`

that's not bad — this is probably close now. I'll look into the failures soon

**Comment by SethTisue** [comment]
The sjson-new failure is because I put it in the wrong space.

The monix failure isn't specific to this branch; should be fixed by freezing at a commit prior to the upgrade to cats 1.0.0-RC1 (we don't have cats that new yet, it's #624)

http4s is the tricky one. We're using a commit from August. The upgrade to jawn 0.11 is in http4s/http4s@9da3db2b1945d2ffb96f0f92946b09892e21da98. So we could try with that commit. (But also, we should keep in mind the possibility of just removing http4s from the build right now, and then bring it back as part of #624 once the Typelevel ecosystem has worked all these upgrades through.)

**Comment by SethTisue** [comment]
new run: https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/2139/consoleFull

**Comment by SethTisue** [comment]
ah, I'd forgotten to use the unforked sjson-new

and behold, https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/2140/console is green! I'll tidy up, then merge

**Pull request merged**
