### PR TITLE
Unfork spray-json

### PR DESCRIPTION
**Pull request by SethTisue**
fyi @ekrich @jodersky @jrudolph

### CODE REVIEW

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/4744/ (404 til Jenkins queue clears)

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/4748/ is green (enough), so we can merge this after we unfreeze the build, post-2.12.9

**Comment by SethTisue** [comment]
I went ahead and merged it as cdaedc77fa6135a84e6ff0317acc71969de028a8

**Comment by ekrich** [comment]
Looks like good progress was made but you are a fast gun.

**Pull request closed without merging**
