### PR TITLE
unfreeze blaze, add boopickle, fix http4s

### PR DESCRIPTION
**Pull request by SethTisue**
in an attempt to make http4s green again

/cc @rossabaker

### CODE REVIEW

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/3497/consoleFull (404 for now)

**Comment by SethTisue** [comment]
hmm

```
[http4s] [error] /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.14/project-builds/http4s-72bd2d938d1ead7a6e213448dca6510dc50f3370/blaze-core/src/main/scala/org/http4s/blazecore/Http1Stage.scala:222:5: not found: value sendOutboundCommand
[http4s] [error]     sendOutboundCommand(Command.Error(t))
[http4s] [error]     ^
```

the blaze dependency that http4s actually declares is on 0.14.0-M4

so let's try blaze's 0.14.0-M4 tag instead of HEAD

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/3499/consoleFull

**Comment by SethTisue** [comment]
blaze thing is sorted now, but:

```
[http4s] Processing subproject: boopickle
[http4s] [error] **** Missing dependency: the library io.suzaku#boopickle is not provided (in space "scala.main.jawn_0_11") by any project in this configuration file.
[http4s] [error] In order to control which version is used, please add the corresponding project to the build file
[http4s] [error] (or use "check-missing:false" to ignore (not recommended)).
[http4s] [error] java.lang.RuntimeException: Required dependency not found
```

I'm happy to try and add boopickle, but if I get bogged down, I'll just disable http4s's boopickle subproject.

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/3501/consoleFull

/cc @ochrons

**Comment by SethTisue** [comment]
forked boopickle and opened https://github.com/suzaku-io/boopickle/issues/104

https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/3505/consoleFull

**Comment by SethTisue** [comment]
haha how deep is this rabbithole

```
[http4s] Processing subproject: mimedb-generator
[http4s] [error] **** Missing dependency: the library com.eed3si9n#treehugger is not provided (in space "scala.main.jawn_0_11") by any project in this configuration file.
[http4s] [error] In order to control which version is used, please add the corresponding project to the build file
[http4s] [error] (or use "check-missing:false" to ignore (not recommended)).
[http4s] [error] java.lang.RuntimeException: Required dependency not found
```

it would be nice to add treehugger at some point, but I'd like to move on to other work, so I'll just disable the subproject

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/3507/consoleFull

**Comment by SethTisue** [comment]
now this is interesting:

```
[http4s] [error] /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.14/project-builds/http4s-490244c6ca1b1edb715b50c214535c78f76f8b32/tests/src/test/scala/org/http4s/UriSpec.scala:422:7: overloaded method value foreach with alternatives:
[http4s] [error]   [T](matcher: org.specs2.matcher.Matcher[T])org.specs2.matcher.ContainWithResult[T] <and>
[http4s] [error]   [T, R](values: Traversable[T])(f: T => R)(implicit evidence$3: org.specs2.execute.AsResult[R])org.specs2.matcher.MatchResult[Traversable[T]]
[http4s] [error]  cannot be applied to (Iterator[(String, String)])
[http4s] [error]       foreach(Uri(query = Query.empty).params.iterator) { i =>
[http4s] [error]       ^
```

**Comment by SethTisue** [comment]
oh, it's a specs2 version problem. looks like it stems from changes made in specs2 to cross-build for 2.13

the problem is reproducible in the http4s repo, outside dbuild, by doing:

```
-  lazy val specs2Core                       = "org.specs2"             %% "specs2-core"               % "4.1.0"
+  lazy val specs2Core                       = "org.specs2"             %% "specs2-core"               % "4.3.4"
```

let's try it with these changes in our fork: https://github.com/scalacommunitybuild/http4s/commit/d7a9cf7b06f069683e73327fed697245d4cad923

https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/3509/consoleFull

**Comment by SethTisue** [comment]
```
[info] Project http4s----------------------: SUCCESS (project rebuilt ok)
```

🎉

**Comment by SethTisue** [comment]
@rossabaker (you might consider upgrading your specs2 at some point)

**Comment by rossabaker** [comment]
We're pinned to the current specs2 because the latest upgraded to scalacheck-1.14 while cats-laws and cats-effect-laws stayed on 1.13, until Scala 2.13, which had to jump.  It's a terrible mess. There is a cats ticket about cross building against scalacheck, which I think is the only way out.

**Comment by SethTisue** [comment]
>  It's a terrible mess. 

DEPENDENCIES!!!!  (in “Wrath of Khan” voice)

**Comment by SethTisue** [comment]
oh my. https://github.com/typelevel/cats/pull/2312

**Pull request merged**
