### PR TITLE
add doodle

### PR DESCRIPTION
**Pull request by SethTisue**
fyi @noelwelsh @davegurnell

### CODE REVIEW

**Comment by SethTisue** [comment]
test run queued (404 for now, til Jenkins queue clears): https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/1542/consoleFull

**Comment by SethTisue** [comment]
```
[doodle] Processing subproject: doodleJVM
[doodle] [error] **** Missing dependency: the library org.typelevel#cats is not provided (in space "default") by any project in this configuration file.
[doodle] [error] In order to control which version is used, please add the corresponding project to the build file
```

which doesn't make sense, cats is certainly in the build. maybe the dependency needs to be changed from `cats` to `cats-core`. I may not have time to mess with it until after June 14

**Comment by SethTisue** [comment]
puzzled why https://github.com/SethTisue/doodle/commit/00829879c2ec5f170bd0554e70cc165b03de5a1a didn't fix it. https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/1551/consoleFull has:

```
[doodle] [error] /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.7-RC1/project-builds/doodle-a09822abe35a7c4a4c12bd5392f7b8be717b63a1/shared/src/main/scala/doodle/examples/BrownianMotion.scala:62: value sequenceU is not a member of List[doodle.random.Random[doodle.core.Image]]
[doodle] [error]       iter(steps, Random.always(start), shape).sequenceU.map { imgs =>
[doodle] [error]                                                ^
```

which I don't understand at all and haven't been able to reproduce outside of dbuild

**Comment by xuwei-k** [comment]
https://github.com/typelevel/cats/commit/01711b0063b7949de8a503b833777fafba6c3a9b#diff-dfc66c84b778099ad28a81e9b0ece505L119

**Comment by SethTisue** [comment]
hmm... I'll try https://github.com/SethTisue/community-builds/commit/c33257e08e20d9f4a0ac3134ea6506af5e083e87 (using cats/cats@ 669a0235)

thanks Kenji

**Comment by SethTisue** [comment]
ok so doodle is green now at https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/1554/consoleFull

and here's another run to make sure everything else is also still green with the older cats SHA: https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/1555/consoleFull

**Comment by SethTisue** [comment]
@davegurnell you're in the club

**Comment by noelwelsh** [comment]
Thanks!

**Comment by davegurnell** [comment]
Woo!

**Pull request merged**
