### PR TITLE
unfreeze akka-http and run tests

### PR DESCRIPTION
**Pull request by SethTisue**

### CODE REVIEW

**Comment by SethTisue** [comment]
queued: https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/4915/

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/4924/

**Comment by SethTisue** [comment]
fyi @patriknw

**Comment by patriknw** [comment]
thanks

**Pull request merged**
