### PR TITLE
2.13: new Scala SHA

### PR DESCRIPTION
**Pull request by SethTisue**
~https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/2359/~
https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/2363/

### CODE REVIEW

**Comment by SethTisue** [comment]
http4s failure isn't intermittent?! I should try to reproduce it outside dbuild, I guess

https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/2363/artifact/logs/http4s-build.log

```
[http4s] [error]   x return files included via symlink (25 ms)
[http4s] [error]    Chunk(47, ...) (FileServiceSpec.scala:145)
```

it's not easy to reproduce outside of dbuild because silencer-lib is fully-versioned, and it comes into the http4s build via an sbt plugin. which is a situation I not infrequently find myself in, so I should probably figure out how to override the version.

**Comment by SethTisue** [comment]
Well, shit. I managed to get http4s compiling on the 2.13.5 nightly here over at https://github.com/SethTisue/http4s/tree/seth-20210113, but then the error didn't happen.

Another path forward here could be to return to dbuild and bisect on Scala version to find the culprit PR, but that would be rather time consuming (in the sense of needing to wait for the runs to complete, not in the sense of consuming a lot of effort).

I'm also tempted just to exclude the test on the grounds that perhaps this isn't actually a Scala regression but just an overly sensitive test.

**Comment by SethTisue** [comment]
19 PRs, so it should be only 4 or 5 bisect steps. maybe I should just do it. I can `./narrow http4s`, of course

```
% git hist --first-parent 5273aaf ^0772f76
* 5273aafaf9 - (HEAD -> 2.13.x, origin/HEAD, origin/2.13.x) Merge pull request #9425 from chia7712/MINOR-9425 (3 days ago) <Lukas Rytz>
* 9bb659e62a - Merge pull request #9414 from joroKr21/subkinding (7 days ago) <Lukas Rytz>
* 05d9531697 - Merge pull request #9344 from som-snytt/issue/11894-wrap (7 days ago) <Dale Wijnand>
* 362dcb5383 - Merge pull request #9404 from joroKr21/prefix-direct (8 days ago) <Dale Wijnand>
* b04977538f - Merge pull request #9417 from joroKr21/hk-skolems (8 days ago) <Diego E. Alonso Blas>
* 2e79383245 - Merge pull request #9422 from lrytz/ijdef (8 days ago) <Lukas Rytz>
* 6cca2c07e8 - Merge pull request #9415 from SethTisue/sbt-1.4.6 (8 days ago) <Seth Tisue>
* 01fba66811 - Merge pull request #9416 from martijnhoekstra/bug12294 (9 days ago) <Lukas Rytz>
* 1851c5d637 - Merge pull request #9394 from scalacenter/tasty/support-3.0.0-M3 (3 weeks ago) <Dale Wijnand>
* 912b7865e7 - Merge pull request #9405 from joroKr21/overload-kind (3 weeks ago) <Lukas Rytz>
* 6d45b037b4 - Merge pull request #9397 from scalacenter/tasty/fix-cats-show (3 weeks ago) <Lukas Rytz>
* 4ef2d22868 - Merge pull request #9410 from NthPortal/NthPortal-patch-1 (3 weeks ago) <Dale Wijnand>
* da5fd59d2d - Merge pull request #9406 from joroKr21/repeated-singleton (3 weeks ago) <Dale Wijnand>
* 69a5b9fb2c - Merge pull request #9412 from som-snytt/tweak/repl-debug (3 weeks ago) <Seth Tisue>
* 98acd0f0fd - new TRAVIS_TOKEN (3 weeks ago) <Seth Tisue>
* f273450484 - Merge pull request #9411 from SethTisue/travis-ci-com (3 weeks ago) <Seth Tisue>
* 408da91e3d - Merge pull request #9402 from joroKr21/test/10272 (3 weeks ago) <Dale Wijnand>
* 1a250cb4c1 - Merge pull request #9407 from dwijnand/two-blankies (3 weeks ago) <Dale Wijnand>
* cc06c086ff - Merge pull request #9400 from joroKr21/kind-check (3 weeks ago) <Dale Wijnand>
* 193169fdb5 - Merge pull request #9391 from Marcono1234/marcono1234/https-links (3 weeks ago) <Dale Wijnand>
* 54eab984dc - Merge pull request #8949 from som-snytt/improve/8928 (3 weeks ago) <Dale Wijnand>
* 5d8ded9ede - Merge pull request #9337 from som-snytt/issue/array-equals-doc (3 weeks ago) <Dale Wijnand>
* 0f64691c95 - Merge pull request #9399 from som-snytt/tweak/tailcalls-enabled (3 weeks ago) <Lukas Rytz>
* 8067272d87 - Merge pull request #9395 from dotty-staging/dotty-release-3.0.0-M3 (3 weeks ago) <Dale Wijnand>
* 1a4fa666f5 - Merge pull request #9390 from SethTisue/sbt-1.4.5 (4 weeks ago) <Seth Tisue>
* 0fd5d84648 - Merge pull request #9396 from som-snytt/issue/10052 (4 weeks ago) <Lukas Rytz>
```

**Comment by SethTisue** [comment]
I'm going to merge this and if there end up being failures, I'll figure something out, maybe just exclude the test.

**Comment by SethTisue** [comment]
bisecting:

* bad 2.13.5-bin-5273aaf
* bad 2.13.5-bin-69a5b9f-SNAPSHOT https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/2380/
* bad 2.13.5-bin-193169f-SNAPSHOT https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/2381/
* bad 2.13.5-bin-8067272 https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/2382/
  * rebuild https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/2387/ queued
  * JARs https://scala-ci.typesafe.com/artifactory/scala-integration/org/scala-lang/scala-library/2.13.5-bin-8067272/
* good 2.13.5-bin-1a4fa66 https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/2385/
  * rebuild https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/2386/ queued
  * JARs https://scala-ci.typesafe.com/artifactory/scala-integration/org/scala-lang/scala-library/2.13.5-bin-1a4fa66/
* good 2.13.5-bin-0fd5d84 https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/2383/
* good 2.13.5-bin-0772f76 https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/2369/

I don't know why I used `-SNAPSHOT` initially, I dropped it once I realized. Not that it should matter.

**Comment by SethTisue** [comment]
the bisect points to https://github.com/scala/scala/pull/9395, which hardly seems plausible

```
curl -O -L 'https://scala-ci.typesafe.com/artifactory/scala-integration/org/scala-lang/scala-library/2.13.5-bin-1a4fa66/scala-library-2.13.5-bin-1a4fa66.jar'
curl -O -L 'https://scala-ci.typesafe.com/artifactory/scala-integration/org/scala-lang/scala-compiler/2.13.5-bin-1a4fa66/scala-compiler-2.13.5-bin-1a4fa66.jar'
curl -O -L 'https://scala-ci.typesafe.com/artifactory/scala-integration/org/scala-lang/scala-library/2.13.5-bin-8067272/scala-library-2.13.5-bin-8067272.jar' 
curl -O -L 'https://scala-ci.typesafe.com/artifactory/scala-integration/org/scala-lang/scala-compiler/2.13.5-bin-8067272/scala-compiler-2.13.5-bin-8067272.jar'
```

**Comment by SethTisue** [comment]
`jardiff` shows no differences in the compiler or library JARs other than timestamps and version numbers?!

**Comment by SethTisue** [comment]
I'm able to reproduce the failure locally. (I deleted an earlier comment that said I couldn't. Maybe I was on the wrong branch or something.)

**Comment by SethTisue** [comment]
We may need to consider outside-the-box explanations, like what else happened around Dec 21? We switched from travis-ci.org to travis-ci.com. I should check to see if 8067272 was the first release built in .com.

I could also compare _all_ of the files released, instead of just comparing the library and compiler JARs.

**Comment by griggt** [comment]
Completely random thought:

This wouldn't have anything to do with the auto-updating file headers (via some plugin?), e.g. 

```diff
--- a/server/src/test/scala/org/http4s/server/staticcontent/FileServiceSpec.scala
+++ b/server/src/test/scala/org/http4s/server/staticcontent/FileServiceSpec.scala
@@ -1,5 +1,5 @@
 /*
- * Copyright 2013-2020 http4s.org
+ * Copyright 2013-2021 http4s.org
  *
  * SPDX-License-Identifier: Apache-2.0
  */
```

Since it looks like the failing test checks the contents of that particular file, I wonder if for some reason one side of the check has the file before the header is updated and the other side is getting the updated version?

```
[http4s] [error]    Chunk(47, 42, 10, 32, 42, 32, 67, 111, 112, 121, 114, 105, 103, 104, 116, 32, 
                          50, 48, 49, 51, 45, 50, 48, 50, 48, 32,
                                                          ^^
                      this byte in particular would be 48 before the update and 49 after
```

No idea how this relates to the commit that bisect found, however...

**Comment by SethTisue** [comment]
@griggt that seems as plausible as any other wild hypothesis I've currently got. thanks, I'll look into it

**Comment by SethTisue** [comment]
I've pushed https://github.com/scalacommunitybuild/http4s/commit/6709de772946c5e2ac95f1faa60005502e1e25e5 and e13e569a0124576309400a3899d95ae94a173884, hopefully that does it. I did have a green run locally but this seems to be something of a Heisenbug, so time will tell.

I still don't understand why/how this _appeared_ to be Scala-version-dependent. 🤷

**Pull request merged**
