### PR TITLE
compile many more tests

### LINKED ISSUE #280: make sure we are compiling tests
even when we don't run them

in the run-up to 2.12 it happened at least twice that we missed out finding out about regressions because of this:
- scala-refactoring: https://github.com/scala/scala/pull/5388#issuecomment-246170392 (@Sciss)
- shapeless: https://github.com/scala/scala/pull/5394 (@milessabin)

### PR DESCRIPTION
**Pull request by SethTisue**
also: re-add scalariform
also: drop scala-refactoring until
  https://github.com/scala-ide/scala-refactoring/issues/168
  is addressed

fixes #280

### CODE REVIEW

**Comment by SethTisue** [comment]
test run: https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/817/consoleFull

**Comment by SethTisue** [comment]
fyi @milessabin, we are compiling Shapeless tests now. very very glad you called our attention to this.

we aren't _running_ Shapeless tests though, because `shapeless.CachedTest` failed — not sure if you want to investigate that? perhaps it will come up when you build for 2.12.0-RC2

**Comment by SethTisue** [comment]
scalikejdbc failed but I think it's farfetched that could be related to these changes (in fact, it looks like an intermittent failure I might have seen before). so, merging

**Comment by milessabin** [comment]
I'll take a look as soon as I have a 2.12.0-RC2 build of macro-paradise to work with. For shapeless being able to compile the tests is a much bigger hurdle than actually running them, so I'm not overly concerned that you're seeing a test failure ... I'll investigate ASAP.

**Pull request merged**
