### PR TITLE
various fixes (scalafix, twitter-util, jawn, http4s)

### PR DESCRIPTION
**Pull request by SethTisue**
trying to get scalafix and http4s green.
also seeing if we can enable more of sttp.

sequel to #786 

fyi @adamw @rossabaker @olafurpg @alexandru

### CODE REVIEW

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/3494/consoleFull

**Comment by SethTisue** [comment]
twitter-util green, scalafix green, jawn-0-11 green

```
[http4s] Processing subproject: blaze-core
...
[http4s] [error] /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.14/project-builds/http4s-16cf54f73637e8785f0e346206cfeaf67b573068/blaze-core/src/main/scala/org/http4s/blazecore/Http1Stage.scala:10:30: object parser is not a member of package org.http4s.blaze.http
[http4s] [error] import org.http4s.blaze.http.parser.BaseExceptions.ParserException
[http4s] [error]                              ^
```

```
[sttp] Processing subproject: monix
...
[sttp] [error] /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.14/project-builds/sttp-c40d23e4428ba1fa2c174fe4245a2b348c42b10b/implementations/monix/shared/src/main/scala/com/softwaremill/sttp/impl/monix/TaskMonadAsyncError.scala:18:19: missing parameter type
[sttp] [error]     Task.async { (_, cb) =>
[sttp] [error]                   ^
[sttp] [error] /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.14/project-builds/sttp-c40d23e4428ba1fa2c174fe4245a2b348c42b10b/implementations/monix/shared/src/main/scala/com/softwaremill/sttp/impl/monix/TaskMonadAsyncError.scala:18:22: missing parameter type
```

**Comment by SethTisue** [comment]
the sttp+monix part of this was just a would-be-nice, so I've dropped that part

http4s isn't green yet, but I'm going to merge this regardless since everything here is an improvement. I'll take up http4s in another PR

**Comment by adamw** [comment]
@SethTisue I can add the missing type annotation, though I'm not sure if that's the goal of the community build - apparently you are using a different Scala compiler version, so maybe it's good that it fails comparing to the current stable one?

**Comment by SethTisue** [comment]
@adamw we're on Scala 2.12.7-bin-1c56139. but here, the likelier cause isn't a Scala version difference, but rather a different version of one of your dependencies, probably monix itself — I see recent changes on monix's master branch that look plausibly related (e.g. monix/monix@0f44a168d1cfece16310abde3c36d4b6fa49cd53)

you currently have monix at `v3.0.0-RC1`. I suggest we do nothing until sometime after monix 3.0 final is released and you've upgraded sttp to use it. at that point I can try upgrading the entire community build to monix 3.0 and re-enabling sttp's monix subprojects.

(you might expect another possible course of action would be to freeze monix at v3.0.0-RC1 here, but I don't think that would work because our versions of monix's dependencies (e.g. cats-effect) are now too new)

there is an element of guesswork to all this, but verifying the guesses would be work. I'm comfortable just leaving this alone for the time being. the community build needs to be a huge pile of code, it isn't *too* important *exactly* what's in the pile

@alexandru (I was a bit surprised to see that several months have passed since 3.0.0-RC1. maybe it's time for an RC2? are you waiting for cats-effect to go 1.0 final?)

**Comment by alexandru** [comment]
> @alexandru (I was a bit surprised to see that several months have passed since 3.0.0-RC1. maybe it's time for an RC2? are you waiting for cats-effect to go 1.0 final?)

I was waiting for Cats-Effect 1.0.0 and now that it is here I'm working on improvements.

Yes, it is time for a RC2. It's not ready yet, but maybe I should just release what we have.

**Pull request merged**
