### PR TITLE
Run all Cats JVM projects

### PR DESCRIPTION
**Pull request by adelbertc**

### CODE REVIEW

**Comment by SethTisue** [comment]
isn't this just going to fail for lack of #13?

**Comment by adelbertc** [comment]
Yep. I saw https://github.com/scala/community-builds/pull/371 and incorrectly assumed everything is OK now.

**Comment by SethTisue** [comment]
care to rebase and try again now, after https://github.com/scala/community-builds/pull/448 ?

**Comment by adelbertc** [comment]
@SethTisue rebased

**Comment by SethTisue** [comment]
test run: https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/1148/consoleFull (404 til Jenkins finishes up some other work)

**Comment by SethTisue** [comment]
`[cats] These subprojects will be built: macrosJVM, kernelJVM, coreJVM, kernelLawsJVM, lawsJVM, testsJVM, jvm, freeJVM, docs, bench, catsJVM` — we'll need to use `extra.exclude` to exclude `docs` and `bench`

**Comment by SethTisue** [comment]
yeah, we don't have `tut`:

```text
[cats] Processing subproject: docs
[cats] [error] **** Missing dependency: the library org.tpolecat#tut-core is not provided (in space "default") by any project in this configuration file.
[cats] [error] In order to control which version is used, please add the corresponding project to the build file
[cats] [error] (or use "check-missing:false" to ignore (not recommended)).
[cats] java.lang.RuntimeException: Required dependency not found
```

as for `bench`, not sure if it actually errors, but in general in the community build we prefer to leave benchmarks out

**Comment by SethTisue** [comment]
new test run: https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/1151/consoleFull (404 til Jenkins finishes polishing Eric Torreborre's silver)

**Comment by SethTisue** [comment]
hmm

```
[cats] [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[cats] [warn] 	::          UNRESOLVED DEPENDENCIES         ::
[cats] [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[cats] [warn] 	:: org.typelevel#cats-bench;0.9.0-dbuildx1e6079055102c537004201ab8985305c310a2e5c: not found
[cats] [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
```

normally excluding a subproject doesn't do this. not sure if it's dbuild's fault, or it's something weird about the cats build. 

I'll fiddle with it

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/1153/consoleFull

**Comment by dwijnand** [comment]
It's possible it didn't work because the dependency on bench is defined as `bench % "compile-internal;test-internal -> test"`.

/cc @cunei who:
* might be interested, and/or
* might know already about this/knows that it's true, and/or
* might know how to make it work the way you want it to work.

**Pull request merged**
