### PR TITLE
fix pfps-shopping-cart by pulling in refined fix

### PR DESCRIPTION
**Pull request by SethTisue**

### CODE REVIEW

**Comment by SethTisue** [comment]
testing @fthomas's https://github.com/fthomas/refined/issues/260 — I merged it into my fork. if that fixes it, I can do the same in the scalacommunitybuild fork

queued: https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/3082/

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/3084/artifact/logs/pfps-shopping-cart-build.log

```
[pfps-shopping-cart] [error] /home/jenkins/workspace/scala-2.13.x-integrate-community-build/target-0.9.16/project-builds/pfps-shopping-cart-359d75fbe365d5b50eb7a18f3c940aa138be2db4/modules/core/src/main/scala/shop/domain/package.scala:15:21: value repr is not a member of type parameter B
[pfps-shopping-cart] [error]         Eq[A].eqv(x.repr.asInstanceOf[A], y.repr.asInstanceOf[A])
[pfps-shopping-cart] [error]                     ^
```

I'll try an older commit

**Comment by SethTisue** [comment]
@gvolpe can you tell from the error why this isn't working? might I need to use a different version of some dependency? or, is there some older commit of pfps-shopping-cart itself I should try rewinding to?

I tried, arbitrarily, gvolpe/pfps-shopping-cart@67f4aa9c72d83db8109b1fb009221e9a4912f7b9 but it seemed to want an older cats-retry than what we have, so that's too old. and I also tried gvolpe/pfps-shopping-cart@f6ac99b634e43824d81ea0092a3028707ac9fc81 but that gave the same `.repr` errors)

(note that it wouldn't be the end of the world if we had to pull pfps-shopping-cart from the build. it's a nice-to-have, but we shouldn't sink too much time into keeping it. sometimes projects that sit on top of a rapidly evolving tree of dependencies are just too much trouble)

**Comment by gvolpe** [comment]
Hi @SethTisue , that `.repr` comes from the `newtype` library. There needs to be the following import in scope:

```scala
import io.estatico.newtype.ops._
```

It is in that `package object domain` in `master`. Are you building `master`? 

Also, is `newtype-0.4.3` part of the community build? It uses macros and it requires the following flag for Scala 2.13.x:

```scala
scalacOptions += "-Ymacro-annotations"
```

> (note that it wouldn't be the end of the world if we had to pull pfps-shopping-cart from the build. it's a nice-to-have, but we shouldn't sink too much time into keeping it. sometimes projects that sit on top of a rapidly evolving tree of dependencies are just too much trouble)

No problems, I really appreciate the effort. Happy to help with whatever comes up if I can :)

**Comment by SethTisue** [comment]
> Also, is newtype-0.4.3 part of the community build?

yes, but we were building a newer commit; using their `v0.4.3` tag instead seems to have fixed it

in local testing anyway; let's do a Jenkins run to be sure something doesn't break somewhere else.

queued: https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/3087/

**Comment by gvolpe** [comment]
Awesome! Anyway, I'll have a look at `newtype@master` to see what's changed :thinking:

**Pull request merged**
