### PR TITLE
add Breeze and Spire back in, and add Algebra

### PR DESCRIPTION
**Pull request by SethTisue**
the necessary work in the Spire repo appears to have happened

### CODE REVIEW

**Comment by SethTisue** [comment]
test run (against 2.12.1): ~~https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/1165/console~~ https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/1166/consoleFull

note that I optimistically re-enabled Spire's tests, we'll see how that goes

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/1168/consoleFull (404 while Jenkins practices juggling silk scarves with his eyes closed)

**Comment by SethTisue** [comment]
fyi @dlwh @tixxit @non @johnynek

@dlwh note breeze tests are still disabled as per https://github.com/scalanlp/breeze/issues/587, I could re-enable them if you have reason to believe the situation has changed

**Comment by johnynek** [comment]
+1 thanks!

**Pull request merged**
