### PR TITLE
move tags for sbt & modules to 1.2.1

### PR DESCRIPTION
**Pull request by SethTisue**
not all modules have a 1.2.1 tag. see sbt/sbt@a1d1c773113

### CODE REVIEW

**Comment by SethTisue** [comment]
/cc @eed3si9n

test run: 
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/3273/ (404 for now)

**Comment by SethTisue** [comment]
@eed3si9n looks like these tags don't exist, can you create them, please?

**Comment by eed3si9n** [comment]
Done:
- https://github.com/sbt/zinc/releases/tag/v1.2.1
- https://github.com/sbt/io/releases/tag/v1.2.1

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/3284/ (404 til queue clears)

**Comment by SethTisue** [comment]
@eed3si9n what do you make of

```
[sbt] [error] /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.14/extraction/8fc1b013997597617fb1fbfe853e34340b4c14c2/projects/2d467e9f68636ba62d9ae70c3ca0b1da62ec45fb/project/Scripted.scala:8:12: object ScriptedPlugin is not a member of package sbt
[sbt] [error] import sbt.ScriptedPlugin.autoImport._
[sbt] [error]            ^
[sbt] [error] one error found
[sbt] [error] (Compile / compileIncremental) Compilation failed
[sbt] Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? 
```

```
[zinc:error] /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.14/extraction/8fc1b013997597617fb1fbfe853e34340b4c14c2/projects/a6abec59b857a8cd6302c7a382c6519a3bb20b46/build.sbt:605: error: not found: value scriptedBufferLog
[zinc:error]   scriptedBufferLog := true,
[zinc:error]   ^
[zinc:error] /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.14/extraction/8fc1b013997597617fb1fbfe853e34340b4c14c2/projects/a6abec59b857a8cd6302c7a382c6519a3bb20b46/build.sbt:607: error: not found: value scripted
[zinc:error]   scripted := scriptedTask.evaluated,
[zinc:error]   ^
[zinc:error] /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.14/extraction/8fc1b013997597617fb1fbfe853e34340b4c14c2/projects/a6abec59b857a8cd6302c7a382c6519a3bb20b46/build.sbt:628: error: not found: value scriptedBufferLog
[zinc:error]     scriptedBufferLog.value,
[zinc:error]     ^
[zinc:error] /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.14/extraction/8fc1b013997597617fb1fbfe853e34340b4c14c2/projects/a6abec59b857a8cd6302c7a382c6519a3bb20b46/build.sbt:660: error: not found: value scriptedBufferLog
[zinc:error]     scriptedBufferLog.value,
[zinc:error]     ^
```

**Comment by xuwei-k** [comment]
https://github.com/scala/community-builds/blob/74107db400fee05bd608aeb9fa71fd4e0c6818db/configs/community.dbuild#L1960

```diff
    uri:  ${vars.uris.sbt-uri}
-   extra.sbt-version: ${vars.sbt-1-1-version}
+   extra.sbt-version: ${vars.sbt-1-2-version}
    extra.options: [
```

- https://github.com/sbt/sbt/blob/v1.2.1/project/build.properties
- https://github.com/sbt/sbt/blob/v1.2.0/project/build.properties

**Comment by SethTisue** [comment]
hmm looks like I did a bad merge or something and the state of this branch had become confused. rebased.

new test run: 
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/3306/ (404 for now)

**Comment by SethTisue** [comment]
oh, right @xuwei-k, looks like we need to use 1.2.0 to build 1.2.1, neither 1.1.6 nor 1.2.1 works

let's try

```diff
--- a/configs/community.dbuild
+++ b/configs/community.dbuild
@@ -1929,7 +1929,7 @@ build += {
   ${vars.base} {
     name: "zinc"
     uri:  ${vars.uris.zinc-uri}
-    extra.sbt-version: ${vars.sbt-1-1-version}
+    extra.sbt-version: "1.2.0"  // yup, 1.2.1 is built with 1.2.0
     extra.exclude: [
       "zincBenchmarks"
       // has circular dependency on sbt repo
@@ -1955,7 +1955,7 @@ build += {
   ${vars.base} {
     name: "sbt"
     uri:  ${vars.uris.sbt-uri}
-    extra.sbt-version: ${vars.sbt-1-1-version}
+    extra.sbt-version: "1.2.0"  // yup, 1.2.1 is built with 1.2.0
     extra.options: [
       "-Xmx2048m"
       "-Dbintray.user=dummy", "-Dbintray.pass=dummy"
```

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/3312/

**Pull request merged**
