### PR TITLE
re-enable some zinc tests

### PR DESCRIPTION
**Pull request by SethTisue**
references https://github.com/sbt/zinc/issues/485

/cc @jvican

### CODE REVIEW

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/3386/ (404 for now)

**Comment by SethTisue** [comment]
same errors, so I've reopened https://github.com/sbt/zinc/issues/485

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/3402/

**Comment by jvican** [comment]
`publishBridges` is a command: https://github.com/sbt/zinc/blob/develop/build.sbt#L801-L813 , mentioning because dbuild seems to think it's a task.
  
In case it's useful, these are the commands run in the Drone CI so that everything works https://github.com/sbt/zinc/blob/develop/bin/run-ci.sh

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/3409/

**Comment by SethTisue** [comment]
it's a bit different in `v1.2.1`:

```
[zinc] [error] Not a valid key: publishBridges (similar: publishSigned, publisher, publish)
[zinc] [error] publishBridges
[zinc] [error]               ^
```

looking at `bin/run-ci.sh` at that tag, looks like it's `publishBridgesAndSet`

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/3434/ (404 for now)

**Comment by SethTisue** [comment]
@jvican not sure what to make of this:

```
[zinc] [info] Non-compiled module 'compiler-bridge_2.10' for Scala 2.12.7-bin-38282c7. Compiling...
[zinc:error] /var/folders/j1/sv5gcszx0tn0t_q5xr58v1q40000gn/T/sbt_b47f4bdf/xsbt/Compat.scala:130: error: not found: type MacroExpansionAttachment
[zinc:error]   implicit class MacroExpansionAttachmentCompat(self: MacroExpansionAttachment) {
[zinc:error]                                                       ^
[zinc:error] one error found
```

**Comment by jvican** [comment]
This is probably happening because dbuild is forcing the scala version and doesn't respect `+`. My advice is that you use latest master (now called `develop` branch) and add that to the dbuild instead as the build has changed for the better.
  
Once you've done that, following what `bin/run-ci.sh` does and disabling all the modules whose name end with `211` and `210` will make the build work.

**Comment by SethTisue** [comment]
thanks. I'll give it a try.

**Comment by jvican** [comment]
@SethTisue Let me know if you need more help, I'm now back from vacation.

**Comment by SethTisue** [comment]
@jvican @eed3si9n @cunei this is detailed enough work that I'm kinda hoping you guys could take the lead on it. I'm available to help with the community build specific side, of course. like if you submitted a revised PR, I'd try to help you get it across the finish line? from the Scala team's perspective, zinc and sbt are leaf projects and using the latest versions probably really isn't helping us test scalac.

apologetically,
Seth

**Comment by SethTisue** [comment]
(I'm around now through December 7, after that I'm out til January)

**Comment by SethTisue** [comment]
closing since it doesn't seem to be a priority. happy to revisit if there's interest

**Pull request closed without merging**
