### PR TITLE
enable more zinc tests

### PR DESCRIPTION
**Pull request by SethTisue**
@dwijnand thought this was probably worthwhile. let's at least look at it and see what it might take

https://scala-ci.typesafe.com/job/scala-2.13.x-jdk8-integrate-community-build/3855/

### CODE REVIEW

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/job/scala-2.13.x-jdk8-integrate-community-build/3855/consoleFull

```
[zinc] Processing subproject: compilerBridgeTest
...
[zinc] [error] /home/jenkins/workspace/scala-2.13.x-jdk8-integrate-community-build/target-0.9.17/project-builds/zinc-e7f6e8b93b1e49c07727e179ccb81d2b8eba33c5/internal/compiler-bridge-test/src/test/scala/sbt/internal/inc/CompilingSpecification.scala:72:34: type mismatch;
[zinc] [error]  found   : scala.collection.mutable.ArrayBuffer[(String, String)]
[zinc] [error]  required: Seq[(String, String)]
[zinc] [error]       binaryDependencies.collect { case (_, bin, src, DependencyByMemberRef)        => src -> bin },
[zinc] [error]                                  ^
```

**Comment by dwijnand** [comment]
Seq vs Seq issue 🥱

**Comment by SethTisue** [comment]
closing for now, with "revisit" label

**Comment by dwijnand** [comment]
We noticed that the failure was in a compiler-bridge-test.  If just enabling the zinc tests pass, that would be well worth landing.

**Comment by dwijnand** [comment]
Oh, and compiler-bridge-test doesn't build on 2.13 (in sbt/zinc).

**Comment by SethTisue** [comment]
rebased, and re-excluded `compilerBridgeTest`. let's see what fails now:

https://scala-ci.typesafe.com/job/scala-2.13.x-jdk8-integrate-community-build/3916/

**Comment by SethTisue** [comment]
```
[zinc] [error] Failed tests:
[zinc] [error] 	sbt.inc.MultiProjectIncrementalSpec
[zinc] [error] 	sbt.inc.NameHashingCompilerSpec
[zinc] [error] 	sbt.inc.ClasspathHashingHookSpec
[zinc] [error] 	sbt.inc.IncrementalCompilerSpec
[zinc] [error] 	sbt.inc.OutputSpec
[zinc] [error] 	sbt.inc.BinaryDepSpec
[zinc] [error] 	sbt.inc.NestedJavaClassSpec
[zinc] [error] 	sbt.inc.ClassFileManagerHookSpec
```

**Comment by dwijnand** [comment]
Those all failed with:

```
[zinc] [error] Test suite sbt.inc.MultiProjectIncrementalSpec failed with java.lang.ClassNotFoundException: xsbt.CompilerInterface.
[zinc] [error] This may be due to the ClassLoaderLayeringStrategy (Flat) used by your task.
[zinc] [error] To improve performance and reduce memory, sbt attempts to cache the class loaders used to load the project dependencies.
[zinc] [error] The project class files are loaded in a separate class loader that is created for each test run.
[zinc] [error] The test class loader accesses the project dependency classes using the cached project dependency classloader.
[zinc] [error] With this approach, class loading may fail under the following conditions:
[zinc] [error] 
[zinc] [error]  * Dependencies use reflection to access classes in your project's classpath.
[zinc] [error]    Java serialization/deserialization may cause this.
[zinc] [error]  * An open package is accessed across layers. If the project's classes access or extend
[zinc] [error]    jvm package private classes defined in a project dependency, it may cause an IllegalAccessError
[zinc] [error]    because the jvm enforces package private at the classloader level.
[zinc] [error] 
[zinc] [error] These issues, along with others that were not enumerated above, may be resolved by changing the class loader layering strategy.
[zinc] [error] The Flat and ScalaLibrary strategies bundle the full project classpath in the same class loader.
[zinc] [error] To use one of these strategies, set the  ClassLoaderLayeringStrategy key
[zinc] [error] in your configuration, for example:
[zinc] [error] 
[zinc] [error] set zincJVM2_13 / Test / classLoaderLayeringStrategy := ClassLoaderLayeringStrategy.ScalaLibrary
[zinc] [error] set zincJVM2_13 / Test / classLoaderLayeringStrategy := ClassLoaderLayeringStrategy.Flat
[zinc] [error] 
[zinc] [error] See ClassLoaderLayeringStrategy.scala for the full list of options.
```

Is that something you've handled before in the CB?  Otherwise I think this might be too hard to be worth it...

**Comment by SethTisue** [comment]
> Is that something you've handled before in the CB?

not really

(the only times I can recall encountering `classLoaderLayeringStrategy` stuff here before, it was because we were trying to use a too-new sbt version, but that's not the case here)

**Comment by SethTisue** [comment]
closing for inactivity. in ebfe6cbf1346bfc117dd8db1feac2aca23ed86a4 I left a breadcrumb in `zinc.conf` in case we ever decide to return to this

**Pull request closed without merging**
