### PR TITLE
add mdoc

### PR DESCRIPTION
**Pull request by SethTisue**

### CODE REVIEW

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/3973/ (404 til Jenkins queue clears)

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/3982/

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/3989/

**Comment by SethTisue** [comment]
```
[mdoc] [error] /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.16/project-builds/mdoc-35732b6825b5d1573551ed7c5979160f97724fee/mdoc-lsp/src/main/scala/mdoc/internal/lsp/LspLogger.scala:35:67: type mismatch;
[mdoc] [error]  found   : scribe.output.LogOutput
[mdoc] [error]  required: String
[mdoc] [error]       client.logMessage(new MessageParams(MessageType.Log, record.message))
[mdoc] [error]                                                                   ^
[mdoc] [error] one error found
[mdoc] [error] (lsp / Compile / compileIncremental) Compilation failed
```

it isn't obvious to me what this is about. @olafurpg ?

**Comment by olafurpg** [comment]
@SethTisue please exclude the `lsp` module from the community build, it's an undocumented and untested module.

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/3998/

**Comment by SethTisue** [comment]
~~https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/4000/~~
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/4003/

**Pull request merged**
