### PR TITLE
add scalafmt

### PR DESCRIPTION
**Pull request by SethTisue**

### CODE REVIEW

**Comment by SethTisue** [comment]
this can be rebased once #535 is merged

**Comment by SethTisue** [comment]
hey @olafurpg I'm getting this:

```
[scalafmt] [error] /Users/tisue/community-builds.212/target-0.9.7/project-builds/scalafmt-864ced34186e7d2b7c9bcdc3078e074d7e1e8f1e/core/src/main/scala/org/scalafmt/Error.scala:1: both org.scalamacros.paradise.typechecker.AnalyzerPlugins$MacroPlugin$@492d8c60 and org.scalameta.paradise.typechecker.AnalyzerPlugins$MacroPlugin$@53093c67 want to enter a symbol for this tree
[scalafmt] [error] package org.scalafmt
[scalafmt] [error]             ^
[scalafmt] scala.reflect.internal.Types$TypeError: both org.scalamacros.paradise.typechecker.AnalyzerPlugins$MacroPlugin$@492d8c60 and org.scalameta.paradise.typechecker.AnalyzerPlugins$MacroPlugin$@53093c67 want to enter a symbol for this tree
```

looks like somehow org.scalamacros#paradise and org.scalameta#paradise are both getting pulled in

**Comment by SethTisue** [comment]
```
[scalafmt] The following subprojects will be built in project scalafmt: utils, testUtils, core, cli, readme, benchmarks, scalafmtSbt, root
...
[info] Project scalafmt
[info]   depends on: acyclic, fastparse, kind-projector, macro-compat, macro-paradise, meta-paradise, metaconfig, pcplod, scala, scala-js, scala-parser-combinators, scalacheck, scalameta, scalapb, scalapb-lenses, scalariform, scalatags, scalatest, scalatex, scalaz, scopt, shapeless, sourcecode, specs2, utest
```

maybe we could try building only `core`

**Comment by SethTisue** [comment]
@olafurpg I do recall that you were previously skeptical about having scalafix in the community build (https://github.com/scala/community-builds/issues/499#issuecomment-287307613), probably those same concerns about evolution and fragility apply here too

**Comment by SethTisue** [comment]
```
[scalafmt] The following subprojects will be built in project scalafmt: utils, testUtils, core, cli, readme, benchmarks, scalafmtSbt, root
...
[info] Project scalafmt
[info]   depends on: acyclic, fastparse, kind-projector, macro-compat, macro-paradise, meta-paradise, metaconfig, pcplod, scala, scala-js, scala-parser-combinators, scalacheck, scalameta, scalapb, scalapb-lenses, scalariform, scalatags, scalatest, scalatex, scalaz, scopt, shapeless, sourcecode, specs2, utest
```

I tried building only `core`, but that didn't make the error go away

**Comment by SethTisue** [comment]
arggghhh, I think I used olafurpg/scalafmt when I should have used scalameta/scalafmt. let me fix that and see whether that helps...

**Comment by SethTisue** [comment]
sigh, now I get `[scalafmt] [error] **** Missing dependency: the library com.geirsson#metaconfig-typesafe-config is not provided (in space "default") by any project in this configuration file.`

but then if I try add to add `metaconfig-typesafe-config` to the metaconfig entry, I get

```
[metaconfig] [error] /Users/tisue/community-builds.212/target-0.9.7/project-builds/metaconfig-8e797a3467b5923cfd14ceefd02aa3f26e32123d/metaconfig-typesafe-config/src/main/scala/metaconfig/typesafeconfig/package.scala:11: value toFile is not a member of scala.meta.io.AbsolutePath
[metaconfig] [error]  Note: implicit value typesafeConfigMetaconfigParser is not applicable here because it comes after the application point and it lacks an explicit result type
[metaconfig] [error] /Users/tisue/community-builds.212/target-0.9.7/project-builds/metaconfig-8e797a3467b5923cfd14ceefd02aa3f26e32123d/metaconfig-typesafe-config/src/main/scala/metaconfig/typesafeconfig/package.scala:11: value toFile is not a member of scala.meta.io.AbsolutePath
[metaconfig] [error]  Note: implicit value typesafeConfigMetaconfigParser is not applicable here because it comes after the application point and it lacks an explicit result type
[metaconfig] [error]         TypesafeConfig2Class.gimmeConfFromFile(path.toFile)
[metaconfig] [error]         TypesafeConfig2Class.gimmeConfFromFile(path.toFile)
[metaconfig] [error]                                                     ^
[metaconfig] [error]                                                     ^
[metaconfig] [error] one error found
[metaconfig] [error] (metaconfig-typesafe-config/compile:doc) Scaladoc generation failed
[metaconfig] [error] (metaconfig-typesafe-config/compile:compileIncremental) Compilation failed
```

@olafurpg this looks might it might be easily resolvable by ~~having metaconfig use~~ having the community build use a newer scalameta? and/or, how's that plan for scalafmt to abandon its metaconfig dependency coming...?

**Comment by SethTisue** [comment]
test run w/ newer fork of scalameta: https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/1701/consoleFull

**Comment by SethTisue** [comment]
test run w/ newer fork of scalameta: https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/1702/consoleFull

**Comment by SethTisue** [comment]
with a newer scalameta,

```
[info] Project metaconfig--------------: SUCCESS (project rebuilt ok)
```

but then we also need a newer scalafix, and meta-paradise doesn't compile

**Comment by SethTisue** [comment]
it looks like this is doomed because scalafmt wants scalameta 1.7 but scalafix wants 2.0 and there are definite source incompatibilities

or rather, doomed unless we use dbuild's spaces feature to keep this stuff separate

which might not be very hard actually. nothing down near the dependency trunk uses meta, just leaves or near-leaves, so splitting is okay

**Comment by olafurpg** [comment]
Scalafmt will likely be stuck on scalameta 1.7 for a while. The complications are caused by its dependency on scalameta/paradise, which we plan to sunset in favor of scalamacros/scalamacros soon. I think it's best to keep scalafmt out of the CB for now until the new macro annotations stabilize. 

FWIW, scalafix recently dropped its dependency on scalameta/paradise macro annotations.

**Comment by SethTisue** [comment]
having refreshed my memory of how dbuild spaces work in order to accommodate the jawn 0.10/0.11 split, I'm (again) interested in revisiting this. scalafmt is core to the ecosystem, so I'd like to get it in if at all possible.

**Comment by olafurpg** [comment]
Heads up, scalafmt depends on an old version of scalameta (1.7) that is incompatible with scalameta 2.1 which scalafix depends on. I really wish this wasn't the case, but I'm afraid scalafmt v1.x is stuck on scalameta 1.x for the upcoming future unless I'm able to dedicate some work hours to do the fairly painful upgrade.

**Comment by SethTisue** [comment]
> Heads up, scalafmt depends on an old version of scalameta (1.7) that is incompatible with scalameta 2.1 which scalafix depends on

yeah I think I can build both versions of scalameta and keep them separate using dbuild's spaces feature. I think it's worth a try, anyway.

**Comment by SethTisue** [comment]
if/when I tackle this I'll start over with a new PR

**Comment by SethTisue** [comment]
new round of wip on this at https://github.com/sethtisue/community-builds/tree/add-scalafmt-spaces

**Pull request closed without merging**
