### PR TITLE
add Lagom sample apps

### PR DESCRIPTION
**Pull request by SethTisue**
references #846

### CODE REVIEW

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/4184/

**Comment by SethTisue** [comment]
```
[error] Fatal: multiple projects have the same artifacts visible in the same space.
[error] 
[error]   com.example#shopping-cart  from shopping-cart-java and shopping-cart-scala, both visible in space "scala.main"
[error]   com.example#lagom-internal-meta-project-service-locator  from shopping-cart-java and shopping-cart-scala, both visible in space "scala.main"
[error]   com.example#lagom-internal-meta-project-cassandra  from shopping-cart-java and shopping-cart-scala, both visible in space "scala.main"
[error]   com.example#shopping-cart-impl  from shopping-cart-java and shopping-cart-scala, both visible in space "scala.main"
[error]   com.example#shopping-cart-api  from shopping-cart-java and shopping-cart-scala, both visible in space "scala.main"
[error]   com.example#inventory-impl  from shopping-cart-java and shopping-cart-scala, both visible in space "scala.main"
[error]   com.example#lagom-internal-meta-project-kafka  from shopping-cart-java and shopping-cart-scala, both visible in space "scala.main"
[error]   com.example#inventory-api  from shopping-cart-java and shopping-cart-scala, both visible in space "scala.main"
An exception occurred.
```

I could confine these to their own spaces, but since nothing is going to depend on them, it might be cleaner to tell dbuild not to publish anything from either

**Comment by SethTisue** [comment]
> it might be cleaner to tell dbuild not to publish anything from either

I don't know how to do that, and my attempts to change `organization` via `extra.settings` or `extra.commands` didn't work either, I think these are applied too late to affect extraction

I guess I'll have to do spaces. it's fine

**Comment by SethTisue** [comment]
queued: https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/4186/

**Comment by SethTisue** [comment]
gah

```
[shopping-cart-java] [error] References to undefined settings: 
[shopping-cart-java] [error] 
[shopping-cart-java] [error]   lagom-internal-meta-project-cassandra / scalaModuleInfo from lagom-internal-meta-project-cassandra / scalaModuleInfo
[shopping-cart-java] [error]      Did you mean lagom-internal-meta-project-cassandra / updateSbtClassifiers / scalaModuleInfo ?
[shopping-cart-java] [error] 
[shopping-cart-java] [error]   lagom-internal-meta-project-kafka / scalaModuleInfo from lagom-internal-meta-project-kafka / scalaModuleInfo
[shopping-cart-java] [error]      Did you mean lagom-internal-meta-project-kafka / updateSbtClassifiers / scalaModuleInfo ?
[shopping-cart-java] [error] 
[shopping-cart-java] [error]   lagom-internal-meta-project-service-locator / scalaModuleInfo from lagom-internal-meta-project-service-locator / scalaModuleInfo
[shopping-cart-java] [error]      Did you mean lagom-internal-meta-project-service-locator / updateSbtClassifiers / scalaModuleInfo ?
[shopping-cart-java] [error]  
[shopping-cart-java] [error] 	at sbt.internal.util.Init.Uninitialized(Settings.scala:360)
[shopping-cart-java] [error] 	at sbt.internal.util.Init.Uninitialized$(Settings.scala:347)
[shopping-cart-java] [error] 	at sbt.Def$.Uninitialized(Def.scala:20)
```

wtf

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/4194/

**Comment by SethTisue** [comment]
last attempt ran afoul of unrelated breakage. rebased, try again:

https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/4227/

**Comment by SethTisue** [comment]
same "References to undefined settings" errors

**Comment by dwijnand** [comment]
Those repos are now in lagom/lagom-samples

**Comment by SethTisue** [comment]
let's start over in a new PR

**Comment by SethTisue** [comment]
#950

**Pull request closed without merging**
