### PR TITLE
2.13: advance Scala SHA and fix akka-stream

### PR DESCRIPTION
**Pull request by SethTisue**
references https://github.com/scala/scala-dev/issues/660  cc @som-snytt

### CODE REVIEW

**Comment by SethTisue** [comment]
queued: https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/2919/

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/2919/artifact/logs/scala-xml-build.log

```
[scala-xml] [error] Test scala.xml.CompilerErrors.t7185 failed: assertion failed: overloaded method apply with alternatives:
[scala-xml] [error]   (f: scala.xml.Node => Boolean)scala.xml.NodeSeq <and>
[scala-xml] [error]   (i: Int)scala.xml.Node
[scala-xml] [error]  cannot be applied to (), took 0.156 sec
[scala-xml] [error] Failed: Total 200, Failed 1, Errors 0, Passed 199
[scala-xml] [error] Failed tests:
[scala-xml] [error] 	scala.xml.CompilerErrors
[scala-xml] [error] (xml / Test / test) sbt.TestsFailedException: Tests unsuccessful
```

@ashawley can you make sense of this?

**Comment by SethTisue** [comment]
The scala-xml problem is reproducible outside dbuild with `++2.13.2-bin-079713c` followed by `xml/test`

my secret intellectual & magical powers (shhhhh, don't tell, but I don't actually have those — I have something better, I have `git bisect`) located the culprit Scala PR: scala/scala#8592

so, just a very sensitive test, it seems.

to keep this PR focused, I'll just use a slightly older Scala SHA and worry about scala-xml later, unless @ashawley worries about it first ;-)

queued: https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/2928/

**Comment by som-snytt** [comment]
@SethTisue I did mention on that PR that it may change someone's life, I didn't say for the better.

**Comment by SethTisue** [comment]
like sands through the hourglass, so are the

2016-0824-DAYS-AboutImage-1920x1080-KO

**Comment by SethTisue** [comment]
@dwijnand I merged this even though Lagom is failing (for the same reason akka-stream was failing); see https://github.com/lagom/lagom/issues/2579

**Pull request merged**
