### PR TITLE
use sbt.classloader.close to avoid NoClassDefFoundError

### PR DESCRIPTION
**Pull request by SethTisue**
as suggested by @eatkins at
https://github.com/scala/community-builds/issues/966#issuecomment-523635824

### CODE REVIEW

**Comment by SethTisue** [comment]
~~https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/4928/~~
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/4929/

**Comment by smarter** [comment]
... but what does that option do, and why would be it be necessary in these projects ?

**Comment by SethTisue** [comment]
let's fyi @adamw (sttp) and @dwijnand (lagom) since they may hit this if they try to move their projects to sbt 1.3

**Comment by eatkins** [comment]
@smarter sbt 1.3.0 closes the in process classloaders after test and run completes. This allows the classloaders to release their native file handles. Unfortunately, if the user code uses ShutdownHooks or leaks a thread, this can cause a crash after test or run completes. The documentation has explicitly warned users to not use ShutdownHooks with in process test and run, but a number of builds do it anyway. In the case of sttp, they don't directly use ShutdownHooks, but I suspect that they don't properly shutdown the actor systems that they start up in test which causes both a thread leak and a shutdown hook leak.

**Comment by SethTisue** [comment]
@eatkins that'd be a super addition to https://www.lightbend.com/blog/sbt-1.3.0-release

**Comment by SethTisue** [comment]
green in local testing

**Comment by dwijnand** [comment]
What's the downside of upgrading to sbt 1.3 and using `-Dsbt.classloader.close=false`?

**Comment by eatkins** [comment]
The benefits of _not_ setting `-Dsbt.classloader.close=false` are:
1. we release the file handles to jars. Keeping the handles open can prevent these jars from being deleted on windows. This probably doesn't matter on mac and linux unless the system is starved for file descriptors.
2. It can help identify thread leaks which ultimately lead to sbt running out of memory fairly quickly

I've gone back and forth on what the right default is.

**Comment by dwijnand** [comment]
Thanks.

**Pull request merged**
