### PR TITLE
Track typelevel/cats instead of fork - fixes #363

### LINKED ISSUE #363: Add typelevel/cats to build
May be blocked on https://github.com/scala/community-builds/issues/13 for `cats-laws`

Currently the build is tracking @SethTisue 's fork. Once https://github.com/typelevel/cats/pull/1415 is merged we should be able to point back to typelevel/cats and run it against all of `catsJVM` (instead of just core and macros).

### PR DESCRIPTION
**Pull request by adelbertc**

### CODE REVIEW

**Comment by SethTisue** [comment]
test run: https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/856/consoleFull (404 til Jenkins catches up)

**Comment by adelbertc** [comment]
Looks like issues with ScalaCheck - related to https://github.com/scala/community-builds/issues/13 maybe?

**Comment by SethTisue** [comment]
Yes, I think so.

**Comment by adelbertc** [comment]
:(

**Comment by adelbertc** [comment]
Closing in favor of https://github.com/scala/community-builds/pull/375 

Also as of https://github.com/scala/community-builds/pull/371 Cats is being tracked in the main repo

**Pull request closed without merging**
