### PR TITLE
2.13: try Olaf's scalameta branch

### PR DESCRIPTION
**Pull request by SethTisue**
cc @olafurpg

### CODE REVIEW

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/2175/ (404 til Jenkins wakes up)

**Comment by olafurpg** [comment]
Note that the Scalameta build got simplified in https://github.com/scalameta/scalameta/pull/1863 by merging a lot of modules and also removing few unused modules.

**Comment by SethTisue** [comment]
hello, rabbit? are you down here?

/me resumes digging

**Comment by SethTisue** [comment]
scalameta uses its own shaded version of fastparse 1, which is okay, it's under a different org so it won't conflict with any other fastparse versions

but scalameta also uses scalapb, and the version of scalapb we have is too old (resulting in compile errors in scalameta), and the newer versions use fastparse 2

so in order to finish this, I think I will need to tackle #897 first (fastparse 2 upgrade)

**Comment by SethTisue** [comment]
note also that I unforked scalapb but doing so lost the changes in the fork Adriaan made, to add the right Scala version specific source directories to `unmanagedSourceDirectories`, I'll need to cope with that in the usual way (it's better to do it in the dbuild config that handling it by forking)

**Comment by SethTisue** [comment]
I think this will probably have to wait until June or July. @olafurpg thanks for doing the work that allowed us to get this far, at least

**Pull request closed without merging**
