### PR TITLE
[2.12.x] Dedup alterKeyImpl

### PR DESCRIPTION
**Pull request by dwijnand**

### CODE REVIEW

**Comment by dwijnand** [comment]
With some type backflips we could handle the duplicate calls to `in` (see `Scoped.ScopingSetting`), but handling `~=` requires handling the difference between transforming a bare `T` value and transforming a value within a `Task[T]` (and preserving the resulting shape) and for that there isn't any directly supporting code.  So just instanceOf/asInstanceOf pattern match our way out of finding that solution.

**Comment by dwijnand** [comment]
WDYT @SethTisue?

**Comment by SethTisue** [comment]
I’ll get to it :-)

**Comment by dwijnand** [comment]
image

**Comment by SethTisue** [comment]
DON'T YOU DARE DELETE THE BRANCH I KNOW YOU WANT TO

**Comment by dwijnand** [comment]
Let's come back to this one.

**Comment by SethTisue** [comment]
resubmission: #940

**Pull request closed without merging**
