### PR TITLE
add ensime-server

### PR DESCRIPTION
**Pull request by fommil**

### CODE REVIEW

**Comment by fommil** [comment]
I rebased.

**Comment by stacycurl** [comment]
Is everything okay now ?

**Comment by gkossakowski** [comment]
I kicked the build here: https://jenkins-dbuild.typesafe.com:8499/job/Community-2.11.x-manual/116/console

**Comment by gkossakowski** [comment]
It failed again. I created my own branch and I'll try to get it working. You can watch it live here: https://github.com/gkossakowski/community-builds/compare/ensime?expand=1

**Comment by fommil** [comment]
@gkossakowski awesome, thanks. This is just going to take forever unless you have a go at it. It will be incredibly useful for you guys to have ENSIME in the community build because it's like an additional sanity check like scala-ide on the compiler API.

**Comment by stacycurl** [comment]
I want to reiterate that if pimpathon is slowing this down then please
remove it from the community build.

**Comment by fommil** [comment]
@stacycurl it can't be removed because it is an ENSIME dependency and I'm not letting you reach your life goal of executing all users :stuck_out_tongue:

**Comment by stacycurl** [comment]
Obligatory mwahaha.

Is it pimpathon that's causing all this kerfuffle ? Can it be upgraded (I
fixed/clobbered the file.cwd test a while ago).

Let's chat on the pimpathon gitter channel a bit later.

**Comment by fommil** [comment]
It was my fault, I upgraded pimpathon in the ensime build, but this PR was using the old version and our build failed. Probably something else will break. I think they can turn off the pimpathon tests in the worst case.

**Comment by gkossakowski** [comment]
Pimpathon is checked off the list of roadblocks:
```[info] Project pimpathon---------------: SUCCESS (project rebuilt ok)```

Now we have:

```[info] Project ensime------------------: FAILED (RuntimeException: Required dependency not found)```

It's caused by missing scoverage dependency. I'm on it.

**Comment by fommil** [comment]
that should just be an sbt plugin dependency, but I think it would **definitely** be a good community project to have in your checklist anyway! (compiler plugin)

**Comment by fommil** [comment]
also, feel free to use the 8998082625fa31751c361772d22f303c34104713 of ensime-server. We recently bumped the version of scoverage to the latest stable.

**Comment by gkossakowski** [comment]
It's both. The scoverage sbt plugin injects runtime dependency and that's the one that is missing:

```
[ensime] Processing subproject: default-sbt-project
[ensime] [error] **** Missing dependency: the library org.scoverage#scalac-scoverage-runtime is not provided (in space "default") by any project in this configuration file.
```

Good point that the whole scoverage should be added to community build. I didn't realize they have a compiler plugin there!

**Comment by gkossakowski** [comment]
Thanks for a tip. It's good to hear that you guys are on the latest so versions will line up.

**Comment by fommil** [comment]
@gkossakowski any joy?

**Comment by cunei** [comment]
@fommil: Grzegorz is away this week, but judging from this build log I suppose it worked ok: https://jenkins-dbuild.typesafe.com:8499/job/Community-2.11.x-manual/129/console
/cc @gkossakowski

**Comment by fommil** [comment]
can't see it

**Comment by cunei** [comment]
The link should be public; I just connected from an incognito browser and it connected ok. But in any event, it contains:
```
[info] ---==  Execution Report ==---
[info] Report from the dbuild run for dbuild: 
[info] Project akka--------------------: SUCCESS (project rebuilt ok)
[...]
[info] Project dispatch-http-210-------: SUCCESS (unchanged, not rebuilt)
[info] Project ensime------------------: SUCCESS (project rebuilt ok)
[info] Project genjavadoc--------------: SUCCESS (unchanged, not rebuilt)
[...]
[info] Project scalaz-210--------------: SUCCESS (unchanged, not rebuilt)
[info] Project scoverage---------------: SUCCESS (unchanged, not rebuilt)
[info] Project shapeless---------------: SUCCESS (unchanged, not rebuilt)
[...]
[info] Project zinc--------------------: SUCCESS (unchanged, not rebuilt)
[info] >>> The dbuild result is------------: SUCCESS (project rebuilt ok)
```
I cannot tell you more about the details though; Grzegorz did all the testing. He will be back next week.

**Comment by fommil** [comment]
looks good!

@cunei are you sure the server/port is available to the interwebz? I get "ERR_TUNNEL_CONNECTION_FAILED"

**Comment by cunei** [comment]
@fommil: I'm positive. Please note that it is https (not http), over port 8499.

**Comment by fommil** [comment]
could be my company firewall

**Comment by gkossakowski** [comment]
Yep, I got ensime to build in community build right before going off for one week of skiing. A new PR has been created now: #89. I think it would be great to get rid of non-standard port the next time we touch this particular Jenkins instance.

**Pull request closed without merging**
