### PR TITLE
include more of Play

### PR DESCRIPTION
**Pull request by SethTisue**
fyi @dwijnand. @adriaanm suggested a fresh attempt at including as much of Play as possible. the main idea is to help get ready for 2.13, but I'm starting here on 2.12 as a baseline.

### CODE REVIEW

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/3824/

**Comment by SethTisue** [comment]
before: `[playframework] The following subprojects will be built in project playframework: Play-Streams, Play-Exceptions, Build-Link, Play, Play-Guice, Play-Server, Play-Netty-Server, Play-Akka-Http-Server, Play-Test, Play-WS, Play-Specs2, Play-Java, Play-Logback, Play-Cache, Play-Caffeine-Cache, Play-AHC-WS, Filters-Helpers, Play-JDBC-Api, Play-JDBC`

after: `These subprojects will be built: Play-Framework, Play-Docs-SBT-Plugin, SBT-Routes-Compiler, Run-Support, Play-Ehcache, Play-JCache, Play-Microbenchmark, Play-Integration-Test, Play-OpenID, Filters-Helpers, Play-AHC-WS, Play-Caffeine-Cache, Play-Cache, Play-Java-Forms, Play-Java-JPA, Play-JDBC-Evolutions, Play-Java-JDBC, Play-Java, Play-Akka-Http2-Support, Play-Docs, Play-JDBC, Play-Joda-Forms, Play-Logback, Play-Specs2, Play-WS, Play-Test, Play-Akka-Http-Server, Play-Netty-Server, Play-Server, Play-JDBC-Api, Play-Guice, Play, Build-Link, Play-Exceptions, Play-Streams, Routes-Compiler`

**Comment by SethTisue** [comment]
in Play-Integration-Test

looks like it's happening during `FormFieldOrderSpec`

```
[playframework:error] java.lang.NoSuchMethodError: sun.security.ssl.SSLSessionImpl.<init>(Lsun/security/ssl/ProtocolVersion;Lsun/security/ssl/CipherSuite;Ljava/util/Collection;Ljava/security/SecureRandom;Ljava/lang/String;IZ)V
[playframework:error] 	at sun.security.ssl.ServerHandshaker.clientHello(ServerHandshaker.java:787)
[playframework:error] 	at sun.security.ssl.ServerHandshaker.processMessage(ServerHandshaker.java:232)
[playframework:error] 	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1052)
[playframework:error] 	at sun.security.ssl.Handshaker$1.run(Handshaker.java:992)
[playframework:error] 	at sun.security.ssl.Handshaker$1.run(Handshaker.java:989)
[playframework:error] 	at java.security.AccessController.doPrivileged(Native Method)
[playframework:error] 	at sun.security.ssl.Handshaker$DelegatedTask.run(Handshaker.java:1467)
[playframework:error] 	at akka.stream.impl.io.TLSActor.runDelegatedTasks(TLSActor.scala:404)
[playframework:error] 	at akka.stream.impl.io.TLSActor.doUnwrap(TLSActor.scala:373)
[playframework:error] 	at akka.stream.impl.io.TLSActor.doInbound(TLSActor.scala:292)
[playframework:error] 	at akka.stream.impl.io.TLSActor.$anonfun$bidirectional$1(TLSActor.scala:227)
[playframework:error] 	at akka.stream.impl.Pump.pump(Transfer.scala:201)
[playframework:error] 	at akka.stream.impl.Pump.pump$(Transfer.scala:199)
[playframework:error] 	at akka.stream.impl.io.TLSActor.pump(TLSActor.scala:50)
[playframework:error] 	at akka.stream.impl.SimpleOutputs$$anonfun$downstreamRunning$1.applyOrElse(ActorProcessor.scala:239)
[playframework:error] 	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:38)
[playframework:error] 	at akka.stream.impl.SubReceive.apply(Transfer.scala:18)
[playframework:error] 	at akka.stream.impl.FanOut$OutputBunch$$anonfun$subreceive$1.applyOrElse(FanOut.scala:231)
[playframework:error] 	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:38)
[playframework:error] 	at akka.stream.impl.SubReceive.apply(Transfer.scala:18)
[playframework:error] 	at akka.stream.impl.SubReceive.apply(Transfer.scala:14)
[playframework:error] 	at scala.PartialFunction.applyOrElse(PartialFunction.scala:127)
[playframework:error] 	at scala.PartialFunction.applyOrElse$(PartialFunction.scala:126)
[playframework:error] 	at akka.stream.impl.SubReceive.applyOrElse(Transfer.scala:14)
[playframework:error] 	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:176)
[playframework:error] 	at akka.actor.Actor.aroundReceive(Actor.scala:517)
[playframework:error] 	at akka.actor.Actor.aroundReceive$(Actor.scala:515)
[playframework:error] 	at akka.stream.impl.io.TLSActor.aroundReceive(TLSActor.scala:50)
[playframework:error] 	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:588)
[playframework:error] 	at akka.actor.ActorCell.invoke(ActorCell.scala:557)
[playframework:error] 	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
[playframework:error] 	at akka.dispatch.Mailbox.run(Mailbox.scala:225)
[playframework:error] 	at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
[playframework:error] 	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
[playframework:error] 	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
[playframework:error] 	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
[playframework:error] 	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/3826/consoleFull

**Comment by adriaanm** [comment]
> [playframework:error] java.lang.NoSuchMethodError: sun.security.ssl.SSLSessionImpl.<init>(Lsun/security/ssl/ProtocolVersion;Lsun/security/ssl/CipherSuite;Ljava/util/Collection;Ljava/security/SecureRandom;Ljava/lang/String;IZ)V

sounds like a jdk incompatibility?

**Comment by SethTisue** [comment]
@dwijnand some Oracle vs OpenJDK thing, you think?

**Comment by dwijnand** [comment]
Can't remember but check one of the latest PRs in akka-grpc where @raboof ran into it.  I think it might be the broken jdk (can't remember if oracle or open) in Ubuntu that we expect Canonical will fix.

**Comment by raboof** [comment]
Reminds me of https://github.com/jetty-project/jetty-alpn/issues/22 and https://github.com/eclipse/jetty.project/issues/3100#issuecomment-440634414 indeed

**Comment by SethTisue** [comment]
@dwijnand can you see which test I need to disable in order for https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/3826/consoleFull to progress farther? it isn't obvious to me from the log

**Comment by dwijnand** [comment]
`Play-Integration-Test/test:test`.  Can't tell either more specifically than that.

**Comment by SethTisue** [comment]
okay, let's skip Play-Integration-Test for now, and then hopefully come back to it. I can move our Jenkins to a different JDK build if needed

for now, let's just do a fresh run with the latest changes, and skipping Play-Integration-Test, and see what happens: 
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/3940/

**Comment by dwijnand** [comment]
It might be `EndpointIntegrationSpecificationSpec` (https://github.com/playframework/playframework/issues/8829), for the next time we try and re-enable them.

**Comment by SethTisue** [comment]
```
[playframework] [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[playframework] [warn] 	::          UNRESOLVED DEPENDENCIES         ::
[playframework] [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[playframework] [warn] 	:: org.openjdk.jmh#jmh-core;2.7.0-dbuildx7d03fd1026c1c21aa7dbf023d8b1bb46e11b308f: not found
[playframework] [warn] 	:: org.openjdk.jmh#jmh-generator-bytecode;2.7.0-dbuildx7d03fd1026c1c21aa7dbf023d8b1bb46e11b308f: not found
[playframework] [warn] 	:: org.openjdk.jmh#jmh-generator-reflection;2.7.0-dbuildx7d03fd1026c1c21aa7dbf023d8b1bb46e11b308f: not found
[playframework] [warn] 	:: com.typesafe.play#play-integration-test;2.7.0-dbuildx7d03fd1026c1c21aa7dbf023d8b1bb46e11b308f: not found
[playframework] [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
```

trying again with Play-Microbenchmark disabled (which is fine, we routinely exclude benchmark subprojects, considering them out of scope): 
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/3943/

**Comment by SethTisue** [comment]
```
[playframework] Processing subproject: Run-Support
[playframework] [error] **** Missing dependency: the library com.lightbend.play#play-file-watch is not provided (in space "scala.main") by any project in this configuration file.
[playframework] [error] In order to control which version is used, please add the corresponding project to the build file
[playframework] [error] (or use "check-missing:false" to ignore (not recommended)).
```

should be easy to add [play-file-watch](https://github.com/playframework/play-file-watch); I'll do that next

**Comment by SethTisue** [comment]
as an aside, https://github.com/playframework/play-file-watch/watchers doesn't include any current Play team members, y'all should probably watch it :-)  /cc @marcospereira 

Quis custodiet ipsos custodes?

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/3947/

**Comment by SethTisue** [comment]
play-file-watch is failing because it uses a much older version of better-files than the one in the community build

**Comment by marcospereira** [comment]
> play-file-watch is failing because it uses a much older version of better-files than the one in the community build

Hum... this is something we can only solve when dropping support for sbt 0.13 (Scala 2.10). Is there something else we can do on our side to help you?

**Comment by SethTisue** [comment]
hmm...

the actual compile error is 

```
[play-file-watch] [error] /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.16/project-builds/play-file-watch-544cb3249b59fcea9b3d661557f2251ba5eebe6d/src/main/scala/play/dev/filewatch/JNotifyFileWatchService.scala:140: overloaded method constructor ZipFile with alternatives:
[play-file-watch] [error]   (x$1: java.io.File,x$2: java.nio.charset.Charset)java.util.zip.ZipFile <and>
[play-file-watch] [error]   (x$1: String,x$2: java.nio.charset.Charset)java.util.zip.ZipFile <and>
[play-file-watch] [error]   (x$1: java.io.File,x$2: Int)java.util.zip.ZipFile
[play-file-watch] [error]  cannot be applied to (java.io.File, scala.io.Codec)
[play-file-watch] [error]       zipFile <- new ZipFile(thisFile.toJava, codec).autoClosed
[play-file-watch] [error]                  ^
```

is there a way to tweak the code so that it's source-compatible with both versions of better-files?

if not, I can just fork play-file-watch

**Comment by dwijnand** [comment]
https://github.com/playframework/play-file-watch/pull/25

**Comment by SethTisue** [comment]
new run: 
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/3969/

**Comment by SethTisue** [comment]
unrelated failure, no usable results

trying again with fix merged onto branch: new run:
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/3974/

**Comment by SethTisue** [comment]
hmm, what do you make of this?

```
[play-file-watch] [error] /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.16/project-builds/play-file-watch-c0e00a52ebb72b2a252530fb32d79346a2ce0324/src/main/scala/play/dev/filewatch/JNotifyFileWatchService.scala:144: value > is not a member of java.io.InputStream
[play-file-watch] [error]     } zipFile.getInputStream(entry) > file.newOutputStream
[play-file-watch] [error]                                     ^
[play-file-watch] [error] /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.16/project-builds/play-file-watch-c0e00a52ebb72b2a252530fb32d79346a2ce0324/src/main/scala/play/dev/filewatch/JNotifyFileWatchService.scala:144: value > is not a member of java.io.InputStream
[play-file-watch] [error]     } zipFile.getInputStream(entry) > file.newOutputStream
[play-file-watch] [error]                                     ^
```

**Comment by dwijnand** [comment]
More missing implicits in better-files 3.7?

**Comment by SethTisue** [comment]
yeah, looks like it

**Comment by dwijnand** [comment]
I'll try to get it to it in the next few days.

**Comment by dwijnand** [comment]
https://github.com/playframework/play-file-watch/pull/26

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/4036/

**Comment by SethTisue** [comment]
green at https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/4055/ (the failures are unrelated)

the subprojects that we ended up adding are: Play-Akka-Http2-Support, Play-Ehcache, Play-Framework, Play-JCache, Play-JDBC-Api, Play-JDBC-Evolutions, Play-Java-Forms, Play-Java-JDBC, Play-Java-JPA, Play-Joda-Forms, Play-OpenID, Routes-Compiler, Run-Support, SBT-Routes-Compiler

the only significant remaining exclusion is Play-Integration-Test. details on that above. I won't try to get that one over the finish line myself, but if the Play team wants to tackle it, I can help. (No opinion on whether doing so is actually worth the effort.)

**Comment by SethTisue** [comment]
followup issue suggesting possible further additions: https://github.com/scala/community-builds/issues/846

**Pull request merged**
