### PR TITLE
fix sconfig using jodersky spray-json fork

### PR DESCRIPTION
**Pull request by SethTisue**
fyi @ekrich

### CODE REVIEW

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/4340/

**Comment by ekrich** [comment]
Is the spray-json fork in the community build as well or does this just keep track of it as a `sconfig` dependency? 

Is the extra sbt setting something that could be changed in the build or is that a common thing?

**Comment by SethTisue** [comment]
> Is the spray-json fork in the community build as well or does this just keep track of it as a `sconfig` dependency?

I'm currently trying to add the fork to the community build and use it on all projects that use spray-json, not just for sconfig. If that doesn't work out, I'll try using the fork in sconfig only.

> Is the extra sbt setting something that could be changed in the build or is that a common thing?

If you mean the change I made to the sconfig section, I took that out, I must have been confused and/or fat-fingered something, not sure what I was thinking.

**Comment by SethTisue** [comment]
in a local test, `[info] Project sconfig---------------------: SUCCESS (project rebuilt ok)`, so then I just need to see if anything else breaks.

https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/4342/

**Review by ekrich — COMMENTED** [review]
I was referring to this change. I'm not sure how to do a review with the code highlighted. Anyway, this line. `"set every gpgWarnOnFailure := true"`

**Comment by SethTisue** [comment]
oh, it's not important either way, feel free to set that in your build or not, it's fine. it's pretty common that we have to tweak this in the community build for repos that use sbt-gpg

**Comment by SethTisue** [comment]
as an afterthought on this, it probably would have made more sense to set `organization` in the spray-json config section, rather than changing the organization in every downstream repo :-/

**Comment by ekrich** [comment]
I guess I saw that but not all that familiar with the setup. There will be more opportunities for clean up I'm sure 😄

**Pull request merged**
