### PR TITLE
2.13: new Scala SHA (and add Finch)

### PR DESCRIPTION
**Pull request by SethTisue**
candidate 2.13.8 candidate

~waiting on https://app.travis-ci.com/github/scala/scala/builds/243537738~

~https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/3393/~
~https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/3394/~
https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/3398/
https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/3399/

### CODE REVIEW

**Comment by SethTisue** [comment]
cats and twitter-util are failing?!

**Comment by lrytz** [comment]
OOME in both 🤔

**Comment by SethTisue** [comment]
cats failure is reproducible outside of dbuild with `++2.13.8-bin-b59fa66` and `testsJVM/testOnly *NonEmptyListSuite`

but you have to `publishLocal` kind-projector 0.13.2 and semanticdb-scalac 4.4.30 for 2.13.8-bin-b59fa66 first (`cp -rp semanticdb/scalac/library/src/main/scala-2.13.7 semanticdb/scalac/library/src/main/scala-2.13.8`, `semanticdbScalacPlugin/publishLocal`, `semanticdbScalacCore/publishLocal`)

```
==> X cats.tests.NonEmptyListSuite.grouped is consistent with iterator.toList.grouped  8.578s munit.FailException: Failing seed: zagPzwaJu-99K9DrqnArRx9CQPJ9lpLoh2EIUF8F5qI=
You can reproduce this failure by adding the following override to your suite:

  override val scalaCheckInitialSeed = "zagPzwaJu-99K9DrqnArRx9CQPJ9lpLoh2EIUF8F5qI="

Exception raised on property evaluation.
> ARG_0: NonEmptyList(1188467134)
> ARG_1: 474128334
> ARG_1_ORIGINAL: 1896513336
> Exception: java.lang.OutOfMemoryError: Java heap space
    at munit.ScalaCheckSuite.propToTry(ScalaCheckSuite.scala:98)
Caused by: java.lang.OutOfMemoryError: Java heap space
```

note the `.grouped`, which suggests scala/scala#9818 as a likely cause

**Comment by SethTisue** [comment]
twitter-util failure is reproducible outside dbuild with `++2.13.8-bin-b59fa66` and `util-core/testOnly com.twitter.concurrent.AsyncStreamTest`

```
[info] - Cons: grouped() works like Seq.grouped *** FAILED ***
[info]   OutOfMemoryError was thrown during property evaluation.
[info]     Message: Java heap space
[info]     Occurred when passed generated values (
[info]       arg0 = List(),
[info]       arg1 = 536870911 // 2 shrinks
[info]     )
```

again, `grouped`, so I think we just need to revert that PR

**Comment by SethTisue** [comment]
~waiting for Travis-CI to [publish](https://app.travis-ci.com/github/scala/scala/builds/243651137) a nightly for https://github.com/scala/scala/pull/9859, then we can try again~

new runs queued

**Pull request merged**
