### PR TITLE
2.12: project SHAs, forward march! hut, two!

### PR DESCRIPTION
**Pull request by SethTisue**
(note to self: should I also add a commit to bump the sbt version to 1.3.4?)

### CODE REVIEW

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/5265/

**Comment by SethTisue** [comment]
`EXTRACTION FAILED (failed: play-file-watch, scala-ssh, scalaprops)`

* https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/5265/artifact/logs/play-file-watch-extract.log
  * `unresolved dependency: com.typesafe.play#interplay;2.1.3: not found`
* https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/5265/artifact/logs/scala-ssh-extract.log
  * `error: not found: value Sbt` `[scala-ssh:error] scalafmtOnCompile in Sbt := false`
* https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/5265/artifact/logs/scalaprops-extract.log
  * `[scalaprops] [error] [/home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.16/extraction/e9e7b237e36102d53312c3e4f95ce6bb2e9e38d7/projects/2c51eb1f62b88f3e450d66351511a5824f0265b2/project/plugins.sbt]:19: illegal start of simple expression`

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/5268/

**Comment by SethTisue** [comment]
* https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/5268/artifact/logs/doodle-build.log
  * compilation errors, offhand I wonder if we might be using a too-bloody bleeding-edge commit? leaf project, not really worth digging into, maybe just freeze at last green?
* https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/5268/artifact/logs/finagle-build.log
  * object JavaSingleton is not a member of package com.twitter.util
  * possible version mismatch with twitter-util?
* https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/5268/artifact/logs/scala-ssh-build.log
  * `gpg: signing failed: No secret key`, probably just needs the usual ignore-gpg-problems workaround
* https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/5268/artifact/logs/splain-build.log
  * gpg error, probably just needs the usual ignore-gpg-problems workaround
* https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/5268/artifact/logs/akka-http-json-build.log
  * probable version mismatch with jsoniter-scala: `com.github.plokhotnyuk.jsoniter_scala.core.ReaderConfig.type does not take parameters`
* https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/5268/artifact/logs/alpakka-kafka-build.log
  * not sure what this might be about: `sbt.librarymanagement.ResolveException: Error downloading org.apache.kafka:kafka-clients:2.4.0`

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/5272/

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/5275/

**Comment by ennru** [comment]
> not sure what this might be about: sbt.librarymanagement.ResolveException: Error downloading org.apache.kafka:kafka-clients:2.4.0

We merged an upgrade to Kafka 2.4.0-RC1 which is available from a snapshot repo. I'll try to find time to update my Kafka clone to the latest stuff. They haven't released 2.4.0, yet.

**Comment by SethTisue** [comment]
@ennru I froze alpakka-kafka at an earlier commit for now. I think it's fine if we just wait until 2.4.0 comes out before we unfreeze

**Pull request merged**
