### PR TITLE
add lsp4s's dependencies: enumeratum, circe-derivation, scrooge, scrooge-shapes, perfolation, scribe, circe-generic-extras

### PR DESCRIPTION
**Pull request by SethTisue**

### CODE REVIEW

**Comment by SethTisue** [comment]
test run: https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/3058/

**Comment by SethTisue** [comment]
enumeratum is green now.

but then:

```
[lsp4s] [error] **** Missing dependency: the library com.outr#scribe is not provided (in space "scala.main.jawn_0_11") by any project in this configuration file.
```

**Comment by SethTisue** [comment]
test run: https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/3073/

**Comment by SethTisue** [comment]
also needs circe-derivation, and circe-derivation needs something called scrooge (from Stripe?)

**Comment by SethTisue** [comment]
new test run to refresh my memory of where we stand here: https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/3101/ (404 for now, Jenkins is backed up)

**Comment by SethTisue** [comment]
this rabbit hole is pretty deep. is there really a rabbit down here, or what?

**Comment by SethTisue** [comment]
@olafurpg in general, this many dependencies makes me nervous...

**Comment by olafurpg** [comment]
It makes me nervous as well @SethTisue, and it used to be worse! I try to justify it here https://github.com/scalameta/lsp4s#lsp4s, stdlib `Future` is not a good fit because LSP requests are cancelable. I tried to use upickle instead of circe for JSON but in the end I prefer circe. Logging could be sl4j but all the Java logging frameworks are almost impossible to configure programmatically (or lack of documentation on how to makes you think so).

**Comment by olafurpg** [comment]
Enumeratum is easy to tear out by either writing boilerplate or rolling a custom tiny macro. I kept it in lsp4s because I don't want to maintain macros it was already there, the lsp4s module was torn out of the metals repo.

**Comment by SethTisue** [comment]
okay we've reached a milestone here where all of the dependencies are green ([log](https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/3135/console)), at least, so I've squashed all the wip commits

**Comment by SethTisue** [comment]
@olafurpg okay, thanks for the pointer and the insight

**Comment by SethTisue** [comment]
@olafurpg lsp4s is failing to compile with errors such as

```
[lsp4s] [error] /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.12/project-builds/lsp4s-bec77cad142ced0d05aaf4956e150d2bac7f82c9/jsonrpc/src/main/scala/scala/meta/jsonrpc/BaseProtocolMessageParser.scala:9:35: object ObservableLike is not a member of package monix.reactive.observables
[lsp4s] [error] import monix.reactive.observables.ObservableLike.Operator
```

I believe this is a monix 2.3 vs 3.0 change. is there any chance of getting lsp4s onto monix 3.0?

**Comment by olafurpg** [comment]
We can definitely upgrade to monix v3, I opened https://github.com/scalameta/lsp4s/issues/13 We haven't upgraded yet because it's still a milestone and we still had hopes to avoid the cats dependency. But now that we've doubled down on circe it looks like cats is with use for better or worse even if we don't use it directly.

I wish all of my libraries were dependency free, but it's a fine balance between continuously re-inventing the wheel and keeping your build clean and upgradeable.

**Comment by SethTisue** [comment]
let's get a fresh read on the current status: https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/3405/

if all the new additions are still green except for lsp4s itself, I should probably merge that much, and then make a narrower PR just for lsp4s

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/3410/ (404 for now)

**Comment by SethTisue** [comment]
the final piece of this (adding lsp4s itself) is now #780

**Pull request merged**
