### PR TITLE
2.13: advance project SHAs

### PR DESCRIPTION
**Pull request by SethTisue**
~~https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/1531/~~
~~https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/1532/~~
~~https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/1540/~~
https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/1541/

### CODE REVIEW

**Comment by SethTisue** [comment]
```
[sjson-new] Processing subproject: shadedJawnParser
[sjson-new] All Dependencies for subproject shadedJawnParser:
[sjson-new]    org.scala-lang:scala-compiler:2.13.3-bin-27bdf60:scala-tool->default,optional(default)
[sjson-new]    org.scala-lang:scala-library:2.13.3-bin-27bdf60:scala-tool->default,optional(default)
[sjson-new]    com.lightbend:cloc-plugin:0.0.1-dbuildx6cc1991814ba192890169e1ed67af76a42c7f618:plugin->default(compile)
[sjson-new]    org.scala-lang:scala-library:2.13.3-bin-27bdf60
[sjson-new]    org.typelevel:jawn-parser:1.0.0-dbuildx9f544ce777f48e74a7d95d1e4699836b2717f0c9
[sjson-new] Running build: shadedJawnParser
[sjson-new] [info] Wrote /home/jenkins/workspace/scala-2.13.x-integrate-community-build/target-0.9.16/project-builds/sjson-new-bf19930503e09b81d6fa1513bcf8fb8da80708ca/shaded-jawn-parser/target/scala-2.13/shaded-jawn-parser-0.8.3-dbuildxbf19930503e09b81d6fa1513bcf8fb8da80708ca.pom
[sjson-new] [error] java.lang.RuntimeException: org.typelevel:jawn-parser:1.0.0 was not found
```

**Comment by SethTisue** [comment]
tried for a while to fix or work around that and ended up throwing up my hands and just freezing sjson-new, fyi @eed3si9n

**Comment by eed3si9n** [comment]
@SethTisue If shadedJawnParser did manage to depend on `org.typelevel:jawn-parser:1.0.0-dbuildx9f544ce777f48e74a7d95d1e4699836b2717f0c9`, maybe I can just relax Jar Jar Abrams to not be too fussy about the version number here - https://github.com/eed3si9n/jarjar-abrams/blob/e6bc7a6c65ebf0d560f90b0ca09c68e3104c0ade/sbtplugin/src/main/scala/com/eed3si9n/jarjarabrams/sbtjarjarabrams/JarjarAbramsPlugin.scala#L110-L126

**Comment by SethTisue** [comment]
@eed3si9n that sounds plausible. I'd be happy to work on it with you after this PR is merged, and after 2.13.3 is out (should be this week)

**Pull request merged**
