### PR TITLE
add sconfig

### PR DESCRIPTION
**Pull request by SethTisue**
fyi @ekrich

### CODE REVIEW

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/3967/

**Comment by ekrich** [comment]
@SethTisue That makes this very official which is new territory for me. Thanks.

**Comment by SethTisue** [comment]
it's official enough you should be happy but not so official you should be nervous :-)

**Comment by SethTisue** [comment]
@ekrich what do you make of this?

```
[sconfig] [error] Test org.ekrich.config.impl.ConfigTest.test01Origins failed: description ends with url and line 'test01.conf @ file:/home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.16/project-builds/sconfig-6b0d83e2b4999ecd42d8a994d549f0af0b21eb7b/sconfig/target/scala-2.12.9-bin-329deac/test-classes/test01.conf: 3', took 0.004 sec
[sconfig] [error] Failed: Total 530, Failed 1, Errors 0, Passed 529
[sconfig] [error] Failed tests:
[sconfig] [error] 	org.ekrich.config.impl.ConfigTest
[sconfig] [error] (sconfig / Test / test) sbt.TestsFailedException: Tests unsuccessful
```

**Comment by ekrich** [comment]
Is this jdk8? I know it won't work with jdk11. What is the version of Scala here so I can test it out locally?

**Comment by SethTisue** [comment]
yes, JDK 8, and the Scala version is `2.12.9-bin-329deac`(see https://stackoverflow.com/a/40622879/86485)

**Comment by ekrich** [comment]
How do I know what version is getting pulled? Latest off master?

**Comment by ekrich** [comment]
@SethTisue I found the issue - also see previous question. I'm not sure why `path` is being used but I didn't write the test. The path was expecting a production type path of `scala-2.12/classes` without anything past the `minor` portion of the version number.

https://github.com/ekrich/sconfig/blob/master/sconfig/src/test/scala/org/ekrich/config/impl/ConfigTest.scala#L934-L945

Should I add some logic looking for a `-` or something to just use the whole string otherwise use the bin compat version like it does now?

**Comment by SethTisue** [comment]
> How do I know what version is getting pulled? Latest off master?

yes, see the diffs for this PR, it just has `https://github.com/ekrich/sconfig.git`, which defaults to using `master`. also fwiw groveling though the Jenkins log will show which specific commit was actually used in a particular run

if fixing the string-mangling logic in the test proves tricky, another possibility would be to use sbt-buildinfo to have sbt tell the test exactly where the directory is, so you don't have to worry about whether your logic matches sbt's

**Comment by ekrich** [comment]
Well, it looks like all the community builds will use `-` in the version number so I can just finagle the path and add a comment. I had to change it again to include `jvm` for cross builds as I'm working towards Scala Native support so no big deal. Thanks for the help.

**Comment by SethTisue** [comment]
cool, just let me know when I should trigger a new run.

**Comment by ekrich** [comment]
@SethTisue I made a couple of changes so it should be good to go now.

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/3993/

**Comment by SethTisue** [comment]
I'll comment here if it fails on JDK 11

**Pull request merged**
