### PR TITLE
2.13: re-enable linker subproject in scala-js

### PR DESCRIPTION
**Pull request by SethTisue**
now that scala-parallel-collections are ported to new collections

sequel to #829 

/cc @sjrd

### CODE REVIEW

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/1759/

**Comment by SethTisue** [comment]
need to fix this brand-new regression first:

```
[scala-parallel-collections] [error] Failed tests:
[scala-parallel-collections] [error] 	scala.SerializationStabilityTest
[scala-parallel-collections] [error] 	scala.collection.parallel.SerializationTest
```

**Comment by SethTisue** [comment]
scala-parallel-collections is fixed. next:

https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/1767/consoleFull

```
[scala-js] [error] /home/jenkins/workspace/scala-2.13.x-integrate-community-build/target-0.9.16/project-builds/scala-js-8aec33c906c33d941a07f3df62901683431d90a5/linker/jvm/src/main/scala/org/scalajs/linker/backend/closure/ClosureModuleBuilder.scala:58: type mismatch;
[scala-js] [error]  found   : scala.collection.mutable.ListBuffer[com.google.javascript.rhino.Node]
[scala-js] [error]  required: Seq[?]
[scala-js] [error]       val root = transformer.setNodePosition(IR.script(treeBuf: _*), NoPosition)
[scala-js] [error]                                                        ^
```

@sjrd looks like a `scala.collection.Seq` vs `scala.collection.immutable.Seq` thing?

**Comment by sjrd** [comment]
Yes, we haven't even tried making the linker code compiling with 2.13 at all, since we were missing the dependency for parallel collections. I'll have to figure out how to do and test that locally with a local build of Scala and of the parallel collections, I guess.

**Comment by SethTisue** [comment]
> I'll have to figure out how to do and test that locally with a local build of Scala and of the parallel collections, I guess.

since parallel collections depend on scalacheck, you'd need to publish that locally too, using the community-build-2.13 branch of the scalacommunitybuild fork

all that local publishing, and making sure you're doing it from the right forks and branches where the needed post-M5 tweaks are in place, gets annoying fast. it might be better to just use dbuild.

in case you'd like to try it out, I have made a branch for you where the config contains only Scala.js and its dependencies: https://github.com/SethTisue/community-builds/tree/scalajs-testing

so you just need to edit the `  scala-js-uri:                 "https://github.com/scala-js/scala-js.git"` line of `configs/project-refs.conf` to point to the branch where you're pushing your changes, and `./run.sh`. since I cut the config file down to almost nothing, it only takes a few minutes to run, and followup runs will be even faster.

**Comment by SethTisue** [comment]
> since parallel collections depend on scalacheck, you'd need to publish that locally too, using the community-build-2.13 branch of the scalacommunitybuild fork

(well, I guess that's not true. the dependency is test-only, so you can publish scala-parallel-collections even without publishing scalacheck first. still, you might want to go the dbuild route anyway.)

**Comment by sjrd** [comment]
Hum OK, I'll try and have a look at it next week. Thank you.

**Comment by SethTisue** [comment]
waiting for 2.13.0-RC1 is also okay

**Comment by SethTisue** [comment]
@sjrd interested in returning to this? it should be easier now that RC1 is out and your dependencies have published.

**Comment by sjrd** [comment]
Yes, it's on my to-do list. But I don't know when I'll have time to dig into it.

**Comment by SethTisue** [comment]
okay. I'd prefer to just close this then; we normally keep todos on specific projects just as comments in the config file. 3f6417c2f2540a5d88e656a6ac8dcf637d7cb2c5

**Comment by SethTisue** [comment]
@sjrd fwiw I tried re-enabling "linker" just now and it didn't work:

```
[scala-js] [error] /home/jenkins/workspace/scala-2.13.x-integrate-community-build/target-0.9.16/project-builds/scala-js-30d45c0cf57aa6bcaa044cd4f328baf744433595/linker/jvm/src/main/scala/org/scalajs/linker/backend/closure/ClosureModuleBuilder.scala:58: type mismatch;
[scala-js] [error]  found   : scala.collection.mutable.ListBuffer[com.google.javascript.rhino.Node]
[scala-js] [error]  required: Seq[?]
[scala-js] [error]       val root = transformer.setNodePosition(IR.script(treeBuf: _*), NoPosition)
[scala-js] [error]                                                        ^
```

definitely not urgent at all.

**Comment by sjrd** [comment]
Yeah, we haven't even really tried porting `linker` to 2.13.x yet. We've had much more pressing things to do. After Scala Days (more realistically, after Scala Matsuri), I'll have time to revisit.

**Pull request closed without merging**
