### PR TITLE
unfreeze scala-collection-compat

### PR DESCRIPTION
**Pull request by SethTisue**

### CODE REVIEW

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/4074/ (404 til Jenkins queue clears)

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/4083/ has `failed: kxbmap-configs, scalikejdbc`, but that doesn't block anything downstream

**Comment by SethTisue** [comment]
ah, it's https://github.com/scala/scala-collection-compat/pull/152 /cc @seratch @kxbmap @xuwei-k

**Comment by SethTisue** [comment]
@xuwei-k if I published scala-collection-compat 0.2.2, would you able to use it in these two projects and remove the `collectionCompatVersion` setting workaround you're currently doing?

**Comment by seratch** [comment]
@SethTisue Thank you for letting me know this. At this moment, is there anything I can do for you?

**Comment by SethTisue** [comment]
I published scala-collection-compat 0.2.2 and upgraded scalikejdbc and kxbmap-configs to use it in my forks

@seratch I'll let you know after we see how this does:
~~https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/4113/~~ 
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/4115/

**Comment by seratch** [comment]
@SethTisue I got it. Thanks for working on this.

**Comment by SethTisue** [comment]
oops, I meant to hit "squash". fixed by force-pushing 311991c23c6a6d48e50c03e9647c984fb7fd3cf9 instead

**Comment by SethTisue** [comment]
submitted: https://github.com/scalikejdbc/scalikejdbc/pull/984, https://github.com/kxbmap/configs/pull/36

there's nothing else to do

**Pull request merged**
