### PR TITLE
try newer Specs2

### PR DESCRIPTION
**Pull request by SethTisue**
cuz Eric fixed a thing, see https://github.com/etorreborre/specs2/issues/526

### CODE REVIEW

**Comment by SethTisue** [comment]
test run: https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/1047/consoleFull (404 til Jenkins obtains the correct implement for whisking matcha into a delicious green froth)

**Comment by SethTisue** [comment]
errors starting with:

```
[specs2] [error] /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.7-RC1/project-builds/specs2-35b8f406905244b6d45979f6d8e3075271191946/common/src/main/scala/org/specs2/control/eff/Eff.scala:138: not found: type ?
[specs2] [error]   implicit final def EffMonad[R]: Monad[Eff[R, ?]] = new Monad[Eff[R, ?]] with BindRec[Eff[R, ?]] {
[specs2] [error]                                                ^
[specs2] [error] /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.7-RC1/project-builds/specs2-35b8f406905244b6d45979f6d8e3075271191946/common/src/main/scala/org/specs2/control/eff/Eff.scala:138: org.specs2.control.eff.Eff[R,<error>] takes no type parameters, expected: one
[specs2] [error]   implicit final def EffMonad[R]: Monad[Eff[R, ?]] = new Monad[Eff[R, ?]] with BindRec[Eff[R, ?]] {
[specs2] [error]                                         ^
[specs2] [error] /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.7-RC1/project-builds/specs2-35b8f406905244b6d45979f6d8e3075271191946/common/src/main/scala/org/specs2/control/eff/AsyncEffect.scala:89: could not find implicit value for parameter ev: scalaz.Leibniz.===[scalaz.\/[Throwable,Any],G[B]]
[specs2] [error]             }.sequence
[specs2] [error]               ^
[specs2] [error] /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.7-RC1/project-builds/specs2-35b8f406905244b6d45979f6d8e3075271191946/common/src/main/scala/org/specs2/control/eff/AsyncEffect.scala:92: type mismatch;
[specs2] [error]  found   : Any
[specs2] [error]  required: Throwable
[specs2] [error]             case -\/(t)     => pure(\/.left(t))
[specs2] [error]                                             ^
```

not sure what this is about. `?` looks like kind-projector syntax?

dbuild seems to be picking up that specs2 is using kind-projector:

```
[info] Project specs2
[info]   depends on: kind-projector, macro-compat, macro-paradise, scala, scala-parser-combinators, scalacheck, scalatest, scalaz, shapeless
```

I see that in 3b64cc533b33f7272e964be2c2ef80831f248a74 Eric moved to a newer kind-projector. but 0.9.3 is the same version we have in the community build, and there weren't any associated code changes, so I don't know why there would be a source incompatibility

**Comment by etorreborre** [comment]
I don't understand this, especially since everything is fine on my build.

**Comment by SethTisue** [comment]
I don't currently have time to look into this — hopefully next month

**Comment by SethTisue** [comment]
rebased, new test run: https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/1151/consoleFull (404 til Jenkins comes out from the clock repair shop after the earthquake)

**Comment by SethTisue** [comment]
the `guide` subproject had compile errors, eff-related. trying again with that excluded: https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/1151/consoleFull

**Comment by SethTisue** [comment]
local run is green. whatever that kind-projector thing was, I guess it fixed itself `¯\_(ツ)_/¯`

**Pull request merged**
