### PR TITLE
sbt 1.3.5 (was 1.3.4)

### PR DESCRIPTION
**Pull request by SethTisue**
fyi @eed3si9n

### CODE REVIEW

**Comment by SethTisue** [comment]
queued: https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/5320/

**Comment by SethTisue** [comment]
```
[twirl] [info] Twirl compiler
[twirl] [info] - should compile successfully (real) *** FAILED ***
[twirl] [info]   play.twirl.compiler.test.Helper$CompilationError: Symbol 'type scala.xml.NodeSeq' is missing from the classpath.
[twirl] [info] This symbol is required by 'value play.twirl.api.BaseScalaTemplate.x'.
[twirl] [info] Make sure that type NodeSeq is in your classpath and check for conflicting dependencies with `-Ylog-classpath`.
[twirl] [info] A full rebuild may help if 'BaseScalaTemplate.class' was compiled against an incompatible version of scala.xml.
[twirl] [info] (NOTE: It looks like the scala-xml module is missing; try adding a dependency on "org.scala-lang.modules" : "scala-xml".
[twirl] [info]        See http://docs.scala-lang.org/overviews/ for more information.)
```

**Comment by SethTisue** [comment]
@eed3si9n I dealt with the Twirl failure by using 1.3.4 instead in that one repo. does it seem like something you might want to investigate...?

**Comment by eed3si9n** [comment]
Yea. That sounds like a regression.

**Pull request merged**
