### PR TITLE
bump sbt version, add scalatags, unfork monocle, unfork cats, unfreeze Akka, unbreak scalaz

### PR DESCRIPTION
**Pull request by SethTisue**
(there is no relation between these changes)

### CODE REVIEW

**Comment by SethTisue** [comment]
let's try unforking cats too: https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/861/consoleFull

**Comment by SethTisue** [comment]
the deprecation of the old style sbt operators sure causes a lot of noise in the build logs :-\

on the balance, I think it's worth doing though. dogfooding new sbt version is important. over time, as project maintainers update their builds, the noise level should go down

**Comment by SethTisue** [comment]
continue piling on: https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/862/consoleFull

**Comment by SethTisue** [comment]
pulled Abide, it doesn't compile on 2.12, reported upstream

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/863/consoleFull (404 for now)

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/864/consoleFull

**Comment by SethTisue** [comment]
I'm going to go ahead and merge — we haven't seen a fully green run yet, because low-level dependencies keep changing, but I think I have enough evidence from various runs

**Comment by SethTisue** [comment]
fyi @dwijnand @lihaoyi @xuwei-k @julien-truffaut @adelbertc @bantonsson @ktoso @larsrh

**Comment by bantonsson** [comment]
@SethTisue The akka build will probably fail for `master` until the changes in akka/akka#21737 are merged. The akka-scala-nightly project included a few too many projects.

**Comment by bantonsson** [comment]
@SethTisue And now the akka fixes are in master.

**Comment by SethTisue** [comment]
thanks Björn!

**Pull request merged**
