### PR TITLE
Add scalastyle

### PR DESCRIPTION
**Pull request by matthewfarwell**

### CODE REVIEW

**Comment by SethTisue** [comment]
test run: https://scala-ci.typesafe.com/job/scala-2.11.x-integrate-community-build/174/consoleFull

**Comment by SethTisue** [comment]
@matthewfarwell any idea what this is about?

```
[scalastyle] java.lang.RuntimeException: The configured repo MUST be a maven repo, but was: FileRepository(deploy-to-local-repo,FileConfiguration(true,None),Patterns(ivyPatterns=List(), artifactPatterns=List(/home/jenkins/workspace/scala-2.11.x-integrate-community-build/target-0.9.5/project-builds/scalastyle-f35b87524ecfea01fd360be9166e9f26ef467e63/.dbuild/local-publish-repo/[organisation]/[module](_[scalaVersion])(_[sbtVersion])/[revision]/[artifact]-[revision](-[classifier]).[ext]), isMavenCompatible=true, descriptorOptional=false, skipConsistencyCheck=false))
[scalastyle]    at scala.sys.package$.error(package.scala:27)
[scalastyle]    at aether.Aether$$anonfun$1.applyOrElse(Plugin.scala:98)
[scalastyle]    at aether.Aether$$anonfun$1.applyOrElse(Plugin.scala:96)
[scalastyle]    at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:33)
[scalastyle]    at scala.Option.collect(Option.scala:250)
[scalastyle]    at aether.Aether$.deployIt(Plugin.scala:96)
[scalastyle]    at aether.Aether$$anonfun$deployTask$1.apply(Plugin.scala:68)
[scalastyle]    at aether.Aether$$anonfun$deployTask$1.apply(Plugin.scala:67)
```

**Comment by matthewfarwell** [comment]
Yeah. I've replaced deploy with aetherDeploy, because I use a maven repo to deploy to. Do you call deploy as part of the build?

**Comment by cunei** [comment]
Yes, the community build first modifies `publishTo` (pointing to a local directory), then invokes `publish` so that the artifacts generated by each project are collected and cached.

**Comment by SethTisue** [comment]
@matthewfarwell there are two possible ways forward here: either you can change the build in your repo to somehow allow what dbuild wants, or, you can update this PR to customize the build in the context of the community build only, e.g by using `extra.commands` to alter some settings on the fly

sometimes both are necessary: the build needs to be altered to add some kind of hook, and then the entry in `common.conf` needs to be altered to take advantage of that new hook

**Comment by SethTisue** [comment]
@matthewfarwell Happy New Year! still interested in pursuing this?

**Comment by matthewfarwell** [comment]
Yes I am, but haven't had time to look at it yet.

**Comment by matthewfarwell** [comment]
I've added an option to not publish automatically to a maven repo - can you tell if this works?

**Comment by SethTisue** [comment]
test run: https://scala-ci.typesafe.com/job/scala-2.11.x-integrate-community-build/243/consoleFull (will be 404 for a while, Jenkins is backed up)

**Comment by SethTisue** [comment]
You'll need to rebase this against current `2.11.x`.

**Comment by SethTisue** [comment]
Can you rebase this onto current `2.11.x`, please? It's no longer possible to test unless recent changes are included.

**Comment by SethTisue** [comment]
@matthewfarwell interested in getting this across the finish line...?

**Comment by SethTisue** [comment]
@matthewfarwell interested in getting this across the finish line...?

**Comment by SethTisue** [comment]
closing for apparent lack of interest

**Comment by SethTisue** [comment]
I'm working on resolving this by forking scalastyle and just removing the aether-deploy stuff. see #577, #535

**Comment by matthewfarwell** [comment]
Thanks for taking this up Seth. Is this just a case of removing the aetherDeploy (with a flag somehow) when running under the community builds?

**Comment by SethTisue** [comment]
@matthewfarwell see my commits at https://github.com/scalacommunitybuild/scalastyle/commits/community-build-2.12

I had to fork anyway to get rid of the bintray stuff (an unfortunate dbuild limitation), so having forked, I didn't need to worry about putting the aether stuff behind a flag, I could just delete it.

**Comment by matthewfarwell** [comment]
Thing is, I don't use bintray any more, I deploy to sonatype. So that can be removed on my end as well, and indeed has been done in master.

For the aether-deploy, do you need to remove both the plugin and **Seq(aetherPublishBothSettings: _*)**, or just the **Seq(aetherPublishBothSettings: _*)** ?

**Comment by SethTisue** [comment]
@matthewfarwell looks like removing the plugin isn't necessary, so I was able to unfork in a2a81cee2c65c4817f05fa06b8ff3a3e47f72ec2

**Pull request closed without merging**
