### PR TITLE
move to cats (and cats-effect) 2.2.0 and cats-mtl 1.0

### PR DESCRIPTION
**Pull request by SethTisue**
and removing meow-mtl and pfps-shopping-cart for now

~~https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/1917/~~
~~https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/1922/~~
https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/1971/

### CODE REVIEW

**Comment by SethTisue** [comment]
latest refined expects cats 2.2.0. I'm experimenting with expanding the scope of this PR to include that upgrade. (so far, I've found it requires replacing simulacrum with simulacrum-scalafix, and adding discipline-munit.)

**Comment by SethTisue** [comment]
circe hasn't upgraded. I get the same compile errors that we also see at https://github.com/circe/circe/pull/1529

there are a few other failures but I think circe is the blocker here

**Comment by SethTisue** [comment]
I'm just going to close this for now. Will surely return to it later.

@travisbrown Is the 2.2 upgrade a priority for circe? Is it something we ought to look for a volunteer to tackle?

**Comment by travisbrown** [comment]
@SethTisue It should just be a matter of updating without the Scalafix migrations from Scala Steward. I'm trying it now.

**Comment by SethTisue** [comment]
```
[error] /home/travis/build/circe/circe/modules/core/shared/src/main/scala/io/circe/Decoder.scala:1069:31: Option[cats.data.NonEmptyMap[K,V]] does not take parameters
[error]       NonEmptyMap.fromMap(map)(orderK).toRight("[K, V]NonEmptyMap[K, V]")
[error]                               ^
```

**Comment by SethTisue** [comment]
I'll reopen once the linked PR lands.

**Comment by SethTisue** [comment]
circe is green now 👍 

Good progress here. Working on dealing with some other failures downstream. I may need to open some tickets requesting that downstream maintainers upgrade.

**Comment by SethTisue** [comment]
@oleg-py I'll have to remove meow-mtl for now, pending resolution of https://github.com/oleg-py/meow-mtl/pull/18

@gvolpe and with meow-mtl out, pfps-shopping-cart is out too — but I'm eager to re-add them both once doing so becomes possible again

**Pull request merged**
