### PR TITLE
2.11.x failing due to missing spray-json-shapeless dependency for ensime-server

### PR DESCRIPTION
**Pull request by SethTisue**
https://scala-ci.typesafe.com/job/scala-2.11.x-integrate-community-build/49/console shows the failure:

> Missing dependency: the library com.github.fommil#spray-json-shapeless is not provided (in space "default") by any project in this configuration file`

the cause is https://github.com/ensime/ensime-server/commit/88cd6e33e946c472e1a1c3477942425211ac6974 

perhaps it will be straightforward to just add the dependency? we'll see. spray-json-shapeless's dependencies are here: https://github.com/fommil/spray-json-shapeless/blob/master/build.sbt

### CODE REVIEW

**Comment by SethTisue** [comment]
testing: https://scala-ci.typesafe.com/job/scala-2.11.x-integrate-community-build/51/

**Comment by SethTisue** [comment]
go https://scala-ci.typesafe.com/job/scala-2.11.x-integrate-community-build/53/ !

**Comment by lrytz** [comment]
specs2 failed, because there was a change in shapeless that changed `ToList` from a trait to a type alias (https://github.com/milessabin/shapeless/commit/dc9bc0d31e1a855a90c16d856c3f8b19143fac01).

It seems you need to update specs2 to include https://github.com/etorreborre/specs2/commit/0b08208fc89d6bc57a5435792cc3ed913bb01eb6

```
scala> trait ToTraversable[L, M[_]] { type Lub; type Out = M[Lub] }
warning: there was one feature warning; re-run with -feature for details
defined trait ToTraversable

scala> type Aux[T, M[_], Lub0] = ToTraversable[T,M] { type Lub = Lub0 }
warning: there was one feature warning; re-run with -feature for details
defined type alias Aux

scala> type ToList[L, Lub] = Aux[L, List, Lub]
defined type alias ToList

scala> new ToList[Int, Int] {}
<console>:15: error: class type required but ToTraversable[Int,List]{type Lub = Int} found
       new ToList[Int, Int] {}
           ^
```

**Comment by SethTisue** [comment]
for 2.11.x, this was resolved by #126 simply by not upgrading ENSIME.

I plan to revisit this (am already revisiting it, on a wip branch) in the context of 2.11.x-jdk8. 2.11.x(jdk6) is more legacy at this point, more something we're content to freeze versions in.

**Comment by SethTisue** [comment]
improvements to this are in #147

**Pull request closed without merging**
