### PR TITLE
add avro4s

### PR DESCRIPTION
**Pull request by SethTisue**
fyi @sksamuel @propensive

### CODE REVIEW

**Comment by SethTisue** [comment]
already green in local testing

**Comment by SethTisue** [comment]
@sksamuel note the excluded failing test, not sure if that's worth investigating or not

**Comment by sksamuel** [comment]
Where can I see the test that is failing ?

**Comment by SethTisue** [comment]
>Where can I see the test that is failing ?

it's reproducible outside dbuild on my Mac simply by cloning the avro4s repo and running `avro4s-core/testOnly *Github292`:

```
[info] Github292:
[info] com.sksamuel.avro4s.github.Github292 *** ABORTED ***
[info]   java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: com/sksamuel/avro4s/github/Foo (wrong name: com/sksamuel/avro4s/github/FOO)
[info]   at com.sksamuel.avro4s.github.Github292.$anonfun$new$1(Github292.scala:22)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.FunSuiteLike$$anon$1.apply(FunSuiteLike.scala:186)
[info]   at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
[info]   at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
[info]   at org.scalatest.FunSuite.withFixture(FunSuite.scala:1560)
[info]   ...
[info]   Cause: java.lang.NoClassDefFoundError: com/sksamuel/avro4s/github/Foo (wrong name: com/sksamuel/avro4s/github/FOO)
[info]   at java.lang.ClassLoader.defineClass1(Native Method)
[info]   at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
[info]   at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
[info]   at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
[info]   at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
[info]   at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
[info]   at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
[info]   at java.security.AccessController.doPrivileged(Native Method)
[info]   at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
[info]   at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[info]   ...
[trace] Stack trace suppressed: run last avro4s-core/test:testOnly for the full output.
[error] Could not run test com.sksamuel.avro4s.github.Github292: java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: com/sksamuel/avro4s/github/Foo (wrong name: com/sksamuel/avro4s/github/FOO)
[trace] Stack trace suppressed: run last avro4s-core/test:testOnly for the full output.
[error] java.lang.NullPointerException
```

**Comment by SethTisue** [comment]
just a guess, but perhaps it depends on whether the test runs on a case-sensitive or case-insensitive filesystem? (`Foo` vs `FOO`)

**Comment by sksamuel** [comment]
That looks like it. Two classes and on a Mac it doesn't load the right one. I've pushed a fix.

**Comment by SethTisue** [comment]
2e313691961320c46985d2008de2e7a1ca8038d1

**Comment by SethTisue** [comment]
@sksamuel in the context of https://github.com/scala/community-build/pull/1034 I started seeing test failures. log is https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/5371/artifact/logs/avro4s-build.log

```
[avro4s] [error] Failed tests:
[avro4s] [error] 	com.sksamuel.avro4s.github.Github318
[avro4s] [error] 	com.sksamuel.avro4s.record.encoder.AvroNameEncoderTest
[avro4s] [error] 	com.sksamuel.avro4s.schema.SealedTraitSchemaTest
[avro4s] [error] 	com.sksamuel.avro4s.schema.AvroNamespaceTest
[avro4s] [error] 	com.sksamuel.avro4s.github.GithubIssue346
[avro4s] [error] 	com.sksamuel.avro4s.github.Github292
```

I don't know what this is about but I can't really afford to look into it myself (since it seems unlikely to point to a bug in Scala itself, though I can't be completely certain of that) so I will just disable avro4s's test suites for now

**Comment by sksamuel** [comment]
Ok thanks for the heads up. I had a quick look and can't see anything obvious. And we're already on ScalaTest 3.1

**Pull request merged**
