### PR TITLE
unfreeze shapeless

### PR DESCRIPTION
**Pull request by SethTisue**

### CODE REVIEW

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/3332/

**Comment by SethTisue** [comment]
breaks argonaut-shapeless downstream because it expects the macro-compat dependency

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/3340/

**Comment by SethTisue** [comment]
fyi @milessabin

**Comment by milessabin** [comment]
@SethTisue I'm a bit confused ... are you reporting that the fix to case-app has fixed argonaut-shapeless? Or that argonaut-shapeless is still broken despite case-app being fixed? Or something else?

**Comment by SethTisue** [comment]
I fixed the argonaut-shapeless entry here in the community build by artificially injecting the macro-compat dependency (see diffs)

**Comment by SethTisue** [comment]
FYI @alexarchambault

**Comment by alexarchambault** [comment]
It's been fixed in argonaut-shapeless too, https://github.com/alexarchambault/argonaut-shapeless/pull/105 (merged - it's been done after the fix for case-app).

**Comment by SethTisue** [comment]
@alexarchambault fbdc3f2207b1fcf8ab5ee790c9f2becf6a209d02 👍

**Pull request merged**
