### PR TITLE
add breeze v0.12

### PR DESCRIPTION
**Pull request by dlwh**
this is the latest stable release of breeze.

Breeze will stresstest specialization like nothing else. :-)

### CODE REVIEW

**Comment by SethTisue** [comment]
test run: https://scala-ci.typesafe.com/job/scala-2.11.x-integrate-community-build/202/

**Comment by dlwh** [comment]
sorry if that reviewable thing is due to me. we were trying it at work

**Comment by SethTisue** [comment]
> sorry if that reviewable thing is due to me. we were trying it at work

heh, no worries. I just edited out it right out of there

**Comment by SethTisue** [comment]
```
[breeze] Processing subproject: macros
[breeze] [error] **** Missing dependency: the library org.scalamacros#paradise is not provided (in space "default") by any project in this configuration file.
[breeze] [error] In order to control which version is used, please add the corresponding project to the build file
[breeze] [error] (or use "check-missing:false" to ignore (not recommended)).
[breeze] java.lang.RuntimeException: Required dependency not found
```

but you're in luck — it so happens that I added macro paradise to the community build just the other day. can you rebase your branch onto current upstream 2.11.x, and we'll try again?

**Comment by dlwh** [comment]
Thanks! I rebased. Trying to build on my machine in parallel... last time it failed because specs failed?

**Comment by SethTisue** [comment]
new test run: https://scala-ci.typesafe.com/job/scala-2.11.x-integrate-community-build/206/ (link will be valid once worker node spins up)

not sure what you mean about specs.

**Comment by dlwh** [comment]
I just meant that when i ran " bin/dbuild community.dbuild  breeze", it
failed to build specs2 and refused to get to breeze. but I guess not a
problem on your test server.

-- David

**Comment by SethTisue** [comment]
> failed to build specs2 and refused to get to breeze

(I see. I'd have to see the actual error log in order to say anything intelligent about it.)

**Comment by SethTisue** [comment]
`[info] Project breeze------------------: SUCCESS (project rebuilt ok)` :tada:

**Comment by SethTisue** [comment]
thank you, David, for this contribution!

**Comment by SethTisue** [comment]
I'll let you know if there's any trouble once this gets merged into the 2.11.x-jdk8 and 2.12.x builds. (no news is good news.)

**Comment by dlwh** [comment]
you're most welcome! thanks for running this!

**Pull request merged**
