### PR TITLE
2.13: sbt 1.9.0-RC1 (was 1.8.2)

### PR DESCRIPTION
**Pull request by SethTisue**
fyi @eed3si9n 

~https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/4458/~
~https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/4459/~
https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/4461/
https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/4462/

### CODE REVIEW

**Comment by eed3si9n** [comment]
I guess this is the only failure, and likely we can ignore?

```scala
[scastie] [info] set current project to scastie (in build file:/home/jenkins/workspace/scala-2.13.x-jdk11-integrate-community-build/target-0.9.20/extraction/0e22b7d358939ee2ee2396c77af0eaa4e903a626/projects/f20e20cb9377bb03128df4c875aeff949bdbfd68/)
[scastie:error] java.lang.RuntimeException: This version of the ScalablyTyped plugin only supports 1.8.x. You're currently using 1.9.0-RC1
[scastie:error] 	at scala.sys.package$.error(package.scala:30)
[scastie:error] 	at org.scalablytyped.converter.plugin.ScalablyTypedPluginBase$.$anonfun$globalSettings$2(ScalablyTypedPluginBase.scala:117)
[scastie:error] 	at spray.revolver.RevolverPlugin$.$anonfun$settings$23(RevolverPlugin.scala:105)
```

**Comment by SethTisue** [comment]
that's an extraction failure, which means the actual builds aren't happening yet

I will pin that project to 1.8.2 and re-rerun

**Comment by SethTisue** [comment]
@eed3si9n 1.9.0-RC2 also green

**Comment by SethTisue** [comment]
1.9.0-RC3 also green

**Pull request merged**
