### PR TITLE
add scala-pet-store

### PR DESCRIPTION
**Pull request by SethTisue**
fyi @pauljamescleary

### CODE REVIEW

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/3968/

**Comment by SethTisue** [comment]
```
[scala-pet-store] Processing subproject: default-sbt-project
[scala-pet-store] [error] **** Missing dependency: the library io.circe#circe-java8 is not provided (in space "scala.main.jawn_0_11") by any project in this configuration file.
[scala-pet-store] [error] In order to control which version is used, please add the corresponding project to the build file
```

fix attempt pushed. let's try it again: 
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/3976/

**Comment by SethTisue** [comment]
oops wrong subproject name, try again: 
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/3979/

**Comment by SethTisue** [comment]
oh, we need Doobie  /cc @tpolecat

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/3984/

**Comment by SethTisue** [comment]
`EXTRACTION FAILED (failed: doobie)`

```
[doobie:error] com.fasterxml.jackson.databind.JsonMappingException: Required property 'version' is missing.
[doobie:error] {}
[doobie:error]  ^
[doobie:error] 	at com.typesafe.dbuild.model.Utils$$anonfun$readValueT$1.apply(Utils.scala:47)
```

gah. I know I've seen this before

**Comment by SethTisue** [comment]
ah, my 2016 self informs me, at https://github.com/scala/community-builds/issues/292#issuecomment-248791320, that it's because Doobie overrides `onLoad`, which confuses dbuild

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/3991/

**Comment by tpolecat** [comment]
@SethTisue what do you need from me? The tests require a Postgres instance but we could skip that bit if that makes it easier. You can delete the `onLoad` thing, it's just there to annoy me when my dependencies are out of date. Feel free to find me on gitter if that's easier. I have some time today.

**Comment by SethTisue** [comment]
> The tests require a Postgres instance but we could skip that bit if that makes it easier

yeah, how do I skip that? I can skip an entire subproject, or skip particular `.scala` files by name

**Comment by tpolecat** [comment]
Ok looks like you need to skip tests for `postgres`, `postgres-circe`, and `example`. So this works for me with Postgres turned off.

```
sbt              \
  compile        \
  core/test      \
  free/test      \
  h2/test        \
  hikari/test    \
  refined/test   \
  scalatest/test \
  specs2/test
```

**Comment by SethTisue** [comment]
~~https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/4015/~~ 
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/4023/ (no new changes, just bringing the branch up to date with latest fixes so we can see what's needed next)

**Comment by SethTisue** [comment]
status: doobie is green. scala-pet-store is blocked because http4s has started failing, which I'll look into soon

**Comment by SethTisue** [comment]
note that I'm having to add https://github.com/jmcardon/tsec (cc @jmcardon), but I don't know yet how that's going because it's also blocked for now by the http4s issue

**Comment by SethTisue** [comment]
#844 attempts to resolve the http4s breakage, I've also cherry-picked it here

**Comment by SethTisue** [comment]
I moved the doobie part to #847

**Comment by SethTisue** [comment]
the next hurdle here is tsec-http4s, which scala-pet-store needs, but tsec's dependencies are out of date compared to what we have

I've opened https://github.com/jmcardon/tsec/pull/203 on it. I'll need help with this

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/4065/

**Comment by SethTisue** [comment]
the good news: tsec is now green, thanks to @ChristopherDavenport 🙏

the bad news: 

```
[scala-pet-store] [error] Modules were resolved with conflicting cross-version suffixes in ProjectRef(uri("file:/home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.16/project-builds/scala-pet-store-e249de889c51c8f52f7f6a7bc3000539579e6765/"), "scala-pet-store-e249de889c51c8f52f7f6a7bc3000539579e6765"):
[scala-pet-store] [error]    com.beachape:enumeratum <none>, _2.12
[scala-pet-store] [error] java.lang.RuntimeException: Conflicting cross-version suffixes in: com.beachape:enumeratum
```

I'll look into it.

**Comment by pauljamescleary** [comment]
@SethTisue apologies did not see this until this morning, @zakpatterson gave me the heads up

**Comment by pauljamescleary** [comment]
Feel free as well to pop in gitter, usually @zakpatterson or myself are around (although timeliness of responses will vary, someone is usually lurking at some point every day) - https://gitter.im/scala-pet-store/scala-pet-store

**Comment by SethTisue** [comment]
merged the tsec part separately as #848

**Pull request merged**
