### PR TITLE
Avoid -Ymacro-annot for akka-stream and akka-more

### PR DESCRIPTION
**Pull request by raboof**

### CODE REVIEW

**Comment by adriaanm** [comment]
Yeah, may as well avoid running into trouble.  macro annotations are a -Y flag since they’re still as experimental as before.  I hope their bugs won’t  keep us from releasing.

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/2005/

**Comment by SethTisue** [comment]
@raboof 

```
[akka-stream] [error] /home/jenkins/workspace/scala-2.13.x-integrate-community-build/target-0.9.16/project-builds/akka-stream-9be07dd183b3c09961dad4eb6cdd29298d5e149c/akka-stream-tests/src/test/scala/akka/stream/scaladsl/SinkSpec.scala:363:45: postfix operator sum needs to be enabled
[akka-stream] [error] by making the implicit value scala.language.postfixOps visible.
[akka-stream] [error] ----
[akka-stream] [error] This can be achieved by adding the import clause 'import scala.language.postfixOps'
[akka-stream] [error] or by setting the compiler option -language:postfixOps.
[akka-stream] [error] See the Scaladoc for value scala.language.postfixOps for a discussion
[akka-stream] [error] why the feature needs to be explicitly enabled.
[akka-stream] [error]       assert(result.futureValue == (1 to 10 sum))
[akka-stream] [error]                                             ^
[akka-stream] [error] one error found
[akka-stream] [error] (akka-stream-tests / Test / compileIncremental) Compilation failed
```

**Comment by SethTisue** [comment]
some form of this got merged in dc0228da8b6a73d36b315a2bcb07c51a304d781f and 2f0e9c1d42ab905ae308f7b0344314912c487315

**Comment by SethTisue** [comment]
I'm experimenting with not overriding projects' macro-annotation settings at all anymore at https://github.com/SethTisue/community-builds/commit/05726db28fdb7992967e57504ab4d8e109d79177

(it was something we definitely needed to do in the 2.13 CB back when macro annotations first landed in scala/scala, but hopefully isn't necessary anymore, probably most projects have upgraded their builds already)

**Pull request closed without merging**
