### PR TITLE
Add metrics-scala.

### PR DESCRIPTION
**Pull request by SethTisue**

### CODE REVIEW

**Comment by SethTisue** [comment]
let's see what Jenkins has to say: https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/2674/consoleFull

**Comment by SethTisue** [comment]
```
[info] Project metrics-scala---------------: SUCCESS (project rebuilt ok)
```

thanks @erikvanoosten!

**Comment by erikvanoosten** [comment]
> in your build.sbt can you update this logic
>
>      case v if v.startsWith("2.12") => Tests.Argument("-l", "<scala2.12")
>
> to accommodate Scala 2.13 as well? since this will be merged forward into the 2.13 community build as well

Sorry, I missed that one. Its fixed!
Hmm not yet. I am on it...

**Comment by erikvanoosten** [comment]
It should work now :)

**Comment by SethTisue** [comment]
I've merged this onto 2.13.x now. If it isn't green in the next run, I'll come back here and comment, if you don't hear, it's all good.

**Pull request merged**
