### PR TITLE
add `narrow` script for trimming down list of projects

### PR DESCRIPTION
**Pull request by SethTisue**
so e.g. if you're working on Play, you might `./narrow play-webgoat` and now you don't have to wait for 200 repos to extract (which takes an hour or more the first time, and 5 minutes subsequent times; even 5 minutes is painful when you're testing changes), you can just extract (and then build) the 20 needed

enabling this was one of my main motivations for doing the big config file reorg (where each project has its own separate config file now)

### CODE REVIEW

**Comment by ashawley** [comment]
This looks awesome.  I've been slimming  down `community.dbuild` by hand for a long time for the same purpose of trying to shorten iteration cycles.

**Comment by SethTisue** [comment]
cool, glad to have a user besides me, hope it works for you

**Comment by SethTisue** [comment]
@cunei you might enjoy looking at this (and #987)

**Comment by SethTisue** [comment]
wiki now documents this

**Pull request merged**
