### PR TITLE
Add basic setup for ScalaFX

### PR DESCRIPTION
**Pull request by jpsacha**
ScalaFX cross-builds for Scala 2.13.1, 2.12.11, and 2.11.12

Stable/release builds are on branch 'stable'

### CODE REVIEW

**Comment by SethTisue** [comment]
After a few tweaks I'm able to run this locally, but it hits https://github.com/scala/bug/issues/12060, so this won't become mergeable until there's a fix or workaround for that

**Comment by jpsacha** [comment]
I added workaround to deal with  scala/bug#12060 - the the problematic implicit conversions are applied explicitly. The code compiles and tests fine with Scala 2.13.2, 2.12.12, and 2.11.12.  
The commit with a workaround is linked above. The "stable" commit to reference for this issue is this:
https://github.com/scalafx/scalafx/commit/69614c0b20ccb429db6faff6f7840f1560eaece1
I hope this will enable to move this issue forward without waiting for fix for scala/bug#12060

**Comment by SethTisue** [comment]
green in local test — thanks!

**Comment by SethTisue** [comment]
(Note that this isn't eligible for a backport to our 2.11.x and 2.12.x branches, because those branches are stuck on ScalaTest 3.0.)

**Comment by SethTisue** [comment]
@jpsacha I merged this because it was green locally on MacOS, but on our Jenkins [I get](https://scala-ci.typesafe.com/view/scala-2.13.x/job/scala-2.13.x-jdk11-integrate-community-build/1647/):

```
[scalafx] [info] ChoiceBoxSpec:
[scalafx] [info] A ChoiceBox
[scalafx:error] Exception in thread "Thread-5" java.lang.UnsupportedOperationException: Unable to open DISPLAY
[scalafx:error] 	at com.sun.glass.ui.gtk.GtkApplication.lambda$new$6(GtkApplication.java:173)
[scalafx:error] 	at java.base/java.security.AccessController.doPrivileged(Native Method)
[scalafx:error] 	at com.sun.glass.ui.gtk.GtkApplication.<init>(GtkApplication.java:171)
[scalafx:error] 	at com.sun.glass.ui.gtk.GtkPlatformFactory.createApplication(GtkPlatformFactory.java:41)
[scalafx:error] 	at com.sun.glass.ui.Application.run(Application.java:144)
[scalafx:error] 	at com.sun.javafx.tk.quantum.QuantumToolkit.startup(QuantumToolkit.java:280)
[scalafx:error] 	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:269)
[scalafx:error] 	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158)
[scalafx:error] 	at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:658)
[scalafx:error] 	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:678)
[scalafx:error] 	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
[scalafx:error] 	at java.base/java.lang.Thread.run(Thread.java:834)
Build timed out (after 15 minutes). Marking the build as aborted.
```

looks like I won't be able to run the tests without xfvb? is there a way to run just the tests that don't require xfvb, or do they all require it?

**Comment by SethTisue** [comment]
for now anyway, I've dealt with it by just compiling the tests but not attempting to run any of them:  https://github.com/scala/community-build/commit/6653ed0f5091a7a9906fcb8e586d71d3e77fffd6

...but if you think we can do better than that, let me know.

**Comment by jpsacha** [comment]
Thanks for your help in making this work.
ScalaFX is an UI toolkit. Most of the test do need xfvb. There are few could run without it. I will look what can be done to enable only selected tests and do a separate PR for that.

**Comment by SethTisue** [comment]
@jpsacha okay. only if it's reasonably easy — it's not worth more than minor time/effort, the chances of the full test suite turning up Scala regressions is probably small. if you're seriously concerned that Scala regressions might cause test failures

**Comment by SethTisue** [comment]
@jpsacha sure, but (I suggest) only if it's reasonably easy to do. from the Scala team's perspective, it's not worth too much effort, since the chances of the full test suite turning up Scala regressions is probably small. from your own perspective, if you're concerned that Scala regressions might result in bugs/failures, you could get full coverage by adding "latest 2.13 nightly", "latest 2.12 nightly" etc to your own CI matrix; see https://github.com/scala/scala-dev/issues/648

**Pull request merged**
