### PR TITLE
split new pprint repo off from upickle-pprint

### PR DESCRIPTION
**Pull request by SethTisue**

### CODE REVIEW

**Comment by SethTisue** [comment]
test run: https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/1527/consoleFull (404 til Jenkins finishes remembering all the words to the "I love Bumblebee, Bumblebee Tuna" song)

**Comment by SethTisue** [comment]
fyi @lihaoyi @MasseGuillaume

**Comment by lihaoyi** [comment]
Cool, you can probably kill the upickle-pprint repo entirely now that It's EOL.

**Comment by SethTisue** [comment]
> you can probably kill the upickle-pprint repo entirely now that It's EOL

(leaving it in for now since it's frozen and working, but I won't hesitate to drop it if there's trouble)

**Pull request merged**
