### PR TITLE
add (just a little bit) more of zinc

### PR DESCRIPTION
**Pull request by SethTisue**
sequel to #1131 

fyi @eed3si9n

~~queued https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/1379/~~
queued https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/1397/

### CODE REVIEW

**Comment by SethTisue** [comment]
@eed3si9n wdyt of the failures at https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/1379/artifact/logs/zinc-build.log ? is this worth pursuing?

**Comment by eed3si9n** [comment]
`xsbt.CompilerInterface` is an entry point for the compiler bridge, which is dynamically compiled out of source for each Zinc * Scala combination.

For whatever reason Zinc is failing to locate `xsbt.CompilerInterface` in `target-bridge-2.13.2-bin-a789d81.jar` here.

```
[zinc] [debug] Returning already retrieved and compiled bridge: /tmp/sbt_2cc1e2cc/target-bridge-2.13.2-bin-a789d81.jar.
[zinc] [error] ## Exception when compiling 1 sources to /tmp/sbt_5a20fafc/classes
[zinc] [error] java.lang.ClassNotFoundException: xsbt.CompilerInterface
[zinc] [error] java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
[zinc] [error] java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
[zinc] [error] java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
[zinc] [error] java.base/java.lang.Class.forName0(Native Method)
[zinc] [error] java.base/java.lang.Class.forName(Class.java:398)
[zinc] [error] sbt.internal.inc.AnalyzingCompiler.getInterfaceClass(AnalyzingCompiler.scala:289)
[zinc] [error] sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:256)
[zinc] [error] sbt.internal.inc.AnalyzingCompiler.newCachedCompiler(AnalyzingCompiler.scala:152)
[zinc] [error] sbt.internal.inc.AnalyzingCompiler.newCachedCompiler(AnalyzingCompiler.scala:139)
[zinc] [error] sbt.internal.inc.FreshCompilerCache.apply(CompilerCache.scala:103)
[zinc] [error] sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:99)
```

I don't think this happens on Travis CI.

> is this worth pursuing?

I think this is meh, unless it's easy to get it fixed.

Something that's worth validating is getting sbt nightly baking again (I've fallen behind on that) and automatically running 2.13.x Community Builds using that to validate _Zinc_ PRs (as opposed to Scala 2.13.x).

**Comment by SethTisue** [comment]
> I think this is meh, unless it's easy to get it fixed.

I can't think of any easy things to try, so okay, I'll reduce the scope of PR to just compiling the tests in this subproject, not running them.

> Something that's worth validating is getting sbt nightly baking again (I've fallen behind on that) and automatically running 2.13.x Community Builds using that to validate Zinc PRs (as opposed to Scala 2.13.x).

Ah, that does sound appealing.

**Comment by SethTisue** [comment]
green in local test

**Pull request merged**
